# Libraries

In [2]:
import numpy as np
import pandas as pd

from ucimlrepo import fetch_ucirepo
from sklearn.datasets import fetch_california_housing

from tensorflow.keras import layers, models
import tensorflow as tf

from sklearn.metrics import confusion_matrix, f1_score, classification_report, accuracy_score, balanced_accuracy_score, ConfusionMatrixDisplay, roc_auc_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# own functions
from active_learning import random_sampling, uncertainty_sampling, label_data, active_learning_bc, active_learning_mc, sasla_bc, sasla_mc
from active_learning import balanced_weights, tune_params, retrieve_params, cv_classification, create_model

from time import time

# Models

## Breast Cancer

In [3]:
breast_cancer = fetch_ucirepo(id=17)

bcwd_df = pd.concat(
    [breast_cancer.data.features, breast_cancer.data.targets],
    axis=1
)
bcwd_df.head()

,radius1,texture1,perimeter1,area1,smoothness1,compactness1,concavity1,concave_points1,symmetry1,fractal_dimension1,...,texture3,perimeter3,area3,smoothness3,compactness3,concavity3,concave_points3,symmetry3,fractal_dimension3,Diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,M
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,M
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,M
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,M
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,M

In [4]:
X = breast_cancer.data.features.to_numpy()
y = (breast_cancer.data.targets).iloc[:, 0].map({"B": 0, "M": 1}).astype("int32").to_numpy()

X_pool, X_test, y_pool, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=51
)

In [4]:
acts = ['relu', 'leaky_relu', 'elu', 'gelu', 'swish']
balance = [False, True]
name = "base"
for state in balance:
    if state:
        name = 'balanced'
    else:
        name = 'base'

    for activation in acts:
        base_params = tune_params(X_pool, y_pool,
                                  loss='binary_crossentropy',
                                  out_units=1, out_act='sigmoid',
                                  k=5, activation=activation,
                                  balanced=False,
                                  random_state=42,
                                  n_trials=50,
                                  export=True, file = f'params/breast_cancer/{name}_{activation}.json'
        )

[I 2026-09-25 19:56:55,369] A new study created in memory with name: no-name-455c1104-dff1-40ab-b8ea-5ad80ccf7a06

WARNING:tensorflow:From C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

[W 2026-09-25 19:57:01,649] Trial 0 failed with parameters: {'hidden_layer': 17, 'learning_rate': 0.0025303472686758082, 'momentum': 0.05187663174830328, 'weight_decay': 0.0006069634458336872} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\optuna\study\_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "C:\Users\dawid\OneDrive - Stellenbosch University\Documents\Universiteit\4th year\ML\assignment3\ML441_Assigment3\active_learning.py", line 582, in obj
    model.fit(
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\backend\tensorflow\trainer.py", line 375, in fit
    for begin_step, end_step, iterator in epoch_iterator:
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\backend\tensorflow\trainer.py", line 742, in __next__
    return next(self._epoch_iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\trainers\epoch_iterator.py", line 125, in _enumerate_iterator
    self._current_iterator = iter(self._get_iterator())
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 501, in __iter__
    return iterator_ops.OwnedIterator(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 709, in __init__
    self._create_iterator(dataset)
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 748, in _create_iterator
    gen_dataset_ops.make_iterator(ds_variant, self._iterator_resource)
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 3478, in make_iterator
    _result = pywrap_tfe.TFE_Py_FastPathExecute(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
[W 2026-09-25 19:57:01,795] Trial 0 failed with value None.

KeyboardInterrupt:

In [4]:
acts = ['relu', 'leaky_relu', 'elu', 'gelu', 'swish']
balance = [False, True]

results = []
name = "base"
for state in balance:
    if state:
        name = 'balanced'
    else:
        name = 'base'

    for activation in acts:
        setup = {'activation': activation, 'balanced': state}
        alpha = 0
        params = retrieve_params(f'params/breast_cancer/{name}_{activation}.json')
        if activation == 'leaky_relu':
            alpha = params["leaky_relu_alpha"]
        elif activation == 'elu':
            alpha = params["elu_alpha"]
        result = cv_classification(X_pool, y_pool, out_units=1, out_act='sigmoid', loss="binary_crossentropy", k=5, random_state=42, 
                  hidden_units=params['hidden_layer'], activation=activation, alpha=alpha, 
                  learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], balanced=state)
        for key, val in result.items():
            setup[key] = val
    
        results.append(setup)

results_df = pd.DataFrame(results)
results_df.round(4).to_csv(f"results/breast_cancer/cv_validation.csv", index=False)

WARNING:tensorflow:From C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

In [13]:
results_df = pd.read_csv("results/breast_cancer/cv_validation.csv")
results_df[results_df['balanced'] == False]

   activation  balanced     auc     acc      f1
0        relu     False  0.9926  0.9648  0.9624
1  leaky_relu     False  0.9909  0.9670  0.9647
2         elu     False  0.9922  0.9736  0.9715
3        gelu     False  0.9921  0.9692  0.9671
4       swish     False  0.9922  0.9714  0.9693

In [16]:
activation = 'elu'
params = retrieve_params(f'params/breast_cancer/base_{activation}.json')
scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)

model = create_model(X_train.shape[1], hidden_units=params['hidden_layer'], activation=activation, alpha=params['elu_alpha'], out_units=1, out_act='sigmoid', 
                 learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], loss='binary_crossentropy')
# params['learning_rate']
history = []
runs = 100
epochs = 200 // runs
fit_kwargs = {
    "epochs": epochs,
    "batch_size": 32,
    # "validation_split": 0.15,
    # "callbacks": [early_stopping],
    "verbose": 0
}
tic = time()
for i in range(runs):
    iteration = {'cumulative epochs': epochs * (i + 1)}
    iter_hist = model.fit(
        X_train,
        y_pool,
        **fit_kwargs
    )

    train_loss = iter_hist.history['loss']
    weights = model.get_weights()

    if not all(np.all(np.isfinite(w)) for w in weights):
        print(f"Model became unstable at iteration {i + 1}")
        break

    y_prob = model.predict(X_val, verbose=0).ravel()

    if not np.all(np.isfinite(y_prob)):
        print(f"NaN/Inf predictions at iteration {i + 1}")
        break
        
    y_pred = (y_prob >= 0.5).astype(int)
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average='macro')
    auc = roc_auc_score(y_test, y_prob)
    toc = time()
    
    iteration['Training loss'] = train_loss[-1]
    iteration['Accuracy'] = acc
    iteration['macro F1'] = f1
    iteration['ROC-AUC'] = auc
    iteration['time'] = toc - tic
    history.append(iteration)
    print(f"Iteration {i+1}: ")
    for l in range(len(train_loss)):
        print(f"\t{train_loss[l]}")

run_df = pd.DataFrame(history)
run_df.round(4).to_csv(f"results/breast_cancer/passive_learning.csv", index=False)

Iteration 1:
	0.31497400999069214
	0.12422307580709457
Iteration 2:
	0.10408703982830048
	0.09339655190706253
Iteration 3:
	0.08665139973163605
	0.0814039409160614
Iteration 4:
	0.07830493152141571
	0.0757574513554573
Iteration 5:
	0.07305547595024109
	0.07225505262613297
Iteration 6:
	0.07031994313001633
	0.06819263845682144
Iteration 7:
	0.06699642539024353
	0.0656541958451271
Iteration 8:
	0.06443711370229721
	0.06362545490264893
Iteration 9:
	0.06300844252109528
	0.06177350878715515
Iteration 10:
	0.06105828657746315
	0.05996248871088028
Iteration 11:
	0.05970074608922005
	0.05898311734199524
Iteration 12:
	0.0583430752158165
	0.057868074625730515
Iteration 13:
	0.05711057409644127
	0.05644910782575607
Iteration 14:
	0.05618635565042496
	0.0554165318608284
Iteration 15:
	0.05479390174150467
	0.05460323393344879
Iteration 16:
	0.05417875200510025
	0.05368169769644737
Iteration 17:
	0.05365431308746338
	0.053356196731328964
Iteration 18:
	0.05275879055261612
	0.05213972553610802
Iteration 19:
	0.051673609763383865
	0.05145760998129845
Iteration 20:
	0.05081096291542053
	0.050532061606645584
Iteration 21:
	0.05048048123717308
	0.04990371689200401
Iteration 22:
	0.049612537026405334
	0.049282465130090714
Iteration 23:
	0.04902688041329384
	0.0486321747303009
Iteration 24:
	0.048352014273405075
	0.04812602326273918
Iteration 25:
	0.04804609343409538
	0.04765056073665619
Iteration 26:
	0.04765677824616432
	0.04704839736223221
Iteration 27:
	0.04652947932481766
	0.04641859605908394
Iteration 28:
	0.04588721692562103
	0.04602764919400215
Iteration 29:
	0.04623676463961601
	0.0454183891415596
Iteration 30:
	0.045484330505132675
	0.04468142241239548
Iteration 31:
	0.04500618949532509
	0.04425553232431412
Iteration 32:
	0.04420340433716774
	0.04346592724323273
Iteration 33:
	0.04359724745154381
	0.04300198704004288
Iteration 34:
	0.04325106739997864
	0.04287175461649895
Iteration 35:
	0.04259234294295311
	0.04223541170358658
Iteration 36:
	0.041912615299224854
	0.04171597957611084
Iteration 37:
	0.04177548736333847
	0.04214854910969734
Iteration 38:
	0.041177403181791306
	0.04127408191561699
Iteration 39:
	0.04036027565598488
	0.040076810866594315
Iteration 40:
	0.03995199501514435
	0.040761254727840424
Iteration 41:
	0.03957739844918251
	0.039085753262043
Iteration 42:
	0.039334215223789215
	0.03852058947086334
Iteration 43:
	0.038428064435720444
	0.03844780474901199
Iteration 44:
	0.03798177093267441
	0.038002241402864456
Iteration 45:
	0.03766566514968872
	0.037291646003723145
Iteration 46:
	0.037530843168497086
	0.03694116324186325
Iteration 47:
	0.03679385408759117
	0.03639298304915428
Iteration 48:
	0.03651369363069534
	0.035924673080444336
Iteration 49:
	0.03551318123936653
	0.03554555028676987
Iteration 50:
	0.03505554050207138
	0.03540383651852608
Iteration 51:
	0.03465518355369568
	0.034274883568286896
Iteration 52:
	0.03437037020921707
	0.03396504744887352
Iteration 53:
	0.03344595059752464
	0.033388420939445496
Iteration 54:
	0.03328457474708557
	0.03296799957752228
Iteration 55:
	0.03281845152378082
	0.032641004770994186
Iteration 56:
	0.03261607885360718
	0.032158851623535156
Iteration 57:
	0.031759727746248245
	0.03158598020672798
Iteration 58:
	0.03131643682718277
	0.031106624752283096
Iteration 59:
	0.030856771394610405
	0.030618727207183838
Iteration 60:
	0.030786244198679924
	0.030399568378925323
Iteration 61:
	0.030326547101140022
	0.02980916202068329
Iteration 62:
	0.029689375311136246
	0.029560856521129608
Iteration 63:
	0.02939075045287609
	0.029170125722885132
Iteration 64:
	0.029692521318793297
	0.028549659997224808
Iteration 65:
	0.028658661991357803
	0.0283854678273201
Iteration 66:
	0.028197551146149635
	0.02794291451573372
Iteration 67:
	0.027721285820007324
	0.02754759043455124
Iteration 68:
	0.027303893119096756
	0.026898745447397232
Iteration 69:
	0.02727341093122959
	0.026857543736696243
Iteration 70:
	0.026499610394239426
	0.026363104581832886
Iteration 71:
	0.02615980990231037
	0.026091787964105606
Iteration 72:
	0.025889737531542778
	0.025704320520162582
Iteration 73:
	0.025420445948839188
	0.0253054928034544
Iteration 74:
	0.025273585692048073
	0.024951666593551636
Iteration 75:
	0.02492755837738514
	0.024681461974978447
Iteration 76:
	0.02446996048092842
	0.024464914575219154
Iteration 77:
	0.02421494945883751
	0.023821769282221794
Iteration 78:
	0.023923000320792198
	0.023780016228556633
Iteration 79:
	0.023599697276949883
	0.023770172148942947
Iteration 80:
	0.023419762030243874
	0.023561879992485046
Iteration 81:
	0.02329178899526596
	0.02304949052631855
Iteration 82:
	0.022863391786813736
	0.0226820670068264
Iteration 83:
	0.02262175641953945
	0.022527797147631645
Iteration 84:
	0.02236837148666382
	0.022216569632291794
Iteration 85:
	0.022144485265016556
	0.02193647250533104
Iteration 86:
	0.021921765059232712
	0.022227823734283447
Iteration 87:
	0.021788423880934715
	0.021756505593657494
Iteration 88:
	0.02130136266350746
	0.021089758723974228
Iteration 89:
	0.021053768694400787
	0.02094421163201332
Iteration 90:
	0.02083052694797516
	0.020732387900352478
Iteration 91:
	0.02050139755010605
	0.020423654466867447
Iteration 92:
	0.020204341039061546
	0.020124267786741257
Iteration 93:
	0.020031185820698738
	0.01990329846739769
Iteration 94:
	0.019982097670435905
	0.019815923646092415
Iteration 95:
	0.019840113818645477
	0.01961015909910202
Iteration 96:
	0.019614307209849358
	0.01936453767120838
Iteration 97:
	0.019084539264440536
	0.01922099106013775
Iteration 98:
	0.019047705456614494
	0.018772296607494354
Iteration 99:
	0.018916813656687737
	0.018819211050868034
Iteration 100:
	0.018557466566562653
	0.018873181194067

In [7]:
activation = 'elu'
params = retrieve_params(f'params/breast_cancer/base_{activation}.json')

scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)

history = active_learning_bc(X_train, y_pool, X_val, y_test, random_sampling, num_iter=100, unlab_size=0.9, random_state=100, verbose=True,
                               hidden_units=params['hidden_layer'], activation=activation, alpha=params['elu_alpha'], balanced=False,
                               learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], loss='binary_crossentropy' 
)

run_df = pd.DataFrame(history)
run_df.round(4).to_csv(f"results/breast_cancer/uncertainty_sampling.csv", index=False)

Iteration 1: 45 labelled instances
	Training loss = 0.40008431673049927

Iteration 2: 49 labelled instances
	Training loss = 0.22699640691280365

Iteration 3: 53 labelled instances
	Training loss = 0.15667562186717987

Iteration 4: 57 labelled instances
	Training loss = 0.11602528393268585

Iteration 5: 61 labelled instances
	Training loss = 0.10972920060157776

Iteration 6: 65 labelled instances
	Training loss = 0.10710886120796204

Iteration 7: 69 labelled instances
	Training loss = 0.09189688414335251

Iteration 8: 73 labelled instances
	Training loss = 0.07976818829774857

Iteration 9: 77 labelled instances
	Training loss = 0.07067061960697174

Iteration 10: 81 labelled instances
	Training loss = 0.06417559087276459

Iteration 11: 85 labelled instances
	Training loss = 0.05795629322528839

Iteration 12: 89 labelled instances
	Training loss = 0.05915168300271034

Iteration 13: 93 labelled instances
	Training loss = 0.054313674569129944

Iteration 14: 97 labelled instances
	Training loss = 0.05989112704992294

Iteration 15: 101 labelled instances
	Training loss = 0.05721062049269676

Iteration 16: 105 labelled instances
	Training loss = 0.05248431861400604

Iteration 17: 109 labelled instances
	Training loss = 0.048586152493953705

Iteration 18: 113 labelled instances
	Training loss = 0.09508540481328964

Iteration 19: 117 labelled instances
	Training loss = 0.08818770945072174

Iteration 20: 121 labelled instances
	Training loss = 0.0830584466457367

Iteration 21: 125 labelled instances
	Training loss = 0.07964344322681427

Iteration 22: 129 labelled instances
	Training loss = 0.07546492666006088

Iteration 23: 133 labelled instances
	Training loss = 0.0774456188082695

Iteration 24: 137 labelled instances
	Training loss = 0.07425554096698761

Iteration 25: 141 labelled instances
	Training loss = 0.07076389342546463

Iteration 26: 145 labelled instances
	Training loss = 0.06726682931184769

Iteration 27: 149 labelled instances
	Training loss = 0.06777410954236984

Iteration 28: 153 labelled instances
	Training loss = 0.06444068253040314

Iteration 29: 157 labelled instances
	Training loss = 0.06387657672166824

Iteration 30: 161 labelled instances
	Training loss = 0.06118730455636978

Iteration 31: 165 labelled instances
	Training loss = 0.058423932641744614

Iteration 32: 169 labelled instances
	Training loss = 0.057349443435668945

Iteration 33: 173 labelled instances
	Training loss = 0.055023495107889175

Iteration 34: 177 labelled instances
	Training loss = 0.052738551050424576

Iteration 35: 181 labelled instances
	Training loss = 0.0532863512635231

Iteration 36: 185 labelled instances
	Training loss = 0.051834095269441605

Iteration 37: 189 labelled instances
	Training loss = 0.05052581802010536

Iteration 38: 193 labelled instances
	Training loss = 0.04992515221238136

Iteration 39: 197 labelled instances
	Training loss = 0.048065442591905594

Iteration 40: 201 labelled instances
	Training loss = 0.046314869076013565

Iteration 41: 205 labelled instances
	Training loss = 0.046905484050512314

Iteration 42: 209 labelled instances
	Training loss = 0.04958011209964752

Iteration 43: 213 labelled instances
	Training loss = 0.049300651997327805

Iteration 44: 217 labelled instances
	Training loss = 0.04941409081220627

Iteration 45: 221 labelled instances
	Training loss = 0.048087164759635925

Iteration 46: 225 labelled instances
	Training loss = 0.04597306624054909

Iteration 47: 229 labelled instances
	Training loss = 0.04647529870271683

Iteration 48: 233 labelled instances
	Training loss = 0.044820770621299744

Iteration 49: 237 labelled instances
	Training loss = 0.04416697844862938

Iteration 50: 241 labelled instances
	Training loss = 0.0426289327442646

Iteration 51: 245 labelled instances
	Training loss = 0.043687596917152405

Iteration 52: 249 labelled instances
	Training loss = 0.041973866522312164

Iteration 53: 253 labelled instances
	Training loss = 0.04044103994965553

Iteration 54: 257 labelled instances
	Training loss = 0.0390578918159008

Iteration 55: 261 labelled instances
	Training loss = 0.03968094289302826

Iteration 56: 265 labelled instances
	Training loss = 0.04001467674970627

Iteration 57: 269 labelled instances
	Training loss = 0.03875144571065903

Iteration 58: 273 labelled instances
	Training loss = 0.0379902608692646

Iteration 59: 277 labelled instances
	Training loss = 0.03617360070347786

Iteration 60: 281 labelled instances
	Training loss = 0.036184825003147125

Iteration 61: 285 labelled instances
	Training loss = 0.03611905127763748

Iteration 62: 289 labelled instances
	Training loss = 0.03439722955226898

Iteration 63: 293 labelled instances
	Training loss = 0.03364519402384758

Iteration 64: 297 labelled instances
	Training loss = 0.03232967108488083

Iteration 65: 301 labelled instances
	Training loss = 0.03089139610528946

Iteration 66: 305 labelled instances
	Training loss = 0.03342162072658539

Iteration 67: 309 labelled instances
	Training loss = 0.03307989612221718

Iteration 68: 313 labelled instances
	Training loss = 0.03201582655310631

Iteration 69: 317 labelled instances
	Training loss = 0.03322742134332657

Iteration 70: 321 labelled instances
	Training loss = 0.03151784837245941

Iteration 71: 325 labelled instances
	Training loss = 0.03097795881330967

Iteration 72: 329 labelled instances
	Training loss = 0.029580505564808846

Iteration 73: 333 labelled instances
	Training loss = 0.028426680713891983

Iteration 74: 337 labelled instances
	Training loss = 0.02736302651464939

Iteration 75: 341 labelled instances
	Training loss = 0.026339134201407433

Iteration 76: 345 labelled instances
	Training loss = 0.02552165649831295

Iteration 77: 349 labelled instances
	Training loss = 0.02453998290002346

Iteration 78: 353 labelled instances
	Training loss = 0.02363237924873829

Iteration 79: 357 labelled instances
	Training loss = 0.02332392707467079

Iteration 80: 361 labelled instances
	Training loss = 0.022389110177755356

Iteration 81: 365 labelled instances
	Training loss = 0.02135307714343071

Iteration 82: 369 labelled instances
	Training loss = 0.02123536355793476

Iteration 83: 373 labelled instances
	Training loss = 0.02025751955807209

Iteration 84: 377 labelled instances
	Training loss = 0.03187888488173485

Iteration 85: 381 labelled instances
	Training loss = 0.030346231535077095

Iteration 86: 385 labelled instances
	Training loss = 0.029623262584209442

Iteration 87: 389 labelled instances
	Training loss = 0.02992616966366768

Iteration 88: 393 labelled instances
	Training loss = 0.03356684744358063

Iteration 89: 397 labelled instances
	Training loss = 0.029537294059991837

Iteration 90: 401 labelled instances
	Training loss = 0.03670044243335724

Iteration 91: 405 labelled instances
	Training loss = 0.036031246185302734

Iteration 92: 409 labelled instances
	Training loss = 0.035164974629879

Iteration 93: 413 labelled instances
	Training loss = 0.03410071134567261

Iteration 94: 417 labelled instances
	Training loss = 0.033163536339998245

Iteration 95: 421 labelled instances
	Training loss = 0.04471785947680473

Iteration 96: 425 labelled instances
	Training loss = 0.04226028919219971

Iteration 97: 429 labelled instances
	Training loss = 0.040844231843948364

Iteration 98: 433 labelled instances
	Training loss = 0.03995779529213905

Iteration 99: 437 labelled instances
	Training loss = 0.04056693613529205

Iteration 100: 455 labelled instances
	Training loss = 0.038987401872873306

In [8]:
activation = 'elu'
params = retrieve_params(f'params/breast_cancer/base_{activation}.json')

scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)
for beta in [0.9]:
    history = sasla_bc(X_train, y_pool, X_val, y_test, num_iter=100, unlab_size=0.9, random_state=100, verbose=True,
                                   hidden_units=params['hidden_layer'], activation=activation, alpha=params['elu_alpha'], balanced=False,
                                   learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], beta=beta)
    
    run_df = pd.DataFrame(history)
    run_df.round(4).to_csv(f"results/breast_cancer/sasla_{beta}.csv", index=False)

Iteration 1: 455 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9811507936507937
	AUC = 0.9990079365079365

Iteration 2: 350 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9811507936507937
	AUC = 0.9993386243386243

Iteration 3: 298 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9811507936507937
	AUC = 0.9993386243386243

Iteration 4: 263 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9811507936507937
	AUC = 0.9993386243386243

Iteration 5: 237 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9811507936507937
	AUC = 0.9993386243386243

Iteration 6: 223 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9996693121693122

Iteration 7: 216 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9996693121693122

Iteration 8: 204 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9996693121693122

Iteration 9: 197 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9996693121693122

Iteration 10: 191 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9996693121693122

Iteration 11: 185 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9996693121693122

Iteration 12: 182 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9996693121693122

Iteration 13: 177 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9996693121693122

Iteration 14: 177 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9996693121693122

Iteration 15: 176 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9996693121693122

Iteration 16: 172 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 1.0

Iteration 17: 170 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 1.0

Iteration 18: 167 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9996693121693122

Iteration 19: 164 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 1.0

Iteration 20: 170 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 1.0

Iteration 21: 176 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 1.0

Iteration 22: 173 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 1.0

Iteration 23: 165 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9996693121693122

Iteration 24: 161 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 1.0

Iteration 25: 158 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 1.0

Iteration 26: 153 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 1.0

Iteration 27: 153 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 1.0

Iteration 28: 152 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 1.0

Iteration 29: 151 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 1.0

Iteration 30: 151 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 1.0

Iteration 31: 150 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 1.0

Iteration 32: 150 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 1.0

Iteration 33: 147 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 1.0

Iteration 34: 146 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9993386243386243

Iteration 35: 148 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9993386243386243

Iteration 36: 147 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9996693121693122

Iteration 37: 146 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9993386243386243

Iteration 38: 146 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9993386243386243

Iteration 39: 145 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.998015873015873

Iteration 40: 143 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9996693121693122

Iteration 41: 142 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9976851851851852

Iteration 42: 141 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9976851851851852

Iteration 43: 142 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9976851851851852

Iteration 44: 140 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9976851851851852

Iteration 45: 138 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9986772486772486

Iteration 46: 137 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9976851851851852

Iteration 47: 136 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9976851851851852

Iteration 48: 133 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9976851851851852

Iteration 49: 133 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.998015873015873

Iteration 50: 133 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9976851851851852

Iteration 51: 128 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9973544973544973

Iteration 52: 131 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9973544973544973

Iteration 53: 130 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9976851851851852

Iteration 54: 128 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9976851851851852

Iteration 55: 129 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9976851851851852

Iteration 56: 128 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9976851851851852

Iteration 57: 126 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9970238095238095

Iteration 58: 127 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9973544973544973

Iteration 59: 125 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9970238095238095

Iteration 60: 125 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9970238095238095

Iteration 61: 123 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9970238095238095

Iteration 62: 123 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9966931216931217

Iteration 63: 123 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9970238095238095

Iteration 64: 121 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9966931216931217

Iteration 65: 120 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9966931216931217

Iteration 66: 118 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9966931216931217

Iteration 67: 118 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9966931216931217

Iteration 68: 117 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9963624338624338

Iteration 69: 117 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9966931216931217

Iteration 70: 117 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9963624338624338

Iteration 71: 114 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9966931216931217

Iteration 72: 112 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.996031746031746

Iteration 73: 112 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9950396825396826

Iteration 74: 112 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9953703703703705

Iteration 75: 111 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9963624338624338

Iteration 76: 110 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9943783068783068

Iteration 77: 110 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9947089947089947

Iteration 78: 111 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9950396825396826

Iteration 79: 110 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9966931216931217

Iteration 80: 108 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9966931216931217

Iteration 81: 109 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9966931216931217

Iteration 82: 109 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9963624338624338

Iteration 83: 108 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9940476190476191

Iteration 84: 107 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9947089947089947

Iteration 85: 108 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.996031746031746

Iteration 86: 108 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9947089947089947

Iteration 87: 107 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9953703703703705

Iteration 88: 106 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9950396825396826

Iteration 89: 106 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9943783068783068

Iteration 90: 105 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9943783068783068

Iteration 91: 105 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9940476190476191

Iteration 92: 104 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9943783068783068

Iteration 93: 103 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9963624338624338

Iteration 94: 102 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9937169312169313

Iteration 95: 102 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9809555629802873
	AUC = 0.9950396825396826

Iteration 96: 98 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9943783068783068

Iteration 97: 98 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9894179894179894

Iteration 98: 102 labelled instances
	Accuracy = 0.9824561403508771
	macro F1 = 0.9811507936507937
	AUC = 0.9920634920634921

Iteration 99: 101 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9937169312169313

Iteration 100: 100 labelled instances
	Accuracy = 0.9912280701754386
	macro F1 = 0.9905276277523889
	AUC = 0.9966931216931217

## Dry beans

In [9]:
dry_bean = fetch_ucirepo(id=602)
bean_df = pd.concat(
    [dry_bean.data.features, dry_bean.data.targets],
    axis=1
)
bean_df.head()

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRatio,Eccentricity,ConvexArea,EquivDiameter,Extent,Solidity,Roundness,Compactness,ShapeFactor1,ShapeFactor2,ShapeFactor3,ShapeFactor4,Class
0,28395,610.291,208.178117,173.888747,1.197191,0.549812,28715,190.141097,0.763923,0.988856,0.958027,0.913358,0.007332,0.003147,0.834222,0.998724,SEKER
1,28734,638.018,200.524796,182.734419,1.097356,0.411785,29172,191.272751,0.783968,0.984986,0.887034,0.953861,0.006979,0.003564,0.909851,0.998430,SEKER
2,29380,624.110,212.826130,175.931143,1.209713,0.562727,29690,193.410904,0.778113,0.989559,0.947849,0.908774,0.007244,0.003048,0.825871,0.999066,SEKER
3,30008,645.884,210.557999,182.516516,1.153638,0.498616,30724,195.467062,0.782681,0.976696,0.903936,0.928329,0.007017,0.003215,0.861794,0.994199,SEKER
4,30140,620.134,201.847882,190.279279,1.060798,0.333680,30417,195.896503,0.773098,0.990893,0.984877,0.970516,0.006697,0.003665,0.941900,0.999166,SEKER

In [10]:
X = dry_bean.data.features.to_numpy()
encoder = LabelEncoder()
y = dry_bean.data.targets.to_numpy().ravel()

n_classes = len(np.unique(y))

y = encoder.fit_transform(y)
bean_map = encoder.classes_
n_classes = len(np.unique(y))

X_pool, X_test, y_pool, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=51
)

In [7]:
acts = ['relu', 'leaky_relu', 'elu', 'gelu', 'swish']
name = "base"
for activation in acts:
    base_params = tune_params(X_pool, y_pool,
                              loss='sparse_categorical_crossentropy',
                              out_units=n_classes, out_act='softmax',
                              k=5, activation=activation,
                              balanced=False,
                              random_state=42,
                              n_trials=80,
                              export=True, file = f'params/dry_bean/{name}_{activation}.json'
    )

[I 2026-09-24 08:58:49,653] A new study created in memory with name: no-name-f7990ee7-4d94-46ba-ad02-462e9c640964
[I 2026-09-24 09:03:42,963] Trial 0 finished with value: 0.2359083592891693 and parameters: {'hidden_layer': 31, 'learning_rate': 0.0010504234588356461, 'momentum': 0.5672917461412101, 'weight_decay': 0.00025515089599309465}. Best is trial 0 with value: 0.2359083592891693.
[I 2026-09-24 09:08:12,182] Trial 1 finished with value: 0.20321372151374817 and parameters: {'hidden_layer': 74, 'learning_rate': 0.006456565189986694, 'momentum': 0.252843329131544, 'weight_decay': 1.3376349549684816e-05}. Best is trial 1 with value: 0.20321372151374817.
[I 2026-09-24 09:12:47,467] Trial 2 finished with value: 0.24281105399131775 and parameters: {'hidden_layer': 26, 'learning_rate': 0.0010622162477497206, 'momentum': 0.514092887324837, 'weight_decay': 4.989903460203718e-05}. Best is trial 1 with value: 0.20321372151374817.
[I 2026-09-24 09:14:24,182] Trial 3 finished with value: 0.20411601662635803 and parameters: {'hidden_layer': 16, 'learning_rate': 0.07885404716254263, 'momentum': 0.20300851453653232, 'weight_decay': 6.613936560012304e-05}. Best is trial 1 with value: 0.20321372151374817.
[I 2026-09-24 09:16:46,019] Trial 4 finished with value: 0.19645296037197113 and parameters: {'hidden_layer': 106, 'learning_rate': 0.0014567150954523447, 'momentum': 0.9685525587288641, 'weight_decay': 0.002561072847106718}. Best is trial 4 with value: 0.19645296037197113.
[I 2026-09-24 09:17:39,634] Trial 5 pruned.
[I 2026-09-24 09:18:20,646] Trial 6 pruned.
[I 2026-09-24 09:20:44,921] Trial 7 finished with value: 0.19586098194122314 and parameters: {'hidden_layer': 120, 'learning_rate': 0.028434218172087043, 'momentum': 0.39136265042181523, 'weight_decay': 0.000736881252101539}. Best is trial 7 with value: 0.19586098194122314.
[I 2026-09-24 09:21:38,680] Trial 8 pruned.
[I 2026-09-24 09:22:03,982] Trial 9 pruned.
[I 2026-09-24 09:23:27,324] Trial 10 finished with value: 0.1982518434524536 and parameters: {'hidden_layer': 125, 'learning_rate': 0.021868036253170162, 'momentum': 0.7324079968764058, 'weight_decay': 2.7204843792693914e-06}. Best is trial 7 with value: 0.19586098194122314.
[I 2026-09-24 09:26:13,389] Trial 11 finished with value: 0.19568899273872375 and parameters: {'hidden_layer': 101, 'learning_rate': 0.0009357658121462737, 'momentum': 0.975714921890348, 'weight_decay': 0.00038573835969758785}. Best is trial 11 with value: 0.19568899273872375.
[I 2026-09-24 09:27:10,727] Trial 12 pruned.
[I 2026-09-24 09:28:46,589] Trial 13 finished with value: 0.1942003220319748 and parameters: {'hidden_layer': 79, 'learning_rate': 0.03364465092534274, 'momentum': 0.7521197228274038, 'weight_decay': 0.00027002028206698776}. Best is trial 13 with value: 0.1942003220319748.
[I 2026-09-24 09:29:41,162] Trial 14 pruned.
[I 2026-09-24 09:30:36,061] Trial 15 pruned.
[I 2026-09-24 09:31:28,943] Trial 16 pruned.
[I 2026-09-24 09:34:27,629] Trial 17 finished with value: 0.1954241842031479 and parameters: {'hidden_layer': 99, 'learning_rate': 0.005443759756530936, 'momentum': 0.8499817591245498, 'weight_decay': 0.00038853782918254}. Best is trial 13 with value: 0.1942003220319748.
[I 2026-09-24 09:35:55,061] Trial 18 finished with value: 0.19775497913360596 and parameters: {'hidden_layer': 50, 'learning_rate': 0.029597581219994673, 'momentum': 0.6695199627118563, 'weight_decay': 1.6970312999708365e-05}. Best is trial 13 with value: 0.1942003220319748.
[I 2026-09-24 09:37:47,846] Trial 19 finished with value: 0.19647642970085144 and parameters: {'hidden_layer': 87, 'learning_rate': 0.008011485054400169, 'momentum': 0.8571414569269052, 'weight_decay': 8.925935172649852e-05}. Best is trial 13 with value: 0.1942003220319748.
[I 2026-09-24 09:41:21,083] Trial 20 finished with value: 0.19711387157440186 and parameters: {'hidden_layer': 109, 'learning_rate': 0.014858060219820945, 'momentum': 0.4063284165148949, 'weight_decay': 0.000572861774021501}. Best is trial 13 with value: 0.1942003220319748.
[I 2026-09-24 09:43:50,353] Trial 21 finished with value: 0.19790445268154144 and parameters: {'hidden_layer': 98, 'learning_rate': 0.0031850846858208037, 'momentum': 0.9097892164961137, 'weight_decay': 0.0003687595260193747}. Best is trial 13 with value: 0.1942003220319748.
[I 2026-09-24 09:44:46,069] Trial 22 finished with value: 0.19869691133499146 and parameters: {'hidden_layer': 77, 'learning_rate': 0.05112572131560338, 'momentum': 0.87160967535503, 'weight_decay': 0.00012190496234364359}. Best is trial 13 with value: 0.1942003220319748.
[I 2026-09-24 09:46:00,284] Trial 23 pruned.
[I 2026-09-24 09:46:50,514] Trial 24 pruned.
[I 2026-09-24 09:47:25,963] Trial 25 pruned.
[I 2026-09-24 09:47:56,742] Trial 26 pruned.
[I 2026-09-24 09:48:33,436] Trial 27 pruned.
[I 2026-09-24 09:49:49,587] Trial 28 finished with value: 0.20161303877830505 and parameters: {'hidden_layer': 81, 'learning_rate': 0.04987335605596431, 'momentum': 0.8621940303086408, 'weight_decay': 3.4453366384175525e-05}. Best is trial 13 with value: 0.1942003220319748.
[I 2026-09-24 09:50:58,908] Trial 29 pruned.
[I 2026-09-24 09:52:06,024] Trial 30 pruned.
[I 2026-09-24 09:52:31,851] Trial 31 pruned.
[I 2026-09-24 09:54:24,259] Trial 32 finished with value: 0.19669879972934723 and parameters: {'hidden_layer': 115, 'learning_rate': 0.0505817374461577, 'momentum': 0.41511970083926014, 'weight_decay': 0.0004705273484312752}. Best is trial 13 with value: 0.1942003220319748.
[I 2026-09-24 09:54:41,606] Trial 33 pruned.
[I 2026-09-24 09:55:53,715] Trial 34 pruned.
[I 2026-09-24 09:56:21,631] Trial 35 pruned.
[I 2026-09-24 09:57:16,730] Trial 36 pruned.
[I 2026-09-24 09:57:46,645] Trial 37 pruned.
[I 2026-09-24 09:58:13,798] Trial 38 pruned.
[I 2026-09-24 09:58:54,336] Trial 39 pruned.
[I 2026-09-24 10:00:04,079] Trial 40 pruned.
[I 2026-09-24 10:00:46,980] Trial 41 pruned.
[I 2026-09-24 10:01:26,210] Trial 42 pruned.
[I 2026-09-24 10:02:12,678] Trial 43 pruned.
[I 2026-09-24 10:03:16,363] Trial 44 pruned.
[I 2026-09-24 10:04:15,578] Trial 45 pruned.
[I 2026-09-24 10:04:53,376] Trial 46 pruned.
[I 2026-09-24 10:05:03,109] Trial 47 pruned.
[I 2026-09-24 10:05:59,945] Trial 48 pruned.
[I 2026-09-24 10:06:57,520] Trial 49 pruned.
[I 2026-09-24 10:07:56,366] Trial 50 pruned.
[I 2026-09-24 10:08:17,587] Trial 51 pruned.
[I 2026-09-24 10:08:56,897] Trial 52 pruned.
[I 2026-09-24 10:10:05,426] Trial 53 finished with value: 0.19670042395591736 and parameters: {'hidden_layer': 85, 'learning_rate': 0.02358927457162806, 'momentum': 0.8911685660235724, 'weight_decay': 3.230625301663292e-05}. Best is trial 13 with value: 0.1942003220319748.
[I 2026-09-24 10:11:30,572] Trial 54 finished with value: 0.19380834698677063 and parameters: {'hidden_layer': 107, 'learning_rate': 0.007758378811390079, 'momentum': 0.9414639060544645, 'weight_decay': 0.0001097303171328828}. Best is trial 54 with value: 0.19380834698677063.
[I 2026-09-24 10:11:50,706] Trial 55 pruned.
[I 2026-09-24 10:13:10,900] Trial 56 finished with value: 0.19593937695026398 and parameters: {'hidden_layer': 101, 'learning_rate': 0.002100455236256793, 'momentum': 0.989295810494104, 'weight_decay': 0.0005945152985652473}. Best is trial 54 with value: 0.19380834698677063.
[I 2026-09-24 10:13:25,634] Trial 57 pruned.
[I 2026-09-24 10:14:39,519] Trial 58 pruned.
[I 2026-09-24 10:14:58,249] Trial 59 pruned.
[I 2026-09-24 10:15:10,079] Trial 60 pruned.
[I 2026-09-24 10:16:28,019] Trial 61 finished with value: 0.19815218448638916 and parameters: {'hidden_layer': 109, 'learning_rate': 0.0023092980534152006, 'momentum': 0.9894408705263026, 'weight_decay': 0.0003188396754058078}. Best is trial 54 with value: 0.19380834698677063.
[I 2026-09-24 10:17:25,068] Trial 62 pruned.
[I 2026-09-24 10:17:43,068] Trial 63 pruned.
[I 2026-09-24 10:18:04,714] Trial 64 pruned.
[I 2026-09-24 10:19:13,964] Trial 65 pruned.
[I 2026-09-24 10:20:34,900] Trial 66 finished with value: 0.19574598968029022 and parameters: {'hidden_layer': 101, 'learning_rate': 0.005265838751299991, 'momentum': 0.9646506063521145, 'weight_decay': 0.0040609716439758406}. Best is trial 54 with value: 0.19380834698677063.
[I 2026-09-24 10:21:06,301] Trial 67 pruned.
[I 2026-09-24 10:22:53,079] Trial 68 finished with value: 0.19474612176418304 and parameters: {'hidden_layer': 96, 'learning_rate': 0.004196078257738516, 'momentum': 0.9597458588971624, 'weight_decay': 0.0001331198264197295}. Best is trial 54 with value: 0.19380834698677063.
[I 2026-09-24 10:23:53,226] Trial 69 pruned.
[I 2026-09-24 10:24:13,612] Trial 70 pruned.
[I 2026-09-24 10:26:21,936] Trial 71 finished with value: 0.19683311879634857 and parameters: {'hidden_layer': 100, 'learning_rate': 0.0029269328429250203, 'momentum': 0.9646273885897985, 'weight_decay': 0.00457834323102515}. Best is trial 54 with value: 0.19380834698677063.
[I 2026-09-24 10:26:37,380] Trial 72 pruned.
[I 2026-09-24 10:26:49,206] Trial 73 pruned.
[I 2026-09-24 10:27:17,025] Trial 74 pruned.
[I 2026-09-24 10:28:14,375] Trial 75 finished with value: 0.19711646437644958 and parameters: {'hidden_layer': 90, 'learning_rate': 0.005319891953000173, 'momentum': 0.9886148602139587, 'weight_decay': 0.00015413036860536844}. Best is trial 54 with value: 0.19380834698677063.
[I 2026-09-24 10:28:34,615] Trial 76 pruned.
[I 2026-09-24 10:28:49,714] Trial 77 pruned.
[I 2026-09-24 10:29:01,847] Trial 78 pruned.
[I 2026-09-24 10:29:59,150] Trial 79 pruned.
[I 2026-09-24 10:29:59,154] A new study created in memory with name: no-name-a76f5a42-c163-4cdd-a42d-f973a868b611

{'hidden_layer': 107, 'learning_rate': 0.007758378811390079, 'momentum': 0.9414639060544645, 'weight_decay': 0.0001097303171328828}
0.19380834698677063

[I 2026-09-24 10:34:40,683] Trial 0 finished with value: 0.603901743888855 and parameters: {'hidden_layer': 38, 'learning_rate': 0.0002673158232409953, 'momentum': 0.032274798726985035, 'weight_decay': 4.936605963515345e-05, 'leaky_relu_alpha': 0.003109727808447892}. Best is trial 0 with value: 0.603901743888855.
[I 2026-09-24 10:39:23,412] Trial 1 finished with value: 0.23986172676086426 and parameters: {'hidden_layer': 83, 'learning_rate': 0.0012903958116131534, 'momentum': 0.3565891977479561, 'weight_decay': 5.9950085693023085e-05, 'leaky_relu_alpha': 0.008350776258629306}. Best is trial 1 with value: 0.23986172676086426.
[I 2026-09-24 10:44:11,391] Trial 2 finished with value: 0.41579437255859375 and parameters: {'hidden_layer': 78, 'learning_rate': 0.0003941285306908751, 'momentum': 0.20072690389699424, 'weight_decay': 0.001403334804497561, 'leaky_relu_alpha': 0.004809521334064588}. Best is trial 1 with value: 0.23986172676086426.
[I 2026-09-24 10:49:39,590] Trial 3 finished with value: 0.2078244388103485 and parameters: {'hidden_layer': 115, 'learning_rate': 0.0013194216604102403, 'momentum': 0.7915970053733546, 'weight_decay': 1.3938878916897325e-06, 'leaky_relu_alpha': 0.03316395396476727}. Best is trial 3 with value: 0.2078244388103485.
[I 2026-09-24 10:51:49,539] Trial 4 finished with value: 0.2027515172958374 and parameters: {'hidden_layer': 34, 'learning_rate': 0.0417638367705893, 'momentum': 0.4477570982737073, 'weight_decay': 0.002593648510417523, 'leaky_relu_alpha': 0.0047153764594807775}. Best is trial 4 with value: 0.2027515172958374.
[I 2026-09-24 10:53:00,321] Trial 5 pruned.
[I 2026-09-24 10:58:08,207] Trial 6 finished with value: 0.2080414742231369 and parameters: {'hidden_layer': 28, 'learning_rate': 0.008913437433683129, 'momentum': 0.19702747869677012, 'weight_decay': 6.469622464482091e-05, 'leaky_relu_alpha': 0.20799307566446795}. Best is trial 4 with value: 0.2027515172958374.
[I 2026-09-24 11:00:42,588] Trial 7 finished with value: 0.19810841977596283 and parameters: {'hidden_layer': 61, 'learning_rate': 0.02269476706835649, 'momentum': 0.6081554124828484, 'weight_decay': 4.5408866354504585e-05, 'leaky_relu_alpha': 0.06691909951102508}. Best is trial 7 with value: 0.19810841977596283.
[I 2026-09-24 11:01:49,356] Trial 8 pruned.
[I 2026-09-24 11:04:41,840] Trial 9 finished with value: 0.20182998478412628 and parameters: {'hidden_layer': 32, 'learning_rate': 0.003951188455143487, 'momentum': 0.8956045152838437, 'weight_decay': 0.004648817832420735, 'leaky_relu_alpha': 0.005352502974701013}. Best is trial 7 with value: 0.19810841977596283.
[I 2026-09-24 11:06:22,650] Trial 10 finished with value: 0.197006493806839 and parameters: {'hidden_layer': 122, 'learning_rate': 0.08048139290158016, 'momentum': 0.6434291571362718, 'weight_decay': 0.0004966127414802385, 'leaky_relu_alpha': 0.11744087155075383}. Best is trial 10 with value: 0.197006493806839.
[I 2026-09-24 11:08:07,196] Trial 11 finished with value: 0.19848179817199707 and parameters: {'hidden_layer': 115, 'learning_rate': 0.07624610521788623, 'momentum': 0.6267164472615651, 'weight_decay': 0.0003771975447405042, 'leaky_relu_alpha': 0.12445487019592466}. Best is trial 10 with value: 0.197006493806839.
[I 2026-09-24 11:10:25,843] Trial 12 finished with value: 0.19912020862102509 and parameters: {'hidden_layer': 57, 'learning_rate': 0.020986041111394023, 'momentum': 0.6257945199054986, 'weight_decay': 0.00039015124210426425, 'leaky_relu_alpha': 0.07703718363882409}. Best is trial 10 with value: 0.197006493806839.
[I 2026-09-24 11:13:08,392] Trial 13 finished with value: 0.1972515881061554 and parameters: {'hidden_layer': 102, 'learning_rate': 0.018179617419872358, 'momentum': 0.5963531802723288, 'weight_decay': 0.00028890012543238564, 'leaky_relu_alpha': 0.06020544985797052}. Best is trial 10 with value: 0.197006493806839.
[I 2026-09-24 11:13:15,055] Trial 14 pruned.
[I 2026-09-24 11:17:29,202] Trial 15 finished with value: 0.19833363592624664 and parameters: {'hidden_layer': 102, 'learning_rate': 0.011121054068428126, 'momentum': 0.5441579024284446, 'weight_decay': 0.0006602858239216283, 'leaky_relu_alpha': 0.015081136163668869}. Best is trial 10 with value: 0.197006493806839.
[I 2026-09-24 11:18:56,352] Trial 16 finished with value: 0.19524262845516205 and parameters: {'hidden_layer': 101, 'learning_rate': 0.035382156738973346, 'momentum': 0.7550894030878125, 'weight_decay': 0.00019819931903280932, 'leaky_relu_alpha': 0.0014401784047655155}. Best is trial 16 with value: 0.19524262845516205.
[I 2026-09-24 11:19:03,291] Trial 17 pruned.
[I 2026-09-24 11:21:52,423] Trial 18 finished with value: 0.19932611286640167 and parameters: {'hidden_layer': 128, 'learning_rate': 0.005172676748685552, 'momentum': 0.8501820460969398, 'weight_decay': 1.5401776780459447e-05, 'leaky_relu_alpha': 0.0013245674783796872}. Best is trial 16 with value: 0.19524262845516205.
[I 2026-09-24 11:23:30,368] Trial 19 finished with value: 0.19709694385528564 and parameters: {'hidden_layer': 93, 'learning_rate': 0.035390563191852464, 'momentum': 0.6867812942765847, 'weight_decay': 0.00015039205693227878, 'leaky_relu_alpha': 0.0019902691309708303}. Best is trial 16 with value: 0.19524262845516205.
[I 2026-09-24 11:24:37,718] Trial 20 pruned.
[I 2026-09-24 11:24:59,831] Trial 21 pruned.
[I 2026-09-24 11:25:10,342] Trial 22 pruned.
[I 2026-09-24 11:27:25,116] Trial 23 finished with value: 0.19531384110450745 and parameters: {'hidden_layer': 94, 'learning_rate': 0.010737545297345396, 'momentum': 0.8566622459676208, 'weight_decay': 0.0001480695204064423, 'leaky_relu_alpha': 0.010176773265611623}. Best is trial 16 with value: 0.19524262845516205.
[I 2026-09-24 11:29:49,638] Trial 24 finished with value: 0.1970396339893341 and parameters: {'hidden_layer': 109, 'learning_rate': 0.007137355282100341, 'momentum': 0.8707928045861969, 'weight_decay': 0.0010712979101729697, 'leaky_relu_alpha': 0.011091640952733909}. Best is trial 16 with value: 0.19524262845516205.
[I 2026-09-24 11:32:02,598] Trial 25 finished with value: 0.1954733282327652 and parameters: {'hidden_layer': 121, 'learning_rate': 0.013163299799665643, 'momentum': 0.8280468069671507, 'weight_decay': 7.364843062155203e-06, 'leaky_relu_alpha': 0.03646449945675441}. Best is trial 16 with value: 0.19524262845516205.
[I 2026-09-24 11:34:18,959] Trial 26 finished with value: 0.19524314999580383 and parameters: {'hidden_layer': 95, 'learning_rate': 0.012905086420853355, 'momentum': 0.797234825656917, 'weight_decay': 4.30262099189048e-06, 'leaky_relu_alpha': 0.03603095053215448}. Best is trial 16 with value: 0.19524262845516205.
[I 2026-09-24 11:37:33,458] Trial 27 finished with value: 0.19772017002105713 and parameters: {'hidden_layer': 72, 'learning_rate': 0.0024888762901801053, 'momentum': 0.9133594305597316, 'weight_decay': 1.8606685467567196e-06, 'leaky_relu_alpha': 0.008817300995594305}. Best is trial 16 with value: 0.19524262845516205.
[I 2026-09-24 11:37:55,136] Trial 28 pruned.
[I 2026-09-24 11:38:12,310] Trial 29 pruned.
[I 2026-09-24 11:40:26,700] Trial 30 finished with value: 0.19512872397899628 and parameters: {'hidden_layer': 97, 'learning_rate': 0.012763357628083108, 'momentum': 0.8092746543510193, 'weight_decay': 8.409359792498953e-05, 'leaky_relu_alpha': 0.0031355408444088202}. Best is trial 30 with value: 0.19512872397899628.
[I 2026-09-24 11:42:28,285] Trial 31 finished with value: 0.19612613320350647 and parameters: {'hidden_layer': 98, 'learning_rate': 0.015154479456286908, 'momentum': 0.8315769362502637, 'weight_decay': 3.290281163442539e-05, 'leaky_relu_alpha': 0.0025638013039493727}. Best is trial 30 with value: 0.19512872397899628.
[I 2026-09-24 11:44:20,389] Trial 32 finished with value: 0.19639882445335388 and parameters: {'hidden_layer': 85, 'learning_rate': 0.030843708976824154, 'momentum': 0.5336967288494858, 'weight_decay': 8.388399136281809e-05, 'leaky_relu_alpha': 0.0071032743906346155}. Best is trial 30 with value: 0.19512872397899628.
[I 2026-09-24 11:46:41,283] Trial 33 finished with value: 0.19712038338184357 and parameters: {'hidden_layer': 76, 'learning_rate': 0.010216139482079226, 'momentum': 0.7884746179508222, 'weight_decay': 0.00023332306709800374, 'leaky_relu_alpha': 0.003648498060656107}. Best is trial 30 with value: 0.19512872397899628.
[I 2026-09-24 11:47:40,103] Trial 34 pruned.
[I 2026-09-24 11:49:02,648] Trial 35 finished with value: 0.19624394178390503 and parameters: {'hidden_layer': 80, 'learning_rate': 0.02679308799837865, 'momentum': 0.9402419130374733, 'weight_decay': 1.0575613839836302e-06, 'leaky_relu_alpha': 0.0015172028361134043}. Best is trial 30 with value: 0.19512872397899628.
[I 2026-09-24 11:50:03,366] Trial 36 finished with value: 0.1972985416650772 and parameters: {'hidden_layer': 93, 'learning_rate': 0.05327431611145708, 'momentum': 0.7589550153449514, 'weight_decay': 1.877286544625219e-05, 'leaky_relu_alpha': 0.0030589749825740416}. Best is trial 30 with value: 0.19512872397899628.
[I 2026-09-24 11:53:48,153] Trial 37 finished with value: 0.1963694542646408 and parameters: {'hidden_layer': 87, 'learning_rate': 0.01683533818786699, 'momentum': 0.4617036347879618, 'weight_decay': 5.644900105882747e-06, 'leaky_relu_alpha': 0.0069710310888475785}. Best is trial 30 with value: 0.19512872397899628.
[I 2026-09-24 11:54:49,871] Trial 38 pruned.
[I 2026-09-24 11:55:48,189] Trial 39 pruned.
[I 2026-09-24 11:56:46,930] Trial 40 pruned.
[I 2026-09-24 11:58:42,260] Trial 41 finished with value: 0.19597318768501282 and parameters: {'hidden_layer': 121, 'learning_rate': 0.013360649304005842, 'momentum': 0.824316525799339, 'weight_decay': 7.483179799334745e-06, 'leaky_relu_alpha': 0.03963874572254789}. Best is trial 30 with value: 0.19512872397899628.
[I 2026-09-24 11:59:22,889] Trial 42 pruned.
[I 2026-09-24 12:00:26,280] Trial 43 pruned.
[I 2026-09-24 12:00:41,961] Trial 44 pruned.
[I 2026-09-24 12:00:51,801] Trial 45 pruned.
[I 2026-09-24 12:01:59,049] Trial 46 pruned.
[I 2026-09-24 12:03:05,241] Trial 47 finished with value: 0.20050100982189178 and parameters: {'hidden_layer': 90, 'learning_rate': 0.02020554708860289, 'momentum': 0.9547217877150316, 'weight_decay': 6.878991933778184e-05, 'leaky_relu_alpha': 0.013807249956196659}. Best is trial 30 with value: 0.19512872397899628.
[I 2026-09-24 12:04:09,282] Trial 48 pruned.
[I 2026-09-24 12:05:01,508] Trial 49 pruned.
[I 2026-09-24 12:07:13,993] Trial 50 finished with value: 0.19619254767894745 and parameters: {'hidden_layer': 74, 'learning_rate': 0.029024540484097944, 'momentum': 0.6574676017711631, 'weight_decay': 0.00012269204780214306, 'leaky_relu_alpha': 0.005475817064856766}. Best is trial 30 with value: 0.19512872397899628.
[I 2026-09-24 12:07:53,245] Trial 51 pruned.
[I 2026-09-24 12:08:12,439] Trial 52 pruned.
[I 2026-09-24 12:10:00,727] Trial 53 finished with value: 0.19573616981506348 and parameters: {'hidden_layer': 119, 'learning_rate': 0.017639385884472784, 'momentum': 0.810206180991334, 'weight_decay': 1.985793656547893e-06, 'leaky_relu_alpha': 0.057931109241329916}. Best is trial 30 with value: 0.19512872397899628.
[I 2026-09-24 12:10:11,299] Trial 54 pruned.
[I 2026-09-24 12:10:34,127] Trial 55 pruned.
[I 2026-09-24 12:11:41,726] Trial 56 finished with value: 0.19510602951049805 and parameters: {'hidden_layer': 118, 'learning_rate': 0.044785578854672506, 'momentum': 0.734962964662905, 'weight_decay': 2.0211986654432807e-06, 'leaky_relu_alpha': 0.01649745463992016}. Best is trial 56 with value: 0.19510602951049805.
[I 2026-09-24 12:12:56,533] Trial 57 finished with value: 0.19704963266849518 and parameters: {'hidden_layer': 66, 'learning_rate': 0.0914951433634227, 'momentum': 0.7235939889414951, 'weight_decay': 0.00047727953911376887, 'leaky_relu_alpha': 0.015974298692542938}. Best is trial 56 with value: 0.19510602951049805.
[I 2026-09-24 12:13:11,767] Trial 58 pruned.
[I 2026-09-24 12:14:40,076] Trial 59 finished with value: 0.19284117221832275 and parameters: {'hidden_layer': 126, 'learning_rate': 0.038499144390277434, 'momentum': 0.8888210220929265, 'weight_decay': 5.114730565238182e-06, 'leaky_relu_alpha': 0.020452474706357127}. Best is trial 59 with value: 0.19284117221832275.
[I 2026-09-24 12:15:11,885] Trial 60 pruned.
[I 2026-09-24 12:15:21,444] Trial 61 pruned.
[I 2026-09-24 12:15:30,064] Trial 62 pruned.
[I 2026-09-24 12:15:41,745] Trial 63 pruned.
[I 2026-09-24 12:16:06,155] Trial 64 pruned.
[I 2026-09-24 12:16:14,649] Trial 65 pruned.
[I 2026-09-24 12:16:41,080] Trial 66 pruned.
[I 2026-09-24 12:18:33,000] Trial 67 finished with value: 0.19407455623149872 and parameters: {'hidden_layer': 98, 'learning_rate': 0.02334889067935584, 'momentum': 0.7830034856718441, 'weight_decay': 0.00010650509273347414, 'leaky_relu_alpha': 0.020691139571523996}. Best is trial 59 with value: 0.19284117221832275.
[I 2026-09-24 12:18:49,034] Trial 68 pruned.
[I 2026-09-24 12:18:58,983] Trial 69 pruned.
[I 2026-09-24 12:21:00,464] Trial 70 finished with value: 0.19549204409122467 and parameters: {'hidden_layer': 100, 'learning_rate': 0.030399217885501435, 'momentum': 0.6345207075278808, 'weight_decay': 0.00029178451747961754, 'leaky_relu_alpha': 0.013586527639412106}. Best is trial 59 with value: 0.19284117221832275.
[I 2026-09-24 12:21:16,604] Trial 71 pruned.
[I 2026-09-24 12:21:31,043] Trial 72 pruned.
[I 2026-09-24 12:22:39,539] Trial 73 finished with value: 0.1963152140378952 and parameters: {'hidden_layer': 105, 'learning_rate': 0.02608118578864961, 'momentum': 0.8574644686654628, 'weight_decay': 5.096998771120321e-06, 'leaky_relu_alpha': 0.04558563525842305}. Best is trial 59 with value: 0.19284117221832275.
[I 2026-09-24 12:23:31,023] Trial 74 pruned.
[I 2026-09-24 12:24:34,556] Trial 75 finished with value: 0.19915379583835602 and parameters: {'hidden_layer': 118, 'learning_rate': 0.06484543062795739, 'momentum': 0.7637567924390544, 'weight_decay': 0.0005044436850205751, 'leaky_relu_alpha': 0.03460778202491961}. Best is trial 59 with value: 0.19284117221832275.
[I 2026-09-24 12:24:55,587] Trial 76 pruned.
[I 2026-09-24 12:25:03,772] Trial 77 pruned.
[I 2026-09-24 12:25:19,488] Trial 78 pruned.
[I 2026-09-24 12:26:26,562] Trial 79 pruned.
[I 2026-09-24 12:26:26,572] A new study created in memory with name: no-name-4606e91e-aa02-4764-bb31-13fa1701fca3

{'hidden_layer': 126, 'learning_rate': 0.038499144390277434, 'momentum': 0.8888210220929265, 'weight_decay': 5.114730565238182e-06, 'leaky_relu_alpha': 0.020452474706357127}
0.19284117221832275

[I 2026-09-24 12:28:10,555] Trial 0 finished with value: 0.20084130764007568 and parameters: {'hidden_layer': 58, 'learning_rate': 0.0094677616697529, 'momentum': 0.9291702662166553, 'weight_decay': 6.679133460540766e-05, 'elu_alpha': 1.2326761011141363}. Best is trial 0 with value: 0.20084130764007568.
[I 2026-09-24 12:29:37,334] Trial 1 finished with value: 0.19823968410491943 and parameters: {'hidden_layer': 70, 'learning_rate': 0.06869919389678714, 'momentum': 0.7515212120359361, 'weight_decay': 6.7135691451640234e-06, 'elu_alpha': 0.10652297231932507}. Best is trial 1 with value: 0.19823968410491943.
[I 2026-09-24 12:33:20,755] Trial 2 finished with value: 0.20361976325511932 and parameters: {'hidden_layer': 40, 'learning_rate': 0.005478168211603529, 'momentum': 0.7312758087345064, 'weight_decay': 4.161424936052871e-06, 'elu_alpha': 1.1496989473310768}. Best is trial 1 with value: 0.19823968410491943.
[I 2026-09-24 12:39:18,291] Trial 3 finished with value: 0.24139642715454102 and parameters: {'hidden_layer': 113, 'learning_rate': 0.0004940003883595988, 'momentum': 0.7129020384661174, 'weight_decay': 7.027409187896037e-05, 'elu_alpha': 0.4927083154175087}. Best is trial 1 with value: 0.19823968410491943.
[I 2026-09-24 12:41:41,441] Trial 4 finished with value: 0.1999131143093109 and parameters: {'hidden_layer': 87, 'learning_rate': 0.025674255844109393, 'momentum': 0.5232610460271254, 'weight_decay': 0.00021925761814745666, 'elu_alpha': 0.31185670214059735}. Best is trial 1 with value: 0.19823968410491943.
[I 2026-09-24 12:43:02,978] Trial 5 finished with value: 0.1978568136692047 and parameters: {'hidden_layer': 82, 'learning_rate': 0.05615954987114987, 'momentum': 0.7170533982513475, 'weight_decay': 1.8984204646629973e-06, 'elu_alpha': 0.20765424657305565}. Best is trial 5 with value: 0.1978568136692047.
[I 2026-09-24 12:44:10,590] Trial 6 pruned.
[I 2026-09-24 12:45:33,410] Trial 7 pruned.
[I 2026-09-24 12:47:36,893] Trial 8 finished with value: 0.20002031326293945 and parameters: {'hidden_layer': 65, 'learning_rate': 0.010680572323239637, 'momentum': 0.8762790384893678, 'weight_decay': 2.8956564503382536e-06, 'elu_alpha': 0.7096403210141091}. Best is trial 5 with value: 0.1978568136692047.
[I 2026-09-24 12:48:42,923] Trial 9 pruned.
[I 2026-09-24 12:49:02,568] Trial 10 pruned.
[I 2026-09-24 12:50:09,400] Trial 11 pruned.
[I 2026-09-24 12:51:52,141] Trial 12 finished with value: 0.19493986666202545 and parameters: {'hidden_layer': 99, 'learning_rate': 0.027204588622188972, 'momentum': 0.7946529816586142, 'weight_decay': 1.3534465034385041e-06, 'elu_alpha': 0.1270444399638707}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 12:51:59,075] Trial 13 pruned.
[I 2026-09-24 12:53:47,346] Trial 14 finished with value: 0.19942548871040344 and parameters: {'hidden_layer': 86, 'learning_rate': 0.025668831214793398, 'momentum': 0.8406040915797465, 'weight_decay': 1.468908956680677e-05, 'elu_alpha': 0.7401036221230325}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 12:54:57,728] Trial 15 pruned.
[I 2026-09-24 12:55:28,948] Trial 16 pruned.
[I 2026-09-24 12:56:11,316] Trial 17 pruned.
[I 2026-09-24 12:57:44,510] Trial 18 finished with value: 0.20065221190452576 and parameters: {'hidden_layer': 29, 'learning_rate': 0.047937335927221374, 'momentum': 0.7993020685611713, 'weight_decay': 2.8000935231358404e-06, 'elu_alpha': 0.4101207379287637}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 12:58:06,482] Trial 19 pruned.
[I 2026-09-24 12:58:21,422] Trial 20 pruned.
[I 2026-09-24 12:59:42,394] Trial 21 finished with value: 0.19991448521614075 and parameters: {'hidden_layer': 71, 'learning_rate': 0.05883941398640401, 'momentum': 0.7708102433373246, 'weight_decay': 6.611006055728497e-06, 'elu_alpha': 0.14811558476770734}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 12:59:56,263] Trial 22 pruned.
[I 2026-09-24 13:00:10,646] Trial 23 pruned.
[I 2026-09-24 13:01:40,348] Trial 24 finished with value: 0.19697031378746033 and parameters: {'hidden_layer': 98, 'learning_rate': 0.09130087122969152, 'momentum': 0.5867893599766931, 'weight_decay': 1.9048843978881829e-06, 'elu_alpha': 0.2685039545360708}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:02:16,497] Trial 25 pruned.
[I 2026-09-24 13:02:29,312] Trial 26 pruned.
[I 2026-09-24 13:03:38,421] Trial 27 pruned.
[I 2026-09-24 13:05:00,439] Trial 28 finished with value: 0.20139841735363007 and parameters: {'hidden_layer': 100, 'learning_rate': 0.09809105797633447, 'momentum': 0.675031725973402, 'weight_decay': 1.4604273808019094e-05, 'elu_alpha': 0.8850526032599425}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:05:17,883] Trial 29 pruned.
[I 2026-09-24 13:06:36,902] Trial 30 finished with value: 0.19810137152671814 and parameters: {'hidden_layer': 54, 'learning_rate': 0.03740167770213086, 'momentum': 0.8317660164967574, 'weight_decay': 2.0645546704686517e-06, 'elu_alpha': 0.44038798762458675}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:07:54,477] Trial 31 finished with value: 0.19923850893974304 and parameters: {'hidden_layer': 47, 'learning_rate': 0.03737380226609939, 'momentum': 0.8476797170469037, 'weight_decay': 1.9061145913602492e-06, 'elu_alpha': 0.4344685641481927}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:09:40,966] Trial 32 finished with value: 0.19704051315784454 and parameters: {'hidden_layer': 61, 'learning_rate': 0.017259956728394192, 'momentum': 0.8122009808534341, 'weight_decay': 1.910986839663682e-06, 'elu_alpha': 0.23356658992282403}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:10:04,021] Trial 33 pruned.
[I 2026-09-24 13:11:34,874] Trial 34 finished with value: 0.19620254635810852 and parameters: {'hidden_layer': 80, 'learning_rate': 0.059771350858372964, 'momentum': 0.6629907361674573, 'weight_decay': 1.0491483179476086e-05, 'elu_alpha': 0.11921712008664472}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:14:06,636] Trial 35 finished with value: 0.1979590654373169 and parameters: {'hidden_layer': 58, 'learning_rate': 0.019845765883266437, 'momentum': 0.579166064958195, 'weight_decay': 1.0674957289902916e-05, 'elu_alpha': 0.10019487020116191}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:14:52,414] Trial 36 pruned.
[I 2026-09-24 13:15:26,228] Trial 37 pruned.
[I 2026-09-24 13:15:35,383] Trial 38 pruned.
[I 2026-09-24 13:16:06,560] Trial 39 pruned.
[I 2026-09-24 13:16:30,189] Trial 40 pruned.
[I 2026-09-24 13:17:48,071] Trial 41 finished with value: 0.19633616507053375 and parameters: {'hidden_layer': 83, 'learning_rate': 0.059956722758996966, 'momentum': 0.7014863212121675, 'weight_decay': 1.444844751656171e-06, 'elu_alpha': 0.19576348051015974}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:17:58,799] Trial 42 pruned.
[I 2026-09-24 13:19:13,376] Trial 43 finished with value: 0.19612836837768555 and parameters: {'hidden_layer': 67, 'learning_rate': 0.04365502221206119, 'momentum': 0.7951834480032415, 'weight_decay': 3.1848002837309736e-06, 'elu_alpha': 0.10668668560130351}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:19:29,476] Trial 44 pruned.
[I 2026-09-24 13:19:38,604] Trial 45 pruned.
[I 2026-09-24 13:20:57,992] Trial 46 finished with value: 0.19543702900409698 and parameters: {'hidden_layer': 85, 'learning_rate': 0.09778999752802484, 'momentum': 0.588784630001667, 'weight_decay': 8.673218004192193e-06, 'elu_alpha': 0.18138648746253938}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:21:58,422] Trial 47 pruned.
[I 2026-09-24 13:22:10,138] Trial 48 pruned.
[I 2026-09-24 13:23:14,489] Trial 49 pruned.
[I 2026-09-24 13:23:36,686] Trial 50 pruned.
[I 2026-09-24 13:23:45,680] Trial 51 pruned.
[I 2026-09-24 13:23:58,821] Trial 52 pruned.
[I 2026-09-24 13:24:10,224] Trial 53 pruned.
[I 2026-09-24 13:24:40,228] Trial 54 pruned.
[I 2026-09-24 13:24:55,170] Trial 55 pruned.
[I 2026-09-24 13:26:51,876] Trial 56 finished with value: 0.19956085085868835 and parameters: {'hidden_layer': 68, 'learning_rate': 0.04773242676204397, 'momentum': 0.35678699942365216, 'weight_decay': 2.667958121762555e-06, 'elu_alpha': 0.4514459008814846}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:27:07,402] Trial 57 pruned.
[I 2026-09-24 13:28:13,363] Trial 58 pruned.
[I 2026-09-24 13:30:24,227] Trial 59 finished with value: 0.1954105794429779 and parameters: {'hidden_layer': 107, 'learning_rate': 0.030262457081581283, 'momentum': 0.6534820192846571, 'weight_decay': 2.3674623200542435e-06, 'elu_alpha': 0.33354807610391035}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:32:15,121] Trial 60 finished with value: 0.19589726626873016 and parameters: {'hidden_layer': 119, 'learning_rate': 0.024526708210810953, 'momentum': 0.7867332536630233, 'weight_decay': 5.228290994347989e-06, 'elu_alpha': 0.358356690631324}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:32:25,137] Trial 61 pruned.
[I 2026-09-24 13:33:03,039] Trial 62 pruned.
[I 2026-09-24 13:33:18,230] Trial 63 pruned.
[I 2026-09-24 13:33:29,009] Trial 64 pruned.
[I 2026-09-24 13:35:32,045] Trial 65 finished with value: 0.20013880729675293 and parameters: {'hidden_layer': 116, 'learning_rate': 0.03105681939680557, 'momentum': 0.710056274097164, 'weight_decay': 1.3737653577924302e-05, 'elu_alpha': 0.8238459168322937}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:35:55,785] Trial 66 pruned.
[I 2026-09-24 13:36:07,591] Trial 67 pruned.
[I 2026-09-24 13:36:35,729] Trial 68 pruned.
[I 2026-09-24 13:38:16,811] Trial 69 finished with value: 0.1975308656692505 and parameters: {'hidden_layer': 103, 'learning_rate': 0.07382446699344986, 'momentum': 0.7903621836274789, 'weight_decay': 5.324481115051095e-06, 'elu_alpha': 0.39201995240119303}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:38:35,839] Trial 70 pruned.
[I 2026-09-24 13:38:56,004] Trial 71 pruned.
[I 2026-09-24 13:40:33,726] Trial 72 finished with value: 0.19893355667591095 and parameters: {'hidden_layer': 73, 'learning_rate': 0.062446021921027495, 'momentum': 0.6117529123828377, 'weight_decay': 2.2717134769086363e-06, 'elu_alpha': 0.23664189221259535}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:41:10,789] Trial 73 pruned.
[I 2026-09-24 13:43:00,869] Trial 74 finished with value: 0.1976684033870697 and parameters: {'hidden_layer': 86, 'learning_rate': 0.051120930846810075, 'momentum': 0.7488827909399318, 'weight_decay': 1.7278184319023555e-06, 'elu_alpha': 0.10350246830262085}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:43:51,112] Trial 75 pruned.
[I 2026-09-24 13:44:04,229] Trial 76 pruned.
[I 2026-09-24 13:45:10,253] Trial 77 finished with value: 0.19977426528930664 and parameters: {'hidden_layer': 79, 'learning_rate': 0.08023982884814143, 'momentum': 0.7280407158581821, 'weight_decay': 1.0193958915591635e-06, 'elu_alpha': 0.3349185494023845}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:45:20,969] Trial 78 pruned.
[I 2026-09-24 13:46:51,158] Trial 79 finished with value: 0.19442996382713318 and parameters: {'hidden_layer': 101, 'learning_rate': 0.02051626937237295, 'momentum': 0.8864171644674076, 'weight_decay': 4.672075226981389e-06, 'elu_alpha': 0.14735774864882512}. Best is trial 79 with value: 0.19442996382713318.
[I 2026-09-24 13:46:51,164] A new study created in memory with name: no-name-7d2b3d2e-9c37-496a-8021-b00d1ccb06d8

{'hidden_layer': 101, 'learning_rate': 0.02051626937237295, 'momentum': 0.8864171644674076, 'weight_decay': 4.672075226981389e-06, 'elu_alpha': 0.14735774864882512}
0.19442996382713318

[I 2026-09-24 13:51:52,237] Trial 0 finished with value: 0.20575518906116486 and parameters: {'hidden_layer': 19, 'learning_rate': 0.006891787018792772, 'momentum': 0.09777210430386579, 'weight_decay': 7.179828845546757e-06}. Best is trial 0 with value: 0.20575518906116486.
[I 2026-09-24 13:56:52,296] Trial 1 finished with value: 0.41323143243789673 and parameters: {'hidden_layer': 89, 'learning_rate': 0.0002451645106203906, 'momentum': 0.553913379963981, 'weight_decay': 0.001562107187700209}. Best is trial 0 with value: 0.20575518906116486.
[I 2026-09-24 14:02:22,269] Trial 2 finished with value: 0.21816515922546387 and parameters: {'hidden_layer': 62, 'learning_rate': 0.00015708629257586912, 'momentum': 0.9609589914977039, 'weight_decay': 1.1241140911007148e-05}. Best is trial 0 with value: 0.20575518906116486.
[I 2026-09-24 14:07:59,571] Trial 3 finished with value: 0.2898070514202118 and parameters: {'hidden_layer': 49, 'learning_rate': 0.0008313006017550257, 'momentum': 0.2302845652836995, 'weight_decay': 6.150789033845649e-05}. Best is trial 0 with value: 0.20575518906116486.
[I 2026-09-24 14:12:57,466] Trial 4 finished with value: 0.21440613269805908 and parameters: {'hidden_layer': 111, 'learning_rate': 0.005078250190460047, 'momentum': 0.012537435306102303, 'weight_decay': 6.025493186483491e-06}. Best is trial 0 with value: 0.20575518906116486.
[I 2026-09-24 14:13:54,918] Trial 5 pruned.
[I 2026-09-24 14:15:11,217] Trial 6 finished with value: 0.19694772362709045 and parameters: {'hidden_layer': 102, 'learning_rate': 0.03317214422993249, 'momentum': 0.8242836317454394, 'weight_decay': 0.0019039840433363454}. Best is trial 6 with value: 0.19694772362709045.
[I 2026-09-24 14:20:57,050] Trial 7 finished with value: 0.20777936279773712 and parameters: {'hidden_layer': 123, 'learning_rate': 0.0028292906326045555, 'momentum': 0.6369089389086, 'weight_decay': 1.0188195991368528e-05}. Best is trial 6 with value: 0.19694772362709045.
[I 2026-09-24 14:22:33,086] Trial 8 finished with value: 0.19699713587760925 and parameters: {'hidden_layer': 47, 'learning_rate': 0.050370251981576755, 'momentum': 0.7089024845032805, 'weight_decay': 0.0001231096374585953}. Best is trial 6 with value: 0.19694772362709045.
[I 2026-09-24 14:23:50,458] Trial 9 finished with value: 0.207393616437912 and parameters: {'hidden_layer': 30, 'learning_rate': 0.02223514432485003, 'momentum': 0.7771346221689707, 'weight_decay': 0.008944563751615736}. Best is trial 6 with value: 0.19694772362709045.
[I 2026-09-24 14:24:05,898] Trial 10 pruned.
[I 2026-09-24 14:25:14,880] Trial 11 finished with value: 0.19851073622703552 and parameters: {'hidden_layer': 89, 'learning_rate': 0.0975687790093705, 'momentum': 0.7748839798642029, 'weight_decay': 0.0004014898189149335}. Best is trial 6 with value: 0.19694772362709045.
[I 2026-09-24 14:25:40,810] Trial 12 pruned.
[I 2026-09-24 14:27:10,558] Trial 13 finished with value: 0.19835856556892395 and parameters: {'hidden_layer': 103, 'learning_rate': 0.02481998245335462, 'momentum': 0.7980943876831551, 'weight_decay': 0.0002626637235614239}. Best is trial 6 with value: 0.19694772362709045.
[I 2026-09-24 14:31:38,062] Trial 14 finished with value: 0.19829809665679932 and parameters: {'hidden_layer': 77, 'learning_rate': 0.011991011216953399, 'momentum': 0.3615646926391501, 'weight_decay': 1.3222224483070426e-06}. Best is trial 6 with value: 0.19694772362709045.
[I 2026-09-24 14:32:34,492] Trial 15 pruned.
[I 2026-09-24 14:32:41,930] Trial 16 pruned.
[I 2026-09-24 14:33:15,984] Trial 17 pruned.
[I 2026-09-24 14:34:51,292] Trial 18 finished with value: 0.19529667496681213 and parameters: {'hidden_layer': 75, 'learning_rate': 0.03779461258207708, 'momentum': 0.85413247408913, 'weight_decay': 0.0006828015779214209}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 14:40:08,694] Trial 19 finished with value: 0.20237627625465393 and parameters: {'hidden_layer': 103, 'learning_rate': 0.0013478980412398357, 'momentum': 0.8632164460062707, 'weight_decay': 0.0004304674915922645}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 14:40:40,944] Trial 20 pruned.
[I 2026-09-24 14:41:56,795] Trial 21 finished with value: 0.19893045723438263 and parameters: {'hidden_layer': 51, 'learning_rate': 0.0480671312407278, 'momentum': 0.7042105767418685, 'weight_decay': 0.00016711693061299278}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 14:43:27,951] Trial 22 finished with value: 0.20145824551582336 and parameters: {'hidden_layer': 78, 'learning_rate': 0.09040221325086195, 'momentum': 0.8545645506223605, 'weight_decay': 3.6498970378523624e-05}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 14:45:22,202] Trial 23 finished with value: 0.2006315439939499 and parameters: {'hidden_layer': 37, 'learning_rate': 0.029300038954612015, 'momentum': 0.6976390807355909, 'weight_decay': 0.003006159822106426}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 14:46:23,501] Trial 24 finished with value: 0.20253288745880127 and parameters: {'hidden_layer': 59, 'learning_rate': 0.044903086621356426, 'momentum': 0.8886546426311894, 'weight_decay': 0.0013774989047240142}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 14:49:22,629] Trial 25 finished with value: 0.19829657673835754 and parameters: {'hidden_layer': 101, 'learning_rate': 0.014108449383821478, 'momentum': 0.6201576297766347, 'weight_decay': 0.00021510426570136107}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 14:53:46,644] Trial 26 finished with value: 0.1989184021949768 and parameters: {'hidden_layer': 115, 'learning_rate': 0.005331365427456205, 'momentum': 0.7344779928020256, 'weight_decay': 0.0007121231802618726}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 14:56:05,296] Trial 27 finished with value: 0.1965148001909256 and parameters: {'hidden_layer': 83, 'learning_rate': 0.032809097705181436, 'momentum': 0.5298618735058961, 'weight_decay': 2.5850843603593917e-05}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 14:58:46,875] Trial 28 finished with value: 0.1979704052209854 and parameters: {'hidden_layer': 83, 'learning_rate': 0.01797602261490874, 'momentum': 0.5345051931822747, 'weight_decay': 1.842947412715056e-05}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 14:59:44,460] Trial 29 pruned.
[I 2026-09-24 15:00:45,310] Trial 30 pruned.
[I 2026-09-24 15:00:57,724] Trial 31 pruned.
[I 2026-09-24 15:02:03,323] Trial 32 finished with value: 0.20257997512817383 and parameters: {'hidden_layer': 80, 'learning_rate': 0.06659219302989285, 'momentum': 0.9295216036804727, 'weight_decay': 2.7624915620023087e-05}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 15:04:12,515] Trial 33 finished with value: 0.19727082550525665 and parameters: {'hidden_layer': 57, 'learning_rate': 0.03275374729225103, 'momentum': 0.628820457216749, 'weight_decay': 0.001320333266073714}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 15:04:25,636] Trial 34 pruned.
[I 2026-09-24 15:04:48,899] Trial 35 pruned.
[I 2026-09-24 15:05:00,349] Trial 36 pruned.
[I 2026-09-24 15:06:10,545] Trial 37 pruned.
[I 2026-09-24 15:06:47,144] Trial 38 pruned.
[I 2026-09-24 15:07:04,725] Trial 39 pruned.
[I 2026-09-24 15:08:10,249] Trial 40 pruned.
[I 2026-09-24 15:09:53,114] Trial 41 finished with value: 0.19749097526073456 and parameters: {'hidden_layer': 56, 'learning_rate': 0.029570955457305974, 'momentum': 0.6476845787847544, 'weight_decay': 0.0013498124920780124}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 15:10:05,069] Trial 42 pruned.
[I 2026-09-24 15:10:23,608] Trial 43 pruned.
[I 2026-09-24 15:11:00,762] Trial 44 pruned.
[I 2026-09-24 15:12:33,037] Trial 45 finished with value: 0.1972278654575348 and parameters: {'hidden_layer': 86, 'learning_rate': 0.07409963871761341, 'momentum': 0.6479482400859403, 'weight_decay': 0.0005525026044098466}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 15:14:01,813] Trial 46 finished with value: 0.19460535049438477 and parameters: {'hidden_layer': 86, 'learning_rate': 0.06916135455563951, 'momentum': 0.8404367717780885, 'weight_decay': 0.0005393788572166543}. Best is trial 46 with value: 0.19460535049438477.
[I 2026-09-24 15:14:19,080] Trial 47 pruned.
[I 2026-09-24 15:16:17,016] Trial 48 finished with value: 0.19739466905593872 and parameters: {'hidden_layer': 75, 'learning_rate': 0.0170045814294272, 'momentum': 0.8414974132717912, 'weight_decay': 0.00026927077460735596}. Best is trial 46 with value: 0.19460535049438477.
[I 2026-09-24 15:17:17,168] Trial 49 pruned.
[I 2026-09-24 15:17:31,539] Trial 50 pruned.
[I 2026-09-24 15:19:13,969] Trial 51 finished with value: 0.19591274857521057 and parameters: {'hidden_layer': 87, 'learning_rate': 0.07164054702365916, 'momentum': 0.66204212828668, 'weight_decay': 0.0003698483090603026}. Best is trial 46 with value: 0.19460535049438477.
[I 2026-09-24 15:19:21,887] Trial 52 pruned.
[I 2026-09-24 15:19:32,774] Trial 53 pruned.
[I 2026-09-24 15:19:42,540] Trial 54 pruned.
[I 2026-09-24 15:20:03,650] Trial 55 pruned.
[I 2026-09-24 15:21:20,786] Trial 56 finished with value: 0.19661568105220795 and parameters: {'hidden_layer': 90, 'learning_rate': 0.059486917190477544, 'momentum': 0.838874118644012, 'weight_decay': 0.0008065864570585746}. Best is trial 46 with value: 0.19460535049438477.
[I 2026-09-24 15:21:34,185] Trial 57 pruned.
[I 2026-09-24 15:21:45,018] Trial 58 pruned.
[I 2026-09-24 15:21:52,785] Trial 59 pruned.
[I 2026-09-24 15:22:13,267] Trial 60 pruned.
[I 2026-09-24 15:23:33,349] Trial 61 finished with value: 0.19770966470241547 and parameters: {'hidden_layer': 85, 'learning_rate': 0.04385456976729937, 'momentum': 0.6730250798944951, 'weight_decay': 0.00013109595717075218}. Best is trial 46 with value: 0.19460535049438477.
[I 2026-09-24 15:23:47,528] Trial 62 pruned.
[I 2026-09-24 15:24:01,731] Trial 63 pruned.
[I 2026-09-24 15:25:20,444] Trial 64 finished with value: 0.19972053170204163 and parameters: {'hidden_layer': 67, 'learning_rate': 0.055655998797402156, 'momentum': 0.7104026979540365, 'weight_decay': 0.00016434921997229317}. Best is trial 46 with value: 0.19460535049438477.
[I 2026-09-24 15:25:35,967] Trial 65 pruned.
[I 2026-09-24 15:25:53,167] Trial 66 pruned.
[I 2026-09-24 15:26:06,597] Trial 67 pruned.
[I 2026-09-24 15:27:01,132] Trial 68 pruned.
[I 2026-09-24 15:27:39,216] Trial 69 pruned.
[I 2026-09-24 15:30:19,191] Trial 70 finished with value: 0.196393221616745 and parameters: {'hidden_layer': 117, 'learning_rate': 0.028145750272882214, 'momentum': 0.5697577291863885, 'weight_decay': 8.523246351071095e-05}. Best is trial 46 with value: 0.19460535049438477.
[I 2026-09-24 15:30:45,589] Trial 71 pruned.
[I 2026-09-24 15:31:08,215] Trial 72 pruned.
[I 2026-09-24 15:32:47,414] Trial 73 finished with value: 0.1958395540714264 and parameters: {'hidden_layer': 126, 'learning_rate': 0.043138055778235936, 'momentum': 0.6025739805330247, 'weight_decay': 6.788219702541154e-05}. Best is trial 46 with value: 0.19460535049438477.
[I 2026-09-24 15:33:07,735] Trial 74 pruned.
[I 2026-09-24 15:34:35,029] Trial 75 finished with value: 0.19626855850219727 and parameters: {'hidden_layer': 126, 'learning_rate': 0.05958608850033863, 'momentum': 0.5968630550898557, 'weight_decay': 2.8593230643194416e-05}. Best is trial 46 with value: 0.19460535049438477.
[I 2026-09-24 15:36:13,233] Trial 76 finished with value: 0.19676615297794342 and parameters: {'hidden_layer': 128, 'learning_rate': 0.06558416933850619, 'momentum': 0.5933028169162893, 'weight_decay': 3.114094506176348e-05}. Best is trial 46 with value: 0.19460535049438477.
[I 2026-09-24 15:36:26,409] Trial 77 pruned.
[I 2026-09-24 15:37:41,800] Trial 78 finished with value: 0.19852006435394287 and parameters: {'hidden_layer': 120, 'learning_rate': 0.09923464968031531, 'momentum': 0.6674791769262818, 'weight_decay': 2.553081621021435e-05}. Best is trial 46 with value: 0.19460535049438477.
[I 2026-09-24 15:37:52,255] Trial 79 pruned.
[I 2026-09-24 15:37:52,260] A new study created in memory with name: no-name-cc5c571f-eb59-481b-9318-d566e9146194

{'hidden_layer': 86, 'learning_rate': 0.06916135455563951, 'momentum': 0.8404367717780885, 'weight_decay': 0.0005393788572166543}
0.19460535049438477

[I 2026-09-24 15:43:04,131] Trial 0 finished with value: 0.21250960230827332 and parameters: {'hidden_layer': 46, 'learning_rate': 0.0061649117765305295, 'momentum': 0.026327865999117597, 'weight_decay': 3.4252575969670253e-06}. Best is trial 0 with value: 0.21250960230827332.
[I 2026-09-24 15:49:11,801] Trial 1 finished with value: 0.5587712526321411 and parameters: {'hidden_layer': 94, 'learning_rate': 0.00014306667156999147, 'momentum': 0.5856017619536737, 'weight_decay': 6.598749807683256e-05}. Best is trial 0 with value: 0.21250960230827332.
[I 2026-09-24 15:51:33,281] Trial 2 finished with value: 0.19777460396289825 and parameters: {'hidden_layer': 86, 'learning_rate': 0.01000314757145471, 'momentum': 0.915372569690932, 'weight_decay': 6.87168975312532e-05}. Best is trial 2 with value: 0.19777460396289825.
[I 2026-09-24 15:56:42,992] Trial 3 finished with value: 0.22301384806632996 and parameters: {'hidden_layer': 33, 'learning_rate': 0.006216506625991501, 'momentum': 0.4984433135412846, 'weight_decay': 0.008491086718110274}. Best is trial 2 with value: 0.19777460396289825.
[I 2026-09-24 16:02:57,341] Trial 4 finished with value: 0.2726334035396576 and parameters: {'hidden_layer': 42, 'learning_rate': 0.0013104994974122816, 'momentum': 0.07899491542688226, 'weight_decay': 0.0003529972369239509}. Best is trial 2 with value: 0.19777460396289825.
[I 2026-09-24 16:04:07,917] Trial 5 pruned.
[I 2026-09-24 16:05:18,009] Trial 6 pruned.
[I 2026-09-24 16:06:28,662] Trial 7 pruned.
[I 2026-09-24 16:07:37,123] Trial 8 pruned.
[I 2026-09-24 16:08:43,956] Trial 9 pruned.
[I 2026-09-24 16:08:51,061] Trial 10 pruned.
[I 2026-09-24 16:10:19,754] Trial 11 finished with value: 0.1976487934589386 and parameters: {'hidden_layer': 88, 'learning_rate': 0.010260998890041565, 'momentum': 0.9588329798305062, 'weight_decay': 6.074992551811758e-06}. Best is trial 11 with value: 0.1976487934589386.
[I 2026-09-24 16:10:27,478] Trial 12 pruned.
[I 2026-09-24 16:12:50,500] Trial 13 finished with value: 0.19922514259815216 and parameters: {'hidden_layer': 90, 'learning_rate': 0.015421609753837625, 'momentum': 0.7968422272088567, 'weight_decay': 9.918751620350613e-06}. Best is trial 11 with value: 0.1976487934589386.
[I 2026-09-24 16:14:33,702] Trial 14 finished with value: 0.1990017145872116 and parameters: {'hidden_layer': 111, 'learning_rate': 0.09200904227941106, 'momentum': 0.8046245456880503, 'weight_decay': 0.0001007830655305349}. Best is trial 11 with value: 0.1976487934589386.
[I 2026-09-24 16:18:29,963] Trial 15 finished with value: 0.19998875260353088 and parameters: {'hidden_layer': 80, 'learning_rate': 0.0059887424434836726, 'momentum': 0.8169002654838706, 'weight_decay': 7.386904756271259e-05}. Best is trial 11 with value: 0.1976487934589386.
[I 2026-09-24 16:22:31,287] Trial 16 finished with value: 0.19941000640392303 and parameters: {'hidden_layer': 109, 'learning_rate': 0.015495931617855707, 'momentum': 0.6592528483197415, 'weight_decay': 1.0945696291878523e-06}. Best is trial 11 with value: 0.1976487934589386.
[I 2026-09-24 16:24:27,240] Trial 17 finished with value: 0.19826741516590118 and parameters: {'hidden_layer': 72, 'learning_rate': 0.015898532957276987, 'momentum': 0.8846006660501893, 'weight_decay': 1.1232584065115825e-05}. Best is trial 11 with value: 0.1976487934589386.
[I 2026-09-24 16:25:33,602] Trial 18 pruned.
[I 2026-09-24 16:25:46,911] Trial 19 pruned.
[I 2026-09-24 16:26:58,702] Trial 20 pruned.
[I 2026-09-24 16:28:47,483] Trial 21 finished with value: 0.199599951505661 and parameters: {'hidden_layer': 75, 'learning_rate': 0.014136034577610002, 'momentum': 0.9022519791985952, 'weight_decay': 1.1972582786534356e-05}. Best is trial 11 with value: 0.1976487934589386.
[I 2026-09-24 16:31:33,850] Trial 22 finished with value: 0.19863054156303406 and parameters: {'hidden_layer': 70, 'learning_rate': 0.010182708559413223, 'momentum': 0.8455293335046096, 'weight_decay': 3.6110792848455234e-06}. Best is trial 11 with value: 0.1976487934589386.
[I 2026-09-24 16:31:48,150] Trial 23 pruned.
[I 2026-09-24 16:33:31,948] Trial 24 finished with value: 0.19720658659934998 and parameters: {'hidden_layer': 61, 'learning_rate': 0.0683777603178037, 'momentum': 0.7518242227052419, 'weight_decay': 8.356145520676276e-06}. Best is trial 24 with value: 0.19720658659934998.
[I 2026-09-24 16:33:46,919] Trial 25 pruned.
[I 2026-09-24 16:34:05,080] Trial 26 pruned.
[I 2026-09-24 16:34:22,597] Trial 27 pruned.
[I 2026-09-24 16:36:23,944] Trial 28 finished with value: 0.1973981410264969 and parameters: {'hidden_layer': 97, 'learning_rate': 0.00818921985462438, 'momentum': 0.9499632066132147, 'weight_decay': 5.480607671976691e-06}. Best is trial 24 with value: 0.19720658659934998.
[I 2026-09-24 16:36:33,158] Trial 29 pruned.
[I 2026-09-24 16:36:51,672] Trial 30 pruned.
[I 2026-09-24 16:39:30,647] Trial 31 finished with value: 0.20010456442832947 and parameters: {'hidden_layer': 84, 'learning_rate': 0.008549688325124111, 'momentum': 0.8609180273688692, 'weight_decay': 5.8082535529192035e-06}. Best is trial 24 with value: 0.19720658659934998.
[I 2026-09-24 16:40:11,569] Trial 32 pruned.
[I 2026-09-24 16:42:08,682] Trial 33 finished with value: 0.20012874901294708 and parameters: {'hidden_layer': 77, 'learning_rate': 0.004266443901339644, 'momentum': 0.9525553792455741, 'weight_decay': 4.5453748480257306e-05}. Best is trial 24 with value: 0.19720658659934998.
[I 2026-09-24 16:45:30,925] Trial 34 finished with value: 0.19821128249168396 and parameters: {'hidden_layer': 66, 'learning_rate': 0.009578362150725188, 'momentum': 0.8490648336997053, 'weight_decay': 2.0653311014890374e-06}. Best is trial 24 with value: 0.19720658659934998.
[I 2026-09-24 16:50:57,564] Trial 35 finished with value: 0.19933392107486725 and parameters: {'hidden_layer': 54, 'learning_rate': 0.007214825055347033, 'momentum': 0.6124495848821656, 'weight_decay': 5.85195413252967e-06}. Best is trial 24 with value: 0.19720658659934998.
[I 2026-09-24 16:53:15,244] Trial 36 finished with value: 0.1979309767484665 and parameters: {'hidden_layer': 96, 'learning_rate': 0.024401712979595366, 'momentum': 0.7608041916472184, 'weight_decay': 1.3992530086201583e-05}. Best is trial 24 with value: 0.19720658659934998.
[I 2026-09-24 16:54:22,304] Trial 37 pruned.
[I 2026-09-24 16:55:19,483] Trial 38 pruned.
[I 2026-09-24 16:56:24,907] Trial 39 pruned.
[I 2026-09-24 16:59:21,465] Trial 40 finished with value: 0.19824562966823578 and parameters: {'hidden_layer': 52, 'learning_rate': 0.020953864772427295, 'momentum': 0.6637428714922422, 'weight_decay': 5.3005062791574354e-05}. Best is trial 24 with value: 0.19720658659934998.
[I 2026-09-24 17:00:40,242] Trial 41 finished with value: 0.20059756934642792 and parameters: {'hidden_layer': 103, 'learning_rate': 0.0663849416168183, 'momentum': 0.7708130078310533, 'weight_decay': 1.6806571083466766e-05}. Best is trial 24 with value: 0.19720658659934998.
[I 2026-09-24 17:01:55,712] Trial 42 pruned.
[I 2026-09-24 17:04:05,819] Trial 43 finished with value: 0.1990853250026703 and parameters: {'hidden_layer': 117, 'learning_rate': 0.022756013785553603, 'momentum': 0.7423763289923636, 'weight_decay': 1.7483256984448636e-05}. Best is trial 24 with value: 0.19720658659934998.
[I 2026-09-24 17:04:46,948] Trial 44 pruned.
[I 2026-09-24 17:05:45,520] Trial 45 pruned.
[I 2026-09-24 17:07:28,640] Trial 46 finished with value: 0.19684985280036926 and parameters: {'hidden_layer': 97, 'learning_rate': 0.018728531471935195, 'momentum': 0.9478700338326816, 'weight_decay': 4.362214357026963e-06}. Best is trial 46 with value: 0.19684985280036926.
[I 2026-09-24 17:08:39,636] Trial 47 pruned.
[I 2026-09-24 17:08:58,169] Trial 48 pruned.
[I 2026-09-24 17:10:24,354] Trial 49 finished with value: 0.19877851009368896 and parameters: {'hidden_layer': 78, 'learning_rate': 0.01669774558316397, 'momentum': 0.9353162498410585, 'weight_decay': 1.2751894549613142e-06}. Best is trial 46 with value: 0.19684985280036926.
[I 2026-09-24 17:13:17,068] Trial 50 finished with value: 0.1973399519920349 and parameters: {'hidden_layer': 49, 'learning_rate': 0.011225010858308642, 'momentum': 0.8202419601075456, 'weight_decay': 4.35474920753278e-06}. Best is trial 46 with value: 0.19684985280036926.
[I 2026-09-24 17:14:18,102] Trial 51 pruned.
[I 2026-09-24 17:15:04,058] Trial 52 pruned.
[I 2026-09-24 17:15:24,754] Trial 53 pruned.
[I 2026-09-24 17:15:38,206] Trial 54 pruned.
[I 2026-09-24 17:17:38,668] Trial 55 finished with value: 0.19917576014995575 and parameters: {'hidden_layer': 48, 'learning_rate': 0.03284981046221159, 'momentum': 0.7988805782155435, 'weight_decay': 0.0010583311775070657}. Best is trial 46 with value: 0.19684985280036926.
[I 2026-09-24 17:19:39,036] Trial 56 finished with value: 0.1994093954563141 and parameters: {'hidden_layer': 101, 'learning_rate': 0.010724588701596689, 'momentum': 0.9265297996461723, 'weight_decay': 2.4288103075288778e-05}. Best is trial 46 with value: 0.19684985280036926.
[I 2026-09-24 17:20:31,435] Trial 57 pruned.
[I 2026-09-24 17:20:49,952] Trial 58 pruned.
[I 2026-09-24 17:21:04,540] Trial 59 pruned.
[I 2026-09-24 17:22:14,753] Trial 60 pruned.
[I 2026-09-24 17:24:07,695] Trial 61 finished with value: 0.19658465683460236 and parameters: {'hidden_layer': 99, 'learning_rate': 0.04548237754227203, 'momentum': 0.792845485986771, 'weight_decay': 1.2372930143932302e-05}. Best is trial 61 with value: 0.19658465683460236.
[I 2026-09-24 17:24:16,188] Trial 62 pruned.
[I 2026-09-24 17:25:26,443] Trial 63 finished with value: 0.19822059571743011 and parameters: {'hidden_layer': 109, 'learning_rate': 0.06535935321830195, 'momentum': 0.8967666480358648, 'weight_decay': 1.1922255552225076e-05}. Best is trial 61 with value: 0.19658465683460236.
[I 2026-09-24 17:25:40,672] Trial 64 pruned.
[I 2026-09-24 17:26:00,271] Trial 65 pruned.
[I 2026-09-24 17:29:20,345] Trial 66 finished with value: 0.19836260378360748 and parameters: {'hidden_layer': 93, 'learning_rate': 0.008970040318920427, 'momentum': 0.8664013959835557, 'weight_decay': 2.894895372794949e-05}. Best is trial 61 with value: 0.19658465683460236.
[I 2026-09-24 17:30:09,349] Trial 67 pruned.
[I 2026-09-24 17:30:23,881] Trial 68 pruned.
[I 2026-09-24 17:30:41,796] Trial 69 pruned.
[I 2026-09-24 17:31:00,000] Trial 70 pruned.
[I 2026-09-24 17:33:23,830] Trial 71 finished with value: 0.19787956774234772 and parameters: {'hidden_layer': 107, 'learning_rate': 0.02525359076493653, 'momentum': 0.7484340063578812, 'weight_decay': 1.4634900090592076e-05}. Best is trial 61 with value: 0.19658465683460236.
[I 2026-09-24 17:33:34,986] Trial 72 pruned.
[I 2026-09-24 17:36:51,022] Trial 73 finished with value: 0.19788047671318054 and parameters: {'hidden_layer': 107, 'learning_rate': 0.02018839633815299, 'momentum': 0.6298565058812167, 'weight_decay': 1.0162680742494428e-05}. Best is trial 61 with value: 0.19658465683460236.
[I 2026-09-24 17:37:47,086] Trial 74 pruned.
[I 2026-09-24 17:38:01,528] Trial 75 pruned.
[I 2026-09-24 17:40:50,417] Trial 76 finished with value: 0.1956712007522583 and parameters: {'hidden_layer': 57, 'learning_rate': 0.026731908629622256, 'momentum': 0.7455897737662243, 'weight_decay': 3.99937172643707e-06}. Best is trial 76 with value: 0.1956712007522583.
[I 2026-09-24 17:41:04,329] Trial 77 pruned.
[I 2026-09-24 17:41:42,454] Trial 78 pruned.
[I 2026-09-24 17:42:36,654] Trial 79 pruned.
[I 2026-09-24 17:42:36,659] A new study created in memory with name: no-name-cf520499-c0e9-489a-b172-e0842096e4e0

{'hidden_layer': 57, 'learning_rate': 0.026731908629622256, 'momentum': 0.7455897737662243, 'weight_decay': 3.99937172643707e-06}
0.1956712007522583

[I 2026-09-24 17:48:15,933] Trial 0 finished with value: 0.374485582113266 and parameters: {'hidden_layer': 70, 'learning_rate': 0.00024927065531605896, 'momentum': 0.6492330335921463, 'weight_decay': 1.2087112005111532e-06}. Best is trial 0 with value: 0.374485582113266.
[I 2026-09-24 17:53:57,007] Trial 1 finished with value: 0.3847348690032959 and parameters: {'hidden_layer': 93, 'learning_rate': 0.000497296738567034, 'momentum': 0.24224269611933166, 'weight_decay': 0.00013289185475650556}. Best is trial 0 with value: 0.374485582113266.
[I 2026-09-24 17:56:44,662] Trial 2 finished with value: 0.21049609780311584 and parameters: {'hidden_layer': 17, 'learning_rate': 0.013905546486568707, 'momentum': 0.5172550951043268, 'weight_decay': 2.8984542946793415e-06}. Best is trial 2 with value: 0.21049609780311584.
[I 2026-09-24 18:00:36,074] Trial 3 finished with value: 0.2036658525466919 and parameters: {'hidden_layer': 111, 'learning_rate': 0.003340192661172581, 'momentum': 0.8233046347797867, 'weight_decay': 0.00010453654248103145}. Best is trial 3 with value: 0.2036658525466919.
[I 2026-09-24 18:03:43,687] Trial 4 finished with value: 0.204203799366951 and parameters: {'hidden_layer': 125, 'learning_rate': 0.014392957979924471, 'momentum': 0.3781466025270735, 'weight_decay': 0.00018738606129558083}. Best is trial 3 with value: 0.2036658525466919.
[I 2026-09-24 18:05:01,007] Trial 5 pruned.
[I 2026-09-24 18:10:41,414] Trial 6 finished with value: 0.21145153045654297 and parameters: {'hidden_layer': 93, 'learning_rate': 0.004661094913205407, 'momentum': 0.3423612820167261, 'weight_decay': 4.504043147982282e-06}. Best is trial 3 with value: 0.2036658525466919.
[I 2026-09-24 18:11:49,337] Trial 7 pruned.
[I 2026-09-24 18:17:01,879] Trial 8 pruned.
[I 2026-09-24 18:18:03,920] Trial 9 pruned.
[I 2026-09-24 18:19:04,976] Trial 10 finished with value: 0.21442492306232452 and parameters: {'hidden_layer': 48, 'learning_rate': 0.08115763372345366, 'momentum': 0.9166938168030934, 'weight_decay': 3.0146202183585106e-05}. Best is trial 3 with value: 0.2036658525466919.
[I 2026-09-24 18:21:35,545] Trial 11 finished with value: 0.19989028573036194 and parameters: {'hidden_layer': 128, 'learning_rate': 0.016299026059511848, 'momentum': 0.7540116037447805, 'weight_decay': 0.0019007958587221934}. Best is trial 11 with value: 0.19989028573036194.
[I 2026-09-24 18:24:08,958] Trial 12 finished with value: 0.20310981571674347 and parameters: {'hidden_layer': 108, 'learning_rate': 0.011316475382810724, 'momentum': 0.7164714576932566, 'weight_decay': 0.00291584284720165}. Best is trial 11 with value: 0.19989028573036194.
[I 2026-09-24 18:25:53,359] Trial 13 finished with value: 0.2011980265378952 and parameters: {'hidden_layer': 107, 'learning_rate': 0.04000897464820287, 'momentum': 0.734621577512478, 'weight_decay': 0.0036098022685279447}. Best is trial 11 with value: 0.19989028573036194.
[I 2026-09-24 18:27:11,659] Trial 14 finished with value: 0.19962742924690247 and parameters: {'hidden_layer': 126, 'learning_rate': 0.0798218948112004, 'momentum': 0.7438367588502337, 'weight_decay': 0.0014129873756869623}. Best is trial 14 with value: 0.19962742924690247.
[I 2026-09-24 18:27:18,410] Trial 15 pruned.
[I 2026-09-24 18:28:43,693] Trial 16 finished with value: 0.19990584254264832 and parameters: {'hidden_layer': 48, 'learning_rate': 0.03267417578204841, 'momentum': 0.7669133142265888, 'weight_decay': 2.846360215545679e-05}. Best is trial 14 with value: 0.19962742924690247.
[I 2026-09-24 18:30:29,010] Trial 17 finished with value: 0.199337437748909 and parameters: {'hidden_layer': 97, 'learning_rate': 0.0309202271687087, 'momentum': 0.6506868798299958, 'weight_decay': 0.0011359862242961826}. Best is trial 17 with value: 0.199337437748909.
[I 2026-09-24 18:30:46,695] Trial 18 pruned.
[I 2026-09-24 18:31:28,958] Trial 19 pruned.
[I 2026-09-24 18:31:47,746] Trial 20 pruned.
[I 2026-09-24 18:34:09,867] Trial 21 finished with value: 0.20172648131847382 and parameters: {'hidden_layer': 127, 'learning_rate': 0.027521159115619018, 'momentum': 0.6514298427732086, 'weight_decay': 0.0028621687647541966}. Best is trial 17 with value: 0.199337437748909.
[I 2026-09-24 18:35:54,541] Trial 22 finished with value: 0.19889774918556213 and parameters: {'hidden_layer': 113, 'learning_rate': 0.021371199662210898, 'momentum': 0.882087157497973, 'weight_decay': 0.0015426476230115387}. Best is trial 22 with value: 0.19889774918556213.
[I 2026-09-24 18:37:00,063] Trial 23 finished with value: 0.20102441310882568 and parameters: {'hidden_layer': 114, 'learning_rate': 0.0524620911590461, 'momentum': 0.8913048161486834, 'weight_decay': 4.2083480757287445e-05}. Best is trial 22 with value: 0.19889774918556213.
[I 2026-09-24 18:37:13,968] Trial 24 pruned.
[I 2026-09-24 18:37:39,690] Trial 25 pruned.
[I 2026-09-24 18:39:32,596] Trial 26 finished with value: 0.19679072499275208 and parameters: {'hidden_layer': 117, 'learning_rate': 0.05739319354764544, 'momentum': 0.6199090799152979, 'weight_decay': 0.0003245595431309842}. Best is trial 26 with value: 0.19679072499275208.
[I 2026-09-24 18:39:59,844] Trial 27 pruned.
[I 2026-09-24 18:41:07,104] Trial 28 pruned.
[W 2026-09-24 18:41:50,358] Trial 29 failed with parameters: {'hidden_layer': 116, 'learning_rate': 0.001962626422012811, 'momentum': 0.6429897489234182, 'weight_decay': 0.00036877761110024396} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\optuna\study\_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "C:\Users\dawid\OneDrive - Stellenbosch University\Documents\Universiteit\4th year\ML\assignment3\ML441_Assigment3\active_learning.py", line 414, in obj
    model.fit(
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\backend\tensorflow\trainer.py", line 377, in fit
    logs = self.train_function(iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\backend\tensorflow\trainer.py", line 220, in function
    opt_outputs = multi_step_on_iterator(iterator)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\util\traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\polymorphic_function.py", line 833, in __call__
    result = self._call(*args, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\polymorphic_function.py", line 878, in _call
    results = tracing_compilation.call_function(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\tracing_compilation.py", line 139, in call_function
    return function._call_flat(  # pylint: disable=protected-access
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\concrete_function.py", line 1322, in _call_flat
    return self._inference_function.call_preflattened(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\atomic_function.py", line 216, in call_preflattened
    flat_outputs = self.call_flat(*args)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\atomic_function.py", line 251, in call_flat
    outputs = self._bound_context.call_function(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\context.py", line 1688, in call_function
    outputs = execute.execute(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
[W 2026-09-24 18:41:50,679] Trial 29 failed with value None.

KeyboardInterrupt:

In [5]:
acts = ['relu', 'leaky_relu', 'elu']

results = []
name = "base"

for activation in acts:
    setup = {'activation': activation, 'balanced': False}
    alpha = 0
    params = retrieve_params(f'params/dry_bean/{name}_{activation}.json')
    if activation == 'leaky_relu':
        alpha = params["leaky_relu_alpha"]
    elif activation == 'elu':
        alpha = params["elu_alpha"]
    result = cv_classification(X_pool, y_pool, 
               out_units=n_classes, out_act='softmax', loss='sparse_categorical_crossentropy', k=5, random_state=42, 
               hidden_units=params['hidden_layer'], activation=activation, alpha=alpha, 
               learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], balanced=False)
    for key, val in result.items():
        setup[key] = val

    results.append(setup)

results_df = pd.DataFrame(results)
results_df.round(4).to_csv(f"results/dry_bean/cv_validation.csv", index=False)

WARNING:tensorflow:From C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

In [9]:
results_df = pd.read_csv("results/dry_bean/cv_validation.csv")
results_df

   activation  balanced     auc     acc      f1
0        relu     False  0.9955  0.9288  0.9398
1  leaky_relu     False  0.9954  0.9277  0.9391
2         elu     False  0.9955  0.9284  0.9393

In [ ]:
activation = 'relu'
params = retrieve_params(f'params/dry_bean/base_{activation}.json')
scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)

model = create_model(X_train.shape[1], hidden_units=params['hidden_layer'], activation=activation, alpha=0, out_units=n_classes, out_act='softmax', 
                 learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], loss='sparse_categorical_crossentropy')
# params['learning_rate']
history = []
runs = 100
epochs = 200 // runs
fit_kwargs = {
    "epochs": epochs,
    "batch_size": 32,
    # "validation_split": 0.15,
    # "callbacks": [early_stopping],
    "verbose": 0
}
tic = time()
for i in range(runs):
    iteration = {'cumulative epochs': epochs * (i + 1)}
    iter_hist = model.fit(
        X_train,
        y_pool,
        **fit_kwargs
    )

    train_loss = iter_hist.history['loss']
    weights = model.get_weights()

    if not all(np.all(np.isfinite(w)) for w in weights):
        print(f"Model became unstable at iteration {i + 1}")
        break

    y_prob = model.predict(X_val, verbose=0)

    if not np.all(np.isfinite(y_prob)):
        print(f"NaN/Inf predictions at iteration {i + 1}")
        break
        
    y_pred = np.argmax(y_prob, axis=1)
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average='macro')
    auc = roc_auc_score(y_test, y_prob, average='macro', multi_class='ovr')
    toc = time()
    
    iteration['Training loss'] = train_loss[-1]
    iteration['Accuracy'] = acc
    iteration['macro F1'] = f1
    iteration['ROC-AUC'] = auc
    iteration['time'] = toc - tic
    history.append(iteration)
    print(f"Iteration {i+1}: ")
    for l in range(len(train_loss)):
        print(f"\t{train_loss[l]}")

run_df = pd.DataFrame(history)
run_df.round(4).to_csv(f"results/dry_bean/passive_learning.csv", index=False)

In [11]:
activation = 'relu'
params = retrieve_params(f'params/dry_bean/base_{activation}.json')

scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)

history = active_learning_mc(X_train, y_pool, X_val, y_test, random_sampling, num_iter=100, unlab_size=0.9, random_state=100, verbose=True,
                               hidden_units=params['hidden_layer'], activation=activation, alpha=0, out_units=n_classes, balanced=False,
                               learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'] 
)

run_df = pd.DataFrame(history)
run_df.round(4).to_csv(f"results/dry_bean/uncertainty_sampling.csv", index=False)

Iteration 1: 1088 labelled instances
	Accuracy = 0.8813808299669482
	macro F1 = 0.8911188677631052
	AUC = 0.990251425608186

Iteration 2: 1186 labelled instances
	Accuracy = 0.9001101726037458
	macro F1 = 0.9107906707820641
	AUC = 0.9932912494900753

Iteration 3: 1284 labelled instances
	Accuracy = 0.9092912229159016
	macro F1 = 0.9208488707035366
	AUC = 0.9938116765912687

Iteration 4: 1382 labelled instances
	Accuracy = 0.9122291590157914
	macro F1 = 0.9227995489553352
	AUC = 0.9942728911874805

Iteration 5: 1480 labelled instances
	Accuracy = 0.9177377892030848
	macro F1 = 0.9291942837619205
	AUC = 0.9944312963420298

Iteration 6: 1578 labelled instances
	Accuracy = 0.9103929489533603
	macro F1 = 0.9226187201645379
	AUC = 0.994367110685262

Iteration 7: 1676 labelled instances
	Accuracy = 0.9125964010282777
	macro F1 = 0.9240986649605885
	AUC = 0.994608292751615

Iteration 8: 1774 labelled instances
	Accuracy = 0.9170033051781123
	macro F1 = 0.9278160942797624
	AUC = 0.9947930819512919

Iteration 9: 1872 labelled instances
	Accuracy = 0.9170033051781123
	macro F1 = 0.9292970484280497
	AUC = 0.994784992088136

Iteration 10: 1970 labelled instances
	Accuracy = 0.9166360631656262
	macro F1 = 0.9282855676201747
	AUC = 0.9949674089318685

Iteration 11: 2068 labelled instances
	Accuracy = 0.9155343371281675
	macro F1 = 0.9260586704165228
	AUC = 0.9949312865454709

Iteration 12: 2166 labelled instances
	Accuracy = 0.9214102093279471
	macro F1 = 0.9326536279550884
	AUC = 0.9950715295341847

Iteration 13: 2264 labelled instances
	Accuracy = 0.9250826294528094
	macro F1 = 0.9359119427364802
	AUC = 0.9950038712560038

Iteration 14: 2362 labelled instances
	Accuracy = 0.9170033051781123
	macro F1 = 0.9287619942050923
	AUC = 0.9951306599100344

Iteration 15: 2460 labelled instances
	Accuracy = 0.9236136614028645
	macro F1 = 0.9345464901174385
	AUC = 0.9948102067278991

Iteration 16: 2558 labelled instances
	Accuracy = 0.9199412412780023
	macro F1 = 0.9303094336469458
	AUC = 0.9950916766203044

Iteration 17: 2656 labelled instances
	Accuracy = 0.9184722732280572
	macro F1 = 0.9300401396367526
	AUC = 0.9949598733628601

Iteration 18: 2754 labelled instances
	Accuracy = 0.9217774513404333
	macro F1 = 0.9328012406020482
	AUC = 0.9951327711393426

Iteration 19: 2852 labelled instances
	Accuracy = 0.9192067572530297
	macro F1 = 0.9301035790233437
	AUC = 0.9952068373719742

Iteration 20: 2950 labelled instances
	Accuracy = 0.9217774513404333
	macro F1 = 0.9316841883049979
	AUC = 0.995179098122197

Iteration 21: 3048 labelled instances
	Accuracy = 0.9225119353654058
	macro F1 = 0.9326865724599738
	AUC = 0.9951463258516624

Iteration 22: 3146 labelled instances
	Accuracy = 0.9210429673154609
	macro F1 = 0.9305220695772525
	AUC = 0.995275844245502

Iteration 23: 3244 labelled instances
	Accuracy = 0.9206757253029747
	macro F1 = 0.9308880538350142
	AUC = 0.9952608760510916

Iteration 24: 3342 labelled instances
	Accuracy = 0.9214102093279471
	macro F1 = 0.9307396883015496
	AUC = 0.9953494823935841

Iteration 25: 3440 labelled instances
	Accuracy = 0.9162688211531399
	macro F1 = 0.9293269477194407
	AUC = 0.9951421141523263

Iteration 26: 3538 labelled instances
	Accuracy = 0.9155343371281675
	macro F1 = 0.9278536831241525
	AUC = 0.9953277016102471

Iteration 27: 3636 labelled instances
	Accuracy = 0.9239809034153507
	macro F1 = 0.9344485029023332
	AUC = 0.9952704295983711

Iteration 28: 3734 labelled instances
	Accuracy = 0.9206757253029747
	macro F1 = 0.9333026746693187
	AUC = 0.9952646338527444

Iteration 29: 3832 labelled instances
	Accuracy = 0.922879177377892
	macro F1 = 0.9325382279846037
	AUC = 0.9952843923790455

Iteration 30: 3930 labelled instances
	Accuracy = 0.919573999265516
	macro F1 = 0.9299420025683253
	AUC = 0.9952140135083162

Iteration 31: 4028 labelled instances
	Accuracy = 0.9188395152405435
	macro F1 = 0.9311522431139183
	AUC = 0.9951359816264238

Iteration 32: 4126 labelled instances
	Accuracy = 0.9173705471905986
	macro F1 = 0.9307353563483155
	AUC = 0.9952768555007419

Iteration 33: 4224 labelled instances
	Accuracy = 0.9280205655526992
	macro F1 = 0.9380902375140435
	AUC = 0.9953685608306262

Iteration 34: 4322 labelled instances
	Accuracy = 0.9239809034153507
	macro F1 = 0.9352158025287585
	AUC = 0.9952681678438884

Iteration 35: 4420 labelled instances
	Accuracy = 0.9269188395152406
	macro F1 = 0.9372763031818382
	AUC = 0.9954356548143143

Iteration 36: 4518 labelled instances
	Accuracy = 0.9261843554902681
	macro F1 = 0.936402869585517
	AUC = 0.9952207862860529

Iteration 37: 4616 labelled instances
	Accuracy = 0.9170033051781123
	macro F1 = 0.9281728148074919
	AUC = 0.9951179379672189

Iteration 38: 4714 labelled instances
	Accuracy = 0.9239809034153507
	macro F1 = 0.9331931671538534
	AUC = 0.9953304734268681

Iteration 39: 4812 labelled instances
	Accuracy = 0.9247153874403232
	macro F1 = 0.9347439910279499
	AUC = 0.9954419919174311

Iteration 40: 4910 labelled instances
	Accuracy = 0.927653323540213
	macro F1 = 0.9376970336685347
	AUC = 0.9954675586114962

Iteration 41: 5008 labelled instances
	Accuracy = 0.9203084832904884
	macro F1 = 0.9323399493817013
	AUC = 0.9953826046067189

Iteration 42: 5106 labelled instances
	Accuracy = 0.9287550495776716
	macro F1 = 0.9392167384635632
	AUC = 0.9953338989338053

Iteration 43: 5204 labelled instances
	Accuracy = 0.9250826294528094
	macro F1 = 0.9353797682620242
	AUC = 0.9954487356252274

Iteration 44: 5302 labelled instances
	Accuracy = 0.9239809034153507
	macro F1 = 0.9346476044643748
	AUC = 0.9954543255536104

Iteration 45: 5400 labelled instances
	Accuracy = 0.9287550495776716
	macro F1 = 0.9390126402286691
	AUC = 0.9954599701347983

Iteration 46: 5498 labelled instances
	Accuracy = 0.922879177377892
	macro F1 = 0.9349353936771302
	AUC = 0.9954152631915717

Iteration 47: 5596 labelled instances
	Accuracy = 0.9210429673154609
	macro F1 = 0.9323958123868129
	AUC = 0.9955634034928161

Iteration 48: 5694 labelled instances
	Accuracy = 0.9243481454278369
	macro F1 = 0.934691236778981
	AUC = 0.9954379933387026

Iteration 49: 5792 labelled instances
	Accuracy = 0.9254498714652957
	macro F1 = 0.9356178076157927
	AUC = 0.9954543901078836

Iteration 50: 5890 labelled instances
	Accuracy = 0.922879177377892
	macro F1 = 0.9336305253932767
	AUC = 0.9955144013435842

Iteration 51: 5988 labelled instances
	Accuracy = 0.9162688211531399
	macro F1 = 0.927665776101841
	AUC = 0.9951811866822976

Iteration 52: 6086 labelled instances
	Accuracy = 0.9272860815277267
	macro F1 = 0.936010194647437
	AUC = 0.9955443092843186

Iteration 53: 6184 labelled instances
	Accuracy = 0.9210429673154609
	macro F1 = 0.9313810069962611
	AUC = 0.9954179131140686

Iteration 54: 6282 labelled instances
	Accuracy = 0.9254498714652957
	macro F1 = 0.9364664605124305
	AUC = 0.9954161172224383

Iteration 55: 6380 labelled instances
	Accuracy = 0.9258171134777818
	macro F1 = 0.9354974745300871
	AUC = 0.9953884610715428

Iteration 56: 6478 labelled instances
	Accuracy = 0.927653323540213
	macro F1 = 0.9383058441801024
	AUC = 0.9954858928219498

Iteration 57: 6576 labelled instances
	Accuracy = 0.9203084832904884
	macro F1 = 0.9336376615389935
	AUC = 0.9954285322894633

Iteration 58: 6674 labelled instances
	Accuracy = 0.9250826294528094
	macro F1 = 0.93532075006491
	AUC = 0.995491980126282

Iteration 59: 6772 labelled instances
	Accuracy = 0.9247153874403232
	macro F1 = 0.9363960809621382
	AUC = 0.9952286895115641

Iteration 60: 6870 labelled instances
	Accuracy = 0.9254498714652957
	macro F1 = 0.9374524820626078
	AUC = 0.9955761773168808

Iteration 61: 6968 labelled instances
	Accuracy = 0.9261843554902681
	macro F1 = 0.9368645484363259
	AUC = 0.9954969121677981

Iteration 62: 7066 labelled instances
	Accuracy = 0.9280205655526992
	macro F1 = 0.9385945793976271
	AUC = 0.9956073633435734

Iteration 63: 7164 labelled instances
	Accuracy = 0.9247153874403232
	macro F1 = 0.9360031770182594
	AUC = 0.9956048600922138

Iteration 64: 7262 labelled instances
	Accuracy = 0.9247153874403232
	macro F1 = 0.9364536619267938
	AUC = 0.9956098615236997

Iteration 65: 7360 labelled instances
	Accuracy = 0.9254498714652957
	macro F1 = 0.9357797268491959
	AUC = 0.9955821762414552

Iteration 66: 7458 labelled instances
	Accuracy = 0.9243481454278369
	macro F1 = 0.9348831670024842
	AUC = 0.9955430538536358

Iteration 67: 7556 labelled instances
	Accuracy = 0.9294895336026442
	macro F1 = 0.9387354302055565
	AUC = 0.9955359866170884

Iteration 68: 7654 labelled instances
	Accuracy = 0.9239809034153507
	macro F1 = 0.9360710206943682
	AUC = 0.9955231868773018

Iteration 69: 7752 labelled instances
	Accuracy = 0.9309585016525891
	macro F1 = 0.94075807417781
	AUC = 0.9955133576298508

Iteration 70: 7850 labelled instances
	Accuracy = 0.9294895336026442
	macro F1 = 0.940338536191626
	AUC = 0.9954895452652602

Iteration 71: 7948 labelled instances
	Accuracy = 0.9272860815277267
	macro F1 = 0.9383954616294241
	AUC = 0.9955742620910598

Iteration 72: 8046 labelled instances
	Accuracy = 0.9283878075651855
	macro F1 = 0.9397379712016672
	AUC = 0.9955472778396571

Iteration 73: 8144 labelled instances
	Accuracy = 0.9250826294528094
	macro F1 = 0.9348294336095281
	AUC = 0.9955878666413075

Iteration 74: 8242 labelled instances
	Accuracy = 0.9283878075651855
	macro F1 = 0.939237366345833
	AUC = 0.9956640215311742

Iteration 75: 8340 labelled instances
	Accuracy = 0.9291222915901579
	macro F1 = 0.9396260880209608
	AUC = 0.9956546295612793

Iteration 76: 8438 labelled instances
	Accuracy = 0.9269188395152406
	macro F1 = 0.938187341512541
	AUC = 0.9956456718299683

Iteration 77: 8536 labelled instances
	Accuracy = 0.9247153874403232
	macro F1 = 0.9363536679618164
	AUC = 0.9955485227190426

Iteration 78: 8634 labelled instances
	Accuracy = 0.9309585016525891
	macro F1 = 0.9417936537029182
	AUC = 0.9956077694316396

Iteration 79: 8732 labelled instances
	Accuracy = 0.9272860815277267
	macro F1 = 0.9380601679165809
	AUC = 0.9954597679363062

Iteration 80: 8830 labelled instances
	Accuracy = 0.9309585016525891
	macro F1 = 0.9422198605607051
	AUC = 0.9957137697276052

Iteration 81: 8928 labelled instances
	Accuracy = 0.9221446933529196
	macro F1 = 0.9357928894802089
	AUC = 0.9954701584728888

Iteration 82: 9026 labelled instances
	Accuracy = 0.9258171134777818
	macro F1 = 0.9380336208853945
	AUC = 0.9954192946587488

Iteration 83: 9124 labelled instances
	Accuracy = 0.9265515975027543
	macro F1 = 0.9375355539854038
	AUC = 0.9954891452078937

Iteration 84: 9222 labelled instances
	Accuracy = 0.9283878075651855
	macro F1 = 0.9390062647049229
	AUC = 0.9956980293080377

Iteration 85: 9320 labelled instances
	Accuracy = 0.9272860815277267
	macro F1 = 0.9379833916401027
	AUC = 0.9957407184401477

Iteration 86: 9418 labelled instances
	Accuracy = 0.9287550495776716
	macro F1 = 0.9404737884363018
	AUC = 0.9954555120120201

Iteration 87: 9516 labelled instances
	Accuracy = 0.9258171134777818
	macro F1 = 0.9367999411013715
	AUC = 0.9953811674863814

Iteration 88: 9614 labelled instances
	Accuracy = 0.9232464193903782
	macro F1 = 0.9352448737735034
	AUC = 0.9953644164357567

Iteration 89: 9712 labelled instances
	Accuracy = 0.9239809034153507
	macro F1 = 0.9377396535484662
	AUC = 0.9955068538375179

Iteration 90: 9810 labelled instances
	Accuracy = 0.9243481454278369
	macro F1 = 0.9359581254776027
	AUC = 0.995534843559902

Iteration 91: 9908 labelled instances
	Accuracy = 0.9239809034153507
	macro F1 = 0.9370589457289445
	AUC = 0.9955065148259182

Iteration 92: 10006 labelled instances
	Accuracy = 0.9269188395152406
	macro F1 = 0.937825264893294
	AUC = 0.9956278174533183

Iteration 93: 10104 labelled instances
	Accuracy = 0.9225119353654058
	macro F1 = 0.9345438616992331
	AUC = 0.995559070327751

Iteration 94: 10202 labelled instances
	Accuracy = 0.9239809034153507
	macro F1 = 0.935488508439794
	AUC = 0.9955727802389445

Iteration 95: 10300 labelled instances
	Accuracy = 0.9269188395152406
	macro F1 = 0.9370669583292791
	AUC = 0.9955068667965475

Iteration 96: 10398 labelled instances
	Accuracy = 0.9221446933529196
	macro F1 = 0.9325620369677304
	AUC = 0.9955965743370024

Iteration 97: 10496 labelled instances
	Accuracy = 0.9217774513404333
	macro F1 = 0.9339015376847536
	AUC = 0.9953926804101305

Iteration 98: 10594 labelled instances
	Accuracy = 0.9272860815277267
	macro F1 = 0.9382013812515196
	AUC = 0.9956631637794863

Iteration 99: 10692 labelled instances
	Accuracy = 0.9221446933529196
	macro F1 = 0.9320783666810554
	AUC = 0.9953833523241645

Iteration 100: 10888 labelled instances
	Accuracy = 0.9247153874403232
	macro F1 = 0.9365417235592964
	AUC = 0.995423493998511

In [12]:
activation = 'relu'
params = retrieve_params(f'params/dry_bean/base_{activation}.json')

scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)
for beta in [0.9]:
    history = sasla_mc(X_train, y_pool, X_val, y_test, num_iter=100, unlab_size=0.9, random_state=100, verbose=True,
                                   hidden_units=params['hidden_layer'], activation=activation, alpha=0, out_units=n_classes, balanced=False,
                                   learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], beta=beta)
    
    run_df = pd.DataFrame(history)
    run_df.round(4).to_csv(f"results/dry_bean/sasla_{beta}.csv", index=False)

Iteration 1: 10888 labelled instances
	Accuracy = 0.9236136614028645
	macro F1 = 0.9352480886269943
	AUC = 0.9952682430632374

Iteration 2: 6769 labelled instances
	Accuracy = 0.922879177377892
	macro F1 = 0.9344069204069907
	AUC = 0.9952337415320337

Iteration 3: 6317 labelled instances
	Accuracy = 0.9206757253029747
	macro F1 = 0.9329518189919968
	AUC = 0.9952427420973337

Iteration 4: 6363 labelled instances
	Accuracy = 0.9269188395152406
	macro F1 = 0.9372744868545337
	AUC = 0.9954562717913088

Iteration 5: 6167 labelled instances
	Accuracy = 0.9258171134777818
	macro F1 = 0.9361983700184542
	AUC = 0.9956172788518913

Iteration 6: 6151 labelled instances
	Accuracy = 0.9258171134777818
	macro F1 = 0.9362081979137613
	AUC = 0.9955711420490718

Iteration 7: 6020 labelled instances
	Accuracy = 0.9269188395152406
	macro F1 = 0.9377109043511966
	AUC = 0.9955865309014433

Iteration 8: 5906 labelled instances
	Accuracy = 0.9269188395152406
	macro F1 = 0.9386452104808033
	AUC = 0.9956148260662104

Iteration 9: 6199 labelled instances
	Accuracy = 0.9272860815277267
	macro F1 = 0.9375993622843944
	AUC = 0.9957165515640639

Iteration 10: 5784 labelled instances
	Accuracy = 0.9254498714652957
	macro F1 = 0.9356100150412974
	AUC = 0.9957533726902142

Iteration 11: 5942 labelled instances
	Accuracy = 0.9294895336026442
	macro F1 = 0.939294623599727
	AUC = 0.995718670658037

Iteration 12: 5972 labelled instances
	Accuracy = 0.9258171134777818
	macro F1 = 0.9370497869747242
	AUC = 0.9956594857362429

Iteration 13: 6087 labelled instances
	Accuracy = 0.9170033051781123
	macro F1 = 0.9320874176770465
	AUC = 0.9953043130982392

Iteration 14: 6145 labelled instances
	Accuracy = 0.9283878075651855
	macro F1 = 0.9392791134544025
	AUC = 0.9957747013315492

Iteration 15: 5947 labelled instances
	Accuracy = 0.9232464193903782
	macro F1 = 0.9325854959203111
	AUC = 0.9956759907630249

Iteration 16: 5852 labelled instances
	Accuracy = 0.9283878075651855
	macro F1 = 0.9382058456518908
	AUC = 0.9957562621696935

Iteration 17: 5924 labelled instances
	Accuracy = 0.927653323540213
	macro F1 = 0.9382910715098584
	AUC = 0.9957841422015202

Iteration 18: 5993 labelled instances
	Accuracy = 0.9305912596401028
	macro F1 = 0.940916086762391
	AUC = 0.9957815555466769

Iteration 19: 5736 labelled instances
	Accuracy = 0.9269188395152406
	macro F1 = 0.9378066554845121
	AUC = 0.9956989103862276

Iteration 20: 5773 labelled instances
	Accuracy = 0.9280205655526992
	macro F1 = 0.9390594048999488
	AUC = 0.9957218947978811

Iteration 21: 5847 labelled instances
	Accuracy = 0.9239809034153507
	macro F1 = 0.9357492093714085
	AUC = 0.995712266227086

Iteration 22: 5740 labelled instances
	Accuracy = 0.922879177377892
	macro F1 = 0.9345939780311078
	AUC = 0.9956378173791018

Iteration 23: 5837 labelled instances
	Accuracy = 0.9265515975027543
	macro F1 = 0.9376238443838093
	AUC = 0.9956449005064636

Iteration 24: 5853 labelled instances
	Accuracy = 0.9272860815277267
	macro F1 = 0.9389539940454724
	AUC = 0.9956238015347705

Iteration 25: 5555 labelled instances
	Accuracy = 0.9239809034153507
	macro F1 = 0.93471090161858
	AUC = 0.995788379388619

Iteration 26: 5374 labelled instances
	Accuracy = 0.9221446933529196
	macro F1 = 0.9331582466734821
	AUC = 0.9956207347011039

Iteration 27: 5434 labelled instances
	Accuracy = 0.9327947117150202
	macro F1 = 0.9441640432923236
	AUC = 0.9957012953842607

Iteration 28: 5783 labelled instances
	Accuracy = 0.9217774513404333
	macro F1 = 0.9323016251975069
	AUC = 0.9955805253908615

Iteration 29: 5277 labelled instances
	Accuracy = 0.9239809034153507
	macro F1 = 0.9371912887567743
	AUC = 0.9956535615261857

Iteration 30: 5739 labelled instances
	Accuracy = 0.9294895336026442
	macro F1 = 0.9400769730688223
	AUC = 0.9955903200722267

Iteration 31: 5737 labelled instances
	Accuracy = 0.9243481454278369
	macro F1 = 0.937482824262113
	AUC = 0.9955856167516876

Iteration 32: 5577 labelled instances
	Accuracy = 0.9258171134777818
	macro F1 = 0.9368212419032852
	AUC = 0.9955566905204546

Iteration 33: 5475 labelled instances
	Accuracy = 0.9250826294528094
	macro F1 = 0.9356119680008037
	AUC = 0.99557438215765

Iteration 34: 5416 labelled instances
	Accuracy = 0.9214102093279471
	macro F1 = 0.9318117460149927
	AUC = 0.9956772244296411

Iteration 35: 5413 labelled instances
	Accuracy = 0.9305912596401028
	macro F1 = 0.9412491062104148
	AUC = 0.995746027725902

Iteration 36: 5455 labelled instances
	Accuracy = 0.9217774513404333
	macro F1 = 0.9344160981857726
	AUC = 0.9952928826983217

Iteration 37: 5480 labelled instances
	Accuracy = 0.9258171134777818
	macro F1 = 0.9379459499692474
	AUC = 0.9956053696329542

Iteration 38: 5583 labelled instances
	Accuracy = 0.9258171134777818
	macro F1 = 0.9372882396964349
	AUC = 0.99559990321904

Iteration 39: 5224 labelled instances
	Accuracy = 0.9250826294528094
	macro F1 = 0.9358128008352307
	AUC = 0.9955901369855119

Iteration 40: 5585 labelled instances
	Accuracy = 0.9217774513404333
	macro F1 = 0.9321183128695045
	AUC = 0.9955287742668375

Iteration 41: 5156 labelled instances
	Accuracy = 0.927653323540213
	macro F1 = 0.9392184136429943
	AUC = 0.9955406169017158

Iteration 42: 5589 labelled instances
	Accuracy = 0.9258171134777818
	macro F1 = 0.9368922199948692
	AUC = 0.9957080639963005

Iteration 43: 5190 labelled instances
	Accuracy = 0.9265515975027543
	macro F1 = 0.937289750435696
	AUC = 0.9956144274135278

Iteration 44: 5329 labelled instances
	Accuracy = 0.922879177377892
	macro F1 = 0.9347786783476355
	AUC = 0.9955197951073289

Iteration 45: 5523 labelled instances
	Accuracy = 0.9239809034153507
	macro F1 = 0.9359285343673388
	AUC = 0.9953938722743764

Iteration 46: 5519 labelled instances
	Accuracy = 0.9166360631656262
	macro F1 = 0.9312592835433623
	AUC = 0.9955581437843071

Iteration 47: 5567 labelled instances
	Accuracy = 0.9254498714652957
	macro F1 = 0.9374160930317358
	AUC = 0.9955023645932268

Iteration 48: 5540 labelled instances
	Accuracy = 0.919573999265516
	macro F1 = 0.9338208089225253
	AUC = 0.9954648452938833

Iteration 49: 5455 labelled instances
	Accuracy = 0.9258171134777818
	macro F1 = 0.9366242739526449
	AUC = 0.995499905902232

Iteration 50: 5148 labelled instances
	Accuracy = 0.9199412412780023
	macro F1 = 0.9330643765890514
	AUC = 0.9954775057826245

Iteration 51: 5289 labelled instances
	Accuracy = 0.9261843554902681
	macro F1 = 0.938531899759795
	AUC = 0.9955261693917433

Iteration 52: 5327 labelled instances
	Accuracy = 0.9280205655526992
	macro F1 = 0.9393807141449778
	AUC = 0.9956955561365431

Iteration 53: 5398 labelled instances
	Accuracy = 0.9258171134777818
	macro F1 = 0.9368435418523662
	AUC = 0.9956800464348952

Iteration 54: 5153 labelled instances
	Accuracy = 0.9261843554902681
	macro F1 = 0.9387220417620268
	AUC = 0.9955705450859063

Iteration 55: 5202 labelled instances
	Accuracy = 0.9269188395152406
	macro F1 = 0.9391191553914929
	AUC = 0.9956349279859168

Iteration 56: 5444 labelled instances
	Accuracy = 0.9250826294528094
	macro F1 = 0.9356815266700514
	AUC = 0.9956282756748551

Iteration 57: 5087 labelled instances
	Accuracy = 0.927653323540213
	macro F1 = 0.9395299390775728
	AUC = 0.9956209228095815

Iteration 58: 5383 labelled instances
	Accuracy = 0.9294895336026442
	macro F1 = 0.9409954860222022
	AUC = 0.9956700058782146

Iteration 59: 5220 labelled instances
	Accuracy = 0.9258171134777818
	macro F1 = 0.9378604674873978
	AUC = 0.9955672277462354

Iteration 60: 5385 labelled instances
	Accuracy = 0.9217774513404333
	macro F1 = 0.9336880695103262
	AUC = 0.9954218207066864

Iteration 61: 5048 labelled instances
	Accuracy = 0.9243481454278369
	macro F1 = 0.9362268294337076
	AUC = 0.9954651029969551

Iteration 62: 5410 labelled instances
	Accuracy = 0.9298567756151304
	macro F1 = 0.9399412766776812
	AUC = 0.9957540218534209

Iteration 63: 5150 labelled instances
	Accuracy = 0.9236136614028645
	macro F1 = 0.9356313607381258
	AUC = 0.9955286256647821

Iteration 64: 5206 labelled instances
	Accuracy = 0.9254498714652957
	macro F1 = 0.9375163816446362
	AUC = 0.9954494017338202

Iteration 65: 5340 labelled instances
	Accuracy = 0.9254498714652957
	macro F1 = 0.9378203525023492
	AUC = 0.9956251673970371

Iteration 66: 5189 labelled instances
	Accuracy = 0.922879177377892
	macro F1 = 0.9338178887568142
	AUC = 0.9954128267447081

Iteration 67: 5210 labelled instances
	Accuracy = 0.9225119353654058
	macro F1 = 0.9342362144961787
	AUC = 0.9954663567211037

Iteration 68: 5341 labelled instances
	Accuracy = 0.9265515975027543
	macro F1 = 0.9383171031275463
	AUC = 0.9956603271569667

Iteration 69: 4996 labelled instances
	Accuracy = 0.9280205655526992
	macro F1 = 0.9394870612896594
	AUC = 0.9954413014347547

Iteration 70: 5208 labelled instances
	Accuracy = 0.9236136614028645
	macro F1 = 0.9358950828113606
	AUC = 0.9954165609470714

Iteration 71: 4883 labelled instances
	Accuracy = 0.9188395152405435
	macro F1 = 0.9335127432755327
	AUC = 0.9951823020936187

Iteration 72: 5281 labelled instances
	Accuracy = 0.9261843554902681
	macro F1 = 0.9387051248815469
	AUC = 0.995556613448624

Iteration 73: 5139 labelled instances
	Accuracy = 0.9254498714652957
	macro F1 = 0.936195367141658
	AUC = 0.9955690072099423

Iteration 74: 5211 labelled instances
	Accuracy = 0.9294895336026442
	macro F1 = 0.9405721731490334
	AUC = 0.9954104064675421

Iteration 75: 5134 labelled instances
	Accuracy = 0.9269188395152406
	macro F1 = 0.9393917710564452
	AUC = 0.9954111027707654

Iteration 76: 5155 labelled instances
	Accuracy = 0.9261843554902681
	macro F1 = 0.9370578413751325
	AUC = 0.9953635179477647

Iteration 77: 5194 labelled instances
	Accuracy = 0.9239809034153507
	macro F1 = 0.9366460329615539
	AUC = 0.9953917180657185

Iteration 78: 4880 labelled instances
	Accuracy = 0.9214102093279471
	macro F1 = 0.9332350252226339
	AUC = 0.9951725533376797

Iteration 79: 5148 labelled instances
	Accuracy = 0.9280205655526992
	macro F1 = 0.9387836634467546
	AUC = 0.9954825561301585

Iteration 80: 5122 labelled instances
	Accuracy = 0.9265515975027543
	macro F1 = 0.9376502262410298
	AUC = 0.9955424975536109

Iteration 81: 5027 labelled instances
	Accuracy = 0.9287550495776716
	macro F1 = 0.9393152352034969
	AUC = 0.9957020236623002

Iteration 82: 4908 labelled instances
	Accuracy = 0.9243481454278369
	macro F1 = 0.9366266745016165
	AUC = 0.9953709618466106

Iteration 83: 5114 labelled instances
	Accuracy = 0.9254498714652957
	macro F1 = 0.936275707761278
	AUC = 0.9954641452996834

Iteration 84: 5123 labelled instances
	Accuracy = 0.9265515975027543
	macro F1 = 0.9374391694541332
	AUC = 0.9955460389056577

Iteration 85: 5100 labelled instances
	Accuracy = 0.9236136614028645
	macro F1 = 0.9361846814356232
	AUC = 0.9953277116087234

Iteration 86: 5266 labelled instances
	Accuracy = 0.9210429673154609
	macro F1 = 0.9331521475018999
	AUC = 0.9954127500678568

Iteration 87: 5082 labelled instances
	Accuracy = 0.9199412412780023
	macro F1 = 0.9309232017923217
	AUC = 0.9952203698344312

Iteration 88: 5147 labelled instances
	Accuracy = 0.9214102093279471
	macro F1 = 0.9314522931120423
	AUC = 0.9952616584811357

Iteration 89: 5116 labelled instances
	Accuracy = 0.922879177377892
	macro F1 = 0.9341159899149585
	AUC = 0.9954441341513703

Iteration 90: 5022 labelled instances
	Accuracy = 0.9203084832904884
	macro F1 = 0.9311257757348061
	AUC = 0.9952471012557479

Iteration 91: 5256 labelled instances
	Accuracy = 0.9280205655526992
	macro F1 = 0.940703235285814
	AUC = 0.9954795350794845

Iteration 92: 4909 labelled instances
	Accuracy = 0.9210429673154609
	macro F1 = 0.9320234489073107
	AUC = 0.9950257430355657

Iteration 93: 4951 labelled instances
	Accuracy = 0.922879177377892
	macro F1 = 0.9337551860706818
	AUC = 0.9951533797067463

Iteration 94: 5109 labelled instances
	Accuracy = 0.9261843554902681
	macro F1 = 0.9386091685868181
	AUC = 0.9953728788190845

Iteration 95: 5017 labelled instances
	Accuracy = 0.9225119353654058
	macro F1 = 0.9344627957805892
	AUC = 0.9953270019063394

Iteration 96: 5216 labelled instances
	Accuracy = 0.9291222915901579
	macro F1 = 0.9408255166878738
	AUC = 0.995379019247829

Iteration 97: 5010 labelled instances
	Accuracy = 0.9236136614028645
	macro F1 = 0.9353065315795138
	AUC = 0.9953827557791374

Iteration 98: 5194 labelled instances
	Accuracy = 0.9206757253029747
	macro F1 = 0.9330285235563313
	AUC = 0.9950736433365389

Iteration 99: 5183 labelled instances
	Accuracy = 0.9265515975027543
	macro F1 = 0.9389206279355145
	AUC = 0.9953356292488218

Iteration 100: 4969 labelled instances
	Accuracy = 0.9247153874403232
	macro F1 = 0.9382230429822606
	AUC = 0.9953390607442882

## Student dropout

In [13]:
student_dropout = fetch_ucirepo(id=697)
dropout_df = pd.concat(
    [student_dropout.data.features, student_dropout.data.targets],
    axis=1
)

# nominal features
nominal = ['Marital Status', 'Course', 'Previous qualification']
# Already international feature
# already parents' qual level and high cardinality
drop = ['Nacionality', "Mother's occupation", "Father's occupation"]

dropout_df.drop(columns=drop, inplace=True)
dropout_df = pd.get_dummies(
    dropout_df,
    columns=nominal,
    dtype=int
)

dropout_df.head()

,Application mode,Application order,Daytime/evening attendance,Previous qualification (grade),Mother's qualification,Father's qualification,Admission grade,Displaced,Educational special needs,Debtor,...,Previous qualification_10,Previous qualification_12,Previous qualification_14,Previous qualification_15,Previous qualification_19,Previous qualification_38,Previous qualification_39,Previous qualification_40,Previous qualification_42,Previous qualification_43
0,17,5,1,122.0,19,12,127.3,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,15,1,1,160.0,1,3,142.5,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,5,1,122.0,37,37,124.8,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,17,2,1,122.0,38,37,119.6,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,39,1,0,100.0,37,38,141.5,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
X = dropout_df.drop(columns=['Target']).to_numpy()
student_encoder = LabelEncoder()
y = student_dropout.data.targets.to_numpy().ravel()

y = student_encoder.fit_transform(y)
dropout_map = student_encoder.classes_
n_classes = len(np.unique(y))

X_pool, X_test, y_pool, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=51
)

In [6]:
# 'relu', 'leaky_relu', 
acts = ['elu']
name = 'base'
for activation in acts:
    base_params = tune_params(X_pool, y_pool,
                              loss='sparse_categorical_crossentropy',
                              out_units=n_classes, out_act='softmax',
                              k=5, activation=activation,
                              balanced=False,
                              random_state=42,
                              n_trials=80,
                              export=True, file = f'params/student_dropout/{name}_{activation}.json'
    )

[I 2026-09-26 00:31:29,054] A new study created in memory with name: no-name-d306407a-e149-4ee0-a73f-f1d8329ca88f

WARNING:tensorflow:From C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

[I 2026-09-26 00:33:57,909] Trial 0 finished with value: 0.6028547883033752 and parameters: {'hidden_layer': 95, 'learning_rate': 0.0020656029332625546, 'momentum': 0.15247620238338155, 'weight_decay': 7.891012996392573e-06, 'elu_alpha': 0.4741044575563499}. Best is trial 0 with value: 0.6028547883033752.
[I 2026-09-26 00:35:40,558] Trial 1 finished with value: 0.6032333374023438 and parameters: {'hidden_layer': 75, 'learning_rate': 0.002147140331196139, 'momentum': 0.7682184833099834, 'weight_decay': 0.0030248390433163263, 'elu_alpha': 0.15745910494041737}. Best is trial 0 with value: 0.6028547883033752.
[I 2026-09-26 00:37:25,875] Trial 2 finished with value: 0.6042537689208984 and parameters: {'hidden_layer': 56, 'learning_rate': 0.002361436847544542, 'momentum': 0.6309182895177561, 'weight_decay': 0.0001362522257912527, 'elu_alpha': 0.4499536210785289}. Best is trial 0 with value: 0.6028547883033752.
[I 2026-09-26 00:39:17,150] Trial 3 finished with value: 0.5902585983276367 and parameters: {'hidden_layer': 86, 'learning_rate': 0.0042179651767204835, 'momentum': 0.4503505300702548, 'weight_decay': 0.0027159456221142, 'elu_alpha': 0.5874622878424292}. Best is trial 3 with value: 0.5902585983276367.
[I 2026-09-26 00:41:44,211] Trial 4 finished with value: 0.7369438409805298 and parameters: {'hidden_layer': 121, 'learning_rate': 0.00024111809354034197, 'momentum': 0.059384181246771736, 'weight_decay': 0.00015785437915296653, 'elu_alpha': 0.34326495795251943}. Best is trial 3 with value: 0.5902585983276367.
[I 2026-09-26 00:41:48,119] Trial 5 pruned.
[I 2026-09-26 00:42:52,934] Trial 6 finished with value: 0.5824297666549683 and parameters: {'hidden_layer': 78, 'learning_rate': 0.016840616848368777, 'momentum': 0.10885154794237688, 'weight_decay': 0.006867806509432818, 'elu_alpha': 0.593243871301732}. Best is trial 6 with value: 0.5824297666549683.
[I 2026-09-26 00:43:01,868] Trial 7 pruned.
[I 2026-09-26 00:43:26,889] Trial 8 pruned.
[I 2026-09-26 00:43:42,146] Trial 9 pruned.
[I 2026-09-26 00:43:44,738] Trial 10 pruned.
[I 2026-09-26 00:44:21,395] Trial 11 finished with value: 0.5865633487701416 and parameters: {'hidden_layer': 116, 'learning_rate': 0.012317716140327948, 'momentum': 0.31169979344552706, 'weight_decay': 0.0016163451751148204, 'elu_alpha': 0.8207523551045319}. Best is trial 6 with value: 0.5824297666549683.
[I 2026-09-26 00:44:56,664] Trial 12 finished with value: 0.5874293446540833 and parameters: {'hidden_layer': 127, 'learning_rate': 0.015910584380307183, 'momentum': 0.275940979805923, 'weight_decay': 0.000910767775262362, 'elu_alpha': 0.8836745416715401}. Best is trial 6 with value: 0.5824297666549683.
[I 2026-09-26 00:45:29,910] Trial 13 finished with value: 0.5912509560585022 and parameters: {'hidden_layer': 111, 'learning_rate': 0.023249294828250604, 'momentum': 0.20827066772812006, 'weight_decay': 0.0006865107080318142, 'elu_alpha': 1.3691573025976727}. Best is trial 6 with value: 0.5824297666549683.
[I 2026-09-26 00:45:54,520] Trial 14 pruned.
[I 2026-09-26 00:46:39,081] Trial 15 finished with value: 0.5880971550941467 and parameters: {'hidden_layer': 110, 'learning_rate': 0.010860546454331007, 'momentum': 0.0013037697836423973, 'weight_decay': 0.0006908990493511563, 'elu_alpha': 1.8508543987629344}. Best is trial 6 with value: 0.5824297666549683.
[I 2026-09-26 00:46:46,160] Trial 16 pruned.
[I 2026-09-26 00:46:54,996] Trial 17 pruned.
[I 2026-09-26 00:47:19,750] Trial 18 finished with value: 0.5985415577888489 and parameters: {'hidden_layer': 49, 'learning_rate': 0.09390821002590703, 'momentum': 0.5368824206063745, 'weight_decay': 0.008990866618351709, 'elu_alpha': 0.7486336410750798}. Best is trial 6 with value: 0.5824297666549683.
[I 2026-09-26 00:47:22,792] Trial 19 pruned.
[I 2026-09-26 00:47:46,666] Trial 20 pruned.
[I 2026-09-26 00:48:16,944] Trial 21 finished with value: 0.5881062746047974 and parameters: {'hidden_layer': 126, 'learning_rate': 0.016380654208832404, 'momentum': 0.11359868675005252, 'weight_decay': 0.0014222828566663097, 'elu_alpha': 0.9315748808424205}. Best is trial 6 with value: 0.5824297666549683.
[I 2026-09-26 00:48:24,473] Trial 22 pruned.
[I 2026-09-26 00:48:27,461] Trial 23 pruned.
[I 2026-09-26 00:49:50,971] Trial 24 finished with value: 0.579735279083252 and parameters: {'hidden_layer': 115, 'learning_rate': 0.007733461728076769, 'momentum': 0.01320589449259181, 'weight_decay': 0.005031964549576615, 'elu_alpha': 0.8884902198997549}. Best is trial 24 with value: 0.579735279083252.
[I 2026-09-26 00:50:07,989] Trial 25 pruned.
[I 2026-09-26 00:51:02,835] Trial 26 finished with value: 0.5842495560646057 and parameters: {'hidden_layer': 89, 'learning_rate': 0.007966375886940031, 'momentum': 0.1699902427031857, 'weight_decay': 5.279432294911263e-05, 'elu_alpha': 1.1125827289770736}. Best is trial 24 with value: 0.579735279083252.
[I 2026-09-26 00:51:18,239] Trial 27 pruned.
[I 2026-09-26 00:51:42,064] Trial 28 pruned.
[I 2026-09-26 00:53:10,501] Trial 29 finished with value: 0.5876563191413879 and parameters: {'hidden_layer': 93, 'learning_rate': 0.003486318728961161, 'momentum': 0.17069240307839165, 'weight_decay': 5.5494240661010645e-05, 'elu_alpha': 1.4420236839764595}. Best is trial 24 with value: 0.579735279083252.
[I 2026-09-26 00:53:35,744] Trial 30 pruned.
[I 2026-09-26 00:53:44,418] Trial 31 pruned.
[I 2026-09-26 00:54:31,605] Trial 32 finished with value: 0.5744708776473999 and parameters: {'hidden_layer': 106, 'learning_rate': 0.024575548606487148, 'momentum': 0.08142248455468477, 'weight_decay': 0.004794425781889501, 'elu_alpha': 0.8996808973918416}. Best is trial 32 with value: 0.5744708776473999.
[I 2026-09-26 00:54:38,109] Trial 33 pruned.
[I 2026-09-26 00:54:59,086] Trial 34 pruned.
[I 2026-09-26 00:55:09,034] Trial 35 pruned.
[I 2026-09-26 00:55:31,245] Trial 36 pruned.
[I 2026-09-26 00:55:53,349] Trial 37 finished with value: 0.5948911905288696 and parameters: {'hidden_layer': 71, 'learning_rate': 0.02421175791893067, 'momentum': 0.6996502313095214, 'weight_decay': 0.0002297568308392888, 'elu_alpha': 0.5967334193505279}. Best is trial 32 with value: 0.5744708776473999.
[I 2026-09-26 00:55:59,267] Trial 38 pruned.
[I 2026-09-26 00:56:03,382] Trial 39 pruned.
[I 2026-09-26 00:58:09,661] Trial 40 finished with value: 0.588050901889801 and parameters: {'hidden_layer': 120, 'learning_rate': 0.0019200532967928404, 'momentum': 0.37860960529989707, 'weight_decay': 0.00262790763548697, 'elu_alpha': 0.2709468777784627}. Best is trial 32 with value: 0.5744708776473999.
[I 2026-09-26 00:58:56,453] Trial 41 finished with value: 0.5849711894989014 and parameters: {'hidden_layer': 119, 'learning_rate': 0.01170388606321336, 'momentum': 0.1551883433059395, 'weight_decay': 0.0054985268005643744, 'elu_alpha': 0.832752783794389}. Best is trial 32 with value: 0.5744708776473999.
[I 2026-09-26 01:00:19,431] Trial 42 finished with value: 0.5820534229278564 and parameters: {'hidden_layer': 106, 'learning_rate': 0.005759783163415122, 'momentum': 0.149306304781896, 'weight_decay': 0.005511782613626159, 'elu_alpha': 0.8816174451914112}. Best is trial 32 with value: 0.5744708776473999.
[I 2026-09-26 01:02:04,368] Trial 43 finished with value: 0.5814500451087952 and parameters: {'hidden_layer': 107, 'learning_rate': 0.005269692279863557, 'momentum': 0.09719577083899389, 'weight_decay': 0.009944239546516145, 'elu_alpha': 0.971217542255635}. Best is trial 32 with value: 0.5744708776473999.
[I 2026-09-26 01:03:31,639] Trial 44 finished with value: 0.5846537947654724 and parameters: {'hidden_layer': 107, 'learning_rate': 0.005349204021415746, 'momentum': 0.08453447917382387, 'weight_decay': 0.006178466581927391, 'elu_alpha': 0.911018062504457}. Best is trial 32 with value: 0.5744708776473999.
[I 2026-09-26 01:03:57,799] Trial 45 pruned.
[I 2026-09-26 01:04:03,028] Trial 46 pruned.
[I 2026-09-26 01:04:23,943] Trial 47 pruned.
[I 2026-09-26 01:04:51,832] Trial 48 finished with value: 0.5916692018508911 and parameters: {'hidden_layer': 106, 'learning_rate': 0.05449376256105741, 'momentum': 0.001273220716914096, 'weight_decay': 0.003440697455042193, 'elu_alpha': 0.5375408610483975}. Best is trial 32 with value: 0.5744708776473999.
[I 2026-09-26 01:05:03,230] Trial 49 pruned.
[I 2026-09-26 01:05:29,165] Trial 50 pruned.
[I 2026-09-26 01:06:17,441] Trial 51 finished with value: 0.5931552648544312 and parameters: {'hidden_layer': 92, 'learning_rate': 0.008365805950356896, 'momentum': 0.15737884033289462, 'weight_decay': 5.426012918824931e-05, 'elu_alpha': 1.1468237444187246}. Best is trial 32 with value: 0.5744708776473999.
[I 2026-09-26 01:07:12,510] Trial 52 finished with value: 0.5829291343688965 and parameters: {'hidden_layer': 87, 'learning_rate': 0.012764482384420493, 'momentum': 0.19687735053600394, 'weight_decay': 0.008944899423188716, 'elu_alpha': 1.0474224830858445}. Best is trial 32 with value: 0.5744708776473999.
[I 2026-09-26 01:08:34,812] Trial 53 finished with value: 0.5773473978042603 and parameters: {'hidden_layer': 63, 'learning_rate': 0.01296245920684304, 'momentum': 0.2171459239653727, 'weight_decay': 0.008941780928223248, 'elu_alpha': 0.6450638337875254}. Best is trial 32 with value: 0.5744708776473999.
[I 2026-09-26 01:08:52,880] Trial 54 pruned.
[I 2026-09-26 01:10:27,535] Trial 55 finished with value: 0.5775435566902161 and parameters: {'hidden_layer': 62, 'learning_rate': 0.010745049180921114, 'momentum': 0.03593475712266582, 'weight_decay': 0.009791994660422543, 'elu_alpha': 0.6263096815866089}. Best is trial 32 with value: 0.5744708776473999.
[I 2026-09-26 01:12:02,818] Trial 56 finished with value: 0.5736604928970337 and parameters: {'hidden_layer': 64, 'learning_rate': 0.009192486108599622, 'momentum': 0.042054381313093, 'weight_decay': 0.009767366643098496, 'elu_alpha': 0.621374494366071}. Best is trial 56 with value: 0.5736604928970337.
[I 2026-09-26 01:12:59,132] Trial 57 finished with value: 0.5766786336898804 and parameters: {'hidden_layer': 65, 'learning_rate': 0.032178098546860046, 'momentum': 0.050644931831687307, 'weight_decay': 0.009966399827213458, 'elu_alpha': 0.4682409392568434}. Best is trial 56 with value: 0.5736604928970337.
[I 2026-09-26 01:13:04,310] Trial 58 pruned.
[I 2026-09-26 01:13:14,132] Trial 59 pruned.
[I 2026-09-26 01:13:51,308] Trial 60 finished with value: 0.5873033404350281 and parameters: {'hidden_layer': 42, 'learning_rate': 0.0469944378948088, 'momentum': 0.03222347863339525, 'weight_decay': 0.0031578011728142286, 'elu_alpha': 0.48019798710712863}. Best is trial 56 with value: 0.5736604928970337.
[I 2026-09-26 01:14:01,818] Trial 61 pruned.
[I 2026-09-26 01:14:17,175] Trial 62 pruned.
[I 2026-09-26 01:14:27,375] Trial 63 pruned.
[I 2026-09-26 01:14:32,534] Trial 64 pruned.
[I 2026-09-26 01:15:48,969] Trial 65 finished with value: 0.5840474963188171 and parameters: {'hidden_layer': 48, 'learning_rate': 0.010093526790414887, 'momentum': 0.13029054804012913, 'weight_decay': 0.0010535522355389212, 'elu_alpha': 0.608572471815352}. Best is trial 56 with value: 0.5736604928970337.
[I 2026-09-26 01:15:59,909] Trial 66 pruned.
[I 2026-09-26 01:16:04,463] Trial 67 pruned.
[I 2026-09-26 01:16:29,252] Trial 68 pruned.
[I 2026-09-26 01:17:30,747] Trial 69 finished with value: 0.5836297273635864 and parameters: {'hidden_layer': 60, 'learning_rate': 0.0077170149801640345, 'momentum': 0.42255766271933676, 'weight_decay': 0.001891919828227196, 'elu_alpha': 0.9619600113089074}. Best is trial 56 with value: 0.5736604928970337.
[I 2026-09-26 01:18:04,837] Trial 70 finished with value: 0.582955002784729 and parameters: {'hidden_layer': 51, 'learning_rate': 0.01858024169180305, 'momentum': 0.6349725487408916, 'weight_decay': 0.006968475818172184, 'elu_alpha': 0.6543148077571936}. Best is trial 56 with value: 0.5736604928970337.
[I 2026-09-26 01:18:22,531] Trial 71 pruned.
[I 2026-09-26 01:18:41,512] Trial 72 pruned.
[I 2026-09-26 01:18:52,645] Trial 73 pruned.
[I 2026-09-26 01:19:19,536] Trial 74 pruned.
[I 2026-09-26 01:19:26,227] Trial 75 pruned.
[I 2026-09-26 01:19:36,804] Trial 76 pruned.
[I 2026-09-26 01:21:38,146] Trial 77 finished with value: 0.576038658618927 and parameters: {'hidden_layer': 109, 'learning_rate': 0.0072713660605485874, 'momentum': 0.028781254745692996, 'weight_decay': 0.009992540226814629, 'elu_alpha': 0.7816246145451607}. Best is trial 56 with value: 0.5736604928970337.
[I 2026-09-26 01:21:52,528] Trial 78 pruned.
[I 2026-09-26 01:22:19,271] Trial 79 pruned.

{'hidden_layer': 64, 'learning_rate': 0.009192486108599622, 'momentum': 0.042054381313093, 'weight_decay': 0.009767366643098496, 'elu_alpha': 0.621374494366071}
0.5736604928970337

In [11]:
acts = ['relu', 'leaky_relu', 'elu']
name = "base"
results = []
for activation in acts:
    setup = {'activation': activation, 'balanced': False}
    alpha = 0
    params = retrieve_params(f'params/student_dropout/{name}_{activation}.json')
    if activation == 'leaky_relu':
        alpha = params["leaky_relu_alpha"]
    elif activation == 'elu':
        alpha = params["elu_alpha"]
    result = cv_classification(X_pool, y_pool, out_units=n_classes, out_act='softmax', 
                    loss='sparse_categorical_crossentropy', k=5, random_state=42, 
                    hidden_units=params['hidden_layer'], activation=activation, alpha=alpha, 
                    learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], balanced=False)
    for key, val in result.items():
        setup[key] = val

    results.append(setup)

results_df = pd.DataFrame(results)
results_df.round(4).to_csv(f"results/student_dropout/cv_validation.csv", index=False)

In [14]:
results_df = pd.read_csv("results/student_dropout/cv_validation.csv")
results_df

   activation  balanced     auc     acc      f1
0        relu     False  0.8775  0.7691  0.6963
1  leaky_relu     False  0.8798  0.7708  0.6991
2         elu     False  0.8837  0.7697  0.6923

In [12]:
activation = 'leaky_relu'
params = retrieve_params(f'params/student_dropout/base_{activation}.json')
scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)

model = create_model(X_train.shape[1], hidden_units=params['hidden_layer'], activation=activation, alpha=params['leaky_relu_alpha'], out_units=n_classes, out_act='softmax', 
                 learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], loss='sparse_categorical_crossentropy')
# params['learning_rate']
history = []
runs = 100
epochs = 200 // runs
fit_kwargs = {
    "epochs": epochs,
    "batch_size": 32,
    # "validation_split": 0.15,
    # "callbacks": [early_stopping],
    "verbose": 0
}
tic = time()
for i in range(runs):
    iteration = {'cumulative epochs': epochs * (i + 1)}
    iter_hist = model.fit(
        X_train,
        y_pool,
        **fit_kwargs
    )

    train_loss = iter_hist.history['loss']
    weights = model.get_weights()

    if not all(np.all(np.isfinite(w)) for w in weights):
        print(f"Model became unstable at iteration {i + 1}")
        break

    y_prob = model.predict(X_val, verbose=0)

    if not np.all(np.isfinite(y_prob)):
        print(f"NaN/Inf predictions at iteration {i + 1}")
        break
        
    y_pred = np.argmax(y_prob, axis=1)
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average='macro')
    auc = roc_auc_score(y_test, y_prob, average='macro', multi_class='ovr')
    toc = time()
    
    iteration['Training loss'] = train_loss[-1]
    iteration['Accuracy'] = acc
    iteration['macro F1'] = f1
    iteration['ROC-AUC'] = auc
    iteration['time'] = toc - tic
    history.append(iteration)
    print(f"Iteration {i+1}: ")
    for l in range(len(train_loss)):
        print(f"\t{train_loss[l]}")

run_df = pd.DataFrame(history)
run_df.round(4).to_csv(f"results/student_dropout/passive_learning.csv", index=False)

Iteration 1:
	0.8640780448913574
	0.6533988118171692
Iteration 2:
	0.6031410098075867
	0.5774428844451904
Iteration 3:
	0.5616981983184814
	0.5496101975440979
Iteration 4:
	0.5397596955299377
	0.530868411064148
Iteration 5:
	0.5254284739494324
	0.5181592106819153
Iteration 6:
	0.5135675072669983
	0.5080148577690125
Iteration 7:
	0.5040453672409058
	0.5001048445701599
Iteration 8:
	0.49652522802352905
	0.49173304438591003
Iteration 9:
	0.4882151186466217
	0.4844587445259094
Iteration 10:
	0.48086151480674744
	0.47841352224349976
Iteration 11:
	0.4746659994125366
	0.4707673192024231
Iteration 12:
	0.468472957611084
	0.4655253291130066
Iteration 13:
	0.46251022815704346
	0.4583451747894287
Iteration 14:
	0.45645052194595337
	0.4541664719581604
Iteration 15:
	0.4499218165874481
	0.4474157691001892
Iteration 16:
	0.4442249536514282
	0.4413573145866394
Iteration 17:
	0.4383985102176666
	0.4365990459918976
Iteration 18:
	0.43302562832832336
	0.43144509196281433
Iteration 19:
	0.42775896191596985
	0.42628154158592224
Iteration 20:
	0.42263156175613403
	0.42113593220710754
Iteration 21:
	0.41741299629211426
	0.41543492674827576
Iteration 22:
	0.4120923578739166
	0.4111364483833313
Iteration 23:
	0.4067917466163635
	0.4050002098083496
Iteration 24:
	0.4033043682575226
	0.4005085229873657
Iteration 25:
	0.3977866470813751
	0.39527085423469543
Iteration 26:
	0.393953800201416
	0.3897584080696106
Iteration 27:
	0.38911619782447815
	0.3851757049560547
Iteration 28:
	0.3840887248516083
	0.38126614689826965
Iteration 29:
	0.3793114721775055
	0.37659353017807007
Iteration 30:
	0.3750501275062561
	0.3713061809539795
Iteration 31:
	0.3704555630683899
	0.3676941394805908
Iteration 32:
	0.3651679456233978
	0.36391839385032654
Iteration 33:
	0.36144551634788513
	0.35886675119400024
Iteration 34:
	0.35755160450935364
	0.35613271594047546
Iteration 35:
	0.3541065454483032
	0.35114869475364685
Iteration 36:
	0.34806832671165466
	0.34739962220191956
Iteration 37:
	0.3468264937400818
	0.3431367576122284
Iteration 38:
	0.34133657813072205
	0.33963242173194885
Iteration 39:
	0.33762964606285095
	0.334780216217041
Iteration 40:
	0.33300352096557617
	0.3308572769165039
Iteration 41:
	0.3301014304161072
	0.3291856348514557
Iteration 42:
	0.32517483830451965
	0.32409974932670593
Iteration 43:
	0.3222687244415283
	0.3198811709880829
Iteration 44:
	0.31914567947387695
	0.3163122832775116
Iteration 45:
	0.3163697123527527
	0.31405264139175415
Iteration 46:
	0.31123319268226624
	0.3113875389099121
Iteration 47:
	0.3069441318511963
	0.30669254064559937
Iteration 48:
	0.3030658960342407
	0.3050647974014282
Iteration 49:
	0.3036629259586334
	0.29812830686569214
Iteration 50:
	0.2985253930091858
	0.2960264980792999
Iteration 51:
	0.29408740997314453
	0.2917214632034302
Iteration 52:
	0.2913520038127899
	0.29006505012512207
Iteration 53:
	0.28949716687202454
	0.2875770628452301
Iteration 54:
	0.2868010699748993
	0.2832598090171814
Iteration 55:
	0.2828620672225952
	0.28144484758377075
Iteration 56:
	0.27794915437698364
	0.27744460105895996
Iteration 57:
	0.2759183645248413
	0.27650704979896545
Iteration 58:
	0.27452635765075684
	0.27280107140541077
Iteration 59:
	0.2711486518383026
	0.27061328291893005
Iteration 60:
	0.2673761248588562
	0.26570263504981995
Iteration 61:
	0.26388031244277954
	0.2609350383281708
Iteration 62:
	0.26310116052627563
	0.2636788785457611
Iteration 63:
	0.2602876126766205
	0.2602268159389496
Iteration 64:
	0.25650203227996826
	0.25398415327072144
Iteration 65:
	0.2532529830932617
	0.253802627325058
Iteration 66:
	0.2508029043674469
	0.25072160363197327
Iteration 67:
	0.24884596467018127
	0.2468814253807068
Iteration 68:
	0.24691420793533325
	0.24834740161895752
Iteration 69:
	0.24404092133045197
	0.2442788928747177
Iteration 70:
	0.24176296591758728
	0.24098579585552216
Iteration 71:
	0.23669971525669098
	0.23632092773914337
Iteration 72:
	0.2379836142063141
	0.2368098497390747
Iteration 73:
	0.2323070615530014
	0.23290647566318512
Iteration 74:
	0.23145563900470734
	0.2311626672744751
Iteration 75:
	0.22718466818332672
	0.23064440488815308
Iteration 76:
	0.2279084175825119
	0.22479908168315887
Iteration 77:
	0.2265956997871399
	0.2244831770658493
Iteration 78:
	0.2212354689836502
	0.2219589352607727
Iteration 79:
	0.2201869934797287
	0.21895872056484222
Iteration 80:
	0.21994857490062714
	0.21642139554023743
Iteration 81:
	0.21594464778900146
	0.21457001566886902
Iteration 82:
	0.21453048288822174
	0.2128800004720688
Iteration 83:
	0.21003448963165283
	0.21228978037834167
Iteration 84:
	0.2092951536178589
	0.20724548399448395
Iteration 85:
	0.20746810734272003
	0.20642757415771484
Iteration 86:
	0.20578613877296448
	0.20274095237255096
Iteration 87:
	0.20302313566207886
	0.2015836238861084
Iteration 88:
	0.20051626861095428
	0.20109429955482483
Iteration 89:
	0.1984415054321289
	0.20061682164669037
Iteration 90:
	0.20109298825263977
	0.1971195936203003
Iteration 91:
	0.19620661437511444
	0.19414418935775757
Iteration 92:
	0.19167977571487427
	0.1934361457824707
Iteration 93:
	0.19246748089790344
	0.19395560026168823
Iteration 94:
	0.1922362595796585
	0.18949301540851593
Iteration 95:
	0.1893804520368576
	0.18976356089115143
Iteration 96:
	0.18863976001739502
	0.1850811392068863
Iteration 97:
	0.18501442670822144
	0.18321187794208527
Iteration 98:
	0.1842324435710907
	0.18256564438343048
Iteration 99:
	0.18224170804023743
	0.1815015971660614
Iteration 100:
	0.17993199825286865
	0.17936229705810547

In [15]:
activation = 'leaky_relu'
params = retrieve_params(f'params/student_dropout/base_{activation}.json')

scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)

history = active_learning_mc(X_train, y_pool, X_val, y_test, random_sampling, num_iter=100, unlab_size=0.9, random_state=100, verbose=True,
                               hidden_units=params['hidden_layer'], activation=activation, alpha=params['leaky_relu_alpha'], out_units=n_classes, balanced=False,
                               learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'] 
)

run_df = pd.DataFrame(history)
run_df.round(4).to_csv(f"results/student_dropout/uncertainty_sampling.csv", index=False)

Iteration 1: 353 labelled instances
	Accuracy = 0.5615819209039548
	macro F1 = 0.47567788026737307
	AUC = 0.6860613262337812

Iteration 2: 385 labelled instances
	Accuracy = 0.6666666666666666
	macro F1 = 0.5035590446395342
	AUC = 0.7538927297994474

Iteration 3: 417 labelled instances
	Accuracy = 0.6779661016949152
	macro F1 = 0.5396888853932326
	AUC = 0.7800173312781339

Iteration 4: 449 labelled instances
	Accuracy = 0.6915254237288135
	macro F1 = 0.5679775703748305
	AUC = 0.7925794189991895

Iteration 5: 481 labelled instances
	Accuracy = 0.6983050847457627
	macro F1 = 0.5801014698069178
	AUC = 0.8023541218354463

Iteration 6: 513 labelled instances
	Accuracy = 0.7028248587570621
	macro F1 = 0.5964596758647653
	AUC = 0.8102467877280217

Iteration 7: 545 labelled instances
	Accuracy = 0.7096045197740113
	macro F1 = 0.6050928113872102
	AUC = 0.8167747461114435

Iteration 8: 577 labelled instances
	Accuracy = 0.7220338983050848
	macro F1 = 0.6215118965118965
	AUC = 0.8225949724903568

Iteration 9: 609 labelled instances
	Accuracy = 0.7231638418079096
	macro F1 = 0.6220408891751449
	AUC = 0.8269029701152929

Iteration 10: 641 labelled instances
	Accuracy = 0.7299435028248588
	macro F1 = 0.6335745749007398
	AUC = 0.8309638912863667

Iteration 11: 673 labelled instances
	Accuracy = 0.7344632768361582
	macro F1 = 0.6328588089339736
	AUC = 0.8357157965766296

Iteration 12: 705 labelled instances
	Accuracy = 0.735593220338983
	macro F1 = 0.6413555628844284
	AUC = 0.8388045024415512

Iteration 13: 737 labelled instances
	Accuracy = 0.7344632768361582
	macro F1 = 0.6496630452025489
	AUC = 0.8394924522909749

Iteration 14: 769 labelled instances
	Accuracy = 0.7378531073446327
	macro F1 = 0.6468125206391622
	AUC = 0.8456675079284454

Iteration 15: 801 labelled instances
	Accuracy = 0.7367231638418079
	macro F1 = 0.6420986743567388
	AUC = 0.8473652368253712

Iteration 16: 833 labelled instances
	Accuracy = 0.7389830508474576
	macro F1 = 0.6594563376385194
	AUC = 0.8467604380271146

Iteration 17: 865 labelled instances
	Accuracy = 0.7378531073446327
	macro F1 = 0.6604697205979507
	AUC = 0.849873042099115

Iteration 18: 897 labelled instances
	Accuracy = 0.7480225988700565
	macro F1 = 0.6638783154684215
	AUC = 0.8521150794146733

Iteration 19: 929 labelled instances
	Accuracy = 0.7446327683615819
	macro F1 = 0.6617356602108644
	AUC = 0.8534791432847086

Iteration 20: 961 labelled instances
	Accuracy = 0.7412429378531074
	macro F1 = 0.6554143949959849
	AUC = 0.8547645745435476

Iteration 21: 993 labelled instances
	Accuracy = 0.7468926553672316
	macro F1 = 0.6657764542004899
	AUC = 0.8552747250694686

Iteration 22: 1025 labelled instances
	Accuracy = 0.7468926553672316
	macro F1 = 0.6609182695174081
	AUC = 0.8569757485028964

Iteration 23: 1057 labelled instances
	Accuracy = 0.7468926553672316
	macro F1 = 0.6608255015050343
	AUC = 0.858289880966152

Iteration 24: 1089 labelled instances
	Accuracy = 0.7457627118644068
	macro F1 = 0.6604700778103437
	AUC = 0.8580675721116174

Iteration 25: 1121 labelled instances
	Accuracy = 0.7446327683615819
	macro F1 = 0.6651232033621991
	AUC = 0.8558128066750008

Iteration 26: 1153 labelled instances
	Accuracy = 0.7502824858757062
	macro F1 = 0.6720309672431215
	AUC = 0.8571909436409286

Iteration 27: 1185 labelled instances
	Accuracy = 0.752542372881356
	macro F1 = 0.6775457247676829
	AUC = 0.8574800092149325

Iteration 28: 1217 labelled instances
	Accuracy = 0.7435028248587571
	macro F1 = 0.6548930806902592
	AUC = 0.8574732255330346

Iteration 29: 1249 labelled instances
	Accuracy = 0.7401129943502824
	macro F1 = 0.6612532071153856
	AUC = 0.853421256858684

Iteration 30: 1281 labelled instances
	Accuracy = 0.7468926553672316
	macro F1 = 0.666048910275689
	AUC = 0.8567889479664209

Iteration 31: 1313 labelled instances
	Accuracy = 0.751412429378531
	macro F1 = 0.6726042643157748
	AUC = 0.8573052453542793

Iteration 32: 1345 labelled instances
	Accuracy = 0.7446327683615819
	macro F1 = 0.6667926751961343
	AUC = 0.8609459497546118

Iteration 33: 1377 labelled instances
	Accuracy = 0.7502824858757062
	macro F1 = 0.6741455468608919
	AUC = 0.8602993495775477

Iteration 34: 1409 labelled instances
	Accuracy = 0.7446327683615819
	macro F1 = 0.6666896715651399
	AUC = 0.8597241649096331

Iteration 35: 1441 labelled instances
	Accuracy = 0.7435028248587571
	macro F1 = 0.6637167725458896
	AUC = 0.8584915051865725

Iteration 36: 1473 labelled instances
	Accuracy = 0.752542372881356
	macro F1 = 0.674428184991056
	AUC = 0.8553429603154616

Iteration 37: 1505 labelled instances
	Accuracy = 0.751412429378531
	macro F1 = 0.6766133936382287
	AUC = 0.8566384519350555

Iteration 38: 1537 labelled instances
	Accuracy = 0.7536723163841808
	macro F1 = 0.6778566765947679
	AUC = 0.8592373973571871

Iteration 39: 1569 labelled instances
	Accuracy = 0.7559322033898305
	macro F1 = 0.6787475644789748
	AUC = 0.8600945666475194

Iteration 40: 1601 labelled instances
	Accuracy = 0.7491525423728813
	macro F1 = 0.6701140250710558
	AUC = 0.8622357541832429

Iteration 41: 1633 labelled instances
	Accuracy = 0.7548022598870057
	macro F1 = 0.6756689070321197
	AUC = 0.8641222603322078

Iteration 42: 1665 labelled instances
	Accuracy = 0.7502824858757062
	macro F1 = 0.6681432962341965
	AUC = 0.8632722639417675

Iteration 43: 1697 labelled instances
	Accuracy = 0.7491525423728813
	macro F1 = 0.6723945460841018
	AUC = 0.862784203861568

Iteration 44: 1729 labelled instances
	Accuracy = 0.7502824858757062
	macro F1 = 0.6736267893263292
	AUC = 0.8633474268727896

Iteration 45: 1761 labelled instances
	Accuracy = 0.7491525423728813
	macro F1 = 0.6705936774415946
	AUC = 0.8629297853876537

Iteration 46: 1793 labelled instances
	Accuracy = 0.7412429378531074
	macro F1 = 0.6624925193102825
	AUC = 0.8633102111568901

Iteration 47: 1825 labelled instances
	Accuracy = 0.7435028248587571
	macro F1 = 0.6608934329788979
	AUC = 0.861999313171955

Iteration 48: 1857 labelled instances
	Accuracy = 0.7401129943502824
	macro F1 = 0.658310533893089
	AUC = 0.8627450501817049

Iteration 49: 1889 labelled instances
	Accuracy = 0.7480225988700565
	macro F1 = 0.6709578292141963
	AUC = 0.8663532833758708

Iteration 50: 1921 labelled instances
	Accuracy = 0.7446327683615819
	macro F1 = 0.667092609230974
	AUC = 0.8612936209305159

Iteration 51: 1953 labelled instances
	Accuracy = 0.752542372881356
	macro F1 = 0.6713469192327258
	AUC = 0.8639861303004194

Iteration 52: 1985 labelled instances
	Accuracy = 0.7491525423728813
	macro F1 = 0.6746049722918647
	AUC = 0.8645652098606106

Iteration 53: 2017 labelled instances
	Accuracy = 0.751412429378531
	macro F1 = 0.6739954484026612
	AUC = 0.8658252764693688

Iteration 54: 2049 labelled instances
	Accuracy = 0.7457627118644068
	macro F1 = 0.665483146405777
	AUC = 0.8661477932335552

Iteration 55: 2081 labelled instances
	Accuracy = 0.752542372881356
	macro F1 = 0.6781126115815668
	AUC = 0.8674382401345913

Iteration 56: 2113 labelled instances
	Accuracy = 0.7480225988700565
	macro F1 = 0.6708527997709294
	AUC = 0.867726512824012

Iteration 57: 2145 labelled instances
	Accuracy = 0.7446327683615819
	macro F1 = 0.673619780846784
	AUC = 0.8669563659254452

Iteration 58: 2177 labelled instances
	Accuracy = 0.7446327683615819
	macro F1 = 0.6695532528793203
	AUC = 0.8680558663036996

Iteration 59: 2209 labelled instances
	Accuracy = 0.7367231638418079
	macro F1 = 0.6618128937283579
	AUC = 0.8677958111850391

Iteration 60: 2241 labelled instances
	Accuracy = 0.7344632768361582
	macro F1 = 0.6636345757797876
	AUC = 0.8669813438468772

Iteration 61: 2273 labelled instances
	Accuracy = 0.7344632768361582
	macro F1 = 0.6596747745436424
	AUC = 0.8666684098281184

Iteration 62: 2305 labelled instances
	Accuracy = 0.7457627118644068
	macro F1 = 0.6703878049227754
	AUC = 0.867921715473332

Iteration 63: 2337 labelled instances
	Accuracy = 0.7412429378531074
	macro F1 = 0.6725110301027563
	AUC = 0.8672430021409773

Iteration 64: 2369 labelled instances
	Accuracy = 0.7446327683615819
	macro F1 = 0.6734012311945078
	AUC = 0.8696344134391234

Iteration 65: 2401 labelled instances
	Accuracy = 0.7423728813559322
	macro F1 = 0.6705211999329647
	AUC = 0.8700935075879578

Iteration 66: 2433 labelled instances
	Accuracy = 0.7401129943502824
	macro F1 = 0.6701129826717366
	AUC = 0.8706614813794832

Iteration 67: 2465 labelled instances
	Accuracy = 0.7457627118644068
	macro F1 = 0.675738612457037
	AUC = 0.8721461933376192

Iteration 68: 2497 labelled instances
	Accuracy = 0.7435028248587571
	macro F1 = 0.676680956218557
	AUC = 0.8685517732883481

Iteration 69: 2529 labelled instances
	Accuracy = 0.7401129943502824
	macro F1 = 0.668995629458072
	AUC = 0.870106656940599

Iteration 70: 2561 labelled instances
	Accuracy = 0.7412429378531074
	macro F1 = 0.6714443348828474
	AUC = 0.8680548935832356

Iteration 71: 2593 labelled instances
	Accuracy = 0.7367231638418079
	macro F1 = 0.6665857192841529
	AUC = 0.8686470900671353

Iteration 72: 2625 labelled instances
	Accuracy = 0.7389830508474576
	macro F1 = 0.6683621838968331
	AUC = 0.8683222642001249

Iteration 73: 2657 labelled instances
	Accuracy = 0.7378531073446327
	macro F1 = 0.6637043351962363
	AUC = 0.8693680029934795

Iteration 74: 2689 labelled instances
	Accuracy = 0.7322033898305085
	macro F1 = 0.6632520907424871
	AUC = 0.8684253220631626

Iteration 75: 2721 labelled instances
	Accuracy = 0.7367231638418079
	macro F1 = 0.6625269747479385
	AUC = 0.8686653188193825

Iteration 76: 2753 labelled instances
	Accuracy = 0.7367231638418079
	macro F1 = 0.6665381402223507
	AUC = 0.8686575583606299

Iteration 77: 2785 labelled instances
	Accuracy = 0.7423728813559322
	macro F1 = 0.6681567439571331
	AUC = 0.8708091076782883

Iteration 78: 2817 labelled instances
	Accuracy = 0.7389830508474576
	macro F1 = 0.6642268371728144
	AUC = 0.8690458158917228

Iteration 79: 2849 labelled instances
	Accuracy = 0.7333333333333333
	macro F1 = 0.6672418796371505
	AUC = 0.8675081902377396

Iteration 80: 2881 labelled instances
	Accuracy = 0.7468926553672316
	macro F1 = 0.6767655219418997
	AUC = 0.8710203760761952

Iteration 81: 2913 labelled instances
	Accuracy = 0.7423728813559322
	macro F1 = 0.6676219958468935
	AUC = 0.8705059277894356

Iteration 82: 2945 labelled instances
	Accuracy = 0.7378531073446327
	macro F1 = 0.6694264890197656
	AUC = 0.8683363535277074

Iteration 83: 2977 labelled instances
	Accuracy = 0.7468926553672316
	macro F1 = 0.6696568061778171
	AUC = 0.8669417480425334

Iteration 84: 3009 labelled instances
	Accuracy = 0.7401129943502824
	macro F1 = 0.6665367018677567
	AUC = 0.8668570449297034

Iteration 85: 3041 labelled instances
	Accuracy = 0.735593220338983
	macro F1 = 0.6691556566166672
	AUC = 0.8656079319799881

Iteration 86: 3073 labelled instances
	Accuracy = 0.7367231638418079
	macro F1 = 0.6625708467016027
	AUC = 0.8674160389877185

Iteration 87: 3105 labelled instances
	Accuracy = 0.7412429378531074
	macro F1 = 0.6736709728985462
	AUC = 0.8673079239813842

Iteration 88: 3137 labelled instances
	Accuracy = 0.7367231638418079
	macro F1 = 0.6683026321389013
	AUC = 0.8668825468854351

Iteration 89: 3169 labelled instances
	Accuracy = 0.735593220338983
	macro F1 = 0.6664159799598766
	AUC = 0.8673084586847556

Iteration 90: 3201 labelled instances
	Accuracy = 0.7378531073446327
	macro F1 = 0.6694051355652308
	AUC = 0.8679316689414248

Iteration 91: 3233 labelled instances
	Accuracy = 0.7322033898305085
	macro F1 = 0.6622878073745765
	AUC = 0.8662599788807391

Iteration 92: 3265 labelled instances
	Accuracy = 0.7389830508474576
	macro F1 = 0.6708641892481082
	AUC = 0.865870859473191

Iteration 93: 3297 labelled instances
	Accuracy = 0.7389830508474576
	macro F1 = 0.6734000402170249
	AUC = 0.8651815117925924

Iteration 94: 3329 labelled instances
	Accuracy = 0.7423728813559322
	macro F1 = 0.6767429999352568
	AUC = 0.870155122715713

Iteration 95: 3361 labelled instances
	Accuracy = 0.7367231638418079
	macro F1 = 0.6658858701096002
	AUC = 0.8673142809996864

Iteration 96: 3393 labelled instances
	Accuracy = 0.7457627118644068
	macro F1 = 0.674683744397666
	AUC = 0.8671373001053416

Iteration 97: 3425 labelled instances
	Accuracy = 0.7457627118644068
	macro F1 = 0.6792700423170861
	AUC = 0.8672627693968251

Iteration 98: 3457 labelled instances
	Accuracy = 0.7412429378531074
	macro F1 = 0.6714290093367774
	AUC = 0.8655861661835577

Iteration 99: 3489 labelled instances
	Accuracy = 0.7435028248587571
	macro F1 = 0.6723375013046181
	AUC = 0.8659280886307094

Iteration 100: 3539 labelled instances
	Accuracy = 0.7491525423728813
	macro F1 = 0.6782587381807111
	AUC = 0.8673357219148708

In [16]:
activation = 'leaky_relu'
params = retrieve_params(f'params/student_dropout/base_{activation}.json')

scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)
for beta in [0.9]:
    history = sasla_mc(X_train, y_pool, X_val, y_test, num_iter=100, unlab_size=0.9, random_state=100, verbose=True,
                                   hidden_units=params['hidden_layer'], activation=activation, alpha=params['leaky_relu_alpha'], out_units=n_classes, balanced=False,
                                   learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], beta=beta)
    
    run_df = pd.DataFrame(history)
    run_df.round(4).to_csv(f"results/student_dropout/sasla_{beta}.csv", index=False)

Iteration 1: 3539 labelled instances
	Accuracy = 0.7423728813559322
	macro F1 = 0.6384317957638651
	AUC = 0.8468673691390545

Iteration 2: 3431 labelled instances
	Accuracy = 0.7435028248587571
	macro F1 = 0.6354365921543771
	AUC = 0.8653379556150451

Iteration 3: 3325 labelled instances
	Accuracy = 0.7559322033898305
	macro F1 = 0.666236186796276
	AUC = 0.8706986684627291

Iteration 4: 3324 labelled instances
	Accuracy = 0.7581920903954802
	macro F1 = 0.6726492995425025
	AUC = 0.874453766585578

Iteration 5: 3293 labelled instances
	Accuracy = 0.752542372881356
	macro F1 = 0.6689318686910865
	AUC = 0.8764532420063725

Iteration 6: 3297 labelled instances
	Accuracy = 0.7559322033898305
	macro F1 = 0.6779258570086543
	AUC = 0.876835009052067

Iteration 7: 3280 labelled instances
	Accuracy = 0.7615819209039548
	macro F1 = 0.6785944997833556
	AUC = 0.8790684539111447

Iteration 8: 3260 labelled instances
	Accuracy = 0.7581920903954802
	macro F1 = 0.6847827258390232
	AUC = 0.8799364309209702

Iteration 9: 3292 labelled instances
	Accuracy = 0.7649717514124293
	macro F1 = 0.6880294906529184
	AUC = 0.8804159466523848

Iteration 10: 3261 labelled instances
	Accuracy = 0.7615819209039548
	macro F1 = 0.6907600833113676
	AUC = 0.8800251975935942

Iteration 11: 3268 labelled instances
	Accuracy = 0.7615819209039548
	macro F1 = 0.6876154684748931
	AUC = 0.8814325853321417

Iteration 12: 3261 labelled instances
	Accuracy = 0.7627118644067796
	macro F1 = 0.6892040108311305
	AUC = 0.8823096925238471

Iteration 13: 3253 labelled instances
	Accuracy = 0.7570621468926554
	macro F1 = 0.6754439128459125
	AUC = 0.8821822584293496

Iteration 14: 3225 labelled instances
	Accuracy = 0.7548022598870057
	macro F1 = 0.677187408370204
	AUC = 0.8817745548094152

Iteration 15: 3241 labelled instances
	Accuracy = 0.7615819209039548
	macro F1 = 0.6877380692053774
	AUC = 0.8834864930735212

Iteration 16: 3246 labelled instances
	Accuracy = 0.7627118644067796
	macro F1 = 0.6870428557653622
	AUC = 0.8829747154580865

Iteration 17: 3217 labelled instances
	Accuracy = 0.7627118644067796
	macro F1 = 0.6802089700993171
	AUC = 0.8839346793183526

Iteration 18: 3190 labelled instances
	Accuracy = 0.7604519774011299
	macro F1 = 0.6899799656871854
	AUC = 0.8831845957336538

Iteration 19: 3207 labelled instances
	Accuracy = 0.7593220338983051
	macro F1 = 0.6809070793690329
	AUC = 0.8843280678549371

Iteration 20: 3210 labelled instances
	Accuracy = 0.7638418079096045
	macro F1 = 0.6970271858250396
	AUC = 0.883148921999258

Iteration 21: 3215 labelled instances
	Accuracy = 0.7638418079096045
	macro F1 = 0.6963076681455179
	AUC = 0.8826943469041807

Iteration 22: 3159 labelled instances
	Accuracy = 0.7706214689265537
	macro F1 = 0.6960078263697337
	AUC = 0.8830186097181602

Iteration 23: 3128 labelled instances
	Accuracy = 0.7649717514124293
	macro F1 = 0.693443907618593
	AUC = 0.8834065605070659

Iteration 24: 3161 labelled instances
	Accuracy = 0.7728813559322034
	macro F1 = 0.7009794141238532
	AUC = 0.8828186368567049

Iteration 25: 3138 labelled instances
	Accuracy = 0.7706214689265537
	macro F1 = 0.7000553797603399
	AUC = 0.882690662446923

Iteration 26: 3125 labelled instances
	Accuracy = 0.7807909604519774
	macro F1 = 0.7068913721347535
	AUC = 0.8828512069731929

Iteration 27: 3090 labelled instances
	Accuracy = 0.7717514124293785
	macro F1 = 0.6987359340937003
	AUC = 0.882998530055306

Iteration 28: 3126 labelled instances
	Accuracy = 0.7762711864406779
	macro F1 = 0.7076489016787524
	AUC = 0.8828065524761564

Iteration 29: 3101 labelled instances
	Accuracy = 0.7774011299435029
	macro F1 = 0.7124706373938356
	AUC = 0.8826495983301026

Iteration 30: 3087 labelled instances
	Accuracy = 0.7728813559322034
	macro F1 = 0.708025562740258
	AUC = 0.880815008623427

Iteration 31: 3081 labelled instances
	Accuracy = 0.7785310734463277
	macro F1 = 0.7115952491276669
	AUC = 0.8818604456075212

Iteration 32: 3078 labelled instances
	Accuracy = 0.7807909604519774
	macro F1 = 0.7126046018083798
	AUC = 0.8819647402830467

Iteration 33: 3073 labelled instances
	Accuracy = 0.7796610169491526
	macro F1 = 0.713555101786595
	AUC = 0.8804245027257845

Iteration 34: 3055 labelled instances
	Accuracy = 0.7717514124293785
	macro F1 = 0.709600566464224
	AUC = 0.8800525712778521

Iteration 35: 3064 labelled instances
	Accuracy = 0.7706214689265537
	macro F1 = 0.700225369079547
	AUC = 0.8793612377451745

Iteration 36: 3037 labelled instances
	Accuracy = 0.7706214689265537
	macro F1 = 0.709213819567541
	AUC = 0.8797228597728081

Iteration 37: 3024 labelled instances
	Accuracy = 0.7751412429378531
	macro F1 = 0.7096633506317841
	AUC = 0.8791598665931385

Iteration 38: 3018 labelled instances
	Accuracy = 0.7728813559322034
	macro F1 = 0.7075524784756544
	AUC = 0.8804699250628079

Iteration 39: 3005 labelled instances
	Accuracy = 0.7785310734463277
	macro F1 = 0.7164103249410901
	AUC = 0.8796984665301739

Iteration 40: 2953 labelled instances
	Accuracy = 0.7661016949152543
	macro F1 = 0.7019417780287345
	AUC = 0.8781036956926722

Iteration 41: 3003 labelled instances
	Accuracy = 0.768361581920904
	macro F1 = 0.7027007995564108
	AUC = 0.8795363458042464

Iteration 42: 2987 labelled instances
	Accuracy = 0.7717514124293785
	macro F1 = 0.7062975416992633
	AUC = 0.8759483982785362

Iteration 43: 2968 labelled instances
	Accuracy = 0.7740112994350282
	macro F1 = 0.7107876829016483
	AUC = 0.8772227163623416

Iteration 44: 2922 labelled instances
	Accuracy = 0.7627118644067796
	macro F1 = 0.6966166863928541
	AUC = 0.8752918838364746

Iteration 45: 2942 labelled instances
	Accuracy = 0.7649717514124293
	macro F1 = 0.6968532635299246
	AUC = 0.877463263067703

Iteration 46: 2910 labelled instances
	Accuracy = 0.7536723163841808
	macro F1 = 0.690095547920574
	AUC = 0.8743031504906332

Iteration 47: 2954 labelled instances
	Accuracy = 0.7593220338983051
	macro F1 = 0.6957132420276592
	AUC = 0.8726694799474034

Iteration 48: 2930 labelled instances
	Accuracy = 0.7604519774011299
	macro F1 = 0.6928954755480956
	AUC = 0.8743909483263853

Iteration 49: 2883 labelled instances
	Accuracy = 0.7694915254237288
	macro F1 = 0.697616069989765
	AUC = 0.8747636954663105

Iteration 50: 2898 labelled instances
	Accuracy = 0.7581920903954802
	macro F1 = 0.6904391743522179
	AUC = 0.8745654139473754

Iteration 51: 2879 labelled instances
	Accuracy = 0.7672316384180791
	macro F1 = 0.6975118100470213
	AUC = 0.8736458770541115

Iteration 52: 2872 labelled instances
	Accuracy = 0.768361581920904
	macro F1 = 0.6976570248055437
	AUC = 0.8755961341550345

Iteration 53: 2824 labelled instances
	Accuracy = 0.7604519774011299
	macro F1 = 0.6892798196998461
	AUC = 0.8720144964605282

Iteration 54: 2870 labelled instances
	Accuracy = 0.7593220338983051
	macro F1 = 0.6923977732987298
	AUC = 0.8714970933622063

Iteration 55: 2893 labelled instances
	Accuracy = 0.751412429378531
	macro F1 = 0.687451392102555
	AUC = 0.8703118965267578

Iteration 56: 2838 labelled instances
	Accuracy = 0.7615819209039548
	macro F1 = 0.6892265149069131
	AUC = 0.8710917291647283

Iteration 57: 2843 labelled instances
	Accuracy = 0.7615819209039548
	macro F1 = 0.6919276460841929
	AUC = 0.8714152494602269

Iteration 58: 2823 labelled instances
	Accuracy = 0.7604519774011299
	macro F1 = 0.6908825195115518
	AUC = 0.8721940804275965

Iteration 59: 2801 labelled instances
	Accuracy = 0.7536723163841808
	macro F1 = 0.6836692058289587
	AUC = 0.8728823433242258

Iteration 60: 2799 labelled instances
	Accuracy = 0.7593220338983051
	macro F1 = 0.6885821877199536
	AUC = 0.8714472501004765

Iteration 61: 2782 labelled instances
	Accuracy = 0.7457627118644068
	macro F1 = 0.6766691095569796
	AUC = 0.8684342224980833

Iteration 62: 2808 labelled instances
	Accuracy = 0.7627118644067796
	macro F1 = 0.6893405770759834
	AUC = 0.873103733785524

Iteration 63: 2766 labelled instances
	Accuracy = 0.7570621468926554
	macro F1 = 0.6879738442225557
	AUC = 0.8704162061024131

Iteration 64: 2755 labelled instances
	Accuracy = 0.7536723163841808
	macro F1 = 0.6797999741208846
	AUC = 0.8683737259518752

Iteration 65: 2740 labelled instances
	Accuracy = 0.7593220338983051
	macro F1 = 0.6871262803269399
	AUC = 0.8698929293002183

Iteration 66: 2717 labelled instances
	Accuracy = 0.7423728813559322
	macro F1 = 0.6727234647568872
	AUC = 0.868141628356819

Iteration 67: 2753 labelled instances
	Accuracy = 0.7480225988700565
	macro F1 = 0.6750245917966011
	AUC = 0.8672817594291202

Iteration 68: 2762 labelled instances
	Accuracy = 0.751412429378531
	macro F1 = 0.682426756601274
	AUC = 0.86604453588148

Iteration 69: 2723 labelled instances
	Accuracy = 0.7480225988700565
	macro F1 = 0.6802407018948166
	AUC = 0.8675430344495924

Iteration 70: 2713 labelled instances
	Accuracy = 0.7423728813559322
	macro F1 = 0.66629441441215
	AUC = 0.8669242809072107

Iteration 71: 2696 labelled instances
	Accuracy = 0.7570621468926554
	macro F1 = 0.6848730641529844
	AUC = 0.8696078617535387

Iteration 72: 2677 labelled instances
	Accuracy = 0.7604519774011299
	macro F1 = 0.6874635005620672
	AUC = 0.8672394142738818

Iteration 73: 2639 labelled instances
	Accuracy = 0.7378531073446327
	macro F1 = 0.6659595616689439
	AUC = 0.8600692689626954

Iteration 74: 2721 labelled instances
	Accuracy = 0.7468926553672316
	macro F1 = 0.6753913138466262
	AUC = 0.866268422559965

Iteration 75: 2619 labelled instances
	Accuracy = 0.7536723163841808
	macro F1 = 0.6803674974389646
	AUC = 0.8638509839412022

Iteration 76: 2668 labelled instances
	Accuracy = 0.7435028248587571
	macro F1 = 0.6755945190238002
	AUC = 0.8654569572548284

Iteration 77: 2665 labelled instances
	Accuracy = 0.7435028248587571
	macro F1 = 0.6817876569330877
	AUC = 0.8626788117697992

Iteration 78: 2673 labelled instances
	Accuracy = 0.7446327683615819
	macro F1 = 0.6750603062078473
	AUC = 0.8629261185318429

Iteration 79: 2649 labelled instances
	Accuracy = 0.7378531073446327
	macro F1 = 0.6592745745938877
	AUC = 0.8611353020681833

Iteration 80: 2620 labelled instances
	Accuracy = 0.7468926553672316
	macro F1 = 0.6750975157042243
	AUC = 0.8627406862881806

Iteration 81: 2622 labelled instances
	Accuracy = 0.7480225988700565
	macro F1 = 0.6801179479898227
	AUC = 0.8604974543953793

Iteration 82: 2589 labelled instances
	Accuracy = 0.7423728813559322
	macro F1 = 0.6710743417443795
	AUC = 0.8597579255420009

Iteration 83: 2626 labelled instances
	Accuracy = 0.7468926553672316
	macro F1 = 0.6738781221916391
	AUC = 0.8631733251508008

Iteration 84: 2570 labelled instances
	Accuracy = 0.7502824858757062
	macro F1 = 0.6792916508160015
	AUC = 0.8611729822460196

Iteration 85: 2554 labelled instances
	Accuracy = 0.7401129943502824
	macro F1 = 0.6721817983959233
	AUC = 0.8613143761471168

Iteration 86: 2587 labelled instances
	Accuracy = 0.7401129943502824
	macro F1 = 0.6684589610307712
	AUC = 0.8599474083086762

Iteration 87: 2588 labelled instances
	Accuracy = 0.7457627118644068
	macro F1 = 0.6739126118082529
	AUC = 0.861906950229276

Iteration 88: 2526 labelled instances
	Accuracy = 0.7468926553672316
	macro F1 = 0.6721855297064997
	AUC = 0.8592943889864019

Iteration 89: 2548 labelled instances
	Accuracy = 0.7367231638418079
	macro F1 = 0.6636601506356584
	AUC = 0.8586182984001723

Iteration 90: 2557 labelled instances
	Accuracy = 0.7401129943502824
	macro F1 = 0.6707726988193116
	AUC = 0.8584410603757774

Iteration 91: 2546 labelled instances
	Accuracy = 0.7446327683615819
	macro F1 = 0.6694293858000596
	AUC = 0.8587992718828511

Iteration 92: 2505 labelled instances
	Accuracy = 0.7435028248587571
	macro F1 = 0.6697333692297587
	AUC = 0.8590528469224772

Iteration 93: 2493 labelled instances
	Accuracy = 0.7480225988700565
	macro F1 = 0.6775712234628793
	AUC = 0.8563962393927559

Iteration 94: 2536 labelled instances
	Accuracy = 0.7401129943502824
	macro F1 = 0.6713331135338941
	AUC = 0.8579565479807174

Iteration 95: 2512 labelled instances
	Accuracy = 0.7446327683615819
	macro F1 = 0.6734729905114184
	AUC = 0.8587754607149684

Iteration 96: 2498 labelled instances
	Accuracy = 0.735593220338983
	macro F1 = 0.6649089258807678
	AUC = 0.8563727000928022

Iteration 97: 2503 labelled instances
	Accuracy = 0.7401129943502824
	macro F1 = 0.6706915482484291
	AUC = 0.8564072158370957

Iteration 98: 2508 labelled instances
	Accuracy = 0.7423728813559322
	macro F1 = 0.6662982113555854
	AUC = 0.8564660477494349

Iteration 99: 2506 labelled instances
	Accuracy = 0.7412429378531074
	macro F1 = 0.6690759613729927
	AUC = 0.8580182760846636

Iteration 100: 2454 labelled instances
	Accuracy = 0.7412429378531074
	macro F1 = 0.6649175903636301
	AUC = 0.8532729538523575