# Libraries

In [1]:
import numpy as np
import pandas as pd

from ucimlrepo import fetch_ucirepo
from sklearn.datasets import fetch_california_housing

from tensorflow.keras import layers, models
import tensorflow as tf

from sklearn.metrics import confusion_matrix, f1_score, classification_report, accuracy_score, balanced_accuracy_score, ConfusionMatrixDisplay, roc_auc_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# own functions
from active_learning import passive_sampling, uncertainty_sampling, label_data, active_learning_bc, active_learning_mc
from active_learning import balanced_weights, tune_params, retrieve_params, cv_classification

# Models

## Breast Cancer

In [2]:
breast_cancer = fetch_ucirepo(id=17)

bcwd_df = pd.concat(
    [breast_cancer.data.features, breast_cancer.data.targets],
    axis=1
)
bcwd_df.head()

,radius1,texture1,perimeter1,area1,smoothness1,compactness1,concavity1,concave_points1,symmetry1,fractal_dimension1,...,texture3,perimeter3,area3,smoothness3,compactness3,concavity3,concave_points3,symmetry3,fractal_dimension3,Diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,M
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,M
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,M
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,M
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,M

In [3]:
X = breast_cancer.data.features.to_numpy()
y = (breast_cancer.data.targets).iloc[:, 0].map({"B": 0, "M": 1}).astype("int32").to_numpy()

X_pool, X_test, y_pool, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=51
)

In [4]:
acts = ['relu', 'leaky_relu', 'elu', 'gelu', 'swish']
balance = [False, True]
name = "base"
for state in balance:
    if state:
        name = 'balanced'
    else:
        name = 'base'

    for activation in acts:
        base_params = tune_params(X_pool, y_pool,
                                  loss='binary_crossentropy',
                                  out_units=1, out_act='sigmoid',
                                  k=3, activation=activation,
                                  balanced=False,
                                  random_state=42,
                                  n_trials=80,
                                  export=True, file = f'params/breast_cancer/{name}_{activation}.json'
        )

[I 2026-09-23 22:03:29,931] A new study created in memory with name: no-name-24dba71f-c3cb-43ce-a0ff-95f374362647

WARNING:tensorflow:From C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

[I 2026-09-23 22:03:58,339] Trial 0 finished with value: 0.09482133388519287 and parameters: {'hidden_layer': 66, 'learning_rate': 0.03443006339334324, 'momentum': 0.7239634414397639, 'weight_decay': 0.0007707799579098195}. Best is trial 0 with value: 0.09482133388519287.
[I 2026-09-23 22:04:42,925] Trial 1 finished with value: 0.353429913520813 and parameters: {'hidden_layer': 86, 'learning_rate': 0.0005070587436265495, 'momentum': 0.36121130642843274, 'weight_decay': 0.0008694008697084097}. Best is trial 0 with value: 0.09482133388519287.
[I 2026-09-23 22:05:26,630] Trial 2 finished with value: 0.3215976655483246 and parameters: {'hidden_layer': 60, 'learning_rate': 0.00044191997669171897, 'momentum': 0.515911551210062, 'weight_decay': 0.0006140902224770801}. Best is trial 0 with value: 0.09482133388519287.
[I 2026-09-23 22:06:12,130] Trial 3 finished with value: 0.20186512172222137 and parameters: {'hidden_layer': 92, 'learning_rate': 0.0020764228915147284, 'momentum': 0.2199950635730576, 'weight_decay': 5.8909797330915914e-06}. Best is trial 0 with value: 0.09482133388519287.
[I 2026-09-23 22:06:54,942] Trial 4 finished with value: 0.10991287976503372 and parameters: {'hidden_layer': 93, 'learning_rate': 0.0050765378103851035, 'momentum': 0.6456791655270113, 'weight_decay': 2.0868557419241347e-05}. Best is trial 0 with value: 0.09482133388519287.
[I 2026-09-23 22:07:14,391] Trial 5 finished with value: 0.094646155834198 and parameters: {'hidden_layer': 38, 'learning_rate': 0.06403083977135648, 'momentum': 0.6806952853405464, 'weight_decay': 0.001323283627365684}. Best is trial 5 with value: 0.094646155834198.
[I 2026-09-23 22:07:28,998] Trial 6 pruned.
[I 2026-09-23 22:07:45,039] Trial 7 pruned.
[I 2026-09-23 22:07:59,630] Trial 8 pruned.
[I 2026-09-23 22:08:45,239] Trial 9 finished with value: 0.12438850849866867 and parameters: {'hidden_layer': 121, 'learning_rate': 0.0010341485784482976, 'momentum': 0.8885167782084122, 'weight_decay': 0.006093869510803479}. Best is trial 5 with value: 0.094646155834198.
[I 2026-09-23 22:08:48,034] Trial 10 pruned.
[I 2026-09-23 22:09:02,214] Trial 11 finished with value: 0.08706935495138168 and parameters: {'hidden_layer': 45, 'learning_rate': 0.09429989712706488, 'momentum': 0.739600026141651, 'weight_decay': 0.00018542489224829533}. Best is trial 11 with value: 0.08706935495138168.
[I 2026-09-23 22:09:21,064] Trial 12 finished with value: 0.10589628666639328 and parameters: {'hidden_layer': 8, 'learning_rate': 0.07855708095074712, 'momentum': 0.7714574042342104, 'weight_decay': 0.00016833641258837405}. Best is trial 11 with value: 0.08706935495138168.
[I 2026-09-23 22:09:59,829] Trial 13 finished with value: 0.11037266999483109 and parameters: {'hidden_layer': 41, 'learning_rate': 0.009980854451528276, 'momentum': 0.5818142154631356, 'weight_decay': 0.00014713797343009007}. Best is trial 11 with value: 0.08706935495138168.
[I 2026-09-23 22:10:18,229] Trial 14 pruned.
[I 2026-09-23 22:10:51,418] Trial 15 finished with value: 0.10491760820150375 and parameters: {'hidden_layer': 25, 'learning_rate': 0.015859631434089427, 'momentum': 0.6238545224150736, 'weight_decay': 2.6328117846729234e-05}. Best is trial 11 with value: 0.08706935495138168.
[I 2026-09-23 22:10:59,027] Trial 16 finished with value: 0.10383454710245132 and parameters: {'hidden_layer': 74, 'learning_rate': 0.08517268038213742, 'momentum': 0.8979445601518701, 'weight_decay': 0.0015063947236337593}. Best is trial 11 with value: 0.08706935495138168.
[I 2026-09-23 22:11:42,288] Trial 17 finished with value: 0.09455174952745438 and parameters: {'hidden_layer': 47, 'learning_rate': 0.02123385450043228, 'momentum': 0.32761190802470036, 'weight_decay': 6.234223069520786e-05}. Best is trial 11 with value: 0.08706935495138168.
[I 2026-09-23 22:11:57,283] Trial 18 pruned.
[I 2026-09-23 22:12:11,648] Trial 19 pruned.
[I 2026-09-23 22:12:51,776] Trial 20 finished with value: 0.09030141681432724 and parameters: {'hidden_layer': 76, 'learning_rate': 0.02319699472138611, 'momentum': 0.44919938866160336, 'weight_decay': 9.558107702657244e-06}. Best is trial 11 with value: 0.08706935495138168.
[I 2026-09-23 22:12:55,286] Trial 21 pruned.
[I 2026-09-23 22:13:43,928] Trial 22 finished with value: 0.09849437326192856 and parameters: {'hidden_layer': 105, 'learning_rate': 0.016828053931639445, 'momentum': 0.5132968661965291, 'weight_decay': 8.105668019340757e-06}. Best is trial 11 with value: 0.08706935495138168.
[I 2026-09-23 22:13:58,949] Trial 23 pruned.
[I 2026-09-23 22:14:06,597] Trial 24 pruned.
[I 2026-09-23 22:14:44,097] Trial 25 finished with value: 0.09196195751428604 and parameters: {'hidden_layer': 66, 'learning_rate': 0.02550865987557615, 'momentum': 0.4446791873645959, 'weight_decay': 1.810089338716655e-05}. Best is trial 11 with value: 0.08706935495138168.
[I 2026-09-23 22:15:12,375] Trial 26 finished with value: 0.08797242492437363 and parameters: {'hidden_layer': 70, 'learning_rate': 0.08981429808338405, 'momentum': 0.4490091407054545, 'weight_decay': 1.7899303682524913e-05}. Best is trial 11 with value: 0.08706935495138168.
[I 2026-09-23 22:15:30,889] Trial 27 finished with value: 0.08464493602514267 and parameters: {'hidden_layer': 101, 'learning_rate': 0.0882544057151034, 'momentum': 0.5548423865278713, 'weight_decay': 3.1972067385643473e-06}. Best is trial 27 with value: 0.08464493602514267.
[I 2026-09-23 22:15:48,599] Trial 28 finished with value: 0.09137552231550217 and parameters: {'hidden_layer': 106, 'learning_rate': 0.0904867225298175, 'momentum': 0.5497636935455058, 'weight_decay': 1.050422027468387e-06}. Best is trial 27 with value: 0.08464493602514267.
[I 2026-09-23 22:16:07,477] Trial 29 finished with value: 0.0945044681429863 and parameters: {'hidden_layer': 127, 'learning_rate': 0.05295950067248041, 'momentum': 0.7374752077066953, 'weight_decay': 3.315854822120384e-06}. Best is trial 27 with value: 0.08464493602514267.
[I 2026-09-23 22:16:18,158] Trial 30 finished with value: 0.09094741940498352 and parameters: {'hidden_layer': 96, 'learning_rate': 0.09993615347209572, 'momentum': 0.8407350881257893, 'weight_decay': 4.181016381670391e-06}. Best is trial 27 with value: 0.08464493602514267.
[I 2026-09-23 22:16:52,287] Trial 31 finished with value: 0.09563583135604858 and parameters: {'hidden_layer': 81, 'learning_rate': 0.03428123635021714, 'momentum': 0.4635914525286593, 'weight_decay': 1.2968121704758966e-05}. Best is trial 27 with value: 0.08464493602514267.
[I 2026-09-23 22:17:12,193] Trial 32 finished with value: 0.09937822818756104 and parameters: {'hidden_layer': 69, 'learning_rate': 0.05434350886940974, 'momentum': 0.6916781749540388, 'weight_decay': 1.1637080145609432e-05}. Best is trial 27 with value: 0.08464493602514267.
[I 2026-09-23 22:17:22,181] Trial 33 pruned.
[I 2026-09-23 22:17:37,795] Trial 34 pruned.
[I 2026-09-23 22:17:43,835] Trial 35 pruned.
[I 2026-09-23 22:17:56,226] Trial 36 pruned.
[I 2026-09-23 22:18:11,305] Trial 37 pruned.
[I 2026-09-23 22:18:34,674] Trial 38 finished with value: 0.10469891875982285 and parameters: {'hidden_layer': 59, 'learning_rate': 0.06820976327917898, 'momentum': 0.47233489373360626, 'weight_decay': 2.7474512216803093e-06}. Best is trial 27 with value: 0.08464493602514267.
[I 2026-09-23 22:18:57,834] Trial 39 finished with value: 0.08498679846525192 and parameters: {'hidden_layer': 92, 'learning_rate': 0.09856655411273978, 'momentum': 0.5481213766071977, 'weight_decay': 1.230947185783723e-06}. Best is trial 27 with value: 0.08464493602514267.
[I 2026-09-23 22:19:18,474] Trial 40 finished with value: 0.09277313947677612 and parameters: {'hidden_layer': 113, 'learning_rate': 0.09972394400154115, 'momentum': 0.5533317488070371, 'weight_decay': 1.161338708766447e-06}. Best is trial 27 with value: 0.08464493602514267.
[I 2026-09-23 22:19:48,430] Trial 41 finished with value: 0.08842587471008301 and parameters: {'hidden_layer': 88, 'learning_rate': 0.06248023439845136, 'momentum': 0.3688357589135173, 'weight_decay': 1.962874518084817e-06}. Best is trial 27 with value: 0.08464493602514267.
[I 2026-09-23 22:20:13,097] Trial 42 finished with value: 0.08637615293264389 and parameters: {'hidden_layer': 88, 'learning_rate': 0.07102264307548421, 'momentum': 0.3524353268309498, 'weight_decay': 1.8212594461665355e-06}. Best is trial 27 with value: 0.08464493602514267.
[I 2026-09-23 22:20:22,028] Trial 43 pruned.
[I 2026-09-23 22:20:57,490] Trial 44 finished with value: 0.08744287490844727 and parameters: {'hidden_layer': 99, 'learning_rate': 0.039682284827672, 'momentum': 0.42130300026791967, 'weight_decay': 6.391741282987452e-06}. Best is trial 27 with value: 0.08464493602514267.
[I 2026-09-23 22:21:12,956] Trial 45 pruned.
[I 2026-09-23 22:21:34,974] Trial 46 finished with value: 0.08704504370689392 and parameters: {'hidden_layer': 106, 'learning_rate': 0.04776712692811282, 'momentum': 0.6581451229631312, 'weight_decay': 5.248489462001085e-06}. Best is trial 27 with value: 0.08464493602514267.
[I 2026-09-23 22:21:56,360] Trial 47 finished with value: 0.08801031112670898 and parameters: {'hidden_layer': 116, 'learning_rate': 0.05169391927625808, 'momentum': 0.745893909895856, 'weight_decay': 1.6015779088031706e-06}. Best is trial 27 with value: 0.08464493602514267.
[I 2026-09-23 22:22:12,101] Trial 48 pruned.
[I 2026-09-23 22:22:23,551] Trial 49 finished with value: 0.10349787026643753 and parameters: {'hidden_layer': 31, 'learning_rate': 0.06651897066960916, 'momentum': 0.7795098835518678, 'weight_decay': 2.361580045973451e-06}. Best is trial 27 with value: 0.08464493602514267.
[I 2026-09-23 22:22:42,519] Trial 50 finished with value: 0.09134841710329056 and parameters: {'hidden_layer': 111, 'learning_rate': 0.074963119835876, 'momentum': 0.6402210319302699, 'weight_decay': 1.6213957412982134e-06}. Best is trial 27 with value: 0.08464493602514267.
[I 2026-09-23 22:23:11,222] Trial 51 finished with value: 0.08509143441915512 and parameters: {'hidden_layer': 91, 'learning_rate': 0.033450394942554515, 'momentum': 0.6024073914150283, 'weight_decay': 5.902307061004167e-06}. Best is trial 27 with value: 0.08464493602514267.
[I 2026-09-23 22:23:19,858] Trial 52 pruned.
[I 2026-09-23 22:23:35,933] Trial 53 pruned.
[I 2026-09-23 22:23:55,861] Trial 54 finished with value: 0.09455990791320801 and parameters: {'hidden_layer': 120, 'learning_rate': 0.04939854760702363, 'momentum': 0.7100347666599529, 'weight_decay': 2.346991091303061e-06}. Best is trial 27 with value: 0.08464493602514267.
[I 2026-09-23 22:24:11,091] Trial 55 pruned.
[I 2026-09-23 22:24:27,203] Trial 56 finished with value: 0.09747997671365738 and parameters: {'hidden_layer': 108, 'learning_rate': 0.0780739095341607, 'momentum': 0.8420536472117868, 'weight_decay': 0.0013026578147506149}. Best is trial 27 with value: 0.08464493602514267.
[I 2026-09-23 22:24:43,497] Trial 57 pruned.
[I 2026-09-23 22:24:59,913] Trial 58 pruned.
[I 2026-09-23 22:25:16,615] Trial 59 pruned.
[I 2026-09-23 22:25:40,915] Trial 60 finished with value: 0.08398696035146713 and parameters: {'hidden_layer': 96, 'learning_rate': 0.032373116376317075, 'momentum': 0.7809132234484888, 'weight_decay': 1.4346698094774194e-06}. Best is trial 60 with value: 0.08398696035146713.
[I 2026-09-23 22:26:07,308] Trial 61 finished with value: 0.09183603525161743 and parameters: {'hidden_layer': 93, 'learning_rate': 0.03392582925433368, 'momentum': 0.770278362690857, 'weight_decay': 1.389294613310321e-06}. Best is trial 60 with value: 0.08398696035146713.
[I 2026-09-23 22:26:32,103] Trial 62 finished with value: 0.09499142318964005 and parameters: {'hidden_layer': 98, 'learning_rate': 0.043681885606157815, 'momentum': 0.6611191978855473, 'weight_decay': 2.92221482014964e-06}. Best is trial 60 with value: 0.08398696035146713.
[I 2026-09-23 22:26:39,364] Trial 63 pruned.
[I 2026-09-23 22:26:51,862] Trial 64 pruned.
[I 2026-09-23 22:27:04,004] Trial 65 pruned.
[I 2026-09-23 22:27:13,305] Trial 66 pruned.
[I 2026-09-23 22:27:17,274] Trial 67 pruned.
[I 2026-09-23 22:27:28,846] Trial 68 pruned.
[I 2026-09-23 22:27:44,589] Trial 69 pruned.
[I 2026-09-23 22:28:07,032] Trial 70 finished with value: 0.09587753564119339 and parameters: {'hidden_layer': 45, 'learning_rate': 0.07360087005346339, 'momentum': 0.41807755257696677, 'weight_decay': 0.00014783930193645406}. Best is trial 60 with value: 0.08398696035146713.
[I 2026-09-23 22:28:22,033] Trial 71 pruned.
[I 2026-09-23 22:28:33,276] Trial 72 pruned.
[I 2026-09-23 22:28:48,159] Trial 73 pruned.
[I 2026-09-23 22:29:14,019] Trial 74 finished with value: 0.09017124027013779 and parameters: {'hidden_layer': 106, 'learning_rate': 0.0612863999131814, 'momentum': 0.5351566516725841, 'weight_decay': 4.02580214616049e-06}. Best is trial 60 with value: 0.08398696035146713.
[I 2026-09-23 22:29:38,215] Trial 75 finished with value: 0.08847183734178543 and parameters: {'hidden_layer': 114, 'learning_rate': 0.07957508614713463, 'momentum': 0.5684994898880774, 'weight_decay': 8.77120267847053e-06}. Best is trial 60 with value: 0.08398696035146713.
[I 2026-09-23 22:29:53,159] Trial 76 pruned.
[I 2026-09-23 22:30:09,245] Trial 77 pruned.
[I 2026-09-23 22:30:24,350] Trial 78 pruned.
[I 2026-09-23 22:30:40,463] Trial 79 pruned.
[I 2026-09-23 22:30:40,467] A new study created in memory with name: no-name-12b16c20-9861-4ccc-9177-e6887eddd210

{'hidden_layer': 96, 'learning_rate': 0.032373116376317075, 'momentum': 0.7809132234484888, 'weight_decay': 1.4346698094774194e-06}
0.08398696035146713

[I 2026-09-23 22:31:13,979] Trial 0 finished with value: 0.10224166512489319 and parameters: {'hidden_layer': 79, 'learning_rate': 0.052754767963352156, 'momentum': 0.17908523735551288, 'weight_decay': 0.00017906767285558243, 'leaky_relu_alpha': 0.01590230789148455}. Best is trial 0 with value: 0.10224166512489319.
[I 2026-09-23 22:31:59,016] Trial 1 finished with value: 0.1346011459827423 and parameters: {'hidden_layer': 21, 'learning_rate': 0.006720837939770634, 'momentum': 0.3357841390733627, 'weight_decay': 6.320713263358466e-05, 'leaky_relu_alpha': 0.011051575355277898}. Best is trial 0 with value: 0.10224166512489319.
[I 2026-09-23 22:32:42,148] Trial 2 finished with value: 0.11142945289611816 and parameters: {'hidden_layer': 27, 'learning_rate': 0.022494270119690754, 'momentum': 0.41450050635359875, 'weight_decay': 0.007746706829439509, 'leaky_relu_alpha': 0.001567975845026253}. Best is trial 0 with value: 0.10224166512489319.
[I 2026-09-23 22:33:25,433] Trial 3 finished with value: 0.09546557068824768 and parameters: {'hidden_layer': 63, 'learning_rate': 0.010028000673277464, 'momentum': 0.5700036185891463, 'weight_decay': 8.660680126226219e-05, 'leaky_relu_alpha': 0.13359069352151015}. Best is trial 3 with value: 0.09546557068824768.
[I 2026-09-23 22:34:11,733] Trial 4 finished with value: 0.498661607503891 and parameters: {'hidden_layer': 80, 'learning_rate': 0.0002876545256082067, 'momentum': 0.016618163886178584, 'weight_decay': 0.00022403348410443533, 'leaky_relu_alpha': 0.1299302300255449}. Best is trial 3 with value: 0.09546557068824768.
[I 2026-09-23 22:34:27,656] Trial 5 pruned.
[I 2026-09-23 22:34:57,025] Trial 6 finished with value: 0.0902031734585762 and parameters: {'hidden_layer': 44, 'learning_rate': 0.020041597277159484, 'momentum': 0.7659550135737376, 'weight_decay': 5.468964691038378e-05, 'leaky_relu_alpha': 0.10131870187630017}. Best is trial 6 with value: 0.0902031734585762.
[I 2026-09-23 22:35:12,392] Trial 7 pruned.
[I 2026-09-23 22:35:16,617] Trial 8 pruned.
[I 2026-09-23 22:35:31,829] Trial 9 pruned.
[I 2026-09-23 22:35:46,093] Trial 10 pruned.
[I 2026-09-23 22:36:21,062] Trial 11 finished with value: 0.09210636466741562 and parameters: {'hidden_layer': 55, 'learning_rate': 0.016107390084348264, 'momentum': 0.6406200500062367, 'weight_decay': 1.579041083922035e-05, 'leaky_relu_alpha': 0.27381529662530013}. Best is trial 6 with value: 0.0902031734585762.
[I 2026-09-23 22:36:39,013] Trial 12 finished with value: 0.09401899576187134 and parameters: {'hidden_layer': 42, 'learning_rate': 0.025339646555910356, 'momentum': 0.6897014887843707, 'weight_decay': 1.3797889438543477e-05, 'leaky_relu_alpha': 0.24176128281145506}. Best is trial 6 with value: 0.0902031734585762.
[I 2026-09-23 22:37:18,422] Trial 13 finished with value: 0.09022215008735657 and parameters: {'hidden_layer': 8, 'learning_rate': 0.020370031203471632, 'momentum': 0.7466226234477996, 'weight_decay': 1.0707372869337812e-05, 'leaky_relu_alpha': 0.06892343904247072}. Best is trial 6 with value: 0.0902031734585762.
[I 2026-09-23 22:37:34,261] Trial 14 pruned.
[I 2026-09-23 22:37:43,780] Trial 15 pruned.
[I 2026-09-23 22:38:00,166] Trial 16 pruned.
[I 2026-09-23 22:38:07,690] Trial 17 pruned.
[I 2026-09-23 22:38:23,700] Trial 18 pruned.
[I 2026-09-23 22:38:39,416] Trial 19 pruned.
[I 2026-09-23 22:38:55,847] Trial 20 pruned.
[I 2026-09-23 22:39:16,240] Trial 21 finished with value: 0.10177018493413925 and parameters: {'hidden_layer': 59, 'learning_rate': 0.028096166922288262, 'momentum': 0.6836081995385567, 'weight_decay': 2.4891190436148295e-05, 'leaky_relu_alpha': 0.2741468733900188}. Best is trial 6 with value: 0.0902031734585762.
[I 2026-09-23 22:39:29,376] Trial 22 pruned.
[I 2026-09-23 22:39:45,200] Trial 23 pruned.
[I 2026-09-23 22:40:02,932] Trial 24 finished with value: 0.08642038702964783 and parameters: {'hidden_layer': 17, 'learning_rate': 0.05006962550877424, 'momentum': 0.8868018076896659, 'weight_decay': 2.0748498822192714e-05, 'leaky_relu_alpha': 0.16803108243200324}. Best is trial 24 with value: 0.08642038702964783.
[I 2026-09-23 22:40:18,590] Trial 25 finished with value: 0.08658821135759354 and parameters: {'hidden_layer': 16, 'learning_rate': 0.04252787708898954, 'momentum': 0.8813832793283297, 'weight_decay': 0.0001188211917839997, 'leaky_relu_alpha': 0.04946199209511706}. Best is trial 24 with value: 0.08642038702964783.
[I 2026-09-23 22:40:33,280] Trial 26 finished with value: 0.0979042649269104 and parameters: {'hidden_layer': 18, 'learning_rate': 0.048051780167682676, 'momentum': 0.9008604922974766, 'weight_decay': 0.00013297250325541485, 'leaky_relu_alpha': 0.03022652564050291}. Best is trial 24 with value: 0.08642038702964783.
[I 2026-09-23 22:40:50,724] Trial 27 finished with value: 0.09239133447408676 and parameters: {'hidden_layer': 33, 'learning_rate': 0.06299945170304884, 'momentum': 0.8971525390126598, 'weight_decay': 0.0007847270017464634, 'leaky_relu_alpha': 0.1780220727458173}. Best is trial 24 with value: 0.08642038702964783.
[I 2026-09-23 22:41:04,537] Trial 28 finished with value: 0.08920177817344666 and parameters: {'hidden_layer': 21, 'learning_rate': 0.037187462985008246, 'momentum': 0.9367532973196536, 'weight_decay': 6.665978567291563e-05, 'leaky_relu_alpha': 0.10320030257355559}. Best is trial 24 with value: 0.08642038702964783.
[I 2026-09-23 22:41:53,654] Trial 29 finished with value: 0.10155898332595825 and parameters: {'hidden_layer': 16, 'learning_rate': 0.04209445508853394, 'momentum': 0.22905570960651273, 'weight_decay': 0.00020842765531720934, 'leaky_relu_alpha': 0.048362353836434856}. Best is trial 24 with value: 0.08642038702964783.
[I 2026-09-23 22:42:09,829] Trial 30 finished with value: 0.09755874425172806 and parameters: {'hidden_layer': 24, 'learning_rate': 0.09961639089675202, 'momentum': 0.8528591568064855, 'weight_decay': 0.00013224578837277217, 'leaky_relu_alpha': 0.02176486821852366}. Best is trial 24 with value: 0.08642038702964783.
[I 2026-09-23 22:42:25,629] Trial 31 finished with value: 0.09040951728820801 and parameters: {'hidden_layer': 38, 'learning_rate': 0.03545704844192686, 'momentum': 0.9314021820234254, 'weight_decay': 5.7067742775727055e-05, 'leaky_relu_alpha': 0.10618534935122996}. Best is trial 24 with value: 0.08642038702964783.
[I 2026-09-23 22:42:34,649] Trial 32 pruned.
[I 2026-09-23 22:42:41,374] Trial 33 pruned.
[I 2026-09-23 22:42:50,779] Trial 34 pruned.
[I 2026-09-23 22:42:55,129] Trial 35 pruned.
[I 2026-09-23 22:43:02,495] Trial 36 pruned.
[I 2026-09-23 22:43:23,819] Trial 37 pruned.
[I 2026-09-23 22:43:29,894] Trial 38 pruned.
[I 2026-09-23 22:43:35,260] Trial 39 pruned.
[I 2026-09-23 22:43:40,243] Trial 40 pruned.
[I 2026-09-23 22:43:51,880] Trial 41 pruned.
[I 2026-09-23 22:44:11,767] Trial 42 pruned.
[I 2026-09-23 22:44:19,489] Trial 43 pruned.
[I 2026-09-23 22:44:39,014] Trial 44 pruned.
[I 2026-09-23 22:44:50,271] Trial 45 pruned.
[I 2026-09-23 22:45:03,088] Trial 46 pruned.
[I 2026-09-23 22:45:17,257] Trial 47 pruned.
[I 2026-09-23 22:45:34,978] Trial 48 pruned.
[I 2026-09-23 22:45:43,118] Trial 49 pruned.
[I 2026-09-23 22:46:02,146] Trial 50 pruned.
[I 2026-09-23 22:46:07,073] Trial 51 pruned.
[I 2026-09-23 22:46:11,898] Trial 52 pruned.
[I 2026-09-23 22:46:21,809] Trial 53 pruned.
[I 2026-09-23 22:46:26,874] Trial 54 pruned.
[I 2026-09-23 22:46:37,079] Trial 55 pruned.
[I 2026-09-23 22:46:47,973] Trial 56 pruned.
[I 2026-09-23 22:47:08,421] Trial 57 pruned.
[I 2026-09-23 22:47:29,777] Trial 58 pruned.
[I 2026-09-23 22:47:37,417] Trial 59 pruned.
[I 2026-09-23 22:48:12,565] Trial 60 finished with value: 0.09718377143144608 and parameters: {'hidden_layer': 41, 'learning_rate': 0.004797384447710284, 'momentum': 0.951367926004344, 'weight_decay': 0.00027743441058263296, 'leaky_relu_alpha': 0.003404109631953469}. Best is trial 24 with value: 0.08642038702964783.
[I 2026-09-23 22:48:31,532] Trial 61 pruned.
[I 2026-09-23 22:49:10,661] Trial 62 finished with value: 0.08332855254411697 and parameters: {'hidden_layer': 55, 'learning_rate': 0.02629634124418907, 'momentum': 0.6925879087882653, 'weight_decay': 1.641676100757875e-05, 'leaky_relu_alpha': 0.11731749012472491}. Best is trial 62 with value: 0.08332855254411697.
[I 2026-09-23 22:49:31,903] Trial 63 finished with value: 0.08481579273939133 and parameters: {'hidden_layer': 55, 'learning_rate': 0.03870828016852914, 'momentum': 0.808003747935754, 'weight_decay': 1.9109173209960107e-05, 'leaky_relu_alpha': 0.11104669695298029}. Best is trial 62 with value: 0.08332855254411697.
[I 2026-09-23 22:49:58,617] Trial 64 finished with value: 0.09206616133451462 and parameters: {'hidden_layer': 75, 'learning_rate': 0.026210349624436354, 'momentum': 0.7700193048442167, 'weight_decay': 1.91395717751308e-05, 'leaky_relu_alpha': 0.07476993149537295}. Best is trial 62 with value: 0.08332855254411697.
[I 2026-09-23 22:50:06,535] Trial 65 pruned.
[I 2026-09-23 22:50:28,577] Trial 66 finished with value: 0.09628844261169434 and parameters: {'hidden_layer': 56, 'learning_rate': 0.043896477117549626, 'momentum': 0.5972169633330147, 'weight_decay': 7.96646603427366e-06, 'leaky_relu_alpha': 0.11379465392460851}. Best is trial 62 with value: 0.08332855254411697.
[I 2026-09-23 22:50:59,878] Trial 67 finished with value: 0.09753727912902832 and parameters: {'hidden_layer': 51, 'learning_rate': 0.018812759367587622, 'momentum': 0.801740621737203, 'weight_decay': 5.267160125115692e-06, 'leaky_relu_alpha': 0.023163065212728387}. Best is trial 62 with value: 0.08332855254411697.
[I 2026-09-23 22:51:10,644] Trial 68 pruned.
[I 2026-09-23 22:51:28,199] Trial 69 pruned.
[I 2026-09-23 22:51:33,722] Trial 70 pruned.
[I 2026-09-23 22:51:41,981] Trial 71 pruned.
[I 2026-09-23 22:52:09,959] Trial 72 finished with value: 0.09137604385614395 and parameters: {'hidden_layer': 46, 'learning_rate': 0.023823082909863038, 'momentum': 0.8357554593058233, 'weight_decay': 4.344069108460744e-05, 'leaky_relu_alpha': 0.1947199119644433}. Best is trial 62 with value: 0.08332855254411697.
[I 2026-09-23 22:52:26,134] Trial 73 pruned.
[I 2026-09-23 22:52:46,172] Trial 74 finished with value: 0.08303141593933105 and parameters: {'hidden_layer': 53, 'learning_rate': 0.05819436643372104, 'momentum': 0.7603317133239147, 'weight_decay': 3.2648678371741576e-05, 'leaky_relu_alpha': 0.12373760796970416}. Best is trial 74 with value: 0.08303141593933105.
[I 2026-09-23 22:52:51,693] Trial 75 pruned.
[I 2026-09-23 22:53:10,266] Trial 76 finished with value: 0.1066851019859314 and parameters: {'hidden_layer': 11, 'learning_rate': 0.09379580037777469, 'momentum': 0.8110874791804025, 'weight_decay': 1.120775835225664e-05, 'leaky_relu_alpha': 0.08890530168262255}. Best is trial 74 with value: 0.08303141593933105.
[I 2026-09-23 22:53:27,646] Trial 77 finished with value: 0.08763974905014038 and parameters: {'hidden_layer': 58, 'learning_rate': 0.0633833858501179, 'momentum': 0.767447823522039, 'weight_decay': 1.8675406200983084e-05, 'leaky_relu_alpha': 0.1270543959176452}. Best is trial 74 with value: 0.08303141593933105.
[I 2026-09-23 22:53:42,993] Trial 78 finished with value: 0.10064307600259781 and parameters: {'hidden_layer': 55, 'learning_rate': 0.06896557785780438, 'momentum': 0.7417583996045124, 'weight_decay': 0.00016404558333935187, 'leaky_relu_alpha': 0.12359142765965324}. Best is trial 74 with value: 0.08303141593933105.
[I 2026-09-23 22:53:49,481] Trial 79 pruned.
[I 2026-09-23 22:53:49,512] A new study created in memory with name: no-name-4c923df1-aaa8-45c2-b74b-6f0e0dae97b9

{'hidden_layer': 53, 'learning_rate': 0.05819436643372104, 'momentum': 0.7603317133239147, 'weight_decay': 3.2648678371741576e-05, 'leaky_relu_alpha': 0.12373760796970416}
0.08303141593933105

[I 2026-09-23 22:54:40,522] Trial 0 finished with value: 0.1179613247513771 and parameters: {'hidden_layer': 67, 'learning_rate': 0.006244555428169414, 'momentum': 0.4163765509570171, 'weight_decay': 0.0002509797943748661, 'elu_alpha': 0.6801604788852802}. Best is trial 0 with value: 0.1179613247513771.
[I 2026-09-23 22:55:30,385] Trial 1 finished with value: 0.10915011167526245 and parameters: {'hidden_layer': 18, 'learning_rate': 0.0004654441139541333, 'momentum': 0.9438743360615905, 'weight_decay': 0.0002002368144097895, 'elu_alpha': 1.5130247580895242}. Best is trial 1 with value: 0.10915011167526245.
[I 2026-09-23 22:56:04,510] Trial 2 finished with value: 0.10097628086805344 and parameters: {'hidden_layer': 62, 'learning_rate': 0.003663667724622732, 'momentum': 0.7321625786171119, 'weight_decay': 0.0001825931974517579, 'elu_alpha': 1.4054887460224557}. Best is trial 2 with value: 0.10097628086805344.
[I 2026-09-23 22:56:51,235] Trial 3 finished with value: 0.7311820983886719 and parameters: {'hidden_layer': 65, 'learning_rate': 0.00010494070472568073, 'momentum': 0.11261476110721036, 'weight_decay': 0.002465133477153044, 'elu_alpha': 0.48980067203168554}. Best is trial 2 with value: 0.10097628086805344.
[I 2026-09-23 22:57:38,347] Trial 4 finished with value: 0.1065167486667633 and parameters: {'hidden_layer': 26, 'learning_rate': 0.0016277689104690202, 'momentum': 0.814217399374474, 'weight_decay': 3.6266095587716346e-05, 'elu_alpha': 1.5794627848381628}. Best is trial 2 with value: 0.10097628086805344.
[I 2026-09-23 22:58:08,380] Trial 5 finished with value: 0.0901794359087944 and parameters: {'hidden_layer': 54, 'learning_rate': 0.0011895590297160848, 'momentum': 0.9675531257469082, 'weight_decay': 4.774169351302347e-06, 'elu_alpha': 1.3970361810742589}. Best is trial 5 with value: 0.0901794359087944.
[I 2026-09-23 22:58:24,484] Trial 6 pruned.
[I 2026-09-23 22:58:39,449] Trial 7 pruned.
[I 2026-09-23 22:58:54,891] Trial 8 pruned.
[I 2026-09-23 22:59:43,562] Trial 9 finished with value: 0.09596594423055649 and parameters: {'hidden_layer': 118, 'learning_rate': 0.008643147708067327, 'momentum': 0.48659251776116375, 'weight_decay': 0.005923697393913077, 'elu_alpha': 1.173417843612769}. Best is trial 5 with value: 0.0901794359087944.
[I 2026-09-23 22:59:46,575] Trial 10 pruned.
[I 2026-09-23 23:00:16,729] Trial 11 finished with value: 0.09500367194414139 and parameters: {'hidden_layer': 122, 'learning_rate': 0.01652163049207441, 'momentum': 0.5429871567008235, 'weight_decay': 0.007523753472275611, 'elu_alpha': 1.1082593035614408}. Best is trial 5 with value: 0.0901794359087944.
[I 2026-09-23 23:00:56,855] Trial 12 finished with value: 0.08888950198888779 and parameters: {'hidden_layer': 46, 'learning_rate': 0.02114030840350776, 'momentum': 0.2888812943713057, 'weight_decay': 1.0687289408221401e-06, 'elu_alpha': 1.0616162261511133}. Best is trial 12 with value: 0.08888950198888779.
[I 2026-09-23 23:01:30,853] Trial 13 finished with value: 0.09832152724266052 and parameters: {'hidden_layer': 45, 'learning_rate': 0.02501354906753907, 'momentum': 0.20189296410767565, 'weight_decay': 1.426908614716831e-06, 'elu_alpha': 1.8509771230343728}. Best is trial 12 with value: 0.08888950198888779.
[I 2026-09-23 23:01:50,949] Trial 14 pruned.
[I 2026-09-23 23:02:05,921] Trial 15 finished with value: 0.08881396055221558 and parameters: {'hidden_layer': 87, 'learning_rate': 0.06847315560298535, 'momentum': 0.6614048268832682, 'weight_decay': 7.304887931014468e-06, 'elu_alpha': 1.2986044444552334}. Best is trial 15 with value: 0.08881396055221558.
[I 2026-09-23 23:02:22,214] Trial 16 finished with value: 0.090565524995327 and parameters: {'hidden_layer': 84, 'learning_rate': 0.06857553081786416, 'momentum': 0.670817812581044, 'weight_decay': 1.0002412189059676e-06, 'elu_alpha': 1.2631570423174083}. Best is trial 15 with value: 0.08881396055221558.
[I 2026-09-23 23:02:47,843] Trial 17 finished with value: 0.09061137586832047 and parameters: {'hidden_layer': 84, 'learning_rate': 0.03305318134489867, 'momentum': 0.4257648909241061, 'weight_decay': 1.764031953408393e-05, 'elu_alpha': 1.6709094852316606}. Best is trial 15 with value: 0.08881396055221558.
[I 2026-09-23 23:02:59,701] Trial 18 finished with value: 0.0916869267821312 and parameters: {'hidden_layer': 104, 'learning_rate': 0.09750921359794998, 'momentum': 0.8022798275257178, 'weight_decay': 2.9099713313390118e-06, 'elu_alpha': 0.6663566473217541}. Best is trial 15 with value: 0.08881396055221558.
[I 2026-09-23 23:03:17,045] Trial 19 pruned.
[I 2026-09-23 23:03:25,459] Trial 20 pruned.
[I 2026-09-23 23:04:02,051] Trial 21 finished with value: 0.09226609021425247 and parameters: {'hidden_layer': 53, 'learning_rate': 0.002831791442735259, 'momentum': 0.905115560109625, 'weight_decay': 4.671546037393062e-06, 'elu_alpha': 1.3890309994627505}. Best is trial 15 with value: 0.08881396055221558.
[I 2026-09-23 23:04:20,102] Trial 22 finished with value: 0.08943629264831543 and parameters: {'hidden_layer': 74, 'learning_rate': 0.021876010715861136, 'momentum': 0.8326984217364749, 'weight_decay': 2.2155773615161822e-06, 'elu_alpha': 1.3724672471617847}. Best is trial 15 with value: 0.08881396055221558.
[I 2026-09-23 23:04:35,284] Trial 23 finished with value: 0.09432735294103622 and parameters: {'hidden_layer': 74, 'learning_rate': 0.019287952116586096, 'momentum': 0.8250641500735626, 'weight_decay': 1.8471387012456857e-06, 'elu_alpha': 1.6945803434672868}. Best is trial 15 with value: 0.08881396055221558.
[I 2026-09-23 23:04:42,929] Trial 24 pruned.
[I 2026-09-23 23:04:49,199] Trial 25 pruned.
[I 2026-09-23 23:05:02,573] Trial 26 pruned.
[I 2026-09-23 23:05:13,381] Trial 27 pruned.
[I 2026-09-23 23:05:16,508] Trial 28 pruned.
[I 2026-09-23 23:05:30,569] Trial 29 pruned.
[I 2026-09-23 23:05:47,478] Trial 30 pruned.
[I 2026-09-23 23:06:05,306] Trial 31 pruned.
[I 2026-09-23 23:06:11,328] Trial 32 pruned.
[I 2026-09-23 23:06:29,088] Trial 33 pruned.
[I 2026-09-23 23:06:59,120] Trial 34 finished with value: 0.09297940135002136 and parameters: {'hidden_layer': 64, 'learning_rate': 0.0028604623979259893, 'momentum': 0.9145929200844776, 'weight_decay': 0.00013410455914957307, 'elu_alpha': 1.6679322651282114}. Best is trial 15 with value: 0.08881396055221558.
[I 2026-09-23 23:07:23,163] Trial 35 finished with value: 0.08017002791166306 and parameters: {'hidden_layer': 26, 'learning_rate': 0.022681603072886865, 'momentum': 0.7840880836834568, 'weight_decay': 3.4891294039344326e-06, 'elu_alpha': 1.2094064557305302}. Best is trial 35 with value: 0.08017002791166306.
[I 2026-09-23 23:07:37,993] Trial 36 pruned.
[I 2026-09-23 23:07:59,169] Trial 37 finished with value: 0.08944600820541382 and parameters: {'hidden_layer': 15, 'learning_rate': 0.07771889521573297, 'momentum': 0.6012805746989147, 'weight_decay': 2.8251003779087097e-05, 'elu_alpha': 1.0606303434452762}. Best is trial 35 with value: 0.08017002791166306.
[I 2026-09-23 23:08:06,361] Trial 38 pruned.
[I 2026-09-23 23:08:22,182] Trial 39 finished with value: 0.09388136863708496 and parameters: {'hidden_layer': 33, 'learning_rate': 0.04660802509029247, 'momentum': 0.8357493575858196, 'weight_decay': 1.0733551677533424e-05, 'elu_alpha': 0.9646380366195069}. Best is trial 35 with value: 0.08017002791166306.
[I 2026-09-23 23:08:43,297] Trial 40 pruned.
[I 2026-09-23 23:08:50,125] Trial 41 pruned.
[I 2026-09-23 23:08:58,317] Trial 42 pruned.
[I 2026-09-23 23:09:31,103] Trial 43 finished with value: 0.08540433645248413 and parameters: {'hidden_layer': 17, 'learning_rate': 0.0369769084173997, 'momentum': 0.6248055096610923, 'weight_decay': 9.146015936012199e-05, 'elu_alpha': 1.0736726504763692}. Best is trial 35 with value: 0.08017002791166306.
[I 2026-09-23 23:09:43,277] Trial 44 pruned.
[I 2026-09-23 23:10:00,437] Trial 45 pruned.
[I 2026-09-23 23:10:40,869] Trial 46 finished with value: 0.0875704288482666 and parameters: {'hidden_layer': 39, 'learning_rate': 0.014264498461254632, 'momentum': 0.6492401427436105, 'weight_decay': 0.00021325850886207438, 'elu_alpha': 1.4432657151396033}. Best is trial 35 with value: 0.08017002791166306.
[I 2026-09-23 23:11:20,686] Trial 47 finished with value: 0.08650532364845276 and parameters: {'hidden_layer': 36, 'learning_rate': 0.013561967292484281, 'momentum': 0.6554803421649442, 'weight_decay': 0.0004295494825321974, 'elu_alpha': 1.6294345796908987}. Best is trial 35 with value: 0.08017002791166306.
[I 2026-09-23 23:11:33,601] Trial 48 pruned.
[I 2026-09-23 23:11:50,996] Trial 49 pruned.
[I 2026-09-23 23:11:57,728] Trial 50 pruned.
[I 2026-09-23 23:12:06,225] Trial 51 pruned.
[I 2026-09-23 23:12:33,986] Trial 52 finished with value: 0.08478119969367981 and parameters: {'hidden_layer': 24, 'learning_rate': 0.032078092540647925, 'momentum': 0.559725594600103, 'weight_decay': 0.0011410544549993718, 'elu_alpha': 1.7842085607456808}. Best is trial 35 with value: 0.08017002791166306.
[I 2026-09-23 23:12:48,598] Trial 53 pruned.
[I 2026-09-23 23:13:05,068] Trial 54 pruned.
[I 2026-09-23 23:13:22,086] Trial 55 finished with value: 0.09240350872278214 and parameters: {'hidden_layer': 8, 'learning_rate': 0.06502249387883971, 'momentum': 0.6520152098678625, 'weight_decay': 0.0005778854144123678, 'elu_alpha': 1.8771289333916104}. Best is trial 35 with value: 0.08017002791166306.
[I 2026-09-23 23:13:30,166] Trial 56 pruned.
[I 2026-09-23 23:13:37,996] Trial 57 pruned.
[I 2026-09-23 23:14:05,066] Trial 58 finished with value: 0.09431079030036926 and parameters: {'hidden_layer': 39, 'learning_rate': 0.043319449805756055, 'momentum': 0.5415136747201126, 'weight_decay': 0.0001732822415290857, 'elu_alpha': 1.415518601603096}. Best is trial 35 with value: 0.08017002791166306.
[I 2026-09-23 23:14:11,001] Trial 59 pruned.
[I 2026-09-23 23:14:43,984] Trial 60 finished with value: 0.0759071409702301 and parameters: {'hidden_layer': 23, 'learning_rate': 0.03093063054452774, 'momentum': 0.6808621906515777, 'weight_decay': 0.0007565474457709201, 'elu_alpha': 1.3032076847905356}. Best is trial 60 with value: 0.0759071409702301.
[I 2026-09-23 23:14:55,645] Trial 61 pruned.
[I 2026-09-23 23:15:15,133] Trial 62 pruned.
[I 2026-09-23 23:15:24,730] Trial 63 pruned.
[I 2026-09-23 23:15:50,068] Trial 64 finished with value: 0.0820208489894867 and parameters: {'hidden_layer': 50, 'learning_rate': 0.055482084129693736, 'momentum': 0.6293825004009133, 'weight_decay': 0.0020399556634531856, 'elu_alpha': 1.584860165879256}. Best is trial 60 with value: 0.0759071409702301.
[I 2026-09-23 23:16:42,825] Trial 65 finished with value: 0.08536472171545029 and parameters: {'hidden_layer': 50, 'learning_rate': 0.009164944992124691, 'momentum': 0.6355027768623116, 'weight_decay': 0.004916845790813452, 'elu_alpha': 1.587873767094474}. Best is trial 60 with value: 0.0759071409702301.
[I 2026-09-23 23:16:59,725] Trial 66 pruned.
[I 2026-09-23 23:17:15,605] Trial 67 finished with value: 0.09590517729520798 and parameters: {'hidden_layer': 51, 'learning_rate': 0.05561893739580493, 'momentum': 0.6900266491190202, 'weight_decay': 0.004339969395881827, 'elu_alpha': 1.5973596431218966}. Best is trial 60 with value: 0.0759071409702301.
[I 2026-09-23 23:17:33,366] Trial 68 pruned.
[I 2026-09-23 23:17:47,509] Trial 69 pruned.
[I 2026-09-23 23:17:53,717] Trial 70 pruned.
[I 2026-09-23 23:18:06,090] Trial 71 pruned.
[I 2026-09-23 23:18:20,216] Trial 72 pruned.
[I 2026-09-23 23:18:39,054] Trial 73 pruned.
[I 2026-09-23 23:18:58,124] Trial 74 pruned.
[I 2026-09-23 23:19:17,855] Trial 75 pruned.
[I 2026-09-23 23:19:51,604] Trial 76 finished with value: 0.08535108715295792 and parameters: {'hidden_layer': 49, 'learning_rate': 0.020753347996019453, 'momentum': 0.6392206471004885, 'weight_decay': 0.00016635072027075025, 'elu_alpha': 1.5656456391668367}. Best is trial 60 with value: 0.0759071409702301.
[I 2026-09-23 23:20:01,204] Trial 77 pruned.
[I 2026-09-23 23:20:34,724] Trial 78 finished with value: 0.09182288497686386 and parameters: {'hidden_layer': 48, 'learning_rate': 0.03453330213772782, 'momentum': 0.5111790145039738, 'weight_decay': 0.0037842793441178555, 'elu_alpha': 1.5842145891181565}. Best is trial 60 with value: 0.0759071409702301.
[I 2026-09-23 23:20:44,104] Trial 79 pruned.
[I 2026-09-23 23:20:44,112] A new study created in memory with name: no-name-1f48019c-5596-46c5-903f-66565f30dee2

{'hidden_layer': 23, 'learning_rate': 0.03093063054452774, 'momentum': 0.6808621906515777, 'weight_decay': 0.0007565474457709201, 'elu_alpha': 1.3032076847905356}
0.0759071409702301

[I 2026-09-23 23:21:39,759] Trial 0 finished with value: 0.575683057308197 and parameters: {'hidden_layer': 76, 'learning_rate': 0.00010402613178658646, 'momentum': 0.17703223291251696, 'weight_decay': 0.000604377916964849}. Best is trial 0 with value: 0.575683057308197.
[I 2026-09-23 23:22:21,243] Trial 1 finished with value: 0.09162136912345886 and parameters: {'hidden_layer': 32, 'learning_rate': 0.05784270555748605, 'momentum': 0.32033413964661617, 'weight_decay': 1.5308437811175388e-05}. Best is trial 1 with value: 0.09162136912345886.
[I 2026-09-23 23:23:17,404] Trial 2 finished with value: 0.17712627351284027 and parameters: {'hidden_layer': 104, 'learning_rate': 0.0027532112360990316, 'momentum': 0.31006051304507853, 'weight_decay': 0.0008544015893003059}. Best is trial 1 with value: 0.09162136912345886.
[I 2026-09-23 23:24:13,423] Trial 3 finished with value: 0.236657977104187 and parameters: {'hidden_layer': 14, 'learning_rate': 0.0019426330511570535, 'momentum': 0.3243986593792416, 'weight_decay': 1.5898969431572502e-05}. Best is trial 1 with value: 0.09162136912345886.
[I 2026-09-23 23:25:02,584] Trial 4 finished with value: 0.16982583701610565 and parameters: {'hidden_layer': 68, 'learning_rate': 0.0005395488286341197, 'momentum': 0.8429577625693561, 'weight_decay': 0.0002447342361080508}. Best is trial 1 with value: 0.09162136912345886.
[I 2026-09-23 23:25:15,929] Trial 5 pruned.
[I 2026-09-23 23:25:28,958] Trial 6 pruned.
[I 2026-09-23 23:26:08,509] Trial 7 finished with value: 0.12318918108940125 and parameters: {'hidden_layer': 106, 'learning_rate': 0.003192802024772427, 'momentum': 0.6772275832011556, 'weight_decay': 8.570676413983733e-05}. Best is trial 1 with value: 0.09162136912345886.
[I 2026-09-23 23:26:21,326] Trial 8 pruned.
[I 2026-09-23 23:27:01,436] Trial 9 finished with value: 0.1137024387717247 and parameters: {'hidden_layer': 46, 'learning_rate': 0.001001453725084271, 'momentum': 0.9303232956987252, 'weight_decay': 2.359545826880546e-05}. Best is trial 1 with value: 0.09162136912345886.
[I 2026-09-23 23:27:29,540] Trial 10 finished with value: 0.09411541372537613 and parameters: {'hidden_layer': 42, 'learning_rate': 0.09153172050517877, 'momentum': 0.009485537237323705, 'weight_decay': 1.0918542833876753e-06}. Best is trial 1 with value: 0.09162136912345886.
[I 2026-09-23 23:27:56,280] Trial 11 finished with value: 0.08966916054487228 and parameters: {'hidden_layer': 43, 'learning_rate': 0.0967853548282389, 'momentum': 0.019898780995213958, 'weight_decay': 1.5739077117906504e-06}. Best is trial 11 with value: 0.08966916054487228.
[I 2026-09-23 23:28:16,216] Trial 12 finished with value: 0.099279023706913 and parameters: {'hidden_layer': 33, 'learning_rate': 0.09720922286978124, 'momentum': 0.08319822436415099, 'weight_decay': 1.555669300126075e-06}. Best is trial 11 with value: 0.08966916054487228.
[I 2026-09-23 23:28:53,450] Trial 13 finished with value: 0.10067042708396912 and parameters: {'hidden_layer': 28, 'learning_rate': 0.018880471233990156, 'momentum': 0.5023907230853956, 'weight_decay': 4.615236870020844e-06}. Best is trial 11 with value: 0.08966916054487228.
[I 2026-09-23 23:29:33,536] Trial 14 finished with value: 0.10895738005638123 and parameters: {'hidden_layer': 63, 'learning_rate': 0.020295269575001756, 'momentum': 0.17776349949126943, 'weight_decay': 0.007539371187969923}. Best is trial 11 with value: 0.08966916054487228.
[I 2026-09-23 23:30:13,860] Trial 15 finished with value: 0.0979480966925621 and parameters: {'hidden_layer': 55, 'learning_rate': 0.028819557310970544, 'momentum': 0.41179773936336644, 'weight_decay': 4.3132504741201044e-05}. Best is trial 11 with value: 0.08966916054487228.
[I 2026-09-23 23:30:27,410] Trial 16 pruned.
[I 2026-09-23 23:30:53,187] Trial 17 finished with value: 0.08807721734046936 and parameters: {'hidden_layer': 27, 'learning_rate': 0.042156649204127275, 'momentum': 0.5508441060702561, 'weight_decay': 5.1548841894355725e-05}. Best is trial 17 with value: 0.08807721734046936.
[I 2026-09-23 23:31:06,456] Trial 18 pruned.
[I 2026-09-23 23:31:37,536] Trial 19 finished with value: 0.08446037024259567 and parameters: {'hidden_layer': 26, 'learning_rate': 0.03369383667749097, 'momentum': 0.5722572901801327, 'weight_decay': 0.003519448501709274}. Best is trial 19 with value: 0.08446037024259567.
[I 2026-09-23 23:32:02,094] Trial 20 finished with value: 0.1003011092543602 and parameters: {'hidden_layer': 23, 'learning_rate': 0.04463314765089374, 'momentum': 0.5647149897198517, 'weight_decay': 0.008023512204960566}. Best is trial 19 with value: 0.08446037024259567.
[I 2026-09-23 23:32:36,587] Trial 21 finished with value: 0.10378244519233704 and parameters: {'hidden_layer': 23, 'learning_rate': 0.010430460918439527, 'momentum': 0.7864714055175205, 'weight_decay': 0.004013081672604747}. Best is trial 19 with value: 0.08446037024259567.
[I 2026-09-23 23:32:56,377] Trial 22 finished with value: 0.09282678365707397 and parameters: {'hidden_layer': 39, 'learning_rate': 0.03675215537284502, 'momentum': 0.7023613058565267, 'weight_decay': 0.00038544571235715763}. Best is trial 19 with value: 0.08446037024259567.
[I 2026-09-23 23:33:15,464] Trial 23 finished with value: 0.09815774112939835 and parameters: {'hidden_layer': 55, 'learning_rate': 0.06212800541245971, 'momentum': 0.5680458726408008, 'weight_decay': 0.002438941394324498}. Best is trial 19 with value: 0.08446037024259567.
[I 2026-09-23 23:33:22,351] Trial 24 pruned.
[I 2026-09-23 23:33:34,650] Trial 25 pruned.
[I 2026-09-23 23:33:48,470] Trial 26 finished with value: 0.10912924259901047 and parameters: {'hidden_layer': 26, 'learning_rate': 0.09994959186416866, 'momentum': 0.7490114762813587, 'weight_decay': 2.7467466955609425e-06}. Best is trial 19 with value: 0.08446037024259567.
[I 2026-09-23 23:34:01,741] Trial 27 pruned.
[I 2026-09-23 23:34:05,017] Trial 28 pruned.
[I 2026-09-23 23:34:33,119] Trial 29 finished with value: 0.09070389717817307 and parameters: {'hidden_layer': 82, 'learning_rate': 0.05683815259727469, 'momentum': 0.25364599003334193, 'weight_decay': 0.0005350525167865724}. Best is trial 19 with value: 0.08446037024259567.
[I 2026-09-23 23:34:42,519] Trial 30 pruned.
[I 2026-09-23 23:35:05,390] Trial 31 finished with value: 0.09321361780166626 and parameters: {'hidden_layer': 85, 'learning_rate': 0.05806210796848279, 'momentum': 0.2331810806171341, 'weight_decay': 0.0006604015480486236}. Best is trial 19 with value: 0.08446037024259567.
[I 2026-09-23 23:35:34,986] Trial 32 finished with value: 0.09919082373380661 and parameters: {'hidden_layer': 89, 'learning_rate': 0.05844952221291629, 'momentum': 0.08802660684564731, 'weight_decay': 0.00342109711221481}. Best is trial 19 with value: 0.08446037024259567.
[I 2026-09-23 23:35:48,501] Trial 33 pruned.
[I 2026-09-23 23:35:54,273] Trial 34 pruned.
[I 2026-09-23 23:36:02,915] Trial 35 pruned.
[I 2026-09-23 23:36:32,485] Trial 36 finished with value: 0.09146150946617126 and parameters: {'hidden_layer': 100, 'learning_rate': 0.04332248350368918, 'momentum': 0.37858609762194223, 'weight_decay': 0.0013660801227326368}. Best is trial 19 with value: 0.08446037024259567.
[I 2026-09-23 23:36:44,805] Trial 37 pruned.
[I 2026-09-23 23:36:58,084] Trial 38 pruned.
[I 2026-09-23 23:37:22,080] Trial 39 finished with value: 0.08632496744394302 and parameters: {'hidden_layer': 76, 'learning_rate': 0.07341722294143702, 'momentum': 0.45067466905587317, 'weight_decay': 2.5582366309862082e-05}. Best is trial 19 with value: 0.08446037024259567.
[I 2026-09-23 23:37:34,917] Trial 40 finished with value: 0.09404782205820084 and parameters: {'hidden_layer': 63, 'learning_rate': 0.07602198443997939, 'momentum': 0.8257982732714686, 'weight_decay': 2.394385428250316e-05}. Best is trial 19 with value: 0.08446037024259567.
[I 2026-09-23 23:38:07,025] Trial 41 finished with value: 0.09366205334663391 and parameters: {'hidden_layer': 73, 'learning_rate': 0.04415192955470752, 'momentum': 0.4373002786877985, 'weight_decay': 6.652817962183315e-05}. Best is trial 19 with value: 0.08446037024259567.
[I 2026-09-23 23:38:27,743] Trial 42 finished with value: 0.09671338647603989 and parameters: {'hidden_layer': 82, 'learning_rate': 0.07065997123795704, 'momentum': 0.5207138591129655, 'weight_decay': 2.4827246429134004e-05}. Best is trial 19 with value: 0.08446037024259567.
[I 2026-09-23 23:38:53,570] Trial 43 finished with value: 0.08957742899656296 and parameters: {'hidden_layer': 95, 'learning_rate': 0.036231218116202286, 'momentum': 0.6391881555917794, 'weight_decay': 1.4011316536290369e-05}. Best is trial 19 with value: 0.08446037024259567.
[I 2026-09-23 23:39:07,217] Trial 44 pruned.
[I 2026-09-23 23:39:29,418] Trial 45 finished with value: 0.08941429853439331 and parameters: {'hidden_layer': 116, 'learning_rate': 0.03720632416807516, 'momentum': 0.7298284468726057, 'weight_decay': 5.8849644754760405e-06}. Best is trial 19 with value: 0.08446037024259567.
[I 2026-09-23 23:39:43,621] Trial 46 pruned.
[I 2026-09-23 23:39:57,323] Trial 47 pruned.
[I 2026-09-23 23:40:10,894] Trial 48 finished with value: 0.09157320111989975 and parameters: {'hidden_layer': 124, 'learning_rate': 0.032589549399817515, 'momentum': 0.8613599042384279, 'weight_decay': 8.642082761588074e-06}. Best is trial 19 with value: 0.08446037024259567.
[I 2026-09-23 23:40:22,884] Trial 49 pruned.
[I 2026-09-23 23:40:33,974] Trial 50 pruned.
[I 2026-09-23 23:40:40,532] Trial 51 pruned.
[I 2026-09-23 23:41:04,859] Trial 52 finished with value: 0.09158456325531006 and parameters: {'hidden_layer': 70, 'learning_rate': 0.048534972051577044, 'momentum': 0.6206297524478055, 'weight_decay': 4.083945960589368e-06}. Best is trial 19 with value: 0.08446037024259567.
[I 2026-09-23 23:41:41,280] Trial 53 finished with value: 0.09760434180498123 and parameters: {'hidden_layer': 42, 'learning_rate': 0.024304818400234837, 'momentum': 0.5618508164776056, 'weight_decay': 1.1100725016088912e-06}. Best is trial 19 with value: 0.08446037024259567.
[I 2026-09-23 23:42:06,883] Trial 54 finished with value: 0.0838327631354332 and parameters: {'hidden_layer': 50, 'learning_rate': 0.03426173900243471, 'momentum': 0.7004744437108474, 'weight_decay': 2.6354926544392144e-06}. Best is trial 54 with value: 0.0838327631354332.
[I 2026-09-23 23:42:11,803] Trial 55 pruned.
[I 2026-09-23 23:42:41,427] Trial 56 finished with value: 0.0893053188920021 and parameters: {'hidden_layer': 104, 'learning_rate': 0.037551973749969575, 'momentum': 0.5335928664240555, 'weight_decay': 3.123167460551853e-06}. Best is trial 54 with value: 0.0838327631354332.
[I 2026-09-23 23:43:17,587] Trial 57 finished with value: 0.08875486999750137 and parameters: {'hidden_layer': 120, 'learning_rate': 0.023105563768875743, 'momentum': 0.5232267528020315, 'weight_decay': 4.404242248810313e-06}. Best is trial 54 with value: 0.0838327631354332.
[I 2026-09-23 23:43:30,237] Trial 58 pruned.
[I 2026-09-23 23:43:43,577] Trial 59 pruned.
[I 2026-09-23 23:43:57,103] Trial 60 pruned.
[I 2026-09-23 23:44:22,010] Trial 61 finished with value: 0.08930155634880066 and parameters: {'hidden_layer': 118, 'learning_rate': 0.0508839446835691, 'momentum': 0.540010528796148, 'weight_decay': 3.1575077292072828e-06}. Best is trial 54 with value: 0.0838327631354332.
[I 2026-09-23 23:44:33,339] Trial 62 pruned.
[I 2026-09-23 23:44:47,021] Trial 63 pruned.
[I 2026-09-23 23:44:56,260] Trial 64 pruned.
[I 2026-09-23 23:45:09,688] Trial 65 pruned.
[I 2026-09-23 23:45:38,540] Trial 66 finished with value: 0.09319227188825607 and parameters: {'hidden_layer': 121, 'learning_rate': 0.037698324434760525, 'momentum': 0.6014653860519948, 'weight_decay': 2.3779354170025214e-06}. Best is trial 54 with value: 0.0838327631354332.
[I 2026-09-23 23:45:52,013] Trial 67 pruned.
[I 2026-09-23 23:46:01,512] Trial 68 pruned.
[I 2026-09-23 23:46:14,896] Trial 69 pruned.
[I 2026-09-23 23:46:28,357] Trial 70 pruned.
[I 2026-09-23 23:46:51,299] Trial 71 finished with value: 0.0935688242316246 and parameters: {'hidden_layer': 113, 'learning_rate': 0.03847172843369664, 'momentum': 0.7361926012348352, 'weight_decay': 5.1342338374235e-06}. Best is trial 54 with value: 0.0838327631354332.
[I 2026-09-23 23:47:04,479] Trial 72 pruned.
[I 2026-09-23 23:47:12,545] Trial 73 pruned.
[I 2026-09-23 23:47:44,943] Trial 74 finished with value: 0.08928672224283218 and parameters: {'hidden_layer': 120, 'learning_rate': 0.028984785797920166, 'momentum': 0.5048302187906654, 'weight_decay': 3.0129600971129914e-06}. Best is trial 54 with value: 0.0838327631354332.
[I 2026-09-23 23:47:58,252] Trial 75 pruned.
[I 2026-09-23 23:48:03,946] Trial 76 pruned.
[I 2026-09-23 23:48:15,504] Trial 77 pruned.
[I 2026-09-23 23:48:40,627] Trial 78 finished with value: 0.08654972165822983 and parameters: {'hidden_layer': 51, 'learning_rate': 0.06483146026813555, 'momentum': 0.442776676044267, 'weight_decay': 1.1507469179299241e-05}. Best is trial 54 with value: 0.0838327631354332.
[I 2026-09-23 23:49:09,434] Trial 79 finished with value: 0.08416786044836044 and parameters: {'hidden_layer': 52, 'learning_rate': 0.06872014635575197, 'momentum': 0.33212915190714903, 'weight_decay': 1.3166344635894295e-05}. Best is trial 54 with value: 0.0838327631354332.
[I 2026-09-23 23:49:09,445] A new study created in memory with name: no-name-6f719ec0-ed17-4321-9735-724bc0118d2f

{'hidden_layer': 50, 'learning_rate': 0.03426173900243471, 'momentum': 0.7004744437108474, 'weight_decay': 2.6354926544392144e-06}
0.0838327631354332

[I 2026-09-23 23:49:50,450] Trial 0 finished with value: 0.17950014770030975 and parameters: {'hidden_layer': 43, 'learning_rate': 0.0021902592075569733, 'momentum': 0.5471669068009473, 'weight_decay': 2.3930804648253217e-06}. Best is trial 0 with value: 0.17950014770030975.
[I 2026-09-23 23:50:29,268] Trial 1 finished with value: 0.39048612117767334 and parameters: {'hidden_layer': 102, 'learning_rate': 0.0003561927378681589, 'momentum': 0.32011132578553214, 'weight_decay': 0.0001097654566272847}. Best is trial 0 with value: 0.17950014770030975.
[I 2026-09-23 23:51:10,606] Trial 2 finished with value: 0.1891241818666458 and parameters: {'hidden_layer': 64, 'learning_rate': 0.0003098109440313933, 'momentum': 0.8971209662989222, 'weight_decay': 2.490933689443521e-06}. Best is trial 0 with value: 0.17950014770030975.
[I 2026-09-23 23:51:51,757] Trial 3 finished with value: 0.4514600336551666 and parameters: {'hidden_layer': 119, 'learning_rate': 0.0003377033234562872, 'momentum': 0.03147270237479859, 'weight_decay': 8.526405905594897e-06}. Best is trial 0 with value: 0.17950014770030975.
[I 2026-09-23 23:52:32,428] Trial 4 finished with value: 0.15898127853870392 and parameters: {'hidden_layer': 52, 'learning_rate': 0.0013118024669291726, 'momentum': 0.7382073915964487, 'weight_decay': 0.0037388408380024194}. Best is trial 4 with value: 0.15898127853870392.
[I 2026-09-23 23:53:17,113] Trial 5 finished with value: 0.12457939237356186 and parameters: {'hidden_layer': 36, 'learning_rate': 0.005491967734458021, 'momentum': 0.5479700589177615, 'weight_decay': 0.005795046218041697}. Best is trial 5 with value: 0.12457939237356186.
[I 2026-09-23 23:53:44,479] Trial 6 finished with value: 0.09108797460794449 and parameters: {'hidden_layer': 8, 'learning_rate': 0.005354670314255247, 'momentum': 0.9266688633215079, 'weight_decay': 7.149993850241184e-05}. Best is trial 6 with value: 0.09108797460794449.
[I 2026-09-23 23:54:25,244] Trial 7 finished with value: 0.10276725888252258 and parameters: {'hidden_layer': 98, 'learning_rate': 0.0028411806353826107, 'momentum': 0.8460598465757972, 'weight_decay': 4.736842152233636e-05}. Best is trial 6 with value: 0.09108797460794449.
[I 2026-09-23 23:54:38,842] Trial 8 pruned.
[I 2026-09-23 23:55:20,034] Trial 9 finished with value: 0.10901053994894028 and parameters: {'hidden_layer': 126, 'learning_rate': 0.0014275849047267622, 'momentum': 0.8992921679201045, 'weight_decay': 2.903448058057685e-05}. Best is trial 6 with value: 0.09108797460794449.
[I 2026-09-23 23:55:45,407] Trial 10 finished with value: 0.10034197568893433 and parameters: {'hidden_layer': 11, 'learning_rate': 0.04591303660520822, 'momentum': 0.31515366452670246, 'weight_decay': 0.000245954610636056}. Best is trial 6 with value: 0.09108797460794449.
[I 2026-09-23 23:56:15,552] Trial 11 finished with value: 0.09367493540048599 and parameters: {'hidden_layer': 9, 'learning_rate': 0.0639803432779816, 'momentum': 0.2653661222681615, 'weight_decay': 0.0003434350154807495}. Best is trial 6 with value: 0.09108797460794449.
[I 2026-09-23 23:56:46,572] Trial 12 finished with value: 0.09335863590240479 and parameters: {'hidden_layer': 23, 'learning_rate': 0.06422937076761977, 'momentum': 0.13709071294401448, 'weight_decay': 0.0005561627476415768}. Best is trial 6 with value: 0.09108797460794449.
[I 2026-09-23 23:57:28,357] Trial 13 finished with value: 0.11116809397935867 and parameters: {'hidden_layer': 29, 'learning_rate': 0.016589229043765207, 'momentum': 0.006303657931098106, 'weight_decay': 0.0009446304456714842}. Best is trial 6 with value: 0.09108797460794449.
[I 2026-09-23 23:58:08,502] Trial 14 finished with value: 0.09050183743238449 and parameters: {'hidden_layer': 28, 'learning_rate': 0.012032168578328738, 'momentum': 0.7145887123662148, 'weight_decay': 0.0007896842665595269}. Best is trial 14 with value: 0.09050183743238449.
[I 2026-09-23 23:58:46,937] Trial 15 finished with value: 0.09087111800909042 and parameters: {'hidden_layer': 76, 'learning_rate': 0.01093229301281244, 'momentum': 0.7196188918426437, 'weight_decay': 1.240421634878673e-05}. Best is trial 14 with value: 0.09050183743238449.
[I 2026-09-23 23:59:23,602] Trial 16 finished with value: 0.0985332727432251 and parameters: {'hidden_layer': 82, 'learning_rate': 0.015156472714605447, 'momentum': 0.7156587763808033, 'weight_decay': 1.4462935052411879e-05}. Best is trial 14 with value: 0.09050183743238449.
[I 2026-09-24 00:00:02,636] Trial 17 finished with value: 0.09411612898111343 and parameters: {'hidden_layer': 73, 'learning_rate': 0.014724797702033818, 'momentum': 0.6728939717362583, 'weight_decay': 6.821592783519857e-06}. Best is trial 14 with value: 0.09050183743238449.
[I 2026-09-24 00:00:37,502] Trial 18 finished with value: 0.09208974987268448 and parameters: {'hidden_layer': 89, 'learning_rate': 0.02420621488444296, 'momentum': 0.43191407074797983, 'weight_decay': 0.0011241665837716124}. Best is trial 14 with value: 0.09050183743238449.
[I 2026-09-24 00:00:50,795] Trial 19 pruned.
[I 2026-09-24 00:01:15,311] Trial 20 finished with value: 0.0932849571108818 and parameters: {'hidden_layer': 72, 'learning_rate': 0.032947301665350474, 'momentum': 0.782095708936875, 'weight_decay': 0.00016276144825826556}. Best is trial 14 with value: 0.09050183743238449.
[I 2026-09-24 00:01:31,980] Trial 21 finished with value: 0.1095634177327156 and parameters: {'hidden_layer': 24, 'learning_rate': 0.00705061495276541, 'momentum': 0.9719999648543277, 'weight_decay': 4.6501312888976014e-05}. Best is trial 14 with value: 0.09050183743238449.
[I 2026-09-24 00:01:36,371] Trial 22 pruned.
[I 2026-09-24 00:02:10,089] Trial 23 finished with value: 0.0911024808883667 and parameters: {'hidden_layer': 47, 'learning_rate': 0.010147500192933027, 'momentum': 0.8031352188414924, 'weight_decay': 6.199317007043865e-05}. Best is trial 14 with value: 0.09050183743238449.
[I 2026-09-24 00:02:23,711] Trial 24 pruned.
[I 2026-09-24 00:02:37,347] Trial 25 pruned.
[I 2026-09-24 00:02:58,183] Trial 26 finished with value: 0.09007085114717484 and parameters: {'hidden_layer': 81, 'learning_rate': 0.09390015667980431, 'momentum': 0.4709381688937436, 'weight_decay': 9.926618306986465e-05}. Best is trial 26 with value: 0.09007085114717484.
[I 2026-09-24 00:03:06,837] Trial 27 pruned.
[I 2026-09-24 00:03:38,802] Trial 28 finished with value: 0.0935429260134697 and parameters: {'hidden_layer': 62, 'learning_rate': 0.06762623155585588, 'momentum': 0.46026774420615624, 'weight_decay': 0.00017057284935861233}. Best is trial 26 with value: 0.09007085114717484.
[I 2026-09-24 00:04:36,919] Trial 29 finished with value: 0.09058830887079239 and parameters: {'hidden_layer': 107, 'learning_rate': 0.0205383666847045, 'momentum': 0.5992220196159354, 'weight_decay': 2.6642973676158704e-06}. Best is trial 26 with value: 0.09007085114717484.
[I 2026-09-24 00:05:03,280] Trial 30 finished with value: 0.08580371737480164 and parameters: {'hidden_layer': 111, 'learning_rate': 0.09135595558375166, 'momentum': 0.5744946871781065, 'weight_decay': 1.0997688672327493e-06}. Best is trial 30 with value: 0.08580371737480164.
[I 2026-09-24 00:05:25,075] Trial 31 finished with value: 0.0820181593298912 and parameters: {'hidden_layer': 104, 'learning_rate': 0.09181821657590672, 'momentum': 0.595920765083554, 'weight_decay': 1.010225699793154e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:05:59,269] Trial 32 finished with value: 0.08745875209569931 and parameters: {'hidden_layer': 110, 'learning_rate': 0.08640270907330777, 'momentum': 0.5324103970793335, 'weight_decay': 1.766192575715122e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:06:37,313] Trial 33 finished with value: 0.08429961651563644 and parameters: {'hidden_layer': 111, 'learning_rate': 0.09670098844407997, 'momentum': 0.38778588105966194, 'weight_decay': 1.1132971636490078e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:07:14,462] Trial 34 finished with value: 0.08941275626420975 and parameters: {'hidden_layer': 113, 'learning_rate': 0.09626638873208364, 'momentum': 0.35280001257576177, 'weight_decay': 1.0050777064587924e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:07:33,299] Trial 35 pruned.
[I 2026-09-24 00:08:09,280] Trial 36 finished with value: 0.09164143353700638 and parameters: {'hidden_layer': 118, 'learning_rate': 0.04870543189199665, 'momentum': 0.5334175282717823, 'weight_decay': 3.4891489649223278e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:08:32,837] Trial 37 finished with value: 0.08970210701227188 and parameters: {'hidden_layer': 128, 'learning_rate': 0.0884743907836312, 'momentum': 0.23143831072044985, 'weight_decay': 1.5456837024704252e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:09:01,389] Trial 38 finished with value: 0.08961793035268784 and parameters: {'hidden_layer': 106, 'learning_rate': 0.03825379032574698, 'momentum': 0.5711412796533326, 'weight_decay': 4.600045833683218e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:09:22,906] Trial 39 finished with value: 0.0938674733042717 and parameters: {'hidden_layer': 93, 'learning_rate': 0.06695178499965876, 'momentum': 0.5170789171690402, 'weight_decay': 1.8663452117062586e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:09:36,517] Trial 40 pruned.
[I 2026-09-24 00:09:42,566] Trial 41 pruned.
[I 2026-09-24 00:10:05,760] Trial 42 finished with value: 0.0899447426199913 and parameters: {'hidden_layer': 109, 'learning_rate': 0.0986615000320015, 'momentum': 0.2966967965169183, 'weight_decay': 1.6968667780581545e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:10:33,222] Trial 43 finished with value: 0.08756827563047409 and parameters: {'hidden_layer': 122, 'learning_rate': 0.05212598451084088, 'momentum': 0.6071548595266957, 'weight_decay': 1.100827202829724e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:10:57,837] Trial 44 finished with value: 0.0932866707444191 and parameters: {'hidden_layer': 123, 'learning_rate': 0.05036006138388232, 'momentum': 0.6023002421143193, 'weight_decay': 2.9639142399006207e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:11:11,938] Trial 45 pruned.
[I 2026-09-24 00:11:35,402] Trial 46 finished with value: 0.09430447220802307 and parameters: {'hidden_layer': 121, 'learning_rate': 0.06726552725171761, 'momentum': 0.573547701273815, 'weight_decay': 4.704035938758271e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:12:02,461] Trial 47 finished with value: 0.08259537816047668 and parameters: {'hidden_layer': 103, 'learning_rate': 0.03599950084969973, 'momentum': 0.6732988834388698, 'weight_decay': 2.1279551044029424e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:12:31,555] Trial 48 finished with value: 0.09821910411119461 and parameters: {'hidden_layer': 88, 'learning_rate': 0.036760668890471165, 'momentum': 0.18692194630633305, 'weight_decay': 2.023365633812791e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:12:50,450] Trial 49 finished with value: 0.10092576593160629 and parameters: {'hidden_layer': 94, 'learning_rate': 0.0698971282987978, 'momentum': 0.6694125789978889, 'weight_decay': 3.2443394336165555e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:13:03,315] Trial 50 pruned.
[I 2026-09-24 00:13:30,120] Trial 51 finished with value: 0.09312132745981216 and parameters: {'hidden_layer': 110, 'learning_rate': 0.04605497209647559, 'momentum': 0.6170810498693299, 'weight_decay': 1.3938309982882683e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:13:47,941] Trial 52 finished with value: 0.08757994323968887 and parameters: {'hidden_layer': 118, 'learning_rate': 0.07342955523988072, 'momentum': 0.6815631669091683, 'weight_decay': 2.4588379839462793e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:14:05,215] Trial 53 finished with value: 0.08954458683729172 and parameters: {'hidden_layer': 101, 'learning_rate': 0.054161041718986114, 'momentum': 0.7805643742842243, 'weight_decay': 6.430313154022061e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:14:19,147] Trial 54 pruned.
[I 2026-09-24 00:14:32,703] Trial 55 pruned.
[I 2026-09-24 00:14:58,533] Trial 56 finished with value: 0.09067105501890182 and parameters: {'hidden_layer': 114, 'learning_rate': 0.03725283371067712, 'momentum': 0.7012479196299362, 'weight_decay': 3.891978118651388e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:15:15,825] Trial 57 finished with value: 0.09522098302841187 and parameters: {'hidden_layer': 88, 'learning_rate': 0.058208041629499996, 'momentum': 0.7574530630933426, 'weight_decay': 1.2791489417348948e-05}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:15:34,810] Trial 58 finished with value: 0.08407968282699585 and parameters: {'hidden_layer': 101, 'learning_rate': 0.07820412911183623, 'momentum': 0.6384416916612135, 'weight_decay': 2.2603929343090666e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:15:47,926] Trial 59 pruned.
[I 2026-09-24 00:16:07,547] Trial 60 finished with value: 0.09115161746740341 and parameters: {'hidden_layer': 103, 'learning_rate': 0.07715322159569352, 'momentum': 0.4225482989112614, 'weight_decay': 5.6008757970850415e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:16:33,706] Trial 61 finished with value: 0.08701393753290176 and parameters: {'hidden_layer': 109, 'learning_rate': 0.04288923761569679, 'momentum': 0.6560338856519031, 'weight_decay': 2.462935165850565e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:16:47,841] Trial 62 finished with value: 0.09372157603502274 and parameters: {'hidden_layer': 109, 'learning_rate': 0.07995066861989242, 'momentum': 0.7452526845216144, 'weight_decay': 2.5411557926979993e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:17:13,876] Trial 63 finished with value: 0.0921178087592125 and parameters: {'hidden_layer': 99, 'learning_rate': 0.04070791087075078, 'momentum': 0.6591947421222077, 'weight_decay': 2.167764735573514e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:17:38,266] Trial 64 finished with value: 0.08609772473573685 and parameters: {'hidden_layer': 92, 'learning_rate': 0.06069374623211974, 'momentum': 0.5614143017549584, 'weight_decay': 1.9959095492829945e-05}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:18:02,383] Trial 65 finished with value: 0.08899613469839096 and parameters: {'hidden_layer': 91, 'learning_rate': 0.022940596653194537, 'momentum': 0.8208450482778045, 'weight_decay': 1.7177117183543165e-05}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:18:32,051] Trial 66 finished with value: 0.09503209590911865 and parameters: {'hidden_layer': 85, 'learning_rate': 0.03213898137840838, 'momentum': 0.5629443396729921, 'weight_decay': 3.188290336063528e-05}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:18:45,659] Trial 67 pruned.
[I 2026-09-24 00:18:53,516] Trial 68 pruned.
[I 2026-09-24 00:19:03,758] Trial 69 pruned.
[I 2026-09-24 00:19:29,377] Trial 70 finished with value: 0.08825664967298508 and parameters: {'hidden_layer': 77, 'learning_rate': 0.060630698785216805, 'momentum': 0.649934676281239, 'weight_decay': 1.6725814818383815e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:19:52,821] Trial 71 finished with value: 0.08595044165849686 and parameters: {'hidden_layer': 111, 'learning_rate': 0.07489624139635329, 'momentum': 0.5386575695086736, 'weight_decay': 1.299882073644489e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:20:11,166] Trial 72 finished with value: 0.08654403686523438 and parameters: {'hidden_layer': 106, 'learning_rate': 0.08001984944871508, 'momentum': 0.46278907024323995, 'weight_decay': 1.2927271533520759e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:20:34,275] Trial 73 finished with value: 0.08760438114404678 and parameters: {'hidden_layer': 102, 'learning_rate': 0.07823018477274916, 'momentum': 0.45171482085348397, 'weight_decay': 1.2928225564170754e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:20:42,277] Trial 74 pruned.
[I 2026-09-24 00:21:06,043] Trial 75 finished with value: 0.0880141481757164 and parameters: {'hidden_layer': 118, 'learning_rate': 0.09830845126193592, 'momentum': 0.5131050162500523, 'weight_decay': 1.049179301571724e-06}. Best is trial 31 with value: 0.0820181593298912.
[I 2026-09-24 00:21:16,655] Trial 76 pruned.
[I 2026-09-24 00:21:23,445] Trial 77 pruned.
[I 2026-09-24 00:21:28,713] Trial 78 pruned.
[I 2026-09-24 00:21:34,108] Trial 79 pruned.
[I 2026-09-24 00:21:34,108] A new study created in memory with name: no-name-098eed6b-4727-423d-b5c0-986c1a3c14e2

{'hidden_layer': 104, 'learning_rate': 0.09181821657590672, 'momentum': 0.595920765083554, 'weight_decay': 1.010225699793154e-06}
0.0820181593298912

[I 2026-09-24 00:22:05,011] Trial 0 finished with value: 0.09076791256666183 and parameters: {'hidden_layer': 58, 'learning_rate': 0.04007487030054828, 'momentum': 0.26947266737589026, 'weight_decay': 0.0030011561171978474}. Best is trial 0 with value: 0.09076791256666183.
[I 2026-09-24 00:22:45,740] Trial 1 finished with value: 0.1020590290427208 and parameters: {'hidden_layer': 48, 'learning_rate': 0.01906003388494581, 'momentum': 0.4416043787889636, 'weight_decay': 3.110963233400565e-05}. Best is trial 0 with value: 0.09076791256666183.
[I 2026-09-24 00:23:26,168] Trial 2 finished with value: 0.13894504308700562 and parameters: {'hidden_layer': 112, 'learning_rate': 0.0011139584159096363, 'momentum': 0.8237949932424017, 'weight_decay': 2.228601505490009e-06}. Best is trial 0 with value: 0.09076791256666183.
[I 2026-09-24 00:23:46,021] Trial 3 finished with value: 0.09371516853570938 and parameters: {'hidden_layer': 83, 'learning_rate': 0.07208261543491837, 'momentum': 0.5531663257601827, 'weight_decay': 0.002173746827711102}. Best is trial 0 with value: 0.09076791256666183.
[I 2026-09-24 00:24:09,008] Trial 4 finished with value: 0.08806739002466202 and parameters: {'hidden_layer': 25, 'learning_rate': 0.05455090942273781, 'momentum': 0.333721915741008, 'weight_decay': 4.0386911475419334e-05}. Best is trial 4 with value: 0.08806739002466202.
[I 2026-09-24 00:24:22,802] Trial 5 pruned.
[I 2026-09-24 00:24:36,262] Trial 6 pruned.
[I 2026-09-24 00:24:50,051] Trial 7 pruned.
[I 2026-09-24 00:25:03,475] Trial 8 pruned.
[I 2026-09-24 00:25:09,436] Trial 9 pruned.
[I 2026-09-24 00:25:22,984] Trial 10 pruned.
[I 2026-09-24 00:25:44,621] Trial 11 finished with value: 0.09949079155921936 and parameters: {'hidden_layer': 52, 'learning_rate': 0.09533950849768814, 'momentum': 0.20725671927008932, 'weight_decay': 0.0091178784899847}. Best is trial 4 with value: 0.08806739002466202.
[I 2026-09-24 00:25:58,215] Trial 12 pruned.
[I 2026-09-24 00:26:11,803] Trial 13 pruned.
[I 2026-09-24 00:26:37,093] Trial 14 finished with value: 0.09843740612268448 and parameters: {'hidden_layer': 27, 'learning_rate': 0.0593242268769781, 'momentum': 0.5728348387140821, 'weight_decay': 0.00018750677681889932}. Best is trial 4 with value: 0.08806739002466202.
[I 2026-09-24 00:26:40,475] Trial 15 pruned.
[I 2026-09-24 00:26:53,950] Trial 16 pruned.
[I 2026-09-24 00:27:07,530] Trial 17 pruned.
[I 2026-09-24 00:27:21,151] Trial 18 pruned.
[I 2026-09-24 00:27:34,018] Trial 19 pruned.
[I 2026-09-24 00:27:48,002] Trial 20 pruned.
[I 2026-09-24 00:28:06,055] Trial 21 finished with value: 0.08274031430482864 and parameters: {'hidden_layer': 87, 'learning_rate': 0.09979158538619755, 'momentum': 0.5827302073011079, 'weight_decay': 0.0020539504191714694}. Best is trial 21 with value: 0.08274031430482864.
[I 2026-09-24 00:28:31,139] Trial 22 finished with value: 0.08960848301649094 and parameters: {'hidden_layer': 126, 'learning_rate': 0.04872140000525034, 'momentum': 0.6716496260531626, 'weight_decay': 0.0033731978045183227}. Best is trial 21 with value: 0.08274031430482864.
[I 2026-09-24 00:28:50,450] Trial 23 finished with value: 0.09278887510299683 and parameters: {'hidden_layer': 128, 'learning_rate': 0.07555107800856901, 'momentum': 0.6942891103477428, 'weight_decay': 6.22646842254021e-05}. Best is trial 21 with value: 0.08274031430482864.
[I 2026-09-24 00:28:59,062] Trial 24 pruned.
[I 2026-09-24 00:29:12,912] Trial 25 pruned.
[I 2026-09-24 00:29:17,820] Trial 26 pruned.
[I 2026-09-24 00:29:31,797] Trial 27 pruned.
[I 2026-09-24 00:30:05,772] Trial 28 finished with value: 0.10060945898294449 and parameters: {'hidden_layer': 106, 'learning_rate': 0.031211874819822946, 'momentum': 0.47761455680335235, 'weight_decay': 0.001681196775242224}. Best is trial 21 with value: 0.08274031430482864.
[I 2026-09-24 00:30:12,925] Trial 29 pruned.
[I 2026-09-24 00:30:16,409] Trial 30 pruned.
[I 2026-09-24 00:30:29,928] Trial 31 pruned.
[I 2026-09-24 00:30:38,299] Trial 32 pruned.
[I 2026-09-24 00:30:51,976] Trial 33 pruned.
[I 2026-09-24 00:31:04,117] Trial 34 pruned.
[I 2026-09-24 00:31:17,805] Trial 35 pruned.
[I 2026-09-24 00:31:31,784] Trial 36 pruned.
[I 2026-09-24 00:31:55,521] Trial 37 finished with value: 0.08025431632995605 and parameters: {'hidden_layer': 86, 'learning_rate': 0.06537872898442752, 'momentum': 0.6081115610091297, 'weight_decay': 3.690268252998101e-05}. Best is trial 37 with value: 0.08025431632995605.
[I 2026-09-24 00:32:04,804] Trial 38 pruned.
[I 2026-09-24 00:32:10,527] Trial 39 pruned.
[I 2026-09-24 00:32:24,307] Trial 40 pruned.
[I 2026-09-24 00:32:38,180] Trial 41 pruned.
[I 2026-09-24 00:32:56,953] Trial 42 finished with value: 0.08072558045387268 and parameters: {'hidden_layer': 66, 'learning_rate': 0.07036014061562072, 'momentum': 0.743478636603063, 'weight_decay': 5.466219497847069e-05}. Best is trial 37 with value: 0.08025431632995605.
[I 2026-09-24 00:33:04,816] Trial 43 pruned.
[I 2026-09-24 00:33:22,650] Trial 44 finished with value: 0.0884225070476532 and parameters: {'hidden_layer': 68, 'learning_rate': 0.09882050487186228, 'momentum': 0.7341015848154644, 'weight_decay': 0.00011135884226162346}. Best is trial 37 with value: 0.08025431632995605.
[I 2026-09-24 00:33:26,573] Trial 45 pruned.
[I 2026-09-24 00:33:30,674] Trial 46 pruned.
[I 2026-09-24 00:33:44,708] Trial 47 pruned.
[I 2026-09-24 00:33:58,486] Trial 48 pruned.
[I 2026-09-24 00:34:04,644] Trial 49 pruned.
[I 2026-09-24 00:34:09,979] Trial 50 pruned.
[I 2026-09-24 00:34:28,045] Trial 51 finished with value: 0.09007424861192703 and parameters: {'hidden_layer': 70, 'learning_rate': 0.05246622620261688, 'momentum': 0.6584404456503269, 'weight_decay': 0.0002650927785625947}. Best is trial 37 with value: 0.08025431632995605.
[I 2026-09-24 00:34:56,049] Trial 52 finished with value: 0.08987884968519211 and parameters: {'hidden_layer': 27, 'learning_rate': 0.03968784047403654, 'momentum': 0.607430528674708, 'weight_decay': 1.3501743327567828e-05}. Best is trial 37 with value: 0.08025431632995605.
[I 2026-09-24 00:35:03,109] Trial 53 pruned.
[I 2026-09-24 00:35:10,439] Trial 54 pruned.
[I 2026-09-24 00:35:17,668] Trial 55 pruned.
[I 2026-09-24 00:35:28,123] Trial 56 pruned.
[I 2026-09-24 00:35:42,179] Trial 57 pruned.
[I 2026-09-24 00:35:45,510] Trial 58 pruned.
[I 2026-09-24 00:35:59,219] Trial 59 pruned.
[I 2026-09-24 00:36:13,690] Trial 60 pruned.
[I 2026-09-24 00:36:22,480] Trial 61 pruned.
[I 2026-09-24 00:36:36,627] Trial 62 pruned.
[I 2026-09-24 00:37:08,138] Trial 63 finished with value: 0.09477541595697403 and parameters: {'hidden_layer': 29, 'learning_rate': 0.06606758788907824, 'momentum': 0.6595239741495876, 'weight_decay': 1.667449799874849e-05}. Best is trial 37 with value: 0.08025431632995605.
[I 2026-09-24 00:37:17,172] Trial 64 pruned.
[I 2026-09-24 00:37:28,247] Trial 65 pruned.
[I 2026-09-24 00:37:37,163] Trial 66 pruned.
[I 2026-09-24 00:37:55,090] Trial 67 finished with value: 0.09347495436668396 and parameters: {'hidden_layer': 17, 'learning_rate': 0.06119401095753753, 'momentum': 0.8331613218413121, 'weight_decay': 4.856878788514963e-05}. Best is trial 37 with value: 0.08025431632995605.
[I 2026-09-24 00:38:07,821] Trial 68 pruned.
[I 2026-09-24 00:38:22,246] Trial 69 pruned.
[I 2026-09-24 00:38:36,654] Trial 70 pruned.
[I 2026-09-24 00:38:47,743] Trial 71 pruned.
[I 2026-09-24 00:39:01,380] Trial 72 pruned.
[I 2026-09-24 00:39:12,531] Trial 73 pruned.
[I 2026-09-24 00:39:22,216] Trial 74 pruned.
[I 2026-09-24 00:39:51,892] Trial 75 finished with value: 0.09133988618850708 and parameters: {'hidden_layer': 45, 'learning_rate': 0.03579988920023469, 'momentum': 0.6738885792680369, 'weight_decay': 0.0002246960801256031}. Best is trial 37 with value: 0.08025431632995605.
[I 2026-09-24 00:40:05,213] Trial 76 pruned.
[I 2026-09-24 00:40:11,601] Trial 77 pruned.
[I 2026-09-24 00:40:22,469] Trial 78 pruned.
[I 2026-09-24 00:40:28,219] Trial 79 pruned.
[I 2026-09-24 00:40:28,229] A new study created in memory with name: no-name-64039ce6-2356-49cd-b863-f7a7d7a12385

{'hidden_layer': 86, 'learning_rate': 0.06537872898442752, 'momentum': 0.6081115610091297, 'weight_decay': 3.690268252998101e-05}
0.08025431632995605

[I 2026-09-24 00:41:04,510] Trial 0 finished with value: 0.09415929764509201 and parameters: {'hidden_layer': 14, 'learning_rate': 0.02003662082231219, 'momentum': 0.4817452269021503, 'weight_decay': 0.0031155167187036006, 'leaky_relu_alpha': 0.018289757852090232}. Best is trial 0 with value: 0.09415929764509201.
[I 2026-09-24 00:41:42,356] Trial 1 finished with value: 0.11860296875238419 and parameters: {'hidden_layer': 70, 'learning_rate': 0.0009103905070240532, 'momentum': 0.9083048877158582, 'weight_decay': 8.56329388990229e-05, 'leaky_relu_alpha': 0.0323699870390707}. Best is trial 0 with value: 0.09415929764509201.
[I 2026-09-24 00:42:24,089] Trial 2 finished with value: 0.3016667664051056 and parameters: {'hidden_layer': 124, 'learning_rate': 0.00021835790380279402, 'momentum': 0.7719613952558392, 'weight_decay': 0.006222635739941728, 'leaky_relu_alpha': 0.007826936980817059}. Best is trial 0 with value: 0.09415929764509201.
[I 2026-09-24 00:43:05,409] Trial 3 finished with value: 0.3428184986114502 and parameters: {'hidden_layer': 20, 'learning_rate': 0.0010606467823582764, 'momentum': 0.14701676673717934, 'weight_decay': 1.1787303398800716e-06, 'leaky_relu_alpha': 0.003391400335723789}. Best is trial 0 with value: 0.09415929764509201.
[I 2026-09-24 00:43:23,462] Trial 4 finished with value: 0.11150447279214859 and parameters: {'hidden_layer': 35, 'learning_rate': 0.0037745380848991446, 'momentum': 0.9604981972421706, 'weight_decay': 9.29480770579053e-05, 'leaky_relu_alpha': 0.00735424878946643}. Best is trial 0 with value: 0.09415929764509201.
[I 2026-09-24 00:44:05,446] Trial 5 finished with value: 0.11016449332237244 and parameters: {'hidden_layer': 15, 'learning_rate': 0.021552682223249995, 'momentum': 0.026767946395560575, 'weight_decay': 1.108519013223936e-06, 'leaky_relu_alpha': 0.0039392504549118044}. Best is trial 0 with value: 0.09415929764509201.
[I 2026-09-24 00:44:38,234] Trial 6 finished with value: 0.09575599431991577 and parameters: {'hidden_layer': 125, 'learning_rate': 0.012998241373139144, 'momentum': 0.6432812868529345, 'weight_decay': 0.00021539742724387674, 'leaky_relu_alpha': 0.10232447669416524}. Best is trial 0 with value: 0.09415929764509201.
[I 2026-09-24 00:44:52,108] Trial 7 pruned.
[I 2026-09-24 00:45:12,552] Trial 8 finished with value: 0.09359285980463028 and parameters: {'hidden_layer': 67, 'learning_rate': 0.09936433241403907, 'momentum': 0.48915477289079995, 'weight_decay': 0.00813029175066173, 'leaky_relu_alpha': 0.04201668148180585}. Best is trial 8 with value: 0.09359285980463028.
[I 2026-09-24 00:45:26,391] Trial 9 pruned.
[I 2026-09-24 00:45:50,607] Trial 10 finished with value: 0.09148061275482178 and parameters: {'hidden_layer': 94, 'learning_rate': 0.08521197773124527, 'momentum': 0.3946529923637282, 'weight_decay': 2.5210254426677305e-05, 'leaky_relu_alpha': 0.05662945738731793}. Best is trial 10 with value: 0.09148061275482178.
[I 2026-09-24 00:46:14,481] Trial 11 finished with value: 0.0970284715294838 and parameters: {'hidden_layer': 98, 'learning_rate': 0.09654146021697387, 'momentum': 0.41107279501501476, 'weight_decay': 9.554863223898876e-06, 'leaky_relu_alpha': 0.05332476821368356}. Best is trial 10 with value: 0.09148061275482178.
[I 2026-09-24 00:46:35,167] Trial 12 finished with value: 0.09630342572927475 and parameters: {'hidden_layer': 90, 'learning_rate': 0.09209621151516614, 'momentum': 0.3248578191932693, 'weight_decay': 1.4597749513821992e-05, 'leaky_relu_alpha': 0.07517653981783647}. Best is trial 10 with value: 0.09148061275482178.
[I 2026-09-24 00:47:02,058] Trial 13 finished with value: 0.08884529024362564 and parameters: {'hidden_layer': 97, 'learning_rate': 0.04954634397601198, 'momentum': 0.3169018799066587, 'weight_decay': 1.8606407565286812e-05, 'leaky_relu_alpha': 0.22473540850202442}. Best is trial 13 with value: 0.08884529024362564.
[I 2026-09-24 00:47:33,696] Trial 14 finished with value: 0.08480110764503479 and parameters: {'hidden_layer': 100, 'learning_rate': 0.03444211495879301, 'momentum': 0.3013884286803438, 'weight_decay': 1.2322919712649885e-05, 'leaky_relu_alpha': 0.29338682781354725}. Best is trial 14 with value: 0.08480110764503479.
[I 2026-09-24 00:47:47,599] Trial 15 pruned.
[I 2026-09-24 00:48:01,711] Trial 16 pruned.
[I 2026-09-24 00:48:15,521] Trial 17 pruned.
[I 2026-09-24 00:48:52,381] Trial 18 finished with value: 0.09763666987419128 and parameters: {'hidden_layer': 54, 'learning_rate': 0.03657876906670283, 'momentum': 0.21367845503876137, 'weight_decay': 3.893842242131241e-06, 'leaky_relu_alpha': 0.1468087582030511}. Best is trial 14 with value: 0.08480110764503479.
[I 2026-09-24 00:49:06,163] Trial 19 pruned.
[I 2026-09-24 00:49:40,337] Trial 20 finished with value: 0.08794254064559937 and parameters: {'hidden_layer': 81, 'learning_rate': 0.03634742282167007, 'momentum': 0.2863732424740814, 'weight_decay': 2.800823071935923e-05, 'leaky_relu_alpha': 0.12318035835050126}. Best is trial 14 with value: 0.08480110764503479.
[I 2026-09-24 00:49:51,232] Trial 21 pruned.
[I 2026-09-24 00:50:05,603] Trial 22 pruned.
[I 2026-09-24 00:50:37,159] Trial 23 finished with value: 0.08550098538398743 and parameters: {'hidden_layer': 43, 'learning_rate': 0.04619732199604165, 'momentum': 0.2461477867282375, 'weight_decay': 5.515632519122536e-05, 'leaky_relu_alpha': 0.09411842708506445}. Best is trial 14 with value: 0.08480110764503479.
[I 2026-09-24 00:50:51,042] Trial 24 pruned.
[I 2026-09-24 00:51:03,128] Trial 25 pruned.
[I 2026-09-24 00:51:17,152] Trial 26 pruned.
[I 2026-09-24 00:51:31,197] Trial 27 pruned.
[I 2026-09-24 00:51:44,047] Trial 28 pruned.
[I 2026-09-24 00:52:06,919] Trial 29 finished with value: 0.09190672636032104 and parameters: {'hidden_layer': 8, 'learning_rate': 0.05476549158305473, 'momentum': 0.4406355478715356, 'weight_decay': 5.881506067662998e-05, 'leaky_relu_alpha': 0.01827153198774588}. Best is trial 14 with value: 0.08480110764503479.
[I 2026-09-24 00:52:21,003] Trial 30 pruned.
[I 2026-09-24 00:52:47,569] Trial 31 finished with value: 0.08427403122186661 and parameters: {'hidden_layer': 86, 'learning_rate': 0.05787943395502719, 'momentum': 0.3307962870053477, 'weight_decay': 1.5145407824407913e-05, 'leaky_relu_alpha': 0.2399923773575648}. Best is trial 31 with value: 0.08427403122186661.
[I 2026-09-24 00:53:20,378] Trial 32 finished with value: 0.09610439091920853 and parameters: {'hidden_layer': 86, 'learning_rate': 0.026553905396602177, 'momentum': 0.35647528694905606, 'weight_decay': 1.1390487023325973e-05, 'leaky_relu_alpha': 0.2867802916136815}. Best is trial 31 with value: 0.08427403122186661.
[I 2026-09-24 00:53:42,636] Trial 33 finished with value: 0.09749317169189453 and parameters: {'hidden_layer': 73, 'learning_rate': 0.06308820109937206, 'momentum': 0.2699463926707797, 'weight_decay': 0.00014021093008837702, 'leaky_relu_alpha': 0.18761001145017125}. Best is trial 31 with value: 0.08427403122186661.
[I 2026-09-24 00:53:56,750] Trial 34 pruned.
[I 2026-09-24 00:54:10,989] Trial 35 pruned.
[I 2026-09-24 00:54:20,520] Trial 36 pruned.
[I 2026-09-24 00:54:34,613] Trial 37 pruned.
[I 2026-09-24 00:55:03,271] Trial 38 finished with value: 0.09246712177991867 and parameters: {'hidden_layer': 103, 'learning_rate': 0.06410860829694616, 'momentum': 0.15450332155750524, 'weight_decay': 9.397819339896058e-05, 'leaky_relu_alpha': 0.2126459385525451}. Best is trial 31 with value: 0.08427403122186661.
[I 2026-09-24 00:55:17,226] Trial 39 pruned.
[I 2026-09-24 00:55:31,316] Trial 40 pruned.
[I 2026-09-24 00:55:45,548] Trial 41 pruned.
[I 2026-09-24 00:56:14,253] Trial 42 finished with value: 0.09526892751455307 and parameters: {'hidden_layer': 97, 'learning_rate': 0.0689206378016445, 'momentum': 0.1804066742955137, 'weight_decay': 1.4421861398713514e-05, 'leaky_relu_alpha': 0.2313065161555777}. Best is trial 31 with value: 0.08427403122186661.
[I 2026-09-24 00:56:28,424] Trial 43 pruned.
[I 2026-09-24 00:56:40,660] Trial 44 pruned.
[I 2026-09-24 00:57:08,436] Trial 45 finished with value: 0.09723278135061264 and parameters: {'hidden_layer': 95, 'learning_rate': 0.04694514369701524, 'momentum': 0.4936462022285168, 'weight_decay': 1.0951318024155081e-05, 'leaky_relu_alpha': 0.06337248794441122}. Best is trial 31 with value: 0.08427403122186661.
[I 2026-09-24 00:57:29,014] Trial 46 finished with value: 0.08687058091163635 and parameters: {'hidden_layer': 102, 'learning_rate': 0.07459398865749002, 'momentum': 0.4211262464751546, 'weight_decay': 1.8503361065171802e-05, 'leaky_relu_alpha': 0.1653108535884067}. Best is trial 31 with value: 0.08427403122186661.
[I 2026-09-24 00:57:55,148] Trial 47 finished with value: 0.08041799068450928 and parameters: {'hidden_layer': 103, 'learning_rate': 0.0749440102631014, 'momentum': 0.44792596729623424, 'weight_decay': 0.0001229915407432607, 'leaky_relu_alpha': 0.16447960966927988}. Best is trial 47 with value: 0.08041799068450928.
[I 2026-09-24 00:58:01,246] Trial 48 pruned.
[I 2026-09-24 00:58:09,472] Trial 49 pruned.
[I 2026-09-24 00:58:23,681] Trial 50 finished with value: 0.0908711850643158 and parameters: {'hidden_layer': 101, 'learning_rate': 0.06973192018843377, 'momentum': 0.7464956548679775, 'weight_decay': 4.5933367630700996e-05, 'leaky_relu_alpha': 0.2825144001565881}. Best is trial 47 with value: 0.08041799068450928.
[I 2026-09-24 00:58:37,965] Trial 51 pruned.
[I 2026-09-24 00:58:52,025] Trial 52 pruned.
[I 2026-09-24 00:59:22,788] Trial 53 finished with value: 0.09471610933542252 and parameters: {'hidden_layer': 85, 'learning_rate': 0.05666031856561942, 'momentum': 0.3793325729897966, 'weight_decay': 1.4071418493001322e-05, 'leaky_relu_alpha': 0.05130223376599948}. Best is trial 47 with value: 0.08041799068450928.
[I 2026-09-24 00:59:48,082] Trial 54 finished with value: 0.1002640351653099 and parameters: {'hidden_layer': 113, 'learning_rate': 0.07459552227692086, 'momentum': 0.4707641327769785, 'weight_decay': 0.00026349382439089036, 'leaky_relu_alpha': 0.09790452812502379}. Best is trial 47 with value: 0.08041799068450928.
[I 2026-09-24 01:00:01,913] Trial 55 pruned.
[I 2026-09-24 01:00:08,734] Trial 56 pruned.
[I 2026-09-24 01:00:22,411] Trial 57 pruned.
[I 2026-09-24 01:00:37,953] Trial 58 pruned.
[I 2026-09-24 01:00:53,456] Trial 59 pruned.
[I 2026-09-24 01:01:02,721] Trial 60 pruned.
[I 2026-09-24 01:01:10,769] Trial 61 pruned.
[I 2026-09-24 01:01:43,157] Trial 62 finished with value: 0.08988190442323685 and parameters: {'hidden_layer': 93, 'learning_rate': 0.05259227928006881, 'momentum': 0.3146365066134759, 'weight_decay': 3.3964351433667576e-05, 'leaky_relu_alpha': 0.2060865410623615}. Best is trial 47 with value: 0.08041799068450928.
[I 2026-09-24 01:01:49,945] Trial 63 pruned.
[I 2026-09-24 01:02:04,113] Trial 64 pruned.
[I 2026-09-24 01:02:34,146] Trial 65 finished with value: 0.09215482324361801 and parameters: {'hidden_layer': 107, 'learning_rate': 0.04524047754508218, 'momentum': 0.3850158503720953, 'weight_decay': 0.0002059099012870953, 'leaky_relu_alpha': 0.24751888164419494}. Best is trial 47 with value: 0.08041799068450928.
[I 2026-09-24 01:03:01,678] Trial 66 finished with value: 0.09380345791578293 and parameters: {'hidden_layer': 88, 'learning_rate': 0.05867857747975815, 'momentum': 0.33043691356397425, 'weight_decay': 9.315511108538101e-06, 'leaky_relu_alpha': 0.1929377007883344}. Best is trial 47 with value: 0.08041799068450928.
[I 2026-09-24 01:03:15,876] Trial 67 pruned.
[I 2026-09-24 01:03:20,782] Trial 68 pruned.
[I 2026-09-24 01:03:34,735] Trial 69 pruned.
[I 2026-09-24 01:03:48,788] Trial 70 pruned.
[I 2026-09-24 01:03:54,963] Trial 71 pruned.
[I 2026-09-24 01:04:08,406] Trial 72 pruned.
[I 2026-09-24 01:04:39,975] Trial 73 finished with value: 0.09043880552053452 and parameters: {'hidden_layer': 70, 'learning_rate': 0.06669489166379515, 'momentum': 0.12369601915129722, 'weight_decay': 7.793444991096536e-06, 'leaky_relu_alpha': 0.26053189038440294}. Best is trial 47 with value: 0.08041799068450928.
[I 2026-09-24 01:04:54,221] Trial 74 pruned.
[I 2026-09-24 01:05:08,739] Trial 75 pruned.
[I 2026-09-24 01:05:20,535] Trial 76 pruned.
[I 2026-09-24 01:05:34,678] Trial 77 pruned.
[I 2026-09-24 01:05:49,408] Trial 78 pruned.
[I 2026-09-24 01:06:18,469] Trial 79 finished with value: 0.08960036188364029 and parameters: {'hidden_layer': 95, 'learning_rate': 0.06135156058166087, 'momentum': 0.30303757830205347, 'weight_decay': 2.1920658751859116e-05, 'leaky_relu_alpha': 0.17228253322025586}. Best is trial 47 with value: 0.08041799068450928.
[I 2026-09-24 01:06:18,469] A new study created in memory with name: no-name-9a652936-a4fc-4991-a7dc-2c12812dad61

{'hidden_layer': 103, 'learning_rate': 0.0749440102631014, 'momentum': 0.44792596729623424, 'weight_decay': 0.0001229915407432607, 'leaky_relu_alpha': 0.16447960966927988}
0.08041799068450928

[I 2026-09-24 01:07:01,010] Trial 0 finished with value: 0.13194265961647034 and parameters: {'hidden_layer': 36, 'learning_rate': 0.0024884931500405547, 'momentum': 0.21040116714867907, 'weight_decay': 0.0016741099456020721, 'elu_alpha': 1.7279822670946412}. Best is trial 0 with value: 0.13194265961647034.
[I 2026-09-24 01:07:43,934] Trial 1 finished with value: 0.29474321007728577 and parameters: {'hidden_layer': 124, 'learning_rate': 0.00019665131132230184, 'momentum': 0.21561969293479344, 'weight_decay': 0.008664538042956358, 'elu_alpha': 1.7756750286710319}. Best is trial 0 with value: 0.13194265961647034.
[I 2026-09-24 01:08:26,370] Trial 2 finished with value: 0.23992149531841278 and parameters: {'hidden_layer': 42, 'learning_rate': 0.0007839409186013404, 'momentum': 0.265322983201015, 'weight_decay': 0.0002931153060866743, 'elu_alpha': 1.0975205313613343}. Best is trial 0 with value: 0.13194265961647034.
[I 2026-09-24 01:09:09,069] Trial 3 finished with value: 0.365963339805603 and parameters: {'hidden_layer': 116, 'learning_rate': 0.0003506470629912082, 'momentum': 0.11089765149227858, 'weight_decay': 6.184566435017893e-06, 'elu_alpha': 0.5617941511803674}. Best is trial 0 with value: 0.13194265961647034.
[I 2026-09-24 01:09:52,288] Trial 4 finished with value: 0.12118127942085266 and parameters: {'hidden_layer': 50, 'learning_rate': 0.0007714065113845235, 'momentum': 0.6569192719267257, 'weight_decay': 0.004809712920207118, 'elu_alpha': 1.9877588715387304}. Best is trial 4 with value: 0.12118127942085266.
[I 2026-09-24 01:10:34,769] Trial 5 finished with value: 0.10979986935853958 and parameters: {'hidden_layer': 8, 'learning_rate': 0.007872717420643131, 'momentum': 0.17147837360975537, 'weight_decay': 0.00030977526800360177, 'elu_alpha': 1.3051695275346045}. Best is trial 5 with value: 0.10979986935853958.
[I 2026-09-24 01:11:10,573] Trial 6 finished with value: 0.10381641238927841 and parameters: {'hidden_layer': 117, 'learning_rate': 0.025421375179196577, 'momentum': 0.22773300980530747, 'weight_decay': 0.0023752763147704787, 'elu_alpha': 0.7233182183908662}. Best is trial 6 with value: 0.10381641238927841.
[I 2026-09-24 01:11:25,279] Trial 7 finished with value: 0.11855289340019226 and parameters: {'hidden_layer': 9, 'learning_rate': 0.054927853613032415, 'momentum': 0.9620166680472733, 'weight_decay': 3.0581793648705075e-06, 'elu_alpha': 1.0398547024702331}. Best is trial 6 with value: 0.10381641238927841.
[I 2026-09-24 01:12:05,678] Trial 8 finished with value: 0.09578901529312134 and parameters: {'hidden_layer': 26, 'learning_rate': 0.010562340008380825, 'momentum': 0.3046861683267621, 'weight_decay': 0.002064726088592325, 'elu_alpha': 0.9808940363816705}. Best is trial 8 with value: 0.09578901529312134.
[I 2026-09-24 01:12:25,644] Trial 9 finished with value: 0.08521020412445068 and parameters: {'hidden_layer': 49, 'learning_rate': 0.0946047066147945, 'momentum': 0.40100476678233754, 'weight_decay': 0.002089871479790818, 'elu_alpha': 0.8526789488434952}. Best is trial 9 with value: 0.08521020412445068.
[I 2026-09-24 01:12:46,883] Trial 10 finished with value: 0.0876515582203865 and parameters: {'hidden_layer': 85, 'learning_rate': 0.09709553504185818, 'momentum': 0.5193171616618895, 'weight_decay': 3.685560516259268e-05, 'elu_alpha': 0.11385868723085213}. Best is trial 9 with value: 0.08521020412445068.
[I 2026-09-24 01:13:06,427] Trial 11 finished with value: 0.08523235470056534 and parameters: {'hidden_layer': 84, 'learning_rate': 0.08069396943320666, 'momentum': 0.5303715290555733, 'weight_decay': 2.025609702455389e-05, 'elu_alpha': 0.13966575703481152}. Best is trial 9 with value: 0.08521020412445068.
[I 2026-09-24 01:13:37,572] Trial 12 finished with value: 0.08972441405057907 and parameters: {'hidden_layer': 76, 'learning_rate': 0.02851931286689929, 'momentum': 0.49981251117742215, 'weight_decay': 2.2476247040482275e-05, 'elu_alpha': 0.2113999664698526}. Best is trial 9 with value: 0.08521020412445068.
[I 2026-09-24 01:13:51,375] Trial 13 finished with value: 0.09353970736265182 and parameters: {'hidden_layer': 95, 'learning_rate': 0.09216181746397067, 'momentum': 0.77093170493052, 'weight_decay': 0.000138730981569785, 'elu_alpha': 0.5903106469313562}. Best is trial 9 with value: 0.08521020412445068.
[I 2026-09-24 01:14:30,748] Trial 14 finished with value: 0.09191647917032242 and parameters: {'hidden_layer': 61, 'learning_rate': 0.017507654569111557, 'momentum': 0.3931187678102611, 'weight_decay': 1.4904289554060203e-05, 'elu_alpha': 0.3237301253414454}. Best is trial 9 with value: 0.08521020412445068.
[I 2026-09-24 01:15:11,753] Trial 15 finished with value: 0.10252714902162552 and parameters: {'hidden_layer': 65, 'learning_rate': 0.004214092779894066, 'momentum': 0.6213234453011324, 'weight_decay': 1.108687812538768e-06, 'elu_alpha': 1.389518396787615}. Best is trial 9 with value: 0.08521020412445068.
[I 2026-09-24 01:15:46,257] Trial 16 finished with value: 0.087249256670475 and parameters: {'hidden_layer': 99, 'learning_rate': 0.041095657017557546, 'momentum': 0.03173615973497573, 'weight_decay': 0.0006249786355621258, 'elu_alpha': 0.389319191483968}. Best is trial 9 with value: 0.08521020412445068.
[I 2026-09-24 01:15:59,478] Trial 17 pruned.
[I 2026-09-24 01:16:14,125] Trial 18 pruned.
[I 2026-09-24 01:16:41,345] Trial 19 finished with value: 0.08927368372678757 and parameters: {'hidden_layer': 100, 'learning_rate': 0.05721847600083698, 'momentum': 0.3677599328169459, 'weight_decay': 0.00011337517702834385, 'elu_alpha': 0.4641209501567306}. Best is trial 9 with value: 0.08521020412445068.
[I 2026-09-24 01:16:55,607] Trial 20 pruned.
[I 2026-09-24 01:17:05,844] Trial 21 pruned.
[I 2026-09-24 01:17:37,380] Trial 22 finished with value: 0.0970444604754448 and parameters: {'hidden_layer': 91, 'learning_rate': 0.0506537016005585, 'momentum': 0.007115053471313637, 'weight_decay': 0.0005426536106887753, 'elu_alpha': 0.263315225080497}. Best is trial 9 with value: 0.08521020412445068.
[I 2026-09-24 01:17:44,098] Trial 23 pruned.
[I 2026-09-24 01:17:59,244] Trial 24 finished with value: 0.09299711138010025 and parameters: {'hidden_layer': 107, 'learning_rate': 0.09885206431236059, 'momentum': 0.7585347088052825, 'weight_decay': 0.004246891224558779, 'elu_alpha': 0.10764129492480597}. Best is trial 9 with value: 0.08521020412445068.
[I 2026-09-24 01:18:05,588] Trial 25 pruned.
[I 2026-09-24 01:18:35,670] Trial 26 finished with value: 0.0912838950753212 and parameters: {'hidden_layer': 68, 'learning_rate': 0.06414288697863671, 'momentum': 0.10284629663443429, 'weight_decay': 0.0010203979168181244, 'elu_alpha': 0.4863845929155485}. Best is trial 9 with value: 0.08521020412445068.
[I 2026-09-24 01:19:02,922] Trial 27 finished with value: 0.08904645591974258 and parameters: {'hidden_layer': 110, 'learning_rate': 0.032497603031177644, 'momentum': 0.305997602020307, 'weight_decay': 0.00038650948801232217, 'elu_alpha': 0.9080332793749533}. Best is trial 9 with value: 0.08521020412445068.
[I 2026-09-24 01:19:31,614] Trial 28 finished with value: 0.0955803394317627 and parameters: {'hidden_layer': 52, 'learning_rate': 0.017590918330334424, 'momentum': 0.5877316294304955, 'weight_decay': 0.009094272916697517, 'elu_alpha': 1.2384498877388408}. Best is trial 9 with value: 0.08521020412445068.
[I 2026-09-24 01:20:05,291] Trial 29 finished with value: 0.08992785960435867 and parameters: {'hidden_layer': 39, 'learning_rate': 0.042766423524960094, 'momentum': 0.43729584137084804, 'weight_decay': 0.001577773114366525, 'elu_alpha': 0.21256734194656607}. Best is trial 9 with value: 0.08521020412445068.
[I 2026-09-24 01:20:17,424] Trial 30 pruned.
[I 2026-09-24 01:20:27,208] Trial 31 pruned.
[I 2026-09-24 01:20:45,470] Trial 32 finished with value: 0.08013296872377396 and parameters: {'hidden_layer': 94, 'learning_rate': 0.06622278642632293, 'momentum': 0.7208253099396412, 'weight_decay': 2.618721718157445e-05, 'elu_alpha': 0.36359999453362535}. Best is trial 32 with value: 0.08013296872377396.
[I 2026-09-24 01:20:49,955] Trial 33 pruned.
[I 2026-09-24 01:21:04,218] Trial 34 pruned.
[I 2026-09-24 01:21:27,489] Trial 35 finished with value: 0.085929274559021 and parameters: {'hidden_layer': 114, 'learning_rate': 0.03843906326694901, 'momentum': 0.711847200434091, 'weight_decay': 0.00018548953590266705, 'elu_alpha': 0.39471466622269924}. Best is trial 32 with value: 0.08013296872377396.
[I 2026-09-24 01:21:48,588] Trial 36 finished with value: 0.0976053774356842 and parameters: {'hidden_layer': 115, 'learning_rate': 0.06961680386822887, 'momentum': 0.5720207849364238, 'weight_decay': 1.2581444519399648e-05, 'elu_alpha': 0.535582695549504}. Best is trial 32 with value: 0.08013296872377396.
[I 2026-09-24 01:22:02,950] Trial 37 pruned.
[I 2026-09-24 01:22:21,516] Trial 38 finished with value: 0.09053651243448257 and parameters: {'hidden_layer': 107, 'learning_rate': 0.022563000090226906, 'momentum': 0.8406252784284494, 'weight_decay': 2.514987422850746e-05, 'elu_alpha': 0.72965406960109}. Best is trial 32 with value: 0.08013296872377396.
[I 2026-09-24 01:22:35,968] Trial 39 pruned.
[I 2026-09-24 01:23:08,876] Trial 40 finished with value: 0.10119297355413437 and parameters: {'hidden_layer': 46, 'learning_rate': 0.034516441890665654, 'momentum': 0.6098068390410861, 'weight_decay': 8.107840905354896e-06, 'elu_alpha': 0.22870879446070008}. Best is trial 32 with value: 0.08013296872377396.
[I 2026-09-24 01:23:31,630] Trial 41 finished with value: 0.08573547750711441 and parameters: {'hidden_layer': 100, 'learning_rate': 0.03961254088641952, 'momentum': 0.7037035756020728, 'weight_decay': 0.001280239065446017, 'elu_alpha': 0.3950854439565796}. Best is trial 32 with value: 0.08013296872377396.
[I 2026-09-24 01:23:47,844] Trial 42 finished with value: 0.08562012761831284 and parameters: {'hidden_layer': 111, 'learning_rate': 0.06793678641050449, 'momentum': 0.6941754024282281, 'weight_decay': 0.0014356564833096883, 'elu_alpha': 0.42073807532866103}. Best is trial 32 with value: 0.08013296872377396.
[I 2026-09-24 01:24:05,229] Trial 43 finished with value: 0.08917389065027237 and parameters: {'hidden_layer': 31, 'learning_rate': 0.0724666299010266, 'momentum': 0.6684343877007866, 'weight_decay': 0.0016020618418201656, 'elu_alpha': 0.5414227123467663}. Best is trial 32 with value: 0.08013296872377396.
[I 2026-09-24 01:24:21,090] Trial 44 finished with value: 0.0898839607834816 and parameters: {'hidden_layer': 16, 'learning_rate': 0.051782553354607457, 'momentum': 0.81851939500302, 'weight_decay': 0.00294565652256327, 'elu_alpha': 0.6292346396217678}. Best is trial 32 with value: 0.08013296872377396.
[I 2026-09-24 01:24:35,818] Trial 45 finished with value: 0.08839700371026993 and parameters: {'hidden_layer': 104, 'learning_rate': 0.07644353310423761, 'momentum': 0.7404839078176462, 'weight_decay': 0.006000606399348762, 'elu_alpha': 0.293749773965448}. Best is trial 32 with value: 0.08013296872377396.
[I 2026-09-24 01:24:50,258] Trial 46 pruned.
[I 2026-09-24 01:24:56,207] Trial 47 pruned.
[I 2026-09-24 01:25:10,521] Trial 48 pruned.
[I 2026-09-24 01:25:20,137] Trial 49 pruned.
[I 2026-09-24 01:25:53,844] Trial 50 finished with value: 0.09005236625671387 and parameters: {'hidden_layer': 97, 'learning_rate': 0.05065284369927113, 'momentum': 0.2710444254374217, 'weight_decay': 2.1022033189623887e-05, 'elu_alpha': 0.17805720315465226}. Best is trial 32 with value: 0.08013296872377396.
[I 2026-09-24 01:26:04,635] Trial 51 pruned.
[I 2026-09-24 01:26:23,350] Trial 52 finished with value: 0.08781226724386215 and parameters: {'hidden_layer': 125, 'learning_rate': 0.07991570077194092, 'momentum': 0.7279997605281003, 'weight_decay': 0.00027486612960118294, 'elu_alpha': 0.3836194458299078}. Best is trial 32 with value: 0.08013296872377396.
[I 2026-09-24 01:26:43,718] Trial 53 finished with value: 0.08013727515935898 and parameters: {'hidden_layer': 92, 'learning_rate': 0.04776912969610625, 'momentum': 0.8024818863818508, 'weight_decay': 0.001316903650774306, 'elu_alpha': 0.29746429408686453}. Best is trial 32 with value: 0.08013296872377396.
[I 2026-09-24 01:27:00,069] Trial 54 finished with value: 0.083135686814785 and parameters: {'hidden_layer': 92, 'learning_rate': 0.05239540503568381, 'momentum': 0.8187362976495193, 'weight_decay': 0.001280073344852934, 'elu_alpha': 0.2882804465356391}. Best is trial 32 with value: 0.08013296872377396.
[I 2026-09-24 01:27:05,831] Trial 55 pruned.
[I 2026-09-24 01:27:11,275] Trial 56 pruned.
[I 2026-09-24 01:27:26,757] Trial 57 finished with value: 0.08820077776908875 and parameters: {'hidden_layer': 73, 'learning_rate': 0.0277359220475342, 'momentum': 0.8827368236835097, 'weight_decay': 0.0008309792283403438, 'elu_alpha': 0.26711339492811537}. Best is trial 32 with value: 0.08013296872377396.
[I 2026-09-24 01:27:31,748] Trial 58 pruned.
[I 2026-09-24 01:27:42,060] Trial 59 pruned.
[I 2026-09-24 01:27:55,735] Trial 60 pruned.
[I 2026-09-24 01:28:14,979] Trial 61 finished with value: 0.08408969640731812 and parameters: {'hidden_layer': 104, 'learning_rate': 0.044071611382002364, 'momentum': 0.7970293555931232, 'weight_decay': 0.0013152520420441367, 'elu_alpha': 0.4072410627396896}. Best is trial 32 with value: 0.08013296872377396.
[I 2026-09-24 01:28:20,408] Trial 62 pruned.
[I 2026-09-24 01:28:30,792] Trial 63 pruned.
[I 2026-09-24 01:28:51,870] Trial 64 finished with value: 0.08227758854627609 and parameters: {'hidden_layer': 110, 'learning_rate': 0.06211049181447781, 'momentum': 0.7525976922126181, 'weight_decay': 0.002093723883735717, 'elu_alpha': 0.2943078797948232}. Best is trial 32 with value: 0.08013296872377396.
[I 2026-09-24 01:29:01,742] Trial 65 pruned.
[I 2026-09-24 01:29:16,430] Trial 66 pruned.
[I 2026-09-24 01:29:20,315] Trial 67 pruned.
[I 2026-09-24 01:29:41,334] Trial 68 finished with value: 0.09309541434049606 and parameters: {'hidden_layer': 81, 'learning_rate': 0.03091634218575729, 'momentum': 0.8492317895220342, 'weight_decay': 0.0009357663731442039, 'elu_alpha': 0.34663510586958485}. Best is trial 32 with value: 0.08013296872377396.
[I 2026-09-24 01:29:55,878] Trial 69 pruned.
[I 2026-09-24 01:30:00,450] Trial 70 pruned.
[I 2026-09-24 01:30:16,407] Trial 71 finished with value: 0.08537918329238892 and parameters: {'hidden_layer': 111, 'learning_rate': 0.06006703228342565, 'momentum': 0.8220503907972648, 'weight_decay': 0.0017184329642629661, 'elu_alpha': 0.23093460935166105}. Best is trial 32 with value: 0.08013296872377396.
[I 2026-09-24 01:30:23,358] Trial 72 pruned.
[I 2026-09-24 01:30:28,922] Trial 73 pruned.
[I 2026-09-24 01:30:46,369] Trial 74 finished with value: 0.08954095095396042 and parameters: {'hidden_layer': 103, 'learning_rate': 0.0672923509724906, 'momentum': 0.8326614009359248, 'weight_decay': 0.0005492190255339795, 'elu_alpha': 0.17091345297431007}. Best is trial 32 with value: 0.08013296872377396.
[I 2026-09-24 01:31:01,738] Trial 75 finished with value: 0.0877985954284668 and parameters: {'hidden_layer': 88, 'learning_rate': 0.07956892878865655, 'momentum': 0.7807184168543372, 'weight_decay': 5.259067429775468e-05, 'elu_alpha': 0.2699675790339667}. Best is trial 32 with value: 0.08013296872377396.
[I 2026-09-24 01:31:06,056] Trial 76 pruned.
[I 2026-09-24 01:31:20,506] Trial 77 pruned.
[I 2026-09-24 01:31:43,730] Trial 78 finished with value: 0.08519897609949112 and parameters: {'hidden_layer': 114, 'learning_rate': 0.05779989637951293, 'momentum': 0.3922809694037037, 'weight_decay': 0.0010996394460234785, 'elu_alpha': 0.6702008875425078}. Best is trial 32 with value: 0.08013296872377396.
[I 2026-09-24 01:31:58,394] Trial 79 pruned.
[I 2026-09-24 01:31:58,394] A new study created in memory with name: no-name-28217190-bf80-4132-b4e2-5aa314ecb373

{'hidden_layer': 94, 'learning_rate': 0.06622278642632293, 'momentum': 0.7208253099396412, 'weight_decay': 2.618721718157445e-05, 'elu_alpha': 0.36359999453362535}
0.08013296872377396

[I 2026-09-24 01:32:36,998] Trial 0 finished with value: 0.09930193424224854 and parameters: {'hidden_layer': 78, 'learning_rate': 0.004067919586395305, 'momentum': 0.9114221390770122, 'weight_decay': 0.000176375082788953}. Best is trial 0 with value: 0.09930193424224854.
[I 2026-09-24 01:33:20,088] Trial 1 finished with value: 0.18363851308822632 and parameters: {'hidden_layer': 19, 'learning_rate': 0.0020548499190597555, 'momentum': 0.5544956684903524, 'weight_decay': 2.3480733385293147e-05}. Best is trial 0 with value: 0.09930193424224854.
[I 2026-09-24 01:34:04,068] Trial 2 finished with value: 0.11935538798570633 and parameters: {'hidden_layer': 56, 'learning_rate': 0.005328192677086844, 'momentum': 0.5794305072752525, 'weight_decay': 0.0001677576227574097}. Best is trial 0 with value: 0.09930193424224854.
[I 2026-09-24 01:34:47,430] Trial 3 finished with value: 0.12406409531831741 and parameters: {'hidden_layer': 34, 'learning_rate': 0.002472504842041179, 'momentum': 0.826331012598117, 'weight_decay': 7.683462903251824e-05}. Best is trial 0 with value: 0.09930193424224854.
[I 2026-09-24 01:35:28,161] Trial 4 finished with value: 0.26071926951408386 and parameters: {'hidden_layer': 42, 'learning_rate': 0.001507747713706671, 'momentum': 0.03761942484509584, 'weight_decay': 5.366115498310626e-06}. Best is trial 0 with value: 0.09930193424224854.
[I 2026-09-24 01:36:00,070] Trial 5 finished with value: 0.09515884518623352 and parameters: {'hidden_layer': 83, 'learning_rate': 0.04115952157769342, 'momentum': 0.3781185885814086, 'weight_decay': 0.0009427224127624604}. Best is trial 5 with value: 0.09515884518623352.
[I 2026-09-24 01:36:15,023] Trial 6 pruned.
[I 2026-09-24 01:36:52,422] Trial 7 finished with value: 0.09755482524633408 and parameters: {'hidden_layer': 9, 'learning_rate': 0.03619866292981783, 'momentum': 0.15421025165658328, 'weight_decay': 0.00021888337908328704}. Best is trial 5 with value: 0.09515884518623352.
[I 2026-09-24 01:37:07,131] Trial 8 pruned.
[I 2026-09-24 01:37:51,081] Trial 9 finished with value: 0.11817147582769394 and parameters: {'hidden_layer': 118, 'learning_rate': 0.006595024482451029, 'momentum': 0.2905276010363006, 'weight_decay': 0.00019371665618565467}. Best is trial 5 with value: 0.09515884518623352.
[I 2026-09-24 01:38:05,845] Trial 10 pruned.
[I 2026-09-24 01:38:34,409] Trial 11 finished with value: 0.09597021341323853 and parameters: {'hidden_layer': 91, 'learning_rate': 0.08887341685084255, 'momentum': 0.08469510758717734, 'weight_decay': 0.002546145058995726}. Best is trial 5 with value: 0.09515884518623352.
[I 2026-09-24 01:38:57,063] Trial 12 finished with value: 0.0963728204369545 and parameters: {'hidden_layer': 91, 'learning_rate': 0.08589791330573, 'momentum': 0.32991479954387365, 'weight_decay': 0.00901635450223609}. Best is trial 5 with value: 0.09515884518623352.
[I 2026-09-24 01:39:40,362] Trial 13 finished with value: 0.09411691874265671 and parameters: {'hidden_layer': 126, 'learning_rate': 0.033273339729762805, 'momentum': 0.14892224723097985, 'weight_decay': 0.0016172744372867794}. Best is trial 13 with value: 0.09411691874265671.
[I 2026-09-24 01:39:51,797] Trial 14 pruned.
[I 2026-09-24 01:40:35,838] Trial 15 finished with value: 0.09700778126716614 and parameters: {'hidden_layer': 108, 'learning_rate': 0.019545125083144013, 'momentum': 0.40118792633356065, 'weight_decay': 0.001057614489899509}. Best is trial 13 with value: 0.09411691874265671.
[I 2026-09-24 01:40:50,844] Trial 16 pruned.
[I 2026-09-24 01:41:05,474] Trial 17 pruned.
[I 2026-09-24 01:41:20,539] Trial 18 pruned.
[I 2026-09-24 01:41:41,269] Trial 19 finished with value: 0.08757147938013077 and parameters: {'hidden_layer': 111, 'learning_rate': 0.042614586509841366, 'momentum': 0.6663616694099785, 'weight_decay': 0.002764044488862338}. Best is trial 19 with value: 0.08757147938013077.
[I 2026-09-24 01:41:54,029] Trial 20 pruned.
[I 2026-09-24 01:42:00,975] Trial 21 pruned.
[I 2026-09-24 01:42:29,206] Trial 22 finished with value: 0.09646198153495789 and parameters: {'hidden_layer': 113, 'learning_rate': 0.05611442072388954, 'momentum': 0.44205991922414667, 'weight_decay': 0.0004258265174875486}. Best is trial 19 with value: 0.08757147938013077.
[I 2026-09-24 01:42:54,900] Trial 23 finished with value: 0.08818332105875015 and parameters: {'hidden_layer': 119, 'learning_rate': 0.0265582069676524, 'momentum': 0.8171542795044581, 'weight_decay': 0.00633388810706177}. Best is trial 19 with value: 0.08757147938013077.
[I 2026-09-24 01:42:59,129] Trial 24 pruned.
[I 2026-09-24 01:43:13,877] Trial 25 pruned.
[I 2026-09-24 01:43:52,465] Trial 26 finished with value: 0.08830294758081436 and parameters: {'hidden_layer': 122, 'learning_rate': 0.010441308982406756, 'momentum': 0.8043312899460792, 'weight_decay': 0.0018065872914536914}. Best is trial 19 with value: 0.08757147938013077.
[I 2026-09-24 01:43:59,161] Trial 27 pruned.
[I 2026-09-24 01:44:05,431] Trial 28 pruned.
[I 2026-09-24 01:44:10,910] Trial 29 pruned.
[I 2026-09-24 01:44:25,503] Trial 30 pruned.
[I 2026-09-24 01:44:53,493] Trial 31 finished with value: 0.0989798828959465 and parameters: {'hidden_layer': 123, 'learning_rate': 0.024140762735338505, 'momentum': 0.7707732079739985, 'weight_decay': 0.0019353773554896423}. Best is trial 19 with value: 0.08757147938013077.
[I 2026-09-24 01:45:11,624] Trial 32 finished with value: 0.08508116751909256 and parameters: {'hidden_layer': 128, 'learning_rate': 0.054663764652600484, 'momentum': 0.8403186233353104, 'weight_decay': 0.001151266677981886}. Best is trial 32 with value: 0.08508116751909256.
[I 2026-09-24 01:45:27,592] Trial 33 finished with value: 0.09424611181020737 and parameters: {'hidden_layer': 116, 'learning_rate': 0.06043204235907204, 'momentum': 0.8553673671251432, 'weight_decay': 0.006982881631848455}. Best is trial 32 with value: 0.08508116751909256.
[I 2026-09-24 01:45:42,506] Trial 34 pruned.
[I 2026-09-24 01:45:57,501] Trial 35 pruned.
[I 2026-09-24 01:46:09,942] Trial 36 finished with value: 0.09208473563194275 and parameters: {'hidden_layer': 96, 'learning_rate': 0.050177780472646524, 'momentum': 0.953775212342933, 'weight_decay': 0.0031375088464357984}. Best is trial 32 with value: 0.08508116751909256.
[I 2026-09-24 01:46:35,127] Trial 37 finished with value: 0.10136006027460098 and parameters: {'hidden_layer': 54, 'learning_rate': 0.02414048634315925, 'momentum': 0.8470674186655518, 'weight_decay': 0.005238824695460825}. Best is trial 32 with value: 0.08508116751909256.
[I 2026-09-24 01:47:12,417] Trial 38 finished with value: 0.08870307356119156 and parameters: {'hidden_layer': 112, 'learning_rate': 0.004605328474169028, 'momentum': 0.9309526913738517, 'weight_decay': 0.0006362701125795708}. Best is trial 32 with value: 0.08508116751909256.
[I 2026-09-24 01:47:37,132] Trial 39 finished with value: 0.0972973108291626 and parameters: {'hidden_layer': 23, 'learning_rate': 0.09789497085600053, 'momentum': 0.5915924223375245, 'weight_decay': 0.001334447377650134}. Best is trial 32 with value: 0.08508116751909256.
[I 2026-09-24 01:47:51,681] Trial 40 pruned.
[I 2026-09-24 01:48:18,600] Trial 41 finished with value: 0.08833698183298111 and parameters: {'hidden_layer': 112, 'learning_rate': 0.005345362446619659, 'momentum': 0.9366589486934774, 'weight_decay': 0.0006761627964640261}. Best is trial 32 with value: 0.08508116751909256.
[I 2026-09-24 01:48:33,263] Trial 42 pruned.
[I 2026-09-24 01:48:48,093] Trial 43 pruned.
[I 2026-09-24 01:49:02,500] Trial 44 pruned.
[I 2026-09-24 01:49:08,128] Trial 45 pruned.
[I 2026-09-24 01:49:18,489] Trial 46 pruned.
[I 2026-09-24 01:49:33,585] Trial 47 pruned.
[I 2026-09-24 01:49:49,298] Trial 48 finished with value: 0.0924714207649231 and parameters: {'hidden_layer': 36, 'learning_rate': 0.0271708620388563, 'momentum': 0.9282058101662136, 'weight_decay': 0.0002602797599419184}. Best is trial 32 with value: 0.08508116751909256.
[I 2026-09-24 01:50:04,381] Trial 49 pruned.
[I 2026-09-24 01:50:09,242] Trial 50 pruned.
[I 2026-09-24 01:50:42,573] Trial 51 finished with value: 0.09605491161346436 and parameters: {'hidden_layer': 114, 'learning_rate': 0.0048265782592477255, 'momentum': 0.9307916202515184, 'weight_decay': 0.0004930283789792071}. Best is trial 32 with value: 0.08508116751909256.
[I 2026-09-24 01:50:57,298] Trial 52 pruned.
[I 2026-09-24 01:51:21,974] Trial 53 finished with value: 0.09066620469093323 and parameters: {'hidden_layer': 124, 'learning_rate': 0.00847111344040383, 'momentum': 0.9311523328806663, 'weight_decay': 0.001295000211092977}. Best is trial 32 with value: 0.08508116751909256.
[I 2026-09-24 01:51:37,455] Trial 54 pruned.
[I 2026-09-24 01:51:44,471] Trial 55 pruned.
[I 2026-09-24 01:52:00,962] Trial 56 finished with value: 0.08726008981466293 and parameters: {'hidden_layer': 102, 'learning_rate': 0.04640175429180764, 'momentum': 0.8517739638461107, 'weight_decay': 0.0012544433878206587}. Best is trial 32 with value: 0.08508116751909256.
[I 2026-09-24 01:52:18,434] Trial 57 finished with value: 0.08347045630216599 and parameters: {'hidden_layer': 72, 'learning_rate': 0.04532427609220552, 'momentum': 0.8632451289416091, 'weight_decay': 0.003071764563711919}. Best is trial 57 with value: 0.08347045630216599.
[I 2026-09-24 01:52:41,201] Trial 58 finished with value: 0.0854121670126915 and parameters: {'hidden_layer': 75, 'learning_rate': 0.046789145296015855, 'momentum': 0.6311781491507816, 'weight_decay': 0.0033658709912022127}. Best is trial 57 with value: 0.08347045630216599.
[I 2026-09-24 01:52:47,251] Trial 59 pruned.
[I 2026-09-24 01:52:57,225] Trial 60 pruned.
[I 2026-09-24 01:53:29,959] Trial 61 finished with value: 0.09069526940584183 and parameters: {'hidden_layer': 50, 'learning_rate': 0.032678302483479735, 'momentum': 0.7356517430056645, 'weight_decay': 0.009325322116435062}. Best is trial 57 with value: 0.08347045630216599.
[I 2026-09-24 01:54:01,712] Trial 62 finished with value: 0.09100683778524399 and parameters: {'hidden_layer': 70, 'learning_rate': 0.03469814869681519, 'momentum': 0.6693017980576896, 'weight_decay': 0.0013466596083079186}. Best is trial 57 with value: 0.08347045630216599.
[I 2026-09-24 01:54:28,467] Trial 63 finished with value: 0.09818518906831741 and parameters: {'hidden_layer': 85, 'learning_rate': 0.05263944924699048, 'momentum': 0.7009374920450436, 'weight_decay': 0.002902511529110097}. Best is trial 57 with value: 0.08347045630216599.
[I 2026-09-24 01:54:47,906] Trial 64 finished with value: 0.08678077906370163 and parameters: {'hidden_layer': 73, 'learning_rate': 0.03967475656509567, 'momentum': 0.8435907258635217, 'weight_decay': 0.00629605558375538}. Best is trial 57 with value: 0.08347045630216599.
[I 2026-09-24 01:55:02,662] Trial 65 pruned.
[I 2026-09-24 01:55:08,220] Trial 66 pruned.
[I 2026-09-24 01:55:23,235] Trial 67 pruned.
[I 2026-09-24 01:55:53,077] Trial 68 finished with value: 0.09694264084100723 and parameters: {'hidden_layer': 82, 'learning_rate': 0.027911873617239843, 'momentum': 0.776379174742767, 'weight_decay': 0.008474535528671718}. Best is trial 57 with value: 0.08347045630216599.
[I 2026-09-24 01:56:17,079] Trial 69 finished with value: 0.08696728944778442 and parameters: {'hidden_layer': 73, 'learning_rate': 0.08489227304820456, 'momentum': 0.6380982547128975, 'weight_decay': 0.0037878530577109357}. Best is trial 57 with value: 0.08347045630216599.
[I 2026-09-24 01:56:42,326] Trial 70 finished with value: 0.08463802933692932 and parameters: {'hidden_layer': 92, 'learning_rate': 0.09759707052191324, 'momentum': 0.5783938157063713, 'weight_decay': 0.0023691592428833675}. Best is trial 57 with value: 0.08347045630216599.
[I 2026-09-24 01:57:05,486] Trial 71 finished with value: 0.09055326133966446 and parameters: {'hidden_layer': 73, 'learning_rate': 0.0791268874780371, 'momentum': 0.5549831725127795, 'weight_decay': 0.0023472829957013547}. Best is trial 57 with value: 0.08347045630216599.
[I 2026-09-24 01:57:14,710] Trial 72 pruned.
[I 2026-09-24 01:57:42,357] Trial 73 finished with value: 0.10161891579627991 and parameters: {'hidden_layer': 72, 'learning_rate': 0.055220225540623925, 'momentum': 0.5572611277219925, 'weight_decay': 0.001339140771439724}. Best is trial 57 with value: 0.08347045630216599.
[I 2026-09-24 01:58:08,416] Trial 74 finished with value: 0.0907665267586708 and parameters: {'hidden_layer': 92, 'learning_rate': 0.09463928198592245, 'momentum': 0.4876145720810352, 'weight_decay': 0.004973282613527141}. Best is trial 57 with value: 0.08347045630216599.
[I 2026-09-24 01:58:16,449] Trial 75 pruned.
[I 2026-09-24 01:58:45,120] Trial 76 finished with value: 0.0871606171131134 and parameters: {'hidden_layer': 81, 'learning_rate': 0.06329890248435248, 'momentum': 0.45361375207229226, 'weight_decay': 0.0029891994677369695}. Best is trial 57 with value: 0.08347045630216599.
[I 2026-09-24 01:59:08,879] Trial 77 finished with value: 0.08775050193071365 and parameters: {'hidden_layer': 85, 'learning_rate': 0.07220410386164497, 'momentum': 0.4471833195692241, 'weight_decay': 0.0010161302475358194}. Best is trial 57 with value: 0.08347045630216599.
[I 2026-09-24 01:59:40,048] Trial 78 finished with value: 0.08782384544610977 and parameters: {'hidden_layer': 79, 'learning_rate': 0.05977615814793818, 'momentum': 0.35739344475026036, 'weight_decay': 0.003325334565593844}. Best is trial 57 with value: 0.08347045630216599.
[I 2026-09-24 01:59:55,109] Trial 79 pruned.
[I 2026-09-24 01:59:55,113] A new study created in memory with name: no-name-4ed22ccc-2865-44ac-9030-2ad4c0fd5eb7

{'hidden_layer': 72, 'learning_rate': 0.04532427609220552, 'momentum': 0.8632451289416091, 'weight_decay': 0.003071764563711919}
0.08347045630216599

[I 2026-09-24 02:00:40,607] Trial 0 finished with value: 0.26065942645072937 and parameters: {'hidden_layer': 68, 'learning_rate': 0.000362631377812991, 'momentum': 0.7553253189771545, 'weight_decay': 6.522504119075133e-05}. Best is trial 0 with value: 0.26065942645072937.
[I 2026-09-24 02:01:25,761] Trial 1 finished with value: 0.210139200091362 and parameters: {'hidden_layer': 11, 'learning_rate': 0.0006641918231801516, 'momentum': 0.8662309254933128, 'weight_decay': 7.406881922559667e-05}. Best is trial 1 with value: 0.210139200091362.
[I 2026-09-24 02:02:10,717] Trial 2 finished with value: 0.11104544252157211 and parameters: {'hidden_layer': 23, 'learning_rate': 0.009976479865227471, 'momentum': 0.4792395964277038, 'weight_decay': 5.01920849017281e-06}. Best is trial 2 with value: 0.11104544252157211.
[I 2026-09-24 02:02:56,122] Trial 3 finished with value: 0.13400201499462128 and parameters: {'hidden_layer': 45, 'learning_rate': 0.007218203392725648, 'momentum': 0.2921992305043731, 'weight_decay': 0.00027257730745606514}. Best is trial 2 with value: 0.11104544252157211.
[I 2026-09-24 02:03:10,097] Trial 4 finished with value: 0.09992238879203796 and parameters: {'hidden_layer': 51, 'learning_rate': 0.04639664103245827, 'momentum': 0.906099156494064, 'weight_decay': 0.00017571430591347708}. Best is trial 4 with value: 0.09992238879203796.
[I 2026-09-24 02:03:41,239] Trial 5 finished with value: 0.09057583659887314 and parameters: {'hidden_layer': 99, 'learning_rate': 0.017557269227078467, 'momentum': 0.714754390382082, 'weight_decay': 3.356477679026888e-05}. Best is trial 5 with value: 0.09057583659887314.
[I 2026-09-24 02:03:56,635] Trial 6 pruned.
[I 2026-09-24 02:04:24,477] Trial 7 finished with value: 0.09464722126722336 and parameters: {'hidden_layer': 104, 'learning_rate': 0.03063768416525156, 'momentum': 0.5499776760592981, 'weight_decay': 1.2163107376429705e-05}. Best is trial 5 with value: 0.09057583659887314.
[I 2026-09-24 02:05:10,266] Trial 8 finished with value: 0.10047369450330734 and parameters: {'hidden_layer': 43, 'learning_rate': 0.023919249075114404, 'momentum': 0.13639174918636765, 'weight_decay': 0.004805867995370051}. Best is trial 5 with value: 0.09057583659887314.
[I 2026-09-24 02:05:25,427] Trial 9 pruned.
[I 2026-09-24 02:05:43,311] Trial 10 pruned.
[I 2026-09-24 02:06:08,027] Trial 11 finished with value: 0.0936383381485939 and parameters: {'hidden_layer': 112, 'learning_rate': 0.08771313218054283, 'momentum': 0.47476368495165594, 'weight_decay': 8.474205248715045e-06}. Best is trial 5 with value: 0.09057583659887314.
[I 2026-09-24 02:06:35,575] Trial 12 finished with value: 0.09712108224630356 and parameters: {'hidden_layer': 93, 'learning_rate': 0.09948127663115713, 'momentum': 0.3799717930288329, 'weight_decay': 1.4965129988473722e-05}. Best is trial 5 with value: 0.09057583659887314.
[I 2026-09-24 02:06:55,458] Trial 13 finished with value: 0.08738011121749878 and parameters: {'hidden_layer': 127, 'learning_rate': 0.0978418136113342, 'momentum': 0.6582638205896616, 'weight_decay': 2.5436668759800875e-05}. Best is trial 13 with value: 0.08738011121749878.
[I 2026-09-24 02:07:37,925] Trial 14 finished with value: 0.09719869494438171 and parameters: {'hidden_layer': 88, 'learning_rate': 0.0135403408247025, 'momentum': 0.6860453167585084, 'weight_decay': 0.0004657774111492697}. Best is trial 13 with value: 0.08738011121749878.
[I 2026-09-24 02:07:53,101] Trial 15 pruned.
[I 2026-09-24 02:07:58,099] Trial 16 pruned.
[I 2026-09-24 02:08:13,515] Trial 17 pruned.
[I 2026-09-24 02:08:28,655] Trial 18 pruned.
[I 2026-09-24 02:08:43,789] Trial 19 pruned.
[I 2026-09-24 02:09:09,458] Trial 20 finished with value: 0.09457004070281982 and parameters: {'hidden_layer': 114, 'learning_rate': 0.05433678013649507, 'momentum': 0.2978790398685594, 'weight_decay': 0.0012033860723586621}. Best is trial 13 with value: 0.08738011121749878.
[I 2026-09-24 02:09:15,734] Trial 21 pruned.
[I 2026-09-24 02:09:42,398] Trial 22 finished with value: 0.08723077923059464 and parameters: {'hidden_layer': 96, 'learning_rate': 0.07242752065722743, 'momentum': 0.6323233680699304, 'weight_decay': 2.38669868943175e-05}. Best is trial 22 with value: 0.08723077923059464.
[I 2026-09-24 02:09:49,501] Trial 23 pruned.
[I 2026-09-24 02:10:17,530] Trial 24 finished with value: 0.08784160763025284 and parameters: {'hidden_layer': 76, 'learning_rate': 0.01650684922197055, 'momentum': 0.8308891061146878, 'weight_decay': 0.00012664050615424782}. Best is trial 22 with value: 0.08723077923059464.
[I 2026-09-24 02:10:25,756] Trial 25 pruned.
[I 2026-09-24 02:10:45,584] Trial 26 finished with value: 0.09214191883802414 and parameters: {'hidden_layer': 77, 'learning_rate': 0.06002036541762325, 'momentum': 0.8118891402271081, 'weight_decay': 0.0002065461390976817}. Best is trial 22 with value: 0.08723077923059464.
[I 2026-09-24 02:11:18,940] Trial 27 finished with value: 0.09045812487602234 and parameters: {'hidden_layer': 59, 'learning_rate': 0.033704157942247896, 'momentum': 0.5961740172435401, 'weight_decay': 9.144194278354101e-05}. Best is trial 22 with value: 0.08723077923059464.
[I 2026-09-24 02:11:23,753] Trial 28 pruned.
[I 2026-09-24 02:11:30,075] Trial 29 pruned.
[I 2026-09-24 02:11:45,189] Trial 30 pruned.
[I 2026-09-24 02:12:20,629] Trial 31 finished with value: 0.09372038394212723 and parameters: {'hidden_layer': 59, 'learning_rate': 0.03234883859533675, 'momentum': 0.6028698430103239, 'weight_decay': 9.392733029359682e-05}. Best is trial 22 with value: 0.08723077923059464.
[I 2026-09-24 02:12:32,769] Trial 32 pruned.
[I 2026-09-24 02:12:54,579] Trial 33 finished with value: 0.08841413259506226 and parameters: {'hidden_layer': 74, 'learning_rate': 0.021004422578901658, 'momentum': 0.8425483589096694, 'weight_decay': 0.0001259839490607948}. Best is trial 22 with value: 0.08723077923059464.
[I 2026-09-24 02:13:09,430] Trial 34 pruned.
[I 2026-09-24 02:13:18,652] Trial 35 pruned.
[I 2026-09-24 02:13:36,727] Trial 36 finished with value: 0.08567825704813004 and parameters: {'hidden_layer': 30, 'learning_rate': 0.01125045640386955, 'momentum': 0.9411798772146994, 'weight_decay': 2.060507621702798e-05}. Best is trial 36 with value: 0.08567825704813004.
[I 2026-09-24 02:13:47,595] Trial 37 pruned.
[I 2026-09-24 02:14:02,951] Trial 38 pruned.
[I 2026-09-24 02:14:18,694] Trial 39 pruned.
[I 2026-09-24 02:14:30,115] Trial 40 pruned.
[I 2026-09-24 02:14:35,615] Trial 41 pruned.
[I 2026-09-24 02:14:43,422] Trial 42 pruned.
[I 2026-09-24 02:15:17,036] Trial 43 finished with value: 0.09366247057914734 and parameters: {'hidden_layer': 8, 'learning_rate': 0.02480442146226482, 'momentum': 0.7201132450604896, 'weight_decay': 5.4337977723417146e-05}. Best is trial 36 with value: 0.08567825704813004.
[I 2026-09-24 02:15:22,996] Trial 44 pruned.
[I 2026-09-24 02:15:37,704] Trial 45 pruned.
[I 2026-09-24 02:15:52,647] Trial 46 pruned.
[I 2026-09-24 02:16:28,616] Trial 47 finished with value: 0.09722580760717392 and parameters: {'hidden_layer': 101, 'learning_rate': 0.014517746330699936, 'momentum': 0.7401894044844958, 'weight_decay': 2.501747456526545e-05}. Best is trial 36 with value: 0.08567825704813004.
[I 2026-09-24 02:16:49,768] Trial 48 finished with value: 0.08137965947389603 and parameters: {'hidden_layer': 92, 'learning_rate': 0.0746503834098371, 'momentum': 0.6689694158873298, 'weight_decay': 5.181689597395877e-05}. Best is trial 48 with value: 0.08137965947389603.
[I 2026-09-24 02:17:01,201] Trial 49 pruned.
[I 2026-09-24 02:17:27,956] Trial 50 finished with value: 0.08848597854375839 and parameters: {'hidden_layer': 94, 'learning_rate': 0.07128234823388599, 'momentum': 0.5164288114565737, 'weight_decay': 6.873796980774967e-05}. Best is trial 48 with value: 0.08137965947389603.
[I 2026-09-24 02:17:37,106] Trial 51 pruned.
[I 2026-09-24 02:18:07,496] Trial 52 finished with value: 0.08970656245946884 and parameters: {'hidden_layer': 86, 'learning_rate': 0.027020613424297155, 'momentum': 0.7921465132492536, 'weight_decay': 1.9384161830129724e-05}. Best is trial 48 with value: 0.08137965947389603.
[I 2026-09-24 02:18:37,072] Trial 53 finished with value: 0.08591780066490173 and parameters: {'hidden_layer': 54, 'learning_rate': 0.04888147238202226, 'momentum': 0.6694816049673977, 'weight_decay': 1.1538914284381806e-05}. Best is trial 48 with value: 0.08137965947389603.
[I 2026-09-24 02:18:43,099] Trial 54 pruned.
[I 2026-09-24 02:19:05,797] Trial 55 finished with value: 0.07976331561803818 and parameters: {'hidden_layer': 43, 'learning_rate': 0.08140021026615171, 'momentum': 0.653729852145013, 'weight_decay': 8.870494951673605e-06}. Best is trial 55 with value: 0.07976331561803818.
[I 2026-09-24 02:19:26,724] Trial 56 finished with value: 0.08775941282510757 and parameters: {'hidden_layer': 44, 'learning_rate': 0.09898614489972826, 'momentum': 0.6460709180679517, 'weight_decay': 1.0147002685874475e-05}. Best is trial 55 with value: 0.07976331561803818.
[I 2026-09-24 02:19:39,646] Trial 57 pruned.
[I 2026-09-24 02:20:14,660] Trial 58 finished with value: 0.0995560884475708 and parameters: {'hidden_layer': 37, 'learning_rate': 0.05883017862319732, 'momentum': 0.4431309744272555, 'weight_decay': 1.3778306737472135e-05}. Best is trial 55 with value: 0.07976331561803818.
[I 2026-09-24 02:20:43,015] Trial 59 finished with value: 0.09123704582452774 and parameters: {'hidden_layer': 27, 'learning_rate': 0.03925620696311405, 'momentum': 0.6627636086812018, 'weight_decay': 5.739249244115466e-06}. Best is trial 55 with value: 0.07976331561803818.
[I 2026-09-24 02:21:14,198] Trial 60 finished with value: 0.08539199829101562 and parameters: {'hidden_layer': 55, 'learning_rate': 0.054603970183814556, 'momentum': 0.5331490889830516, 'weight_decay': 2.9514256878586055e-05}. Best is trial 55 with value: 0.07976331561803818.
[I 2026-09-24 02:21:49,576] Trial 61 finished with value: 0.10197222232818604 and parameters: {'hidden_layer': 42, 'learning_rate': 0.05525184653387454, 'momentum': 0.339096197501362, 'weight_decay': 3.1024938342090924e-05}. Best is trial 55 with value: 0.07976331561803818.
[I 2026-09-24 02:22:16,734] Trial 62 finished with value: 0.07814949005842209 and parameters: {'hidden_layer': 55, 'learning_rate': 0.07570302734957246, 'momentum': 0.6202457270290017, 'weight_decay': 9.144592300050395e-06}. Best is trial 62 with value: 0.07814949005842209.
[I 2026-09-24 02:22:41,010] Trial 63 finished with value: 0.09207919239997864 and parameters: {'hidden_layer': 47, 'learning_rate': 0.08098015426057933, 'momentum': 0.5800473423858312, 'weight_decay': 9.044888758042466e-06}. Best is trial 62 with value: 0.07814949005842209.
[I 2026-09-24 02:23:08,342] Trial 64 finished with value: 0.08944276720285416 and parameters: {'hidden_layer': 64, 'learning_rate': 0.05606538337543416, 'momentum': 0.5110694450741424, 'weight_decay': 1.8716833711136943e-05}. Best is trial 62 with value: 0.07814949005842209.
[I 2026-09-24 02:23:50,399] Trial 65 finished with value: 0.08836483955383301 and parameters: {'hidden_layer': 53, 'learning_rate': 0.0417633473761569, 'momentum': 0.21225403483973393, 'weight_decay': 3.702536421938774e-06}. Best is trial 62 with value: 0.07814949005842209.
[I 2026-09-24 02:24:01,170] Trial 66 pruned.
[I 2026-09-24 02:24:15,376] Trial 67 pruned.
[I 2026-09-24 02:24:35,539] Trial 68 finished with value: 0.08455053716897964 and parameters: {'hidden_layer': 55, 'learning_rate': 0.061368226929778336, 'momentum': 0.6973948987030911, 'weight_decay': 1.2804719759081574e-05}. Best is trial 62 with value: 0.07814949005842209.
[I 2026-09-24 02:24:50,674] Trial 69 pruned.
[I 2026-09-24 02:25:05,644] Trial 70 pruned.
[I 2026-09-24 02:25:31,365] Trial 71 finished with value: 0.09060126543045044 and parameters: {'hidden_layer': 55, 'learning_rate': 0.06887632199603261, 'momentum': 0.6121927218280598, 'weight_decay': 3.944778954911772e-05}. Best is trial 62 with value: 0.07814949005842209.
[I 2026-09-24 02:25:58,514] Trial 72 finished with value: 0.09783712029457092 and parameters: {'hidden_layer': 62, 'learning_rate': 0.09990889607165743, 'momentum': 0.5910548437168149, 'weight_decay': 2.963340012900136e-05}. Best is trial 62 with value: 0.07814949005842209.
[I 2026-09-24 02:26:29,819] Trial 73 finished with value: 0.0928114727139473 and parameters: {'hidden_layer': 33, 'learning_rate': 0.036674123472922614, 'momentum': 0.5324452497235017, 'weight_decay': 2.274530743107865e-05}. Best is trial 62 with value: 0.07814949005842209.
[I 2026-09-24 02:26:35,775] Trial 74 pruned.
[I 2026-09-24 02:26:50,927] Trial 75 pruned.
[I 2026-09-24 02:27:13,502] Trial 76 finished with value: 0.09677869826555252 and parameters: {'hidden_layer': 97, 'learning_rate': 0.0800884501763444, 'momentum': 0.5673178807760757, 'weight_decay': 1.1911240502324448e-05}. Best is trial 62 with value: 0.07814949005842209.
[I 2026-09-24 02:27:42,793] Trial 77 finished with value: 0.09392399340867996 and parameters: {'hidden_layer': 66, 'learning_rate': 0.048521250456594535, 'momentum': 0.6281243482848397, 'weight_decay': 3.110705466110033e-06}. Best is trial 62 with value: 0.07814949005842209.
[I 2026-09-24 02:27:49,011] Trial 78 pruned.
[I 2026-09-24 02:28:11,957] Trial 79 finished with value: 0.08984968066215515 and parameters: {'hidden_layer': 42, 'learning_rate': 0.06364145765214958, 'momentum': 0.6759245476897222, 'weight_decay': 5.650529593218119e-05}. Best is trial 62 with value: 0.07814949005842209.

{'hidden_layer': 55, 'learning_rate': 0.07570302734957246, 'momentum': 0.6202457270290017, 'weight_decay': 9.144592300050395e-06}
0.07814949005842209

In [4]:
acts = ['relu', 'leaky_relu', 'elu', 'gelu', 'swish']
balance = [False, True]

results = []
name = "base"
for state in balance:
    if state:
        name = 'balanced'
    else:
        name = 'base'

    for activation in acts:
        setup = {'activation': activation, 'balanced': state}
        alpha = 0
        params = retrieve_params(f'params/breast_cancer/{name}_{activation}.json')
        if activation == 'leaky_relu':
            alpha = params["leaky_relu_alpha"]
        elif activation == 'elu':
            alpha = params["elu_alpha"]
        result = cv_classification(X_pool, y_pool, out_units=1, out_act='sigmoid', loss="binary_crossentropy", k=3, random_state=42, 
                  hidden_units=params['hidden_layer'], activation=activation, alpha=alpha, 
                  learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], balanced=state)
        for key, val in result.items():
            setup[key] = val
    
        results.append(setup)

results_df = pd.DataFrame(results)
results_df.round(4).to_csv(f"results/breast_cancer/cv_validation.csv", index=False)

WARNING:tensorflow:From C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

In [ ]:
active_model = tf.keras.Sequential([
    layers.Input(shape=(X_pool.shape[1],)),
    layers.Dense(32, activation="relu"),
    layers.Dense(1, activation='sigmoid')
])

active_model.compile(
    optimizer=tf.keras.optimizers.SGD(learning_rate=0.001),
    loss="binary_crossentropy",
    metrics=["accuracy", tf.keras.metrics.AUC(name="auc"), tf.keras.metrics.F1Score(average='macro')]
)

history = active_learning(
    active_model,
    X_pool,
    y_pool,
    X_test,
    y_test,
    passive_sampling,
    num_iter=3,
    unlab_size=0.9,
    random_state=100,
    verbose=True
)

## Dry beans

In [5]:
dry_bean = fetch_ucirepo(id=602)
bean_df = pd.concat(
    [dry_bean.data.features, dry_bean.data.targets],
    axis=1
)
bean_df.head()

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRatio,Eccentricity,ConvexArea,EquivDiameter,Extent,Solidity,Roundness,Compactness,ShapeFactor1,ShapeFactor2,ShapeFactor3,ShapeFactor4,Class
0,28395,610.291,208.178117,173.888747,1.197191,0.549812,28715,190.141097,0.763923,0.988856,0.958027,0.913358,0.007332,0.003147,0.834222,0.998724,SEKER
1,28734,638.018,200.524796,182.734419,1.097356,0.411785,29172,191.272751,0.783968,0.984986,0.887034,0.953861,0.006979,0.003564,0.909851,0.998430,SEKER
2,29380,624.110,212.826130,175.931143,1.209713,0.562727,29690,193.410904,0.778113,0.989559,0.947849,0.908774,0.007244,0.003048,0.825871,0.999066,SEKER
3,30008,645.884,210.557999,182.516516,1.153638,0.498616,30724,195.467062,0.782681,0.976696,0.903936,0.928329,0.007017,0.003215,0.861794,0.994199,SEKER
4,30140,620.134,201.847882,190.279279,1.060798,0.333680,30417,195.896503,0.773098,0.990893,0.984877,0.970516,0.006697,0.003665,0.941900,0.999166,SEKER

In [6]:
X = dry_bean.data.features.to_numpy()
encoder = LabelEncoder()
y = dry_bean.data.targets.to_numpy().ravel()

y = encoder.fit_transform(y)
bean_map = encoder.classes_
n_classes = len(np.unique(y))

X_pool, X_test, y_pool, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=51
)

In [7]:
acts = ['relu', 'leaky_relu', 'elu', 'gelu', 'swish']
name = "base"
for activation in acts:
    base_params = tune_params(X_pool, y_pool,
                              loss='sparse_categorical_crossentropy',
                              out_units=n_classes, out_act='softmax',
                              k=5, activation=activation,
                              balanced=False,
                              random_state=42,
                              n_trials=80,
                              export=True, file = f'params/dry_bean/{name}_{activation}.json'
    )

[I 2026-09-24 08:58:49,653] A new study created in memory with name: no-name-f7990ee7-4d94-46ba-ad02-462e9c640964
[I 2026-09-24 09:03:42,963] Trial 0 finished with value: 0.2359083592891693 and parameters: {'hidden_layer': 31, 'learning_rate': 0.0010504234588356461, 'momentum': 0.5672917461412101, 'weight_decay': 0.00025515089599309465}. Best is trial 0 with value: 0.2359083592891693.
[I 2026-09-24 09:08:12,182] Trial 1 finished with value: 0.20321372151374817 and parameters: {'hidden_layer': 74, 'learning_rate': 0.006456565189986694, 'momentum': 0.252843329131544, 'weight_decay': 1.3376349549684816e-05}. Best is trial 1 with value: 0.20321372151374817.
[I 2026-09-24 09:12:47,467] Trial 2 finished with value: 0.24281105399131775 and parameters: {'hidden_layer': 26, 'learning_rate': 0.0010622162477497206, 'momentum': 0.514092887324837, 'weight_decay': 4.989903460203718e-05}. Best is trial 1 with value: 0.20321372151374817.
[I 2026-09-24 09:14:24,182] Trial 3 finished with value: 0.20411601662635803 and parameters: {'hidden_layer': 16, 'learning_rate': 0.07885404716254263, 'momentum': 0.20300851453653232, 'weight_decay': 6.613936560012304e-05}. Best is trial 1 with value: 0.20321372151374817.
[I 2026-09-24 09:16:46,019] Trial 4 finished with value: 0.19645296037197113 and parameters: {'hidden_layer': 106, 'learning_rate': 0.0014567150954523447, 'momentum': 0.9685525587288641, 'weight_decay': 0.002561072847106718}. Best is trial 4 with value: 0.19645296037197113.
[I 2026-09-24 09:17:39,634] Trial 5 pruned.
[I 2026-09-24 09:18:20,646] Trial 6 pruned.
[I 2026-09-24 09:20:44,921] Trial 7 finished with value: 0.19586098194122314 and parameters: {'hidden_layer': 120, 'learning_rate': 0.028434218172087043, 'momentum': 0.39136265042181523, 'weight_decay': 0.000736881252101539}. Best is trial 7 with value: 0.19586098194122314.
[I 2026-09-24 09:21:38,680] Trial 8 pruned.
[I 2026-09-24 09:22:03,982] Trial 9 pruned.
[I 2026-09-24 09:23:27,324] Trial 10 finished with value: 0.1982518434524536 and parameters: {'hidden_layer': 125, 'learning_rate': 0.021868036253170162, 'momentum': 0.7324079968764058, 'weight_decay': 2.7204843792693914e-06}. Best is trial 7 with value: 0.19586098194122314.
[I 2026-09-24 09:26:13,389] Trial 11 finished with value: 0.19568899273872375 and parameters: {'hidden_layer': 101, 'learning_rate': 0.0009357658121462737, 'momentum': 0.975714921890348, 'weight_decay': 0.00038573835969758785}. Best is trial 11 with value: 0.19568899273872375.
[I 2026-09-24 09:27:10,727] Trial 12 pruned.
[I 2026-09-24 09:28:46,589] Trial 13 finished with value: 0.1942003220319748 and parameters: {'hidden_layer': 79, 'learning_rate': 0.03364465092534274, 'momentum': 0.7521197228274038, 'weight_decay': 0.00027002028206698776}. Best is trial 13 with value: 0.1942003220319748.
[I 2026-09-24 09:29:41,162] Trial 14 pruned.
[I 2026-09-24 09:30:36,061] Trial 15 pruned.
[I 2026-09-24 09:31:28,943] Trial 16 pruned.
[I 2026-09-24 09:34:27,629] Trial 17 finished with value: 0.1954241842031479 and parameters: {'hidden_layer': 99, 'learning_rate': 0.005443759756530936, 'momentum': 0.8499817591245498, 'weight_decay': 0.00038853782918254}. Best is trial 13 with value: 0.1942003220319748.
[I 2026-09-24 09:35:55,061] Trial 18 finished with value: 0.19775497913360596 and parameters: {'hidden_layer': 50, 'learning_rate': 0.029597581219994673, 'momentum': 0.6695199627118563, 'weight_decay': 1.6970312999708365e-05}. Best is trial 13 with value: 0.1942003220319748.
[I 2026-09-24 09:37:47,846] Trial 19 finished with value: 0.19647642970085144 and parameters: {'hidden_layer': 87, 'learning_rate': 0.008011485054400169, 'momentum': 0.8571414569269052, 'weight_decay': 8.925935172649852e-05}. Best is trial 13 with value: 0.1942003220319748.
[I 2026-09-24 09:41:21,083] Trial 20 finished with value: 0.19711387157440186 and parameters: {'hidden_layer': 109, 'learning_rate': 0.014858060219820945, 'momentum': 0.4063284165148949, 'weight_decay': 0.000572861774021501}. Best is trial 13 with value: 0.1942003220319748.
[I 2026-09-24 09:43:50,353] Trial 21 finished with value: 0.19790445268154144 and parameters: {'hidden_layer': 98, 'learning_rate': 0.0031850846858208037, 'momentum': 0.9097892164961137, 'weight_decay': 0.0003687595260193747}. Best is trial 13 with value: 0.1942003220319748.
[I 2026-09-24 09:44:46,069] Trial 22 finished with value: 0.19869691133499146 and parameters: {'hidden_layer': 77, 'learning_rate': 0.05112572131560338, 'momentum': 0.87160967535503, 'weight_decay': 0.00012190496234364359}. Best is trial 13 with value: 0.1942003220319748.
[I 2026-09-24 09:46:00,284] Trial 23 pruned.
[I 2026-09-24 09:46:50,514] Trial 24 pruned.
[I 2026-09-24 09:47:25,963] Trial 25 pruned.
[I 2026-09-24 09:47:56,742] Trial 26 pruned.
[I 2026-09-24 09:48:33,436] Trial 27 pruned.
[I 2026-09-24 09:49:49,587] Trial 28 finished with value: 0.20161303877830505 and parameters: {'hidden_layer': 81, 'learning_rate': 0.04987335605596431, 'momentum': 0.8621940303086408, 'weight_decay': 3.4453366384175525e-05}. Best is trial 13 with value: 0.1942003220319748.
[I 2026-09-24 09:50:58,908] Trial 29 pruned.
[I 2026-09-24 09:52:06,024] Trial 30 pruned.
[I 2026-09-24 09:52:31,851] Trial 31 pruned.
[I 2026-09-24 09:54:24,259] Trial 32 finished with value: 0.19669879972934723 and parameters: {'hidden_layer': 115, 'learning_rate': 0.0505817374461577, 'momentum': 0.41511970083926014, 'weight_decay': 0.0004705273484312752}. Best is trial 13 with value: 0.1942003220319748.
[I 2026-09-24 09:54:41,606] Trial 33 pruned.
[I 2026-09-24 09:55:53,715] Trial 34 pruned.
[I 2026-09-24 09:56:21,631] Trial 35 pruned.
[I 2026-09-24 09:57:16,730] Trial 36 pruned.
[I 2026-09-24 09:57:46,645] Trial 37 pruned.
[I 2026-09-24 09:58:13,798] Trial 38 pruned.
[I 2026-09-24 09:58:54,336] Trial 39 pruned.
[I 2026-09-24 10:00:04,079] Trial 40 pruned.
[I 2026-09-24 10:00:46,980] Trial 41 pruned.
[I 2026-09-24 10:01:26,210] Trial 42 pruned.
[I 2026-09-24 10:02:12,678] Trial 43 pruned.
[I 2026-09-24 10:03:16,363] Trial 44 pruned.
[I 2026-09-24 10:04:15,578] Trial 45 pruned.
[I 2026-09-24 10:04:53,376] Trial 46 pruned.
[I 2026-09-24 10:05:03,109] Trial 47 pruned.
[I 2026-09-24 10:05:59,945] Trial 48 pruned.
[I 2026-09-24 10:06:57,520] Trial 49 pruned.
[I 2026-09-24 10:07:56,366] Trial 50 pruned.
[I 2026-09-24 10:08:17,587] Trial 51 pruned.
[I 2026-09-24 10:08:56,897] Trial 52 pruned.
[I 2026-09-24 10:10:05,426] Trial 53 finished with value: 0.19670042395591736 and parameters: {'hidden_layer': 85, 'learning_rate': 0.02358927457162806, 'momentum': 0.8911685660235724, 'weight_decay': 3.230625301663292e-05}. Best is trial 13 with value: 0.1942003220319748.
[I 2026-09-24 10:11:30,572] Trial 54 finished with value: 0.19380834698677063 and parameters: {'hidden_layer': 107, 'learning_rate': 0.007758378811390079, 'momentum': 0.9414639060544645, 'weight_decay': 0.0001097303171328828}. Best is trial 54 with value: 0.19380834698677063.
[I 2026-09-24 10:11:50,706] Trial 55 pruned.
[I 2026-09-24 10:13:10,900] Trial 56 finished with value: 0.19593937695026398 and parameters: {'hidden_layer': 101, 'learning_rate': 0.002100455236256793, 'momentum': 0.989295810494104, 'weight_decay': 0.0005945152985652473}. Best is trial 54 with value: 0.19380834698677063.
[I 2026-09-24 10:13:25,634] Trial 57 pruned.
[I 2026-09-24 10:14:39,519] Trial 58 pruned.
[I 2026-09-24 10:14:58,249] Trial 59 pruned.
[I 2026-09-24 10:15:10,079] Trial 60 pruned.
[I 2026-09-24 10:16:28,019] Trial 61 finished with value: 0.19815218448638916 and parameters: {'hidden_layer': 109, 'learning_rate': 0.0023092980534152006, 'momentum': 0.9894408705263026, 'weight_decay': 0.0003188396754058078}. Best is trial 54 with value: 0.19380834698677063.
[I 2026-09-24 10:17:25,068] Trial 62 pruned.
[I 2026-09-24 10:17:43,068] Trial 63 pruned.
[I 2026-09-24 10:18:04,714] Trial 64 pruned.
[I 2026-09-24 10:19:13,964] Trial 65 pruned.
[I 2026-09-24 10:20:34,900] Trial 66 finished with value: 0.19574598968029022 and parameters: {'hidden_layer': 101, 'learning_rate': 0.005265838751299991, 'momentum': 0.9646506063521145, 'weight_decay': 0.0040609716439758406}. Best is trial 54 with value: 0.19380834698677063.
[I 2026-09-24 10:21:06,301] Trial 67 pruned.
[I 2026-09-24 10:22:53,079] Trial 68 finished with value: 0.19474612176418304 and parameters: {'hidden_layer': 96, 'learning_rate': 0.004196078257738516, 'momentum': 0.9597458588971624, 'weight_decay': 0.0001331198264197295}. Best is trial 54 with value: 0.19380834698677063.
[I 2026-09-24 10:23:53,226] Trial 69 pruned.
[I 2026-09-24 10:24:13,612] Trial 70 pruned.
[I 2026-09-24 10:26:21,936] Trial 71 finished with value: 0.19683311879634857 and parameters: {'hidden_layer': 100, 'learning_rate': 0.0029269328429250203, 'momentum': 0.9646273885897985, 'weight_decay': 0.00457834323102515}. Best is trial 54 with value: 0.19380834698677063.
[I 2026-09-24 10:26:37,380] Trial 72 pruned.
[I 2026-09-24 10:26:49,206] Trial 73 pruned.
[I 2026-09-24 10:27:17,025] Trial 74 pruned.
[I 2026-09-24 10:28:14,375] Trial 75 finished with value: 0.19711646437644958 and parameters: {'hidden_layer': 90, 'learning_rate': 0.005319891953000173, 'momentum': 0.9886148602139587, 'weight_decay': 0.00015413036860536844}. Best is trial 54 with value: 0.19380834698677063.
[I 2026-09-24 10:28:34,615] Trial 76 pruned.
[I 2026-09-24 10:28:49,714] Trial 77 pruned.
[I 2026-09-24 10:29:01,847] Trial 78 pruned.
[I 2026-09-24 10:29:59,150] Trial 79 pruned.
[I 2026-09-24 10:29:59,154] A new study created in memory with name: no-name-a76f5a42-c163-4cdd-a42d-f973a868b611

{'hidden_layer': 107, 'learning_rate': 0.007758378811390079, 'momentum': 0.9414639060544645, 'weight_decay': 0.0001097303171328828}
0.19380834698677063

[I 2026-09-24 10:34:40,683] Trial 0 finished with value: 0.603901743888855 and parameters: {'hidden_layer': 38, 'learning_rate': 0.0002673158232409953, 'momentum': 0.032274798726985035, 'weight_decay': 4.936605963515345e-05, 'leaky_relu_alpha': 0.003109727808447892}. Best is trial 0 with value: 0.603901743888855.
[I 2026-09-24 10:39:23,412] Trial 1 finished with value: 0.23986172676086426 and parameters: {'hidden_layer': 83, 'learning_rate': 0.0012903958116131534, 'momentum': 0.3565891977479561, 'weight_decay': 5.9950085693023085e-05, 'leaky_relu_alpha': 0.008350776258629306}. Best is trial 1 with value: 0.23986172676086426.
[I 2026-09-24 10:44:11,391] Trial 2 finished with value: 0.41579437255859375 and parameters: {'hidden_layer': 78, 'learning_rate': 0.0003941285306908751, 'momentum': 0.20072690389699424, 'weight_decay': 0.001403334804497561, 'leaky_relu_alpha': 0.004809521334064588}. Best is trial 1 with value: 0.23986172676086426.
[I 2026-09-24 10:49:39,590] Trial 3 finished with value: 0.2078244388103485 and parameters: {'hidden_layer': 115, 'learning_rate': 0.0013194216604102403, 'momentum': 0.7915970053733546, 'weight_decay': 1.3938878916897325e-06, 'leaky_relu_alpha': 0.03316395396476727}. Best is trial 3 with value: 0.2078244388103485.
[I 2026-09-24 10:51:49,539] Trial 4 finished with value: 0.2027515172958374 and parameters: {'hidden_layer': 34, 'learning_rate': 0.0417638367705893, 'momentum': 0.4477570982737073, 'weight_decay': 0.002593648510417523, 'leaky_relu_alpha': 0.0047153764594807775}. Best is trial 4 with value: 0.2027515172958374.
[I 2026-09-24 10:53:00,321] Trial 5 pruned.
[I 2026-09-24 10:58:08,207] Trial 6 finished with value: 0.2080414742231369 and parameters: {'hidden_layer': 28, 'learning_rate': 0.008913437433683129, 'momentum': 0.19702747869677012, 'weight_decay': 6.469622464482091e-05, 'leaky_relu_alpha': 0.20799307566446795}. Best is trial 4 with value: 0.2027515172958374.
[I 2026-09-24 11:00:42,588] Trial 7 finished with value: 0.19810841977596283 and parameters: {'hidden_layer': 61, 'learning_rate': 0.02269476706835649, 'momentum': 0.6081554124828484, 'weight_decay': 4.5408866354504585e-05, 'leaky_relu_alpha': 0.06691909951102508}. Best is trial 7 with value: 0.19810841977596283.
[I 2026-09-24 11:01:49,356] Trial 8 pruned.
[I 2026-09-24 11:04:41,840] Trial 9 finished with value: 0.20182998478412628 and parameters: {'hidden_layer': 32, 'learning_rate': 0.003951188455143487, 'momentum': 0.8956045152838437, 'weight_decay': 0.004648817832420735, 'leaky_relu_alpha': 0.005352502974701013}. Best is trial 7 with value: 0.19810841977596283.
[I 2026-09-24 11:06:22,650] Trial 10 finished with value: 0.197006493806839 and parameters: {'hidden_layer': 122, 'learning_rate': 0.08048139290158016, 'momentum': 0.6434291571362718, 'weight_decay': 0.0004966127414802385, 'leaky_relu_alpha': 0.11744087155075383}. Best is trial 10 with value: 0.197006493806839.
[I 2026-09-24 11:08:07,196] Trial 11 finished with value: 0.19848179817199707 and parameters: {'hidden_layer': 115, 'learning_rate': 0.07624610521788623, 'momentum': 0.6267164472615651, 'weight_decay': 0.0003771975447405042, 'leaky_relu_alpha': 0.12445487019592466}. Best is trial 10 with value: 0.197006493806839.
[I 2026-09-24 11:10:25,843] Trial 12 finished with value: 0.19912020862102509 and parameters: {'hidden_layer': 57, 'learning_rate': 0.020986041111394023, 'momentum': 0.6257945199054986, 'weight_decay': 0.00039015124210426425, 'leaky_relu_alpha': 0.07703718363882409}. Best is trial 10 with value: 0.197006493806839.
[I 2026-09-24 11:13:08,392] Trial 13 finished with value: 0.1972515881061554 and parameters: {'hidden_layer': 102, 'learning_rate': 0.018179617419872358, 'momentum': 0.5963531802723288, 'weight_decay': 0.00028890012543238564, 'leaky_relu_alpha': 0.06020544985797052}. Best is trial 10 with value: 0.197006493806839.
[I 2026-09-24 11:13:15,055] Trial 14 pruned.
[I 2026-09-24 11:17:29,202] Trial 15 finished with value: 0.19833363592624664 and parameters: {'hidden_layer': 102, 'learning_rate': 0.011121054068428126, 'momentum': 0.5441579024284446, 'weight_decay': 0.0006602858239216283, 'leaky_relu_alpha': 0.015081136163668869}. Best is trial 10 with value: 0.197006493806839.
[I 2026-09-24 11:18:56,352] Trial 16 finished with value: 0.19524262845516205 and parameters: {'hidden_layer': 101, 'learning_rate': 0.035382156738973346, 'momentum': 0.7550894030878125, 'weight_decay': 0.00019819931903280932, 'leaky_relu_alpha': 0.0014401784047655155}. Best is trial 16 with value: 0.19524262845516205.
[I 2026-09-24 11:19:03,291] Trial 17 pruned.
[I 2026-09-24 11:21:52,423] Trial 18 finished with value: 0.19932611286640167 and parameters: {'hidden_layer': 128, 'learning_rate': 0.005172676748685552, 'momentum': 0.8501820460969398, 'weight_decay': 1.5401776780459447e-05, 'leaky_relu_alpha': 0.0013245674783796872}. Best is trial 16 with value: 0.19524262845516205.
[I 2026-09-24 11:23:30,368] Trial 19 finished with value: 0.19709694385528564 and parameters: {'hidden_layer': 93, 'learning_rate': 0.035390563191852464, 'momentum': 0.6867812942765847, 'weight_decay': 0.00015039205693227878, 'leaky_relu_alpha': 0.0019902691309708303}. Best is trial 16 with value: 0.19524262845516205.
[I 2026-09-24 11:24:37,718] Trial 20 pruned.
[I 2026-09-24 11:24:59,831] Trial 21 pruned.
[I 2026-09-24 11:25:10,342] Trial 22 pruned.
[I 2026-09-24 11:27:25,116] Trial 23 finished with value: 0.19531384110450745 and parameters: {'hidden_layer': 94, 'learning_rate': 0.010737545297345396, 'momentum': 0.8566622459676208, 'weight_decay': 0.0001480695204064423, 'leaky_relu_alpha': 0.010176773265611623}. Best is trial 16 with value: 0.19524262845516205.
[I 2026-09-24 11:29:49,638] Trial 24 finished with value: 0.1970396339893341 and parameters: {'hidden_layer': 109, 'learning_rate': 0.007137355282100341, 'momentum': 0.8707928045861969, 'weight_decay': 0.0010712979101729697, 'leaky_relu_alpha': 0.011091640952733909}. Best is trial 16 with value: 0.19524262845516205.
[I 2026-09-24 11:32:02,598] Trial 25 finished with value: 0.1954733282327652 and parameters: {'hidden_layer': 121, 'learning_rate': 0.013163299799665643, 'momentum': 0.8280468069671507, 'weight_decay': 7.364843062155203e-06, 'leaky_relu_alpha': 0.03646449945675441}. Best is trial 16 with value: 0.19524262845516205.
[I 2026-09-24 11:34:18,959] Trial 26 finished with value: 0.19524314999580383 and parameters: {'hidden_layer': 95, 'learning_rate': 0.012905086420853355, 'momentum': 0.797234825656917, 'weight_decay': 4.30262099189048e-06, 'leaky_relu_alpha': 0.03603095053215448}. Best is trial 16 with value: 0.19524262845516205.
[I 2026-09-24 11:37:33,458] Trial 27 finished with value: 0.19772017002105713 and parameters: {'hidden_layer': 72, 'learning_rate': 0.0024888762901801053, 'momentum': 0.9133594305597316, 'weight_decay': 1.8606685467567196e-06, 'leaky_relu_alpha': 0.008817300995594305}. Best is trial 16 with value: 0.19524262845516205.
[I 2026-09-24 11:37:55,136] Trial 28 pruned.
[I 2026-09-24 11:38:12,310] Trial 29 pruned.
[I 2026-09-24 11:40:26,700] Trial 30 finished with value: 0.19512872397899628 and parameters: {'hidden_layer': 97, 'learning_rate': 0.012763357628083108, 'momentum': 0.8092746543510193, 'weight_decay': 8.409359792498953e-05, 'leaky_relu_alpha': 0.0031355408444088202}. Best is trial 30 with value: 0.19512872397899628.
[I 2026-09-24 11:42:28,285] Trial 31 finished with value: 0.19612613320350647 and parameters: {'hidden_layer': 98, 'learning_rate': 0.015154479456286908, 'momentum': 0.8315769362502637, 'weight_decay': 3.290281163442539e-05, 'leaky_relu_alpha': 0.0025638013039493727}. Best is trial 30 with value: 0.19512872397899628.
[I 2026-09-24 11:44:20,389] Trial 32 finished with value: 0.19639882445335388 and parameters: {'hidden_layer': 85, 'learning_rate': 0.030843708976824154, 'momentum': 0.5336967288494858, 'weight_decay': 8.388399136281809e-05, 'leaky_relu_alpha': 0.0071032743906346155}. Best is trial 30 with value: 0.19512872397899628.
[I 2026-09-24 11:46:41,283] Trial 33 finished with value: 0.19712038338184357 and parameters: {'hidden_layer': 76, 'learning_rate': 0.010216139482079226, 'momentum': 0.7884746179508222, 'weight_decay': 0.00023332306709800374, 'leaky_relu_alpha': 0.003648498060656107}. Best is trial 30 with value: 0.19512872397899628.
[I 2026-09-24 11:47:40,103] Trial 34 pruned.
[I 2026-09-24 11:49:02,648] Trial 35 finished with value: 0.19624394178390503 and parameters: {'hidden_layer': 80, 'learning_rate': 0.02679308799837865, 'momentum': 0.9402419130374733, 'weight_decay': 1.0575613839836302e-06, 'leaky_relu_alpha': 0.0015172028361134043}. Best is trial 30 with value: 0.19512872397899628.
[I 2026-09-24 11:50:03,366] Trial 36 finished with value: 0.1972985416650772 and parameters: {'hidden_layer': 93, 'learning_rate': 0.05327431611145708, 'momentum': 0.7589550153449514, 'weight_decay': 1.877286544625219e-05, 'leaky_relu_alpha': 0.0030589749825740416}. Best is trial 30 with value: 0.19512872397899628.
[I 2026-09-24 11:53:48,153] Trial 37 finished with value: 0.1963694542646408 and parameters: {'hidden_layer': 87, 'learning_rate': 0.01683533818786699, 'momentum': 0.4617036347879618, 'weight_decay': 5.644900105882747e-06, 'leaky_relu_alpha': 0.0069710310888475785}. Best is trial 30 with value: 0.19512872397899628.
[I 2026-09-24 11:54:49,871] Trial 38 pruned.
[I 2026-09-24 11:55:48,189] Trial 39 pruned.
[I 2026-09-24 11:56:46,930] Trial 40 pruned.
[I 2026-09-24 11:58:42,260] Trial 41 finished with value: 0.19597318768501282 and parameters: {'hidden_layer': 121, 'learning_rate': 0.013360649304005842, 'momentum': 0.824316525799339, 'weight_decay': 7.483179799334745e-06, 'leaky_relu_alpha': 0.03963874572254789}. Best is trial 30 with value: 0.19512872397899628.
[I 2026-09-24 11:59:22,889] Trial 42 pruned.
[I 2026-09-24 12:00:26,280] Trial 43 pruned.
[I 2026-09-24 12:00:41,961] Trial 44 pruned.
[I 2026-09-24 12:00:51,801] Trial 45 pruned.
[I 2026-09-24 12:01:59,049] Trial 46 pruned.
[I 2026-09-24 12:03:05,241] Trial 47 finished with value: 0.20050100982189178 and parameters: {'hidden_layer': 90, 'learning_rate': 0.02020554708860289, 'momentum': 0.9547217877150316, 'weight_decay': 6.878991933778184e-05, 'leaky_relu_alpha': 0.013807249956196659}. Best is trial 30 with value: 0.19512872397899628.
[I 2026-09-24 12:04:09,282] Trial 48 pruned.
[I 2026-09-24 12:05:01,508] Trial 49 pruned.
[I 2026-09-24 12:07:13,993] Trial 50 finished with value: 0.19619254767894745 and parameters: {'hidden_layer': 74, 'learning_rate': 0.029024540484097944, 'momentum': 0.6574676017711631, 'weight_decay': 0.00012269204780214306, 'leaky_relu_alpha': 0.005475817064856766}. Best is trial 30 with value: 0.19512872397899628.
[I 2026-09-24 12:07:53,245] Trial 51 pruned.
[I 2026-09-24 12:08:12,439] Trial 52 pruned.
[I 2026-09-24 12:10:00,727] Trial 53 finished with value: 0.19573616981506348 and parameters: {'hidden_layer': 119, 'learning_rate': 0.017639385884472784, 'momentum': 0.810206180991334, 'weight_decay': 1.985793656547893e-06, 'leaky_relu_alpha': 0.057931109241329916}. Best is trial 30 with value: 0.19512872397899628.
[I 2026-09-24 12:10:11,299] Trial 54 pruned.
[I 2026-09-24 12:10:34,127] Trial 55 pruned.
[I 2026-09-24 12:11:41,726] Trial 56 finished with value: 0.19510602951049805 and parameters: {'hidden_layer': 118, 'learning_rate': 0.044785578854672506, 'momentum': 0.734962964662905, 'weight_decay': 2.0211986654432807e-06, 'leaky_relu_alpha': 0.01649745463992016}. Best is trial 56 with value: 0.19510602951049805.
[I 2026-09-24 12:12:56,533] Trial 57 finished with value: 0.19704963266849518 and parameters: {'hidden_layer': 66, 'learning_rate': 0.0914951433634227, 'momentum': 0.7235939889414951, 'weight_decay': 0.00047727953911376887, 'leaky_relu_alpha': 0.015974298692542938}. Best is trial 56 with value: 0.19510602951049805.
[I 2026-09-24 12:13:11,767] Trial 58 pruned.
[I 2026-09-24 12:14:40,076] Trial 59 finished with value: 0.19284117221832275 and parameters: {'hidden_layer': 126, 'learning_rate': 0.038499144390277434, 'momentum': 0.8888210220929265, 'weight_decay': 5.114730565238182e-06, 'leaky_relu_alpha': 0.020452474706357127}. Best is trial 59 with value: 0.19284117221832275.
[I 2026-09-24 12:15:11,885] Trial 60 pruned.
[I 2026-09-24 12:15:21,444] Trial 61 pruned.
[I 2026-09-24 12:15:30,064] Trial 62 pruned.
[I 2026-09-24 12:15:41,745] Trial 63 pruned.
[I 2026-09-24 12:16:06,155] Trial 64 pruned.
[I 2026-09-24 12:16:14,649] Trial 65 pruned.
[I 2026-09-24 12:16:41,080] Trial 66 pruned.
[I 2026-09-24 12:18:33,000] Trial 67 finished with value: 0.19407455623149872 and parameters: {'hidden_layer': 98, 'learning_rate': 0.02334889067935584, 'momentum': 0.7830034856718441, 'weight_decay': 0.00010650509273347414, 'leaky_relu_alpha': 0.020691139571523996}. Best is trial 59 with value: 0.19284117221832275.
[I 2026-09-24 12:18:49,034] Trial 68 pruned.
[I 2026-09-24 12:18:58,983] Trial 69 pruned.
[I 2026-09-24 12:21:00,464] Trial 70 finished with value: 0.19549204409122467 and parameters: {'hidden_layer': 100, 'learning_rate': 0.030399217885501435, 'momentum': 0.6345207075278808, 'weight_decay': 0.00029178451747961754, 'leaky_relu_alpha': 0.013586527639412106}. Best is trial 59 with value: 0.19284117221832275.
[I 2026-09-24 12:21:16,604] Trial 71 pruned.
[I 2026-09-24 12:21:31,043] Trial 72 pruned.
[I 2026-09-24 12:22:39,539] Trial 73 finished with value: 0.1963152140378952 and parameters: {'hidden_layer': 105, 'learning_rate': 0.02608118578864961, 'momentum': 0.8574644686654628, 'weight_decay': 5.096998771120321e-06, 'leaky_relu_alpha': 0.04558563525842305}. Best is trial 59 with value: 0.19284117221832275.
[I 2026-09-24 12:23:31,023] Trial 74 pruned.
[I 2026-09-24 12:24:34,556] Trial 75 finished with value: 0.19915379583835602 and parameters: {'hidden_layer': 118, 'learning_rate': 0.06484543062795739, 'momentum': 0.7637567924390544, 'weight_decay': 0.0005044436850205751, 'leaky_relu_alpha': 0.03460778202491961}. Best is trial 59 with value: 0.19284117221832275.
[I 2026-09-24 12:24:55,587] Trial 76 pruned.
[I 2026-09-24 12:25:03,772] Trial 77 pruned.
[I 2026-09-24 12:25:19,488] Trial 78 pruned.
[I 2026-09-24 12:26:26,562] Trial 79 pruned.
[I 2026-09-24 12:26:26,572] A new study created in memory with name: no-name-4606e91e-aa02-4764-bb31-13fa1701fca3

{'hidden_layer': 126, 'learning_rate': 0.038499144390277434, 'momentum': 0.8888210220929265, 'weight_decay': 5.114730565238182e-06, 'leaky_relu_alpha': 0.020452474706357127}
0.19284117221832275

[I 2026-09-24 12:28:10,555] Trial 0 finished with value: 0.20084130764007568 and parameters: {'hidden_layer': 58, 'learning_rate': 0.0094677616697529, 'momentum': 0.9291702662166553, 'weight_decay': 6.679133460540766e-05, 'elu_alpha': 1.2326761011141363}. Best is trial 0 with value: 0.20084130764007568.
[I 2026-09-24 12:29:37,334] Trial 1 finished with value: 0.19823968410491943 and parameters: {'hidden_layer': 70, 'learning_rate': 0.06869919389678714, 'momentum': 0.7515212120359361, 'weight_decay': 6.7135691451640234e-06, 'elu_alpha': 0.10652297231932507}. Best is trial 1 with value: 0.19823968410491943.
[I 2026-09-24 12:33:20,755] Trial 2 finished with value: 0.20361976325511932 and parameters: {'hidden_layer': 40, 'learning_rate': 0.005478168211603529, 'momentum': 0.7312758087345064, 'weight_decay': 4.161424936052871e-06, 'elu_alpha': 1.1496989473310768}. Best is trial 1 with value: 0.19823968410491943.
[I 2026-09-24 12:39:18,291] Trial 3 finished with value: 0.24139642715454102 and parameters: {'hidden_layer': 113, 'learning_rate': 0.0004940003883595988, 'momentum': 0.7129020384661174, 'weight_decay': 7.027409187896037e-05, 'elu_alpha': 0.4927083154175087}. Best is trial 1 with value: 0.19823968410491943.
[I 2026-09-24 12:41:41,441] Trial 4 finished with value: 0.1999131143093109 and parameters: {'hidden_layer': 87, 'learning_rate': 0.025674255844109393, 'momentum': 0.5232610460271254, 'weight_decay': 0.00021925761814745666, 'elu_alpha': 0.31185670214059735}. Best is trial 1 with value: 0.19823968410491943.
[I 2026-09-24 12:43:02,978] Trial 5 finished with value: 0.1978568136692047 and parameters: {'hidden_layer': 82, 'learning_rate': 0.05615954987114987, 'momentum': 0.7170533982513475, 'weight_decay': 1.8984204646629973e-06, 'elu_alpha': 0.20765424657305565}. Best is trial 5 with value: 0.1978568136692047.
[I 2026-09-24 12:44:10,590] Trial 6 pruned.
[I 2026-09-24 12:45:33,410] Trial 7 pruned.
[I 2026-09-24 12:47:36,893] Trial 8 finished with value: 0.20002031326293945 and parameters: {'hidden_layer': 65, 'learning_rate': 0.010680572323239637, 'momentum': 0.8762790384893678, 'weight_decay': 2.8956564503382536e-06, 'elu_alpha': 0.7096403210141091}. Best is trial 5 with value: 0.1978568136692047.
[I 2026-09-24 12:48:42,923] Trial 9 pruned.
[I 2026-09-24 12:49:02,568] Trial 10 pruned.
[I 2026-09-24 12:50:09,400] Trial 11 pruned.
[I 2026-09-24 12:51:52,141] Trial 12 finished with value: 0.19493986666202545 and parameters: {'hidden_layer': 99, 'learning_rate': 0.027204588622188972, 'momentum': 0.7946529816586142, 'weight_decay': 1.3534465034385041e-06, 'elu_alpha': 0.1270444399638707}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 12:51:59,075] Trial 13 pruned.
[I 2026-09-24 12:53:47,346] Trial 14 finished with value: 0.19942548871040344 and parameters: {'hidden_layer': 86, 'learning_rate': 0.025668831214793398, 'momentum': 0.8406040915797465, 'weight_decay': 1.468908956680677e-05, 'elu_alpha': 0.7401036221230325}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 12:54:57,728] Trial 15 pruned.
[I 2026-09-24 12:55:28,948] Trial 16 pruned.
[I 2026-09-24 12:56:11,316] Trial 17 pruned.
[I 2026-09-24 12:57:44,510] Trial 18 finished with value: 0.20065221190452576 and parameters: {'hidden_layer': 29, 'learning_rate': 0.047937335927221374, 'momentum': 0.7993020685611713, 'weight_decay': 2.8000935231358404e-06, 'elu_alpha': 0.4101207379287637}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 12:58:06,482] Trial 19 pruned.
[I 2026-09-24 12:58:21,422] Trial 20 pruned.
[I 2026-09-24 12:59:42,394] Trial 21 finished with value: 0.19991448521614075 and parameters: {'hidden_layer': 71, 'learning_rate': 0.05883941398640401, 'momentum': 0.7708102433373246, 'weight_decay': 6.611006055728497e-06, 'elu_alpha': 0.14811558476770734}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 12:59:56,263] Trial 22 pruned.
[I 2026-09-24 13:00:10,646] Trial 23 pruned.
[I 2026-09-24 13:01:40,348] Trial 24 finished with value: 0.19697031378746033 and parameters: {'hidden_layer': 98, 'learning_rate': 0.09130087122969152, 'momentum': 0.5867893599766931, 'weight_decay': 1.9048843978881829e-06, 'elu_alpha': 0.2685039545360708}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:02:16,497] Trial 25 pruned.
[I 2026-09-24 13:02:29,312] Trial 26 pruned.
[I 2026-09-24 13:03:38,421] Trial 27 pruned.
[I 2026-09-24 13:05:00,439] Trial 28 finished with value: 0.20139841735363007 and parameters: {'hidden_layer': 100, 'learning_rate': 0.09809105797633447, 'momentum': 0.675031725973402, 'weight_decay': 1.4604273808019094e-05, 'elu_alpha': 0.8850526032599425}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:05:17,883] Trial 29 pruned.
[I 2026-09-24 13:06:36,902] Trial 30 finished with value: 0.19810137152671814 and parameters: {'hidden_layer': 54, 'learning_rate': 0.03740167770213086, 'momentum': 0.8317660164967574, 'weight_decay': 2.0645546704686517e-06, 'elu_alpha': 0.44038798762458675}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:07:54,477] Trial 31 finished with value: 0.19923850893974304 and parameters: {'hidden_layer': 47, 'learning_rate': 0.03737380226609939, 'momentum': 0.8476797170469037, 'weight_decay': 1.9061145913602492e-06, 'elu_alpha': 0.4344685641481927}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:09:40,966] Trial 32 finished with value: 0.19704051315784454 and parameters: {'hidden_layer': 61, 'learning_rate': 0.017259956728394192, 'momentum': 0.8122009808534341, 'weight_decay': 1.910986839663682e-06, 'elu_alpha': 0.23356658992282403}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:10:04,021] Trial 33 pruned.
[I 2026-09-24 13:11:34,874] Trial 34 finished with value: 0.19620254635810852 and parameters: {'hidden_layer': 80, 'learning_rate': 0.059771350858372964, 'momentum': 0.6629907361674573, 'weight_decay': 1.0491483179476086e-05, 'elu_alpha': 0.11921712008664472}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:14:06,636] Trial 35 finished with value: 0.1979590654373169 and parameters: {'hidden_layer': 58, 'learning_rate': 0.019845765883266437, 'momentum': 0.579166064958195, 'weight_decay': 1.0674957289902916e-05, 'elu_alpha': 0.10019487020116191}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:14:52,414] Trial 36 pruned.
[I 2026-09-24 13:15:26,228] Trial 37 pruned.
[I 2026-09-24 13:15:35,383] Trial 38 pruned.
[I 2026-09-24 13:16:06,560] Trial 39 pruned.
[I 2026-09-24 13:16:30,189] Trial 40 pruned.
[I 2026-09-24 13:17:48,071] Trial 41 finished with value: 0.19633616507053375 and parameters: {'hidden_layer': 83, 'learning_rate': 0.059956722758996966, 'momentum': 0.7014863212121675, 'weight_decay': 1.444844751656171e-06, 'elu_alpha': 0.19576348051015974}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:17:58,799] Trial 42 pruned.
[I 2026-09-24 13:19:13,376] Trial 43 finished with value: 0.19612836837768555 and parameters: {'hidden_layer': 67, 'learning_rate': 0.04365502221206119, 'momentum': 0.7951834480032415, 'weight_decay': 3.1848002837309736e-06, 'elu_alpha': 0.10668668560130351}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:19:29,476] Trial 44 pruned.
[I 2026-09-24 13:19:38,604] Trial 45 pruned.
[I 2026-09-24 13:20:57,992] Trial 46 finished with value: 0.19543702900409698 and parameters: {'hidden_layer': 85, 'learning_rate': 0.09778999752802484, 'momentum': 0.588784630001667, 'weight_decay': 8.673218004192193e-06, 'elu_alpha': 0.18138648746253938}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:21:58,422] Trial 47 pruned.
[I 2026-09-24 13:22:10,138] Trial 48 pruned.
[I 2026-09-24 13:23:14,489] Trial 49 pruned.
[I 2026-09-24 13:23:36,686] Trial 50 pruned.
[I 2026-09-24 13:23:45,680] Trial 51 pruned.
[I 2026-09-24 13:23:58,821] Trial 52 pruned.
[I 2026-09-24 13:24:10,224] Trial 53 pruned.
[I 2026-09-24 13:24:40,228] Trial 54 pruned.
[I 2026-09-24 13:24:55,170] Trial 55 pruned.
[I 2026-09-24 13:26:51,876] Trial 56 finished with value: 0.19956085085868835 and parameters: {'hidden_layer': 68, 'learning_rate': 0.04773242676204397, 'momentum': 0.35678699942365216, 'weight_decay': 2.667958121762555e-06, 'elu_alpha': 0.4514459008814846}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:27:07,402] Trial 57 pruned.
[I 2026-09-24 13:28:13,363] Trial 58 pruned.
[I 2026-09-24 13:30:24,227] Trial 59 finished with value: 0.1954105794429779 and parameters: {'hidden_layer': 107, 'learning_rate': 0.030262457081581283, 'momentum': 0.6534820192846571, 'weight_decay': 2.3674623200542435e-06, 'elu_alpha': 0.33354807610391035}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:32:15,121] Trial 60 finished with value: 0.19589726626873016 and parameters: {'hidden_layer': 119, 'learning_rate': 0.024526708210810953, 'momentum': 0.7867332536630233, 'weight_decay': 5.228290994347989e-06, 'elu_alpha': 0.358356690631324}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:32:25,137] Trial 61 pruned.
[I 2026-09-24 13:33:03,039] Trial 62 pruned.
[I 2026-09-24 13:33:18,230] Trial 63 pruned.
[I 2026-09-24 13:33:29,009] Trial 64 pruned.
[I 2026-09-24 13:35:32,045] Trial 65 finished with value: 0.20013880729675293 and parameters: {'hidden_layer': 116, 'learning_rate': 0.03105681939680557, 'momentum': 0.710056274097164, 'weight_decay': 1.3737653577924302e-05, 'elu_alpha': 0.8238459168322937}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:35:55,785] Trial 66 pruned.
[I 2026-09-24 13:36:07,591] Trial 67 pruned.
[I 2026-09-24 13:36:35,729] Trial 68 pruned.
[I 2026-09-24 13:38:16,811] Trial 69 finished with value: 0.1975308656692505 and parameters: {'hidden_layer': 103, 'learning_rate': 0.07382446699344986, 'momentum': 0.7903621836274789, 'weight_decay': 5.324481115051095e-06, 'elu_alpha': 0.39201995240119303}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:38:35,839] Trial 70 pruned.
[I 2026-09-24 13:38:56,004] Trial 71 pruned.
[I 2026-09-24 13:40:33,726] Trial 72 finished with value: 0.19893355667591095 and parameters: {'hidden_layer': 73, 'learning_rate': 0.062446021921027495, 'momentum': 0.6117529123828377, 'weight_decay': 2.2717134769086363e-06, 'elu_alpha': 0.23664189221259535}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:41:10,789] Trial 73 pruned.
[I 2026-09-24 13:43:00,869] Trial 74 finished with value: 0.1976684033870697 and parameters: {'hidden_layer': 86, 'learning_rate': 0.051120930846810075, 'momentum': 0.7488827909399318, 'weight_decay': 1.7278184319023555e-06, 'elu_alpha': 0.10350246830262085}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:43:51,112] Trial 75 pruned.
[I 2026-09-24 13:44:04,229] Trial 76 pruned.
[I 2026-09-24 13:45:10,253] Trial 77 finished with value: 0.19977426528930664 and parameters: {'hidden_layer': 79, 'learning_rate': 0.08023982884814143, 'momentum': 0.7280407158581821, 'weight_decay': 1.0193958915591635e-06, 'elu_alpha': 0.3349185494023845}. Best is trial 12 with value: 0.19493986666202545.
[I 2026-09-24 13:45:20,969] Trial 78 pruned.
[I 2026-09-24 13:46:51,158] Trial 79 finished with value: 0.19442996382713318 and parameters: {'hidden_layer': 101, 'learning_rate': 0.02051626937237295, 'momentum': 0.8864171644674076, 'weight_decay': 4.672075226981389e-06, 'elu_alpha': 0.14735774864882512}. Best is trial 79 with value: 0.19442996382713318.
[I 2026-09-24 13:46:51,164] A new study created in memory with name: no-name-7d2b3d2e-9c37-496a-8021-b00d1ccb06d8

{'hidden_layer': 101, 'learning_rate': 0.02051626937237295, 'momentum': 0.8864171644674076, 'weight_decay': 4.672075226981389e-06, 'elu_alpha': 0.14735774864882512}
0.19442996382713318

[I 2026-09-24 13:51:52,237] Trial 0 finished with value: 0.20575518906116486 and parameters: {'hidden_layer': 19, 'learning_rate': 0.006891787018792772, 'momentum': 0.09777210430386579, 'weight_decay': 7.179828845546757e-06}. Best is trial 0 with value: 0.20575518906116486.
[I 2026-09-24 13:56:52,296] Trial 1 finished with value: 0.41323143243789673 and parameters: {'hidden_layer': 89, 'learning_rate': 0.0002451645106203906, 'momentum': 0.553913379963981, 'weight_decay': 0.001562107187700209}. Best is trial 0 with value: 0.20575518906116486.
[I 2026-09-24 14:02:22,269] Trial 2 finished with value: 0.21816515922546387 and parameters: {'hidden_layer': 62, 'learning_rate': 0.00015708629257586912, 'momentum': 0.9609589914977039, 'weight_decay': 1.1241140911007148e-05}. Best is trial 0 with value: 0.20575518906116486.
[I 2026-09-24 14:07:59,571] Trial 3 finished with value: 0.2898070514202118 and parameters: {'hidden_layer': 49, 'learning_rate': 0.0008313006017550257, 'momentum': 0.2302845652836995, 'weight_decay': 6.150789033845649e-05}. Best is trial 0 with value: 0.20575518906116486.
[I 2026-09-24 14:12:57,466] Trial 4 finished with value: 0.21440613269805908 and parameters: {'hidden_layer': 111, 'learning_rate': 0.005078250190460047, 'momentum': 0.012537435306102303, 'weight_decay': 6.025493186483491e-06}. Best is trial 0 with value: 0.20575518906116486.
[I 2026-09-24 14:13:54,918] Trial 5 pruned.
[I 2026-09-24 14:15:11,217] Trial 6 finished with value: 0.19694772362709045 and parameters: {'hidden_layer': 102, 'learning_rate': 0.03317214422993249, 'momentum': 0.8242836317454394, 'weight_decay': 0.0019039840433363454}. Best is trial 6 with value: 0.19694772362709045.
[I 2026-09-24 14:20:57,050] Trial 7 finished with value: 0.20777936279773712 and parameters: {'hidden_layer': 123, 'learning_rate': 0.0028292906326045555, 'momentum': 0.6369089389086, 'weight_decay': 1.0188195991368528e-05}. Best is trial 6 with value: 0.19694772362709045.
[I 2026-09-24 14:22:33,086] Trial 8 finished with value: 0.19699713587760925 and parameters: {'hidden_layer': 47, 'learning_rate': 0.050370251981576755, 'momentum': 0.7089024845032805, 'weight_decay': 0.0001231096374585953}. Best is trial 6 with value: 0.19694772362709045.
[I 2026-09-24 14:23:50,458] Trial 9 finished with value: 0.207393616437912 and parameters: {'hidden_layer': 30, 'learning_rate': 0.02223514432485003, 'momentum': 0.7771346221689707, 'weight_decay': 0.008944563751615736}. Best is trial 6 with value: 0.19694772362709045.
[I 2026-09-24 14:24:05,898] Trial 10 pruned.
[I 2026-09-24 14:25:14,880] Trial 11 finished with value: 0.19851073622703552 and parameters: {'hidden_layer': 89, 'learning_rate': 0.0975687790093705, 'momentum': 0.7748839798642029, 'weight_decay': 0.0004014898189149335}. Best is trial 6 with value: 0.19694772362709045.
[I 2026-09-24 14:25:40,810] Trial 12 pruned.
[I 2026-09-24 14:27:10,558] Trial 13 finished with value: 0.19835856556892395 and parameters: {'hidden_layer': 103, 'learning_rate': 0.02481998245335462, 'momentum': 0.7980943876831551, 'weight_decay': 0.0002626637235614239}. Best is trial 6 with value: 0.19694772362709045.
[I 2026-09-24 14:31:38,062] Trial 14 finished with value: 0.19829809665679932 and parameters: {'hidden_layer': 77, 'learning_rate': 0.011991011216953399, 'momentum': 0.3615646926391501, 'weight_decay': 1.3222224483070426e-06}. Best is trial 6 with value: 0.19694772362709045.
[I 2026-09-24 14:32:34,492] Trial 15 pruned.
[I 2026-09-24 14:32:41,930] Trial 16 pruned.
[I 2026-09-24 14:33:15,984] Trial 17 pruned.
[I 2026-09-24 14:34:51,292] Trial 18 finished with value: 0.19529667496681213 and parameters: {'hidden_layer': 75, 'learning_rate': 0.03779461258207708, 'momentum': 0.85413247408913, 'weight_decay': 0.0006828015779214209}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 14:40:08,694] Trial 19 finished with value: 0.20237627625465393 and parameters: {'hidden_layer': 103, 'learning_rate': 0.0013478980412398357, 'momentum': 0.8632164460062707, 'weight_decay': 0.0004304674915922645}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 14:40:40,944] Trial 20 pruned.
[I 2026-09-24 14:41:56,795] Trial 21 finished with value: 0.19893045723438263 and parameters: {'hidden_layer': 51, 'learning_rate': 0.0480671312407278, 'momentum': 0.7042105767418685, 'weight_decay': 0.00016711693061299278}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 14:43:27,951] Trial 22 finished with value: 0.20145824551582336 and parameters: {'hidden_layer': 78, 'learning_rate': 0.09040221325086195, 'momentum': 0.8545645506223605, 'weight_decay': 3.6498970378523624e-05}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 14:45:22,202] Trial 23 finished with value: 0.2006315439939499 and parameters: {'hidden_layer': 37, 'learning_rate': 0.029300038954612015, 'momentum': 0.6976390807355909, 'weight_decay': 0.003006159822106426}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 14:46:23,501] Trial 24 finished with value: 0.20253288745880127 and parameters: {'hidden_layer': 59, 'learning_rate': 0.044903086621356426, 'momentum': 0.8886546426311894, 'weight_decay': 0.0013774989047240142}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 14:49:22,629] Trial 25 finished with value: 0.19829657673835754 and parameters: {'hidden_layer': 101, 'learning_rate': 0.014108449383821478, 'momentum': 0.6201576297766347, 'weight_decay': 0.00021510426570136107}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 14:53:46,644] Trial 26 finished with value: 0.1989184021949768 and parameters: {'hidden_layer': 115, 'learning_rate': 0.005331365427456205, 'momentum': 0.7344779928020256, 'weight_decay': 0.0007121231802618726}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 14:56:05,296] Trial 27 finished with value: 0.1965148001909256 and parameters: {'hidden_layer': 83, 'learning_rate': 0.032809097705181436, 'momentum': 0.5298618735058961, 'weight_decay': 2.5850843603593917e-05}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 14:58:46,875] Trial 28 finished with value: 0.1979704052209854 and parameters: {'hidden_layer': 83, 'learning_rate': 0.01797602261490874, 'momentum': 0.5345051931822747, 'weight_decay': 1.842947412715056e-05}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 14:59:44,460] Trial 29 pruned.
[I 2026-09-24 15:00:45,310] Trial 30 pruned.
[I 2026-09-24 15:00:57,724] Trial 31 pruned.
[I 2026-09-24 15:02:03,323] Trial 32 finished with value: 0.20257997512817383 and parameters: {'hidden_layer': 80, 'learning_rate': 0.06659219302989285, 'momentum': 0.9295216036804727, 'weight_decay': 2.7624915620023087e-05}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 15:04:12,515] Trial 33 finished with value: 0.19727082550525665 and parameters: {'hidden_layer': 57, 'learning_rate': 0.03275374729225103, 'momentum': 0.628820457216749, 'weight_decay': 0.001320333266073714}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 15:04:25,636] Trial 34 pruned.
[I 2026-09-24 15:04:48,899] Trial 35 pruned.
[I 2026-09-24 15:05:00,349] Trial 36 pruned.
[I 2026-09-24 15:06:10,545] Trial 37 pruned.
[I 2026-09-24 15:06:47,144] Trial 38 pruned.
[I 2026-09-24 15:07:04,725] Trial 39 pruned.
[I 2026-09-24 15:08:10,249] Trial 40 pruned.
[I 2026-09-24 15:09:53,114] Trial 41 finished with value: 0.19749097526073456 and parameters: {'hidden_layer': 56, 'learning_rate': 0.029570955457305974, 'momentum': 0.6476845787847544, 'weight_decay': 0.0013498124920780124}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 15:10:05,069] Trial 42 pruned.
[I 2026-09-24 15:10:23,608] Trial 43 pruned.
[I 2026-09-24 15:11:00,762] Trial 44 pruned.
[I 2026-09-24 15:12:33,037] Trial 45 finished with value: 0.1972278654575348 and parameters: {'hidden_layer': 86, 'learning_rate': 0.07409963871761341, 'momentum': 0.6479482400859403, 'weight_decay': 0.0005525026044098466}. Best is trial 18 with value: 0.19529667496681213.
[I 2026-09-24 15:14:01,813] Trial 46 finished with value: 0.19460535049438477 and parameters: {'hidden_layer': 86, 'learning_rate': 0.06916135455563951, 'momentum': 0.8404367717780885, 'weight_decay': 0.0005393788572166543}. Best is trial 46 with value: 0.19460535049438477.
[I 2026-09-24 15:14:19,080] Trial 47 pruned.
[I 2026-09-24 15:16:17,016] Trial 48 finished with value: 0.19739466905593872 and parameters: {'hidden_layer': 75, 'learning_rate': 0.0170045814294272, 'momentum': 0.8414974132717912, 'weight_decay': 0.00026927077460735596}. Best is trial 46 with value: 0.19460535049438477.
[I 2026-09-24 15:17:17,168] Trial 49 pruned.
[I 2026-09-24 15:17:31,539] Trial 50 pruned.
[I 2026-09-24 15:19:13,969] Trial 51 finished with value: 0.19591274857521057 and parameters: {'hidden_layer': 87, 'learning_rate': 0.07164054702365916, 'momentum': 0.66204212828668, 'weight_decay': 0.0003698483090603026}. Best is trial 46 with value: 0.19460535049438477.
[I 2026-09-24 15:19:21,887] Trial 52 pruned.
[I 2026-09-24 15:19:32,774] Trial 53 pruned.
[I 2026-09-24 15:19:42,540] Trial 54 pruned.
[I 2026-09-24 15:20:03,650] Trial 55 pruned.
[I 2026-09-24 15:21:20,786] Trial 56 finished with value: 0.19661568105220795 and parameters: {'hidden_layer': 90, 'learning_rate': 0.059486917190477544, 'momentum': 0.838874118644012, 'weight_decay': 0.0008065864570585746}. Best is trial 46 with value: 0.19460535049438477.
[I 2026-09-24 15:21:34,185] Trial 57 pruned.
[I 2026-09-24 15:21:45,018] Trial 58 pruned.
[I 2026-09-24 15:21:52,785] Trial 59 pruned.
[I 2026-09-24 15:22:13,267] Trial 60 pruned.
[I 2026-09-24 15:23:33,349] Trial 61 finished with value: 0.19770966470241547 and parameters: {'hidden_layer': 85, 'learning_rate': 0.04385456976729937, 'momentum': 0.6730250798944951, 'weight_decay': 0.00013109595717075218}. Best is trial 46 with value: 0.19460535049438477.
[I 2026-09-24 15:23:47,528] Trial 62 pruned.
[I 2026-09-24 15:24:01,731] Trial 63 pruned.
[I 2026-09-24 15:25:20,444] Trial 64 finished with value: 0.19972053170204163 and parameters: {'hidden_layer': 67, 'learning_rate': 0.055655998797402156, 'momentum': 0.7104026979540365, 'weight_decay': 0.00016434921997229317}. Best is trial 46 with value: 0.19460535049438477.
[I 2026-09-24 15:25:35,967] Trial 65 pruned.
[I 2026-09-24 15:25:53,167] Trial 66 pruned.
[I 2026-09-24 15:26:06,597] Trial 67 pruned.
[I 2026-09-24 15:27:01,132] Trial 68 pruned.
[I 2026-09-24 15:27:39,216] Trial 69 pruned.
[I 2026-09-24 15:30:19,191] Trial 70 finished with value: 0.196393221616745 and parameters: {'hidden_layer': 117, 'learning_rate': 0.028145750272882214, 'momentum': 0.5697577291863885, 'weight_decay': 8.523246351071095e-05}. Best is trial 46 with value: 0.19460535049438477.
[I 2026-09-24 15:30:45,589] Trial 71 pruned.
[I 2026-09-24 15:31:08,215] Trial 72 pruned.
[I 2026-09-24 15:32:47,414] Trial 73 finished with value: 0.1958395540714264 and parameters: {'hidden_layer': 126, 'learning_rate': 0.043138055778235936, 'momentum': 0.6025739805330247, 'weight_decay': 6.788219702541154e-05}. Best is trial 46 with value: 0.19460535049438477.
[I 2026-09-24 15:33:07,735] Trial 74 pruned.
[I 2026-09-24 15:34:35,029] Trial 75 finished with value: 0.19626855850219727 and parameters: {'hidden_layer': 126, 'learning_rate': 0.05958608850033863, 'momentum': 0.5968630550898557, 'weight_decay': 2.8593230643194416e-05}. Best is trial 46 with value: 0.19460535049438477.
[I 2026-09-24 15:36:13,233] Trial 76 finished with value: 0.19676615297794342 and parameters: {'hidden_layer': 128, 'learning_rate': 0.06558416933850619, 'momentum': 0.5933028169162893, 'weight_decay': 3.114094506176348e-05}. Best is trial 46 with value: 0.19460535049438477.
[I 2026-09-24 15:36:26,409] Trial 77 pruned.
[I 2026-09-24 15:37:41,800] Trial 78 finished with value: 0.19852006435394287 and parameters: {'hidden_layer': 120, 'learning_rate': 0.09923464968031531, 'momentum': 0.6674791769262818, 'weight_decay': 2.553081621021435e-05}. Best is trial 46 with value: 0.19460535049438477.
[I 2026-09-24 15:37:52,255] Trial 79 pruned.
[I 2026-09-24 15:37:52,260] A new study created in memory with name: no-name-cc5c571f-eb59-481b-9318-d566e9146194

{'hidden_layer': 86, 'learning_rate': 0.06916135455563951, 'momentum': 0.8404367717780885, 'weight_decay': 0.0005393788572166543}
0.19460535049438477

[I 2026-09-24 15:43:04,131] Trial 0 finished with value: 0.21250960230827332 and parameters: {'hidden_layer': 46, 'learning_rate': 0.0061649117765305295, 'momentum': 0.026327865999117597, 'weight_decay': 3.4252575969670253e-06}. Best is trial 0 with value: 0.21250960230827332.
[I 2026-09-24 15:49:11,801] Trial 1 finished with value: 0.5587712526321411 and parameters: {'hidden_layer': 94, 'learning_rate': 0.00014306667156999147, 'momentum': 0.5856017619536737, 'weight_decay': 6.598749807683256e-05}. Best is trial 0 with value: 0.21250960230827332.
[I 2026-09-24 15:51:33,281] Trial 2 finished with value: 0.19777460396289825 and parameters: {'hidden_layer': 86, 'learning_rate': 0.01000314757145471, 'momentum': 0.915372569690932, 'weight_decay': 6.87168975312532e-05}. Best is trial 2 with value: 0.19777460396289825.
[I 2026-09-24 15:56:42,992] Trial 3 finished with value: 0.22301384806632996 and parameters: {'hidden_layer': 33, 'learning_rate': 0.006216506625991501, 'momentum': 0.4984433135412846, 'weight_decay': 0.008491086718110274}. Best is trial 2 with value: 0.19777460396289825.
[I 2026-09-24 16:02:57,341] Trial 4 finished with value: 0.2726334035396576 and parameters: {'hidden_layer': 42, 'learning_rate': 0.0013104994974122816, 'momentum': 0.07899491542688226, 'weight_decay': 0.0003529972369239509}. Best is trial 2 with value: 0.19777460396289825.
[I 2026-09-24 16:04:07,917] Trial 5 pruned.
[I 2026-09-24 16:05:18,009] Trial 6 pruned.
[I 2026-09-24 16:06:28,662] Trial 7 pruned.
[I 2026-09-24 16:07:37,123] Trial 8 pruned.
[I 2026-09-24 16:08:43,956] Trial 9 pruned.
[I 2026-09-24 16:08:51,061] Trial 10 pruned.
[I 2026-09-24 16:10:19,754] Trial 11 finished with value: 0.1976487934589386 and parameters: {'hidden_layer': 88, 'learning_rate': 0.010260998890041565, 'momentum': 0.9588329798305062, 'weight_decay': 6.074992551811758e-06}. Best is trial 11 with value: 0.1976487934589386.
[I 2026-09-24 16:10:27,478] Trial 12 pruned.
[I 2026-09-24 16:12:50,500] Trial 13 finished with value: 0.19922514259815216 and parameters: {'hidden_layer': 90, 'learning_rate': 0.015421609753837625, 'momentum': 0.7968422272088567, 'weight_decay': 9.918751620350613e-06}. Best is trial 11 with value: 0.1976487934589386.
[I 2026-09-24 16:14:33,702] Trial 14 finished with value: 0.1990017145872116 and parameters: {'hidden_layer': 111, 'learning_rate': 0.09200904227941106, 'momentum': 0.8046245456880503, 'weight_decay': 0.0001007830655305349}. Best is trial 11 with value: 0.1976487934589386.
[I 2026-09-24 16:18:29,963] Trial 15 finished with value: 0.19998875260353088 and parameters: {'hidden_layer': 80, 'learning_rate': 0.0059887424434836726, 'momentum': 0.8169002654838706, 'weight_decay': 7.386904756271259e-05}. Best is trial 11 with value: 0.1976487934589386.
[I 2026-09-24 16:22:31,287] Trial 16 finished with value: 0.19941000640392303 and parameters: {'hidden_layer': 109, 'learning_rate': 0.015495931617855707, 'momentum': 0.6592528483197415, 'weight_decay': 1.0945696291878523e-06}. Best is trial 11 with value: 0.1976487934589386.
[I 2026-09-24 16:24:27,240] Trial 17 finished with value: 0.19826741516590118 and parameters: {'hidden_layer': 72, 'learning_rate': 0.015898532957276987, 'momentum': 0.8846006660501893, 'weight_decay': 1.1232584065115825e-05}. Best is trial 11 with value: 0.1976487934589386.
[I 2026-09-24 16:25:33,602] Trial 18 pruned.
[I 2026-09-24 16:25:46,911] Trial 19 pruned.
[I 2026-09-24 16:26:58,702] Trial 20 pruned.
[I 2026-09-24 16:28:47,483] Trial 21 finished with value: 0.199599951505661 and parameters: {'hidden_layer': 75, 'learning_rate': 0.014136034577610002, 'momentum': 0.9022519791985952, 'weight_decay': 1.1972582786534356e-05}. Best is trial 11 with value: 0.1976487934589386.
[I 2026-09-24 16:31:33,850] Trial 22 finished with value: 0.19863054156303406 and parameters: {'hidden_layer': 70, 'learning_rate': 0.010182708559413223, 'momentum': 0.8455293335046096, 'weight_decay': 3.6110792848455234e-06}. Best is trial 11 with value: 0.1976487934589386.
[I 2026-09-24 16:31:48,150] Trial 23 pruned.
[I 2026-09-24 16:33:31,948] Trial 24 finished with value: 0.19720658659934998 and parameters: {'hidden_layer': 61, 'learning_rate': 0.0683777603178037, 'momentum': 0.7518242227052419, 'weight_decay': 8.356145520676276e-06}. Best is trial 24 with value: 0.19720658659934998.
[I 2026-09-24 16:33:46,919] Trial 25 pruned.
[I 2026-09-24 16:34:05,080] Trial 26 pruned.
[I 2026-09-24 16:34:22,597] Trial 27 pruned.
[I 2026-09-24 16:36:23,944] Trial 28 finished with value: 0.1973981410264969 and parameters: {'hidden_layer': 97, 'learning_rate': 0.00818921985462438, 'momentum': 0.9499632066132147, 'weight_decay': 5.480607671976691e-06}. Best is trial 24 with value: 0.19720658659934998.
[I 2026-09-24 16:36:33,158] Trial 29 pruned.
[I 2026-09-24 16:36:51,672] Trial 30 pruned.
[I 2026-09-24 16:39:30,647] Trial 31 finished with value: 0.20010456442832947 and parameters: {'hidden_layer': 84, 'learning_rate': 0.008549688325124111, 'momentum': 0.8609180273688692, 'weight_decay': 5.8082535529192035e-06}. Best is trial 24 with value: 0.19720658659934998.
[I 2026-09-24 16:40:11,569] Trial 32 pruned.
[I 2026-09-24 16:42:08,682] Trial 33 finished with value: 0.20012874901294708 and parameters: {'hidden_layer': 77, 'learning_rate': 0.004266443901339644, 'momentum': 0.9525553792455741, 'weight_decay': 4.5453748480257306e-05}. Best is trial 24 with value: 0.19720658659934998.
[I 2026-09-24 16:45:30,925] Trial 34 finished with value: 0.19821128249168396 and parameters: {'hidden_layer': 66, 'learning_rate': 0.009578362150725188, 'momentum': 0.8490648336997053, 'weight_decay': 2.0653311014890374e-06}. Best is trial 24 with value: 0.19720658659934998.
[I 2026-09-24 16:50:57,564] Trial 35 finished with value: 0.19933392107486725 and parameters: {'hidden_layer': 54, 'learning_rate': 0.007214825055347033, 'momentum': 0.6124495848821656, 'weight_decay': 5.85195413252967e-06}. Best is trial 24 with value: 0.19720658659934998.
[I 2026-09-24 16:53:15,244] Trial 36 finished with value: 0.1979309767484665 and parameters: {'hidden_layer': 96, 'learning_rate': 0.024401712979595366, 'momentum': 0.7608041916472184, 'weight_decay': 1.3992530086201583e-05}. Best is trial 24 with value: 0.19720658659934998.
[I 2026-09-24 16:54:22,304] Trial 37 pruned.
[I 2026-09-24 16:55:19,483] Trial 38 pruned.
[I 2026-09-24 16:56:24,907] Trial 39 pruned.
[I 2026-09-24 16:59:21,465] Trial 40 finished with value: 0.19824562966823578 and parameters: {'hidden_layer': 52, 'learning_rate': 0.020953864772427295, 'momentum': 0.6637428714922422, 'weight_decay': 5.3005062791574354e-05}. Best is trial 24 with value: 0.19720658659934998.
[I 2026-09-24 17:00:40,242] Trial 41 finished with value: 0.20059756934642792 and parameters: {'hidden_layer': 103, 'learning_rate': 0.0663849416168183, 'momentum': 0.7708130078310533, 'weight_decay': 1.6806571083466766e-05}. Best is trial 24 with value: 0.19720658659934998.
[I 2026-09-24 17:01:55,712] Trial 42 pruned.
[I 2026-09-24 17:04:05,819] Trial 43 finished with value: 0.1990853250026703 and parameters: {'hidden_layer': 117, 'learning_rate': 0.022756013785553603, 'momentum': 0.7423763289923636, 'weight_decay': 1.7483256984448636e-05}. Best is trial 24 with value: 0.19720658659934998.
[I 2026-09-24 17:04:46,948] Trial 44 pruned.
[I 2026-09-24 17:05:45,520] Trial 45 pruned.
[I 2026-09-24 17:07:28,640] Trial 46 finished with value: 0.19684985280036926 and parameters: {'hidden_layer': 97, 'learning_rate': 0.018728531471935195, 'momentum': 0.9478700338326816, 'weight_decay': 4.362214357026963e-06}. Best is trial 46 with value: 0.19684985280036926.
[I 2026-09-24 17:08:39,636] Trial 47 pruned.
[I 2026-09-24 17:08:58,169] Trial 48 pruned.
[I 2026-09-24 17:10:24,354] Trial 49 finished with value: 0.19877851009368896 and parameters: {'hidden_layer': 78, 'learning_rate': 0.01669774558316397, 'momentum': 0.9353162498410585, 'weight_decay': 1.2751894549613142e-06}. Best is trial 46 with value: 0.19684985280036926.
[I 2026-09-24 17:13:17,068] Trial 50 finished with value: 0.1973399519920349 and parameters: {'hidden_layer': 49, 'learning_rate': 0.011225010858308642, 'momentum': 0.8202419601075456, 'weight_decay': 4.35474920753278e-06}. Best is trial 46 with value: 0.19684985280036926.
[I 2026-09-24 17:14:18,102] Trial 51 pruned.
[I 2026-09-24 17:15:04,058] Trial 52 pruned.
[I 2026-09-24 17:15:24,754] Trial 53 pruned.
[I 2026-09-24 17:15:38,206] Trial 54 pruned.
[I 2026-09-24 17:17:38,668] Trial 55 finished with value: 0.19917576014995575 and parameters: {'hidden_layer': 48, 'learning_rate': 0.03284981046221159, 'momentum': 0.7988805782155435, 'weight_decay': 0.0010583311775070657}. Best is trial 46 with value: 0.19684985280036926.
[I 2026-09-24 17:19:39,036] Trial 56 finished with value: 0.1994093954563141 and parameters: {'hidden_layer': 101, 'learning_rate': 0.010724588701596689, 'momentum': 0.9265297996461723, 'weight_decay': 2.4288103075288778e-05}. Best is trial 46 with value: 0.19684985280036926.
[I 2026-09-24 17:20:31,435] Trial 57 pruned.
[I 2026-09-24 17:20:49,952] Trial 58 pruned.
[I 2026-09-24 17:21:04,540] Trial 59 pruned.
[I 2026-09-24 17:22:14,753] Trial 60 pruned.
[I 2026-09-24 17:24:07,695] Trial 61 finished with value: 0.19658465683460236 and parameters: {'hidden_layer': 99, 'learning_rate': 0.04548237754227203, 'momentum': 0.792845485986771, 'weight_decay': 1.2372930143932302e-05}. Best is trial 61 with value: 0.19658465683460236.
[I 2026-09-24 17:24:16,188] Trial 62 pruned.
[I 2026-09-24 17:25:26,443] Trial 63 finished with value: 0.19822059571743011 and parameters: {'hidden_layer': 109, 'learning_rate': 0.06535935321830195, 'momentum': 0.8967666480358648, 'weight_decay': 1.1922255552225076e-05}. Best is trial 61 with value: 0.19658465683460236.
[I 2026-09-24 17:25:40,672] Trial 64 pruned.
[I 2026-09-24 17:26:00,271] Trial 65 pruned.
[I 2026-09-24 17:29:20,345] Trial 66 finished with value: 0.19836260378360748 and parameters: {'hidden_layer': 93, 'learning_rate': 0.008970040318920427, 'momentum': 0.8664013959835557, 'weight_decay': 2.894895372794949e-05}. Best is trial 61 with value: 0.19658465683460236.
[I 2026-09-24 17:30:09,349] Trial 67 pruned.
[I 2026-09-24 17:30:23,881] Trial 68 pruned.
[I 2026-09-24 17:30:41,796] Trial 69 pruned.
[I 2026-09-24 17:31:00,000] Trial 70 pruned.
[I 2026-09-24 17:33:23,830] Trial 71 finished with value: 0.19787956774234772 and parameters: {'hidden_layer': 107, 'learning_rate': 0.02525359076493653, 'momentum': 0.7484340063578812, 'weight_decay': 1.4634900090592076e-05}. Best is trial 61 with value: 0.19658465683460236.
[I 2026-09-24 17:33:34,986] Trial 72 pruned.
[I 2026-09-24 17:36:51,022] Trial 73 finished with value: 0.19788047671318054 and parameters: {'hidden_layer': 107, 'learning_rate': 0.02018839633815299, 'momentum': 0.6298565058812167, 'weight_decay': 1.0162680742494428e-05}. Best is trial 61 with value: 0.19658465683460236.
[I 2026-09-24 17:37:47,086] Trial 74 pruned.
[I 2026-09-24 17:38:01,528] Trial 75 pruned.
[I 2026-09-24 17:40:50,417] Trial 76 finished with value: 0.1956712007522583 and parameters: {'hidden_layer': 57, 'learning_rate': 0.026731908629622256, 'momentum': 0.7455897737662243, 'weight_decay': 3.99937172643707e-06}. Best is trial 76 with value: 0.1956712007522583.
[I 2026-09-24 17:41:04,329] Trial 77 pruned.
[I 2026-09-24 17:41:42,454] Trial 78 pruned.
[I 2026-09-24 17:42:36,654] Trial 79 pruned.
[I 2026-09-24 17:42:36,659] A new study created in memory with name: no-name-cf520499-c0e9-489a-b172-e0842096e4e0

{'hidden_layer': 57, 'learning_rate': 0.026731908629622256, 'momentum': 0.7455897737662243, 'weight_decay': 3.99937172643707e-06}
0.1956712007522583

[I 2026-09-24 17:48:15,933] Trial 0 finished with value: 0.374485582113266 and parameters: {'hidden_layer': 70, 'learning_rate': 0.00024927065531605896, 'momentum': 0.6492330335921463, 'weight_decay': 1.2087112005111532e-06}. Best is trial 0 with value: 0.374485582113266.
[I 2026-09-24 17:53:57,007] Trial 1 finished with value: 0.3847348690032959 and parameters: {'hidden_layer': 93, 'learning_rate': 0.000497296738567034, 'momentum': 0.24224269611933166, 'weight_decay': 0.00013289185475650556}. Best is trial 0 with value: 0.374485582113266.
[I 2026-09-24 17:56:44,662] Trial 2 finished with value: 0.21049609780311584 and parameters: {'hidden_layer': 17, 'learning_rate': 0.013905546486568707, 'momentum': 0.5172550951043268, 'weight_decay': 2.8984542946793415e-06}. Best is trial 2 with value: 0.21049609780311584.
[I 2026-09-24 18:00:36,074] Trial 3 finished with value: 0.2036658525466919 and parameters: {'hidden_layer': 111, 'learning_rate': 0.003340192661172581, 'momentum': 0.8233046347797867, 'weight_decay': 0.00010453654248103145}. Best is trial 3 with value: 0.2036658525466919.
[I 2026-09-24 18:03:43,687] Trial 4 finished with value: 0.204203799366951 and parameters: {'hidden_layer': 125, 'learning_rate': 0.014392957979924471, 'momentum': 0.3781466025270735, 'weight_decay': 0.00018738606129558083}. Best is trial 3 with value: 0.2036658525466919.
[I 2026-09-24 18:05:01,007] Trial 5 pruned.
[I 2026-09-24 18:10:41,414] Trial 6 finished with value: 0.21145153045654297 and parameters: {'hidden_layer': 93, 'learning_rate': 0.004661094913205407, 'momentum': 0.3423612820167261, 'weight_decay': 4.504043147982282e-06}. Best is trial 3 with value: 0.2036658525466919.
[I 2026-09-24 18:11:49,337] Trial 7 pruned.
[I 2026-09-24 18:17:01,879] Trial 8 pruned.
[I 2026-09-24 18:18:03,920] Trial 9 pruned.
[I 2026-09-24 18:19:04,976] Trial 10 finished with value: 0.21442492306232452 and parameters: {'hidden_layer': 48, 'learning_rate': 0.08115763372345366, 'momentum': 0.9166938168030934, 'weight_decay': 3.0146202183585106e-05}. Best is trial 3 with value: 0.2036658525466919.
[I 2026-09-24 18:21:35,545] Trial 11 finished with value: 0.19989028573036194 and parameters: {'hidden_layer': 128, 'learning_rate': 0.016299026059511848, 'momentum': 0.7540116037447805, 'weight_decay': 0.0019007958587221934}. Best is trial 11 with value: 0.19989028573036194.
[I 2026-09-24 18:24:08,958] Trial 12 finished with value: 0.20310981571674347 and parameters: {'hidden_layer': 108, 'learning_rate': 0.011316475382810724, 'momentum': 0.7164714576932566, 'weight_decay': 0.00291584284720165}. Best is trial 11 with value: 0.19989028573036194.
[I 2026-09-24 18:25:53,359] Trial 13 finished with value: 0.2011980265378952 and parameters: {'hidden_layer': 107, 'learning_rate': 0.04000897464820287, 'momentum': 0.734621577512478, 'weight_decay': 0.0036098022685279447}. Best is trial 11 with value: 0.19989028573036194.
[I 2026-09-24 18:27:11,659] Trial 14 finished with value: 0.19962742924690247 and parameters: {'hidden_layer': 126, 'learning_rate': 0.0798218948112004, 'momentum': 0.7438367588502337, 'weight_decay': 0.0014129873756869623}. Best is trial 14 with value: 0.19962742924690247.
[I 2026-09-24 18:27:18,410] Trial 15 pruned.
[I 2026-09-24 18:28:43,693] Trial 16 finished with value: 0.19990584254264832 and parameters: {'hidden_layer': 48, 'learning_rate': 0.03267417578204841, 'momentum': 0.7669133142265888, 'weight_decay': 2.846360215545679e-05}. Best is trial 14 with value: 0.19962742924690247.
[I 2026-09-24 18:30:29,010] Trial 17 finished with value: 0.199337437748909 and parameters: {'hidden_layer': 97, 'learning_rate': 0.0309202271687087, 'momentum': 0.6506868798299958, 'weight_decay': 0.0011359862242961826}. Best is trial 17 with value: 0.199337437748909.
[I 2026-09-24 18:30:46,695] Trial 18 pruned.
[I 2026-09-24 18:31:28,958] Trial 19 pruned.
[I 2026-09-24 18:31:47,746] Trial 20 pruned.
[I 2026-09-24 18:34:09,867] Trial 21 finished with value: 0.20172648131847382 and parameters: {'hidden_layer': 127, 'learning_rate': 0.027521159115619018, 'momentum': 0.6514298427732086, 'weight_decay': 0.0028621687647541966}. Best is trial 17 with value: 0.199337437748909.
[I 2026-09-24 18:35:54,541] Trial 22 finished with value: 0.19889774918556213 and parameters: {'hidden_layer': 113, 'learning_rate': 0.021371199662210898, 'momentum': 0.882087157497973, 'weight_decay': 0.0015426476230115387}. Best is trial 22 with value: 0.19889774918556213.
[I 2026-09-24 18:37:00,063] Trial 23 finished with value: 0.20102441310882568 and parameters: {'hidden_layer': 114, 'learning_rate': 0.0524620911590461, 'momentum': 0.8913048161486834, 'weight_decay': 4.2083480757287445e-05}. Best is trial 22 with value: 0.19889774918556213.
[I 2026-09-24 18:37:13,968] Trial 24 pruned.
[I 2026-09-24 18:37:39,690] Trial 25 pruned.
[I 2026-09-24 18:39:32,596] Trial 26 finished with value: 0.19679072499275208 and parameters: {'hidden_layer': 117, 'learning_rate': 0.05739319354764544, 'momentum': 0.6199090799152979, 'weight_decay': 0.0003245595431309842}. Best is trial 26 with value: 0.19679072499275208.
[I 2026-09-24 18:39:59,844] Trial 27 pruned.
[I 2026-09-24 18:41:07,104] Trial 28 pruned.
[W 2026-09-24 18:41:50,358] Trial 29 failed with parameters: {'hidden_layer': 116, 'learning_rate': 0.001962626422012811, 'momentum': 0.6429897489234182, 'weight_decay': 0.00036877761110024396} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\optuna\study\_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "C:\Users\dawid\OneDrive - Stellenbosch University\Documents\Universiteit\4th year\ML\assignment3\ML441_Assigment3\active_learning.py", line 414, in obj
    model.fit(
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\backend\tensorflow\trainer.py", line 377, in fit
    logs = self.train_function(iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\backend\tensorflow\trainer.py", line 220, in function
    opt_outputs = multi_step_on_iterator(iterator)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\util\traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\polymorphic_function.py", line 833, in __call__
    result = self._call(*args, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\polymorphic_function.py", line 878, in _call
    results = tracing_compilation.call_function(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\tracing_compilation.py", line 139, in call_function
    return function._call_flat(  # pylint: disable=protected-access
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\concrete_function.py", line 1322, in _call_flat
    return self._inference_function.call_preflattened(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\atomic_function.py", line 216, in call_preflattened
    flat_outputs = self.call_flat(*args)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\atomic_function.py", line 251, in call_flat
    outputs = self._bound_context.call_function(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\context.py", line 1688, in call_function
    outputs = execute.execute(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
[W 2026-09-24 18:41:50,679] Trial 29 failed with value None.

KeyboardInterrupt:

In [9]:
acts = ['relu', 'leaky_relu', 'elu', 'gelu', 'swish']

results = []
name = "base"

for activation in acts:
    setup = {'activation': activation, 'balanced': state}
    alpha = 0
    params = retrieve_params(f'params/dry_bean/{name}_{activation}.json')
    if activation == 'leaky_relu':
        alpha = params["leaky_relu_alpha"]
    elif activation == 'elu':
        alpha = params["elu_alpha"]
    result = cv_classification(X_pool, y_pool, 
               out_units=n_classes, out_act='softmax', loss='sparse_categorical_crossentropy', k=5, random_state=42, 
               hidden_units=params['hidden_layer'], activation=activation, alpha=alpha, 
               learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], balanced=False)
    for key, val in result.items():
        setup[key] = val

    results.append(setup)

results_df = pd.DataFrame(results)
results_df.round(4).to_csv(f"results/dry_bean/cv_validation.csv", index=False)

## Student dropout

In [10]:
student_dropout = fetch_ucirepo(id=697)
dropout_df = pd.concat(
    [student_dropout.data.features, student_dropout.data.targets],
    axis=1
)
dropout_df.head()

,Marital Status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17,5,171,1,1,122.0,1,19,12,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15,1,9254,1,1,160.0,1,1,3,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1,5,9070,1,1,122.0,1,37,37,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17,2,9773,1,1,122.0,1,38,37,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39,1,8014,0,1,100.0,1,37,38,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [11]:
X = student_dropout.data.features.to_numpy()
student_encoder = LabelEncoder()
y = student_dropout.data.targets.to_numpy().ravel()

y = student_encoder.fit_transform(y)
dropout_map = student_encoder.classes_
n_classes = len(np.unique(y))

X_pool, X_test, y_pool, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=51
)

In [ ]:
acts = ['relu', 'leaky_relu', 'elu', 'gelu', 'swish']
name = 'base'
for activation in acts:
    base_params = tune_params(X_pool, y_pool,
                              loss='sparse_categorical_crossentropy',
                              out_units=n_classes, out_act='softmax',
                              k=5, activation=activation,
                              balanced=False,
                              random_state=42,
                              n_trials=80,
                              export=True, file = f'params/student_dropout/{name}_{activation}.json'
    )

[I 2026-09-24 20:18:40,418] A new study created in memory with name: no-name-e216e3c9-b63d-426e-a7af-a7a71cc14175
[I 2026-09-24 20:21:20,339] Trial 0 finished with value: 0.685571551322937 and parameters: {'hidden_layer': 93, 'learning_rate': 0.000332670473722622, 'momentum': 0.43414183367375986, 'weight_decay': 1.815090504102778e-05}. Best is trial 0 with value: 0.685571551322937.
[I 2026-09-24 20:23:54,482] Trial 1 finished with value: 0.7891916036605835 and parameters: {'hidden_layer': 53, 'learning_rate': 0.00023365750923479533, 'momentum': 0.1581928059374333, 'weight_decay': 0.001285086752112229}. Best is trial 0 with value: 0.685571551322937.
[I 2026-09-24 20:26:25,343] Trial 2 finished with value: 0.7188781499862671 and parameters: {'hidden_layer': 21, 'learning_rate': 0.0003544044690087883, 'momentum': 0.5258776857070462, 'weight_decay': 1.9429070217827516e-06}. Best is trial 0 with value: 0.685571551322937.
[I 2026-09-24 20:27:18,660] Trial 3 finished with value: 0.5888937711715698 and parameters: {'hidden_layer': 105, 'learning_rate': 0.03702585423013096, 'momentum': 0.1981860143832561, 'weight_decay': 6.59201456831699e-05}. Best is trial 3 with value: 0.5888937711715698.
[I 2026-09-24 20:28:11,759] Trial 4 finished with value: 0.5874055624008179 and parameters: {'hidden_layer': 109, 'learning_rate': 0.0045914371361161985, 'momentum': 0.8464703243089734, 'weight_decay': 0.00011376697766592036}. Best is trial 4 with value: 0.5874055624008179.
[I 2026-09-24 20:28:43,708] Trial 5 finished with value: 0.60506671667099 and parameters: {'hidden_layer': 25, 'learning_rate': 0.023512249972575294, 'momentum': 0.8130758723466993, 'weight_decay': 6.935041658901297e-06}. Best is trial 4 with value: 0.5874055624008179.
[I 2026-09-24 20:30:39,592] Trial 6 finished with value: 0.5900782346725464 and parameters: {'hidden_layer': 59, 'learning_rate': 0.004022149193497478, 'momentum': 0.6233888578337656, 'weight_decay': 2.6624807311278075e-05}. Best is trial 4 with value: 0.5874055624008179.
[I 2026-09-24 20:33:18,616] Trial 7 finished with value: 0.6006240844726562 and parameters: {'hidden_layer': 53, 'learning_rate': 0.0022715369538817117, 'momentum': 0.388278136604472, 'weight_decay': 5.202111815651979e-05}. Best is trial 4 with value: 0.5874055624008179.
[I 2026-09-24 20:33:51,384] Trial 8 pruned.
[I 2026-09-24 20:34:23,206] Trial 9 pruned.
[I 2026-09-24 20:34:29,070] Trial 10 pruned.
[I 2026-09-24 20:34:34,955] Trial 11 pruned.
[I 2026-09-24 20:35:22,871] Trial 12 finished with value: 0.583412766456604 and parameters: {'hidden_layer': 88, 'learning_rate': 0.08836711257922006, 'momentum': 0.25811123890019316, 'weight_decay': 0.008520787091900102}. Best is trial 12 with value: 0.583412766456604.
[I 2026-09-24 20:35:50,002] Trial 13 finished with value: 0.5958711504936218 and parameters: {'hidden_layer': 84, 'learning_rate': 0.009669804029653098, 'momentum': 0.9684071673288478, 'weight_decay': 0.0071964461713612425}. Best is trial 12 with value: 0.583412766456604.
[I 2026-09-24 20:36:37,481] Trial 14 finished with value: 0.5840243697166443 and parameters: {'hidden_layer': 121, 'learning_rate': 0.09741685650184026, 'momentum': 0.250244265324983, 'weight_decay': 0.008229249084095374}. Best is trial 12 with value: 0.583412766456604.
[I 2026-09-24 20:36:45,632] Trial 15 pruned.
[I 2026-09-24 20:37:32,445] Trial 16 finished with value: 0.5831956267356873 and parameters: {'hidden_layer': 128, 'learning_rate': 0.039636872644201356, 'momentum': 0.2920123170578374, 'weight_decay': 0.0018404034517817951}. Best is trial 16 with value: 0.5831956267356873.
[I 2026-09-24 20:38:12,777] Trial 17 finished with value: 0.5901738405227661 and parameters: {'hidden_layer': 72, 'learning_rate': 0.03952441595103588, 'momentum': 0.3388024982332091, 'weight_decay': 0.0015507437486802613}. Best is trial 16 with value: 0.5831956267356873.
[I 2026-09-24 20:38:42,615] Trial 18 pruned.
[I 2026-09-24 20:38:51,238] Trial 19 pruned.
[I 2026-09-24 20:39:21,613] Trial 20 pruned.
[I 2026-09-24 20:39:27,275] Trial 21 pruned.
[I 2026-09-24 20:39:39,178] Trial 22 pruned.
[I 2026-09-24 20:39:46,113] Trial 23 pruned.
[I 2026-09-24 20:42:03,264] Trial 24 finished with value: 0.5803558826446533 and parameters: {'hidden_layer': 100, 'learning_rate': 0.008188126365720121, 'momentum': 0.016762459613326564, 'weight_decay': 0.009929536884029715}. Best is trial 24 with value: 0.5803558826446533.
[I 2026-09-24 20:42:28,610] Trial 25 pruned.
[I 2026-09-24 20:42:47,692] Trial 26 pruned.
[I 2026-09-24 20:44:39,071] Trial 27 finished with value: 0.588528573513031 and parameters: {'hidden_layer': 81, 'learning_rate': 0.007743170805415075, 'momentum': 0.08651147984340127, 'weight_decay': 0.0006334839777986036}. Best is trial 24 with value: 0.5803558826446533.
[I 2026-09-24 20:44:45,599] Trial 28 pruned.
[I 2026-09-24 20:45:55,547] Trial 29 finished with value: 0.5870065093040466 and parameters: {'hidden_layer': 93, 'learning_rate': 0.01319176694749745, 'momentum': 0.4009821044927029, 'weight_decay': 0.0014129004662144715}. Best is trial 24 with value: 0.5803558826446533.
[I 2026-09-24 20:46:48,414] Trial 30 finished with value: 0.5861576199531555 and parameters: {'hidden_layer': 99, 'learning_rate': 0.022676674143797242, 'momentum': 0.4711218920969367, 'weight_decay': 0.004562881852355717}. Best is trial 24 with value: 0.5803558826446533.
[I 2026-09-24 20:47:38,872] Trial 31 finished with value: 0.5769588351249695 and parameters: {'hidden_layer': 112, 'learning_rate': 0.055494594572238556, 'momentum': 0.22664660545347926, 'weight_decay': 0.009417001986048786}. Best is trial 31 with value: 0.5769588351249695.
[I 2026-09-24 20:47:47,076] Trial 32 pruned.
[I 2026-09-24 20:48:00,103] Trial 33 pruned.
[I 2026-09-24 20:48:07,923] Trial 34 pruned.
[I 2026-09-24 20:48:37,895] Trial 35 pruned.
[I 2026-09-24 20:48:50,240] Trial 36 pruned.
[I 2026-09-24 20:49:08,536] Trial 37 pruned.
[I 2026-09-24 20:49:15,450] Trial 38 pruned.
[I 2026-09-24 20:49:26,856] Trial 39 pruned.
[I 2026-09-24 20:49:31,272] Trial 40 pruned.
[I 2026-09-24 20:50:28,301] Trial 41 finished with value: 0.5835605263710022 and parameters: {'hidden_layer': 120, 'learning_rate': 0.07352080214591289, 'momentum': 0.23797359948980676, 'weight_decay': 0.009609544535137394}. Best is trial 31 with value: 0.5769588351249695.
[I 2026-09-24 20:50:38,393] Trial 42 pruned.
[I 2026-09-24 20:50:47,083] Trial 43 pruned.
[I 2026-09-24 20:50:59,063] Trial 44 pruned.
[I 2026-09-24 20:51:07,173] Trial 45 pruned.
[I 2026-09-24 20:51:40,996] Trial 46 pruned.
[I 2026-09-24 20:54:17,491] Trial 47 finished with value: 0.5829880833625793 and parameters: {'hidden_layer': 78, 'learning_rate': 0.006267021166194643, 'momentum': 0.2580412993312393, 'weight_decay': 0.009926210803524524}. Best is trial 31 with value: 0.5769588351249695.
[I 2026-09-24 20:54:42,252] Trial 48 pruned.
[I 2026-09-24 20:55:01,324] Trial 49 pruned.
[I 2026-09-24 20:55:34,056] Trial 50 pruned.
[I 2026-09-24 20:56:06,610] Trial 51 pruned.
[I 2026-09-24 20:58:23,938] Trial 52 finished with value: 0.5796273350715637 and parameters: {'hidden_layer': 70, 'learning_rate': 0.010773873183021556, 'momentum': 0.20865925300789506, 'weight_decay': 0.009856977879032284}. Best is trial 31 with value: 0.5769588351249695.
[I 2026-09-24 20:58:34,748] Trial 53 pruned.
[I 2026-09-24 20:58:57,103] Trial 54 pruned.
[I 2026-09-24 20:59:23,544] Trial 55 pruned.
[I 2026-09-24 21:01:56,956] Trial 56 finished with value: 0.5850900411605835 and parameters: {'hidden_layer': 79, 'learning_rate': 0.0059589698843910315, 'momentum': 0.31178703214958636, 'weight_decay': 0.0071986375457617205}. Best is trial 31 with value: 0.5769588351249695.
[I 2026-09-24 21:02:31,026] Trial 57 pruned.
[I 2026-09-24 21:04:03,765] Trial 58 pruned.
[I 2026-09-24 21:04:19,631] Trial 59 pruned.
[I 2026-09-24 21:04:36,531] Trial 60 pruned.
[I 2026-09-24 21:05:20,042] Trial 61 finished with value: 0.575970470905304 and parameters: {'hidden_layer': 116, 'learning_rate': 0.07891131882926719, 'momentum': 0.24574476009598603, 'weight_decay': 0.007319333737600483}. Best is trial 61 with value: 0.575970470905304.
[I 2026-09-24 21:05:27,719] Trial 62 pruned.
[I 2026-09-24 21:05:34,786] Trial 63 pruned.
[I 2026-09-24 21:06:19,060] Trial 64 finished with value: 0.5850778818130493 and parameters: {'hidden_layer': 109, 'learning_rate': 0.07941069837294229, 'momentum': 0.3457342677512862, 'weight_decay': 0.005390552275276617}. Best is trial 61 with value: 0.575970470905304.
[I 2026-09-24 21:06:24,681] Trial 65 pruned.
[I 2026-09-24 21:06:44,922] Trial 66 pruned.
[I 2026-09-24 21:07:17,616] Trial 67 pruned.
[I 2026-09-24 21:07:33,004] Trial 68 pruned.
[I 2026-09-24 21:07:42,772] Trial 69 pruned.
[I 2026-09-24 21:10:31,531] Trial 70 finished with value: 0.5779221653938293 and parameters: {'hidden_layer': 123, 'learning_rate': 0.007811209764119316, 'momentum': 0.24254084318979507, 'weight_decay': 0.00989002248423567}. Best is trial 61 with value: 0.575970470905304.
[I 2026-09-24 21:13:23,164] Trial 71 finished with value: 0.5825577974319458 and parameters: {'hidden_layer': 116, 'learning_rate': 0.006796664352320072, 'momentum': 0.23435864787657135, 'weight_decay': 0.00984593300172365}. Best is trial 61 with value: 0.575970470905304.
[I 2026-09-24 21:13:41,858] Trial 72 pruned.
[I 2026-09-24 21:14:11,261] Trial 73 pruned.
[I 2026-09-24 21:15:38,114] Trial 74 pruned.
[I 2026-09-24 21:18:04,448] Trial 75 finished with value: 0.5793102979660034 and parameters: {'hidden_layer': 108, 'learning_rate': 0.01070102112784219, 'momentum': 0.1772444313955776, 'weight_decay': 0.00893324160009878}. Best is trial 61 with value: 0.575970470905304.
[I 2026-09-24 21:19:52,177] Trial 76 pruned.
[I 2026-09-24 21:21:56,498] Trial 77 finished with value: 0.5774670243263245 and parameters: {'hidden_layer': 114, 'learning_rate': 0.011019088929831241, 'momentum': 0.16091423794184864, 'weight_decay': 0.007590074288601667}. Best is trial 61 with value: 0.575970470905304.
[I 2026-09-24 21:22:10,518] Trial 78 pruned.
[I 2026-09-24 21:24:34,787] Trial 79 finished with value: 0.5829592943191528 and parameters: {'hidden_layer': 105, 'learning_rate': 0.008573100659624681, 'momentum': 0.10062798066546653, 'weight_decay': 0.007436190931444354}. Best is trial 61 with value: 0.575970470905304.
[I 2026-09-24 21:24:34,793] A new study created in memory with name: no-name-35893988-d5c9-47d7-a7de-f33796f45629

{'hidden_layer': 116, 'learning_rate': 0.07891131882926719, 'momentum': 0.24574476009598603, 'weight_decay': 0.007319333737600483}
0.575970470905304

[I 2026-09-24 21:27:12,630] Trial 0 finished with value: 0.6275041699409485 and parameters: {'hidden_layer': 55, 'learning_rate': 0.001301097691867977, 'momentum': 0.14641735980957374, 'weight_decay': 1.2867470952177964e-05, 'leaky_relu_alpha': 0.001565679063972322}. Best is trial 0 with value: 0.6275041699409485.
[I 2026-09-24 21:29:47,534] Trial 1 finished with value: 0.7303287386894226 and parameters: {'hidden_layer': 97, 'learning_rate': 0.00025297626650023873, 'momentum': 0.18665515641500569, 'weight_decay': 3.0607843654848856e-06, 'leaky_relu_alpha': 0.06634204665438757}. Best is trial 0 with value: 0.6275041699409485.
[I 2026-09-24 21:32:26,608] Trial 2 finished with value: 0.6388384699821472 and parameters: {'hidden_layer': 12, 'learning_rate': 0.001921819171820562, 'momentum': 0.10383898604094759, 'weight_decay': 0.00012192339366717742, 'leaky_relu_alpha': 0.0889338021451944}. Best is trial 0 with value: 0.6275041699409485.
[I 2026-09-24 21:35:23,848] Trial 3 finished with value: 0.6451510190963745 and parameters: {'hidden_layer': 116, 'learning_rate': 0.00023225196194963455, 'momentum': 0.7230935230923456, 'weight_decay': 0.00018123166252773736, 'leaky_relu_alpha': 0.0037859670950883073}. Best is trial 0 with value: 0.6275041699409485.
[I 2026-09-24 21:36:51,677] Trial 4 finished with value: 0.5892899632453918 and parameters: {'hidden_layer': 29, 'learning_rate': 0.0027788761192223174, 'momentum': 0.842129880240342, 'weight_decay': 0.0034650428245774165, 'leaky_relu_alpha': 0.2179531953943768}. Best is trial 4 with value: 0.5892899632453918.
[I 2026-09-24 21:38:55,940] Trial 5 finished with value: 0.598709762096405 and parameters: {'hidden_layer': 52, 'learning_rate': 0.000972585259205889, 'momentum': 0.9205036952748983, 'weight_decay': 7.07658461544767e-06, 'leaky_relu_alpha': 0.0016364187099113137}. Best is trial 4 with value: 0.5892899632453918.
[I 2026-09-24 21:41:43,050] Trial 6 finished with value: 0.5918325185775757 and parameters: {'hidden_layer': 79, 'learning_rate': 0.0010034591481756284, 'momentum': 0.8126759222680158, 'weight_decay': 0.005111414159177215, 'leaky_relu_alpha': 0.0032209751028760103}. Best is trial 4 with value: 0.5892899632453918.

In [ ]:
acts = ['relu', 'leaky_relu', 'elu', 'gelu', 'swish']
name = "base"
for activation in acts:
    setup = {'activation': activation, 'balanced': state}
    alpha = 0
    params = retrieve_params(f'params/student_dropout/{name}_{activation}.json')
    if activation == 'leaky_relu':
        alpha = params["leaky_relu_alpha"]
    elif activation == 'elu':
        alpha = params["elu_alpha"]
    result = cv_classification(X_pool, y_pool, out_units=n_classes, out_act='softmax', 
                    loss='sparse_categorical_crossentropy', k=3, random_state=42, 
                    hidden_units=params['hidden_layer'], activation=activation, alpha=alpha, 
                    learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], balanced=False)
    for key, val in result.items():
        setup[key] = val

    results.append(setup)

results_df = pd.DataFrame(results)
results_df.round(4).to_csv(f"results/student_dropout/cv_validation.csv", index=False)