# Libraries

In [1]:
import numpy as np
import pandas as pd

from ucimlrepo import fetch_ucirepo
from sklearn.datasets import fetch_california_housing

from tensorflow.keras import layers, models
import tensorflow as tf

from sklearn.metrics import root_mean_squared_error, mean_absolute_error, mean_absolute_percentage_error, r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# own functions
from active_regression import random_sampling, uncertainty_sampling_reg, label_data, active_learning_reg, sasla_reg
from active_regression import tune_params, retrieve_params, cv_regression, create_regmodel

from time import time

# Models

## California Housing

In [10]:
california = fetch_california_housing(as_frame=True)
california_df = california.frame
california_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [11]:
X = california_df.drop(columns=['MedHouseVal']).to_numpy()
y = california_df.loc[:, 'MedHouseVal'].to_numpy()

X_pool, X_test, y_pool, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=51
)

In [5]:
acts = ['relu', 'leaky_relu', 'elu']
for activation in acts:
    base_params = tune_params(X_pool, y_pool,
                              loss='mse',
                              out_units=1, out_act='linear',
                              k=5, activation=activation,
                              random_state=42,
                              n_trials=80,
                              export=True, file = f'params/california/{activation}.json'
    )

[I 2026-09-25 07:37:05,168] A new study created in memory with name: no-name-595df385-cb03-48b6-b8c7-d5e3118a9b9b

WARNING:tensorflow:From C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

[I 2026-09-25 07:41:21,891] Trial 0 finished with value: 0.3916826523948034 and parameters: {'hidden_layer': 21, 'learning_rate': 0.003625073723242179, 'momentum': 0.367834230369271, 'weight_decay': 2.5430405201770885e-05}. Best is trial 0 with value: 0.3916826523948034.
[I 2026-09-25 07:41:28,609] Trial 1 finished with value: inf and parameters: {'hidden_layer': 55, 'learning_rate': 0.0044267163631692774, 'momentum': 0.7719791575309446, 'weight_decay': 4.871099891275516e-05}. Best is trial 0 with value: 0.3916826523948034.
[I 2026-09-25 07:47:38,742] Trial 2 finished with value: 0.5027052022348896 and parameters: {'hidden_layer': 30, 'learning_rate': 0.00030453461462901546, 'momentum': 0.003086914225791774, 'weight_decay': 2.7796470503845208e-05}. Best is trial 0 with value: 0.3916826523948034.
[I 2026-09-25 07:51:41,132] Trial 3 finished with value: 0.35935990197524603 and parameters: {'hidden_layer': 80, 'learning_rate': 0.006751255703576771, 'momentum': 0.16903264886659605, 'weight_decay': 0.0003044917422042604}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 07:58:33,840] Trial 4 finished with value: 0.47797452782118893 and parameters: {'hidden_layer': 36, 'learning_rate': 0.0001231110363448914, 'momentum': 0.7215392449250452, 'weight_decay': 1.5735252617682372e-05}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 07:59:55,419] Trial 5 pruned.
[I 2026-09-25 08:01:10,017] Trial 6 pruned.
[I 2026-09-25 08:04:37,891] Trial 7 finished with value: 0.3615210895310855 and parameters: {'hidden_layer': 72, 'learning_rate': 0.004133888435140076, 'momentum': 0.5141885184994636, 'weight_decay': 9.990706223896004e-05}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:05:50,538] Trial 8 pruned.
[I 2026-09-25 08:09:29,427] Trial 9 finished with value: 0.37098183687488506 and parameters: {'hidden_layer': 39, 'learning_rate': 0.000897925489144942, 'momentum': 0.8702193717746981, 'weight_decay': 1.1784209912208708e-05}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:11:10,097] Trial 10 finished with value: inf and parameters: {'hidden_layer': 86, 'learning_rate': 0.008421044735419327, 'momentum': 0.2293431470089783, 'weight_decay': 0.0035635396046568586}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:11:55,343] Trial 11 pruned.
[I 2026-09-25 08:12:01,878] Trial 12 finished with value: inf and parameters: {'hidden_layer': 76, 'learning_rate': 0.00788757216072886, 'momentum': 0.33560539948576973, 'weight_decay': 1.378240451888127e-06}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:12:06,850] Trial 13 finished with value: inf and parameters: {'hidden_layer': 98, 'learning_rate': 0.0014967976809352346, 'momentum': 0.989892017034552, 'weight_decay': 0.000574289347691211}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:17:53,207] Trial 14 finished with value: 0.3720132288913812 and parameters: {'hidden_layer': 60, 'learning_rate': 0.004444256889746512, 'momentum': 0.0020945332569987096, 'weight_decay': 0.0007183839372701406}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:19:00,360] Trial 15 pruned.
[I 2026-09-25 08:20:13,429] Trial 16 pruned.
[I 2026-09-25 08:21:08,194] Trial 17 finished with value: inf and parameters: {'hidden_layer': 99, 'learning_rate': 0.009249039177796847, 'momentum': 0.1654916655980712, 'weight_decay': 0.0002431953131887193}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:21:26,885] Trial 18 pruned.
[I 2026-09-25 08:27:02,776] Trial 19 finished with value: 0.37022260382048483 and parameters: {'hidden_layer': 51, 'learning_rate': 0.0028073336186535246, 'momentum': 0.4528908894882496, 'weight_decay': 0.0017623577083386763}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:27:27,770] Trial 20 pruned.
[I 2026-09-25 08:28:41,357] Trial 21 pruned.
[I 2026-09-25 08:29:33,777] Trial 22 pruned.
[I 2026-09-25 08:30:49,651] Trial 23 pruned.
[I 2026-09-25 08:32:03,593] Trial 24 pruned.
[I 2026-09-25 08:33:18,215] Trial 25 pruned.
[I 2026-09-25 08:33:52,572] Trial 26 pruned.
[I 2026-09-25 08:33:59,440] Trial 27 finished with value: inf and parameters: {'hidden_layer': 92, 'learning_rate': 0.0037217652460164417, 'momentum': 0.8114886005634561, 'weight_decay': 0.00016266779351491281}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:35:14,365] Trial 28 pruned.
[I 2026-09-25 08:36:27,851] Trial 29 pruned.
[I 2026-09-25 08:39:14,051] Trial 30 finished with value: inf and parameters: {'hidden_layer': 64, 'learning_rate': 0.006040182403191989, 'momentum': 0.405551593303278, 'weight_decay': 0.0005126679654698297}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:39:21,434] Trial 31 finished with value: inf and parameters: {'hidden_layer': 43, 'learning_rate': 0.0008240422821081872, 'momentum': 0.9752529935145924, 'weight_decay': 7.772399028749634e-06}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:43:25,787] Trial 32 finished with value: 0.3774068834831906 and parameters: {'hidden_layer': 33, 'learning_rate': 0.0006922138929961935, 'momentum': 0.8930491740087961, 'weight_decay': 1.2296467333672927e-05}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:44:45,746] Trial 33 pruned.
[I 2026-09-25 08:45:15,269] Trial 34 pruned.
[I 2026-09-25 08:45:56,424] Trial 35 pruned.
[I 2026-09-25 08:48:51,636] Trial 36 finished with value: 0.3590877110713562 and parameters: {'hidden_layer': 74, 'learning_rate': 0.0018151866586540834, 'momentum': 0.7973662107501709, 'weight_decay': 1.7969467048451465e-05}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 08:50:07,039] Trial 37 pruned.
[I 2026-09-25 08:53:27,455] Trial 38 finished with value: inf and parameters: {'hidden_layer': 109, 'learning_rate': 0.0034471624984945292, 'momentum': 0.48491014291623796, 'weight_decay': 0.00013229225557744728}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 08:53:34,101] Trial 39 finished with value: inf and parameters: {'hidden_layer': 91, 'learning_rate': 0.004785291707316061, 'momentum': 0.7448247314116762, 'weight_decay': 8.571076166101852e-05}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 08:53:40,712] Trial 40 finished with value: inf and parameters: {'hidden_layer': 64, 'learning_rate': 0.007151782158721232, 'momentum': 0.8330715535265405, 'weight_decay': 5.2722120475392176e-05}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 08:54:20,413] Trial 41 pruned.
[I 2026-09-25 08:55:33,105] Trial 42 pruned.
[I 2026-09-25 08:56:02,638] Trial 43 pruned.
[I 2026-09-25 08:56:09,190] Trial 44 finished with value: inf and parameters: {'hidden_layer': 58, 'learning_rate': 0.0018123760735909017, 'momentum': 0.9162600001162704, 'weight_decay': 2.3696065575836914e-05}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 08:56:15,765] Trial 45 finished with value: inf and parameters: {'hidden_layer': 40, 'learning_rate': 0.00976003674787147, 'momentum': 0.6029941209700773, 'weight_decay': 8.052763066316213e-06}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 08:57:26,097] Trial 46 pruned.
[I 2026-09-25 08:58:04,890] Trial 47 pruned.
[I 2026-09-25 08:58:28,806] Trial 48 pruned.
[I 2026-09-25 08:59:27,526] Trial 49 pruned.
[I 2026-09-25 09:00:05,623] Trial 50 pruned.
[I 2026-09-25 09:01:18,884] Trial 51 pruned.
[I 2026-09-25 09:02:31,932] Trial 52 pruned.
[I 2026-09-25 09:03:38,940] Trial 53 pruned.
[I 2026-09-25 09:04:52,389] Trial 54 pruned.
[I 2026-09-25 09:09:21,566] Trial 55 finished with value: 0.36950022871848837 and parameters: {'hidden_layer': 67, 'learning_rate': 0.005186448882729236, 'momentum': 0.06767825714814266, 'weight_decay': 0.00023356990188993325}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 09:11:42,916] Trial 56 finished with value: inf and parameters: {'hidden_layer': 65, 'learning_rate': 0.008026719266815288, 'momentum': 0.28071052662188856, 'weight_decay': 0.0002493139056812603}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 09:12:51,876] Trial 57 pruned.
[I 2026-09-25 09:12:58,670] Trial 58 finished with value: inf and parameters: {'hidden_layer': 96, 'learning_rate': 0.006131762048176275, 'momentum': 0.5589685935583462, 'weight_decay': 9.515295681817726e-05}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 09:14:01,448] Trial 59 pruned.
[I 2026-09-25 09:15:14,498] Trial 60 pruned.
[I 2026-09-25 09:16:28,265] Trial 61 pruned.
[I 2026-09-25 09:17:43,875] Trial 62 pruned.
[I 2026-09-25 09:18:10,841] Trial 63 pruned.
[I 2026-09-25 09:21:59,763] Trial 64 finished with value: 0.36323093248267446 and parameters: {'hidden_layer': 67, 'learning_rate': 0.006934874668806461, 'momentum': 0.030607902666808018, 'weight_decay': 0.00036262667751965833}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 09:22:54,274] Trial 65 pruned.
[I 2026-09-25 09:24:08,122] Trial 66 pruned.
[I 2026-09-25 09:24:14,961] Trial 67 finished with value: inf and parameters: {'hidden_layer': 67, 'learning_rate': 0.008663404224134886, 'momentum': 0.20616963586066686, 'weight_decay': 3.337422027803434e-05}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 09:27:00,273] Trial 68 finished with value: 0.36230527133664625 and parameters: {'hidden_layer': 48, 'learning_rate': 0.0004862544006524706, 'momentum': 0.9677372011838943, 'weight_decay': 0.008045151313705694}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 09:28:13,306] Trial 69 pruned.
[I 2026-09-25 09:28:21,846] Trial 70 finished with value: inf and parameters: {'hidden_layer': 62, 'learning_rate': 0.0037464344626873575, 'momentum': 0.9598605439953047, 'weight_decay': 0.004835021904821295}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 09:29:30,200] Trial 71 pruned.
[I 2026-09-25 09:30:27,046] Trial 72 pruned.
[I 2026-09-25 09:31:41,430] Trial 73 pruned.
[I 2026-09-25 09:32:30,904] Trial 74 pruned.
[I 2026-09-25 09:33:14,658] Trial 75 pruned.
[I 2026-09-25 09:34:28,783] Trial 76 pruned.
[I 2026-09-25 09:34:35,907] Trial 77 finished with value: inf and parameters: {'hidden_layer': 39, 'learning_rate': 0.0019222484165270868, 'momentum': 0.9823355990001733, 'weight_decay': 5.7182562045791815e-06}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 09:37:05,433] Trial 78 finished with value: inf and parameters: {'hidden_layer': 77, 'learning_rate': 0.006816852627542694, 'momentum': 0.5103375728963397, 'weight_decay': 0.000465591938405848}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 09:38:21,898] Trial 79 pruned.
[I 2026-09-25 09:38:21,903] A new study created in memory with name: no-name-b46efda9-933e-4e3c-ad70-7434da3a0381

{'hidden_layer': 74, 'learning_rate': 0.0018151866586540834, 'momentum': 0.7973662107501709, 'weight_decay': 1.7969467048451465e-05}
0.3590877110713562

[I 2026-09-25 09:44:25,376] Trial 0 finished with value: 0.4570477371068279 and parameters: {'hidden_layer': 42, 'learning_rate': 0.00028896699348474427, 'momentum': 0.5612715360675683, 'weight_decay': 0.0014350985614902906, 'leaky_relu_alpha': 0.009315682944208856}. Best is trial 0 with value: 0.4570477371068279.
[I 2026-09-25 09:48:17,114] Trial 1 finished with value: inf and parameters: {'hidden_layer': 127, 'learning_rate': 0.001363307018331313, 'momentum': 0.7636265700459369, 'weight_decay': 0.0027334731715486305, 'leaky_relu_alpha': 0.11080990486570994}. Best is trial 0 with value: 0.4570477371068279.
[I 2026-09-25 09:54:29,270] Trial 2 finished with value: 0.3639014486574298 and parameters: {'hidden_layer': 123, 'learning_rate': 0.0031019592521037984, 'momentum': 0.13211481220152355, 'weight_decay': 1.2633197640445262e-05, 'leaky_relu_alpha': 0.0040559735830498255}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 10:00:08,080] Trial 3 finished with value: 0.4500262387867406 and parameters: {'hidden_layer': 70, 'learning_rate': 0.0011129620720062986, 'momentum': 0.14876038961331017, 'weight_decay': 3.2544197312777775e-06, 'leaky_relu_alpha': 0.16274056343523874}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 10:04:44,842] Trial 4 finished with value: 0.6560605745740655 and parameters: {'hidden_layer': 29, 'learning_rate': 0.006066933989484268, 'momentum': 0.1640488479537832, 'weight_decay': 1.4284756826481268e-06, 'leaky_relu_alpha': 0.030922125907271492}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 10:07:41,629] Trial 5 pruned.
[I 2026-09-25 10:09:14,269] Trial 6 pruned.
[I 2026-09-25 10:09:22,776] Trial 7 finished with value: inf and parameters: {'hidden_layer': 59, 'learning_rate': 0.004722937988824842, 'momentum': 0.727806824114345, 'weight_decay': 7.164921036231217e-05, 'leaky_relu_alpha': 0.06758521103500197}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 10:10:55,274] Trial 8 pruned.
[I 2026-09-25 10:12:28,194] Trial 9 pruned.
[I 2026-09-25 10:19:36,303] Trial 10 finished with value: 0.3743084901022438 and parameters: {'hidden_layer': 126, 'learning_rate': 0.003085998449735609, 'momentum': 0.022570525223516547, 'weight_decay': 1.2925127946813972e-05, 'leaky_relu_alpha': 0.006286072161644384}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 10:26:17,273] Trial 11 finished with value: 0.37801537767005017 and parameters: {'hidden_layer': 125, 'learning_rate': 0.0030603039124089708, 'momentum': 0.013762780956428826, 'weight_decay': 1.6950764276881127e-05, 'leaky_relu_alpha': 0.005074886518117673}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 10:26:26,014] Trial 12 finished with value: inf and parameters: {'hidden_layer': 104, 'learning_rate': 0.009552291926402234, 'momentum': 0.9760330522914432, 'weight_decay': 1.4164862913956705e-05, 'leaky_relu_alpha': 0.0044256570665292564}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 10:34:01,747] Trial 13 finished with value: 0.3737985634859795 and parameters: {'hidden_layer': 113, 'learning_rate': 0.003024024863355713, 'momentum': 0.028617967748393675, 'weight_decay': 0.0002992875093159527, 'leaky_relu_alpha': 0.007561773118364016}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 10:41:11,436] Trial 14 finished with value: 0.3726778163451504 and parameters: {'hidden_layer': 85, 'learning_rate': 0.0024183170560072896, 'momentum': 0.30588378425287344, 'weight_decay': 0.0005126489487494641, 'leaky_relu_alpha': 0.002994900173532033}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 10:42:35,437] Trial 15 pruned.
[I 2026-09-25 10:44:01,280] Trial 16 pruned.
[I 2026-09-25 10:45:33,790] Trial 17 pruned.
[I 2026-09-25 10:47:03,743] Trial 18 pruned.
[I 2026-09-25 10:54:11,727] Trial 19 finished with value: 0.376818358315537 and parameters: {'hidden_layer': 114, 'learning_rate': 0.0018530791929472466, 'momentum': 0.4098265990274519, 'weight_decay': 4.300766686494685e-06, 'leaky_relu_alpha': 0.0022191534735745344}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 10:57:37,739] Trial 20 finished with value: inf and parameters: {'hidden_layer': 72, 'learning_rate': 0.005939607572922575, 'momentum': 0.2226004096081326, 'weight_decay': 1.100513793741947e-06, 'leaky_relu_alpha': 0.003328459976389941}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 11:03:38,235] Trial 21 finished with value: 0.3722761224252094 and parameters: {'hidden_layer': 113, 'learning_rate': 0.0031997254958048924, 'momentum': 0.08504387500279587, 'weight_decay': 0.0002036946692226469, 'leaky_relu_alpha': 0.00869359025197983}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 11:09:54,825] Trial 22 finished with value: 0.3573790454282096 and parameters: {'hidden_layer': 112, 'learning_rate': 0.004186255774632859, 'momentum': 0.07428273924667625, 'weight_decay': 0.0007528503127045853, 'leaky_relu_alpha': 0.014692463332986903}. Best is trial 22 with value: 0.3573790454282096.
[I 2026-09-25 11:10:16,957] Trial 23 pruned.
[I 2026-09-25 11:16:02,763] Trial 24 finished with value: 0.3618034142081308 and parameters: {'hidden_layer': 117, 'learning_rate': 0.0041680438980751, 'momentum': 0.10243046283694787, 'weight_decay': 2.8893239884764883e-05, 'leaky_relu_alpha': 0.012102686028024678}. Best is trial 22 with value: 0.3573790454282096.
[I 2026-09-25 11:21:10,752] Trial 25 finished with value: 0.3592460827407532 and parameters: {'hidden_layer': 93, 'learning_rate': 0.004750099148554186, 'momentum': 0.11508874528699288, 'weight_decay': 3.134535823023502e-05, 'leaky_relu_alpha': 0.015194884245874323}. Best is trial 22 with value: 0.3573790454282096.
[I 2026-09-25 11:24:25,072] Trial 26 finished with value: inf and parameters: {'hidden_layer': 95, 'learning_rate': 0.0047518608975562525, 'momentum': 0.22843383246838367, 'weight_decay': 2.8285696552659587e-05, 'leaky_relu_alpha': 0.013373185689856185}. Best is trial 22 with value: 0.3573790454282096.
[I 2026-09-25 11:27:42,109] Trial 27 finished with value: inf and parameters: {'hidden_layer': 105, 'learning_rate': 0.006386121868960171, 'momentum': 0.07908973609760496, 'weight_decay': 0.0008774752514145896, 'leaky_relu_alpha': 0.03550710425833637}. Best is trial 22 with value: 0.3573790454282096.
[I 2026-09-25 11:28:55,887] Trial 28 pruned.
[I 2026-09-25 11:30:10,779] Trial 29 pruned.
[I 2026-09-25 11:31:25,610] Trial 30 pruned.
[I 2026-09-25 11:37:19,138] Trial 31 finished with value: 0.3577676287294253 and parameters: {'hidden_layer': 122, 'learning_rate': 0.004450876149795951, 'momentum': 0.10425539481277767, 'weight_decay': 3.0104232686380684e-05, 'leaky_relu_alpha': 0.010353525469877303}. Best is trial 22 with value: 0.3573790454282096.
[I 2026-09-25 11:43:15,082] Trial 32 finished with value: 0.354270402080534 and parameters: {'hidden_layer': 120, 'learning_rate': 0.004400260691686097, 'momentum': 0.10294424836361865, 'weight_decay': 8.504623283074862e-05, 'leaky_relu_alpha': 0.01109933865886212}. Best is trial 32 with value: 0.354270402080534.
[I 2026-09-25 11:43:23,197] Trial 33 finished with value: inf and parameters: {'hidden_layer': 128, 'learning_rate': 0.007499435499643236, 'momentum': 0.18935037803533783, 'weight_decay': 8.485629658018623e-05, 'leaky_relu_alpha': 0.009451499569162303}. Best is trial 32 with value: 0.354270402080534.
[I 2026-09-25 11:44:38,195] Trial 34 pruned.
[I 2026-09-25 11:46:10,123] Trial 35 finished with value: inf and parameters: {'hidden_layer': 110, 'learning_rate': 0.007374492509943337, 'momentum': 0.14093924605778088, 'weight_decay': 3.0793505141484836e-05, 'leaky_relu_alpha': 0.006203040515955463}. Best is trial 32 with value: 0.354270402080534.
[I 2026-09-25 11:47:33,762] Trial 36 finished with value: inf and parameters: {'hidden_layer': 91, 'learning_rate': 0.0023527007242166815, 'momentum': 0.7059462534275397, 'weight_decay': 7.470240561322057e-05, 'leaky_relu_alpha': 0.015308193045368797}. Best is trial 32 with value: 0.354270402080534.
[I 2026-09-25 11:48:50,681] Trial 37 pruned.
[I 2026-09-25 11:50:03,353] Trial 38 finished with value: inf and parameters: {'hidden_layer': 102, 'learning_rate': 0.005444810019088378, 'momentum': 0.17188085777821366, 'weight_decay': 8.501538328567935e-06, 'leaky_relu_alpha': 0.030970872375432692}. Best is trial 32 with value: 0.354270402080534.
[I 2026-09-25 11:50:10,402] Trial 39 finished with value: inf and parameters: {'hidden_layer': 75, 'learning_rate': 0.00376746445880701, 'momentum': 0.9857357753856419, 'weight_decay': 2.255554227581373e-06, 'leaky_relu_alpha': 0.07356742712863355}. Best is trial 32 with value: 0.354270402080534.
[I 2026-09-25 11:51:25,507] Trial 40 pruned.
[I 2026-09-25 11:57:17,907] Trial 41 finished with value: 0.35374399768039405 and parameters: {'hidden_layer': 118, 'learning_rate': 0.0050284500691448065, 'momentum': 0.1195419232485179, 'weight_decay': 4.850866476682255e-05, 'leaky_relu_alpha': 0.019506072456604167}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:00:13,206] Trial 42 finished with value: 0.3626971110885347 and parameters: {'hidden_layer': 120, 'learning_rate': 0.007555523844093053, 'momentum': 0.1144694613412357, 'weight_decay': 4.562445027924939e-05, 'leaky_relu_alpha': 0.01787539747894487}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:06:05,213] Trial 43 finished with value: 0.35506512130421525 and parameters: {'hidden_layer': 128, 'learning_rate': 0.004953671410600529, 'momentum': 0.1817860365291694, 'weight_decay': 5.9621282704095475e-05, 'leaky_relu_alpha': 0.021368415051506877}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:07:18,398] Trial 44 pruned.
[I 2026-09-25 12:13:09,361] Trial 45 finished with value: 0.3602908289237614 and parameters: {'hidden_layer': 107, 'learning_rate': 0.003768573849278384, 'momentum': 0.1893585467682783, 'weight_decay': 5.9457915345280275e-05, 'leaky_relu_alpha': 0.007067461729383667}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:13:59,029] Trial 46 pruned.
[I 2026-09-25 12:14:48,960] Trial 47 finished with value: inf and parameters: {'hidden_layer': 118, 'learning_rate': 0.008989113044302149, 'momentum': 0.16300258212430832, 'weight_decay': 8.771326104232422e-06, 'leaky_relu_alpha': 0.01039618594588215}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:14:55,998] Trial 48 finished with value: inf and parameters: {'hidden_layer': 100, 'learning_rate': 0.0062687445685001624, 'momentum': 0.6378726016553153, 'weight_decay': 0.0006268667578457255, 'leaky_relu_alpha': 0.0052517187526441005}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:16:10,210] Trial 49 pruned.
[I 2026-09-25 12:17:10,374] Trial 50 pruned.
[I 2026-09-25 12:23:00,768] Trial 51 finished with value: 0.3601886625034824 and parameters: {'hidden_layer': 108, 'learning_rate': 0.004449380600914902, 'momentum': 0.11921282616177196, 'weight_decay': 4.562671969741101e-05, 'leaky_relu_alpha': 0.014526210232399538}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:23:07,995] Trial 52 finished with value: inf and parameters: {'hidden_layer': 115, 'learning_rate': 0.005337507135746012, 'momentum': 0.911121211854161, 'weight_decay': 6.787244234134047e-05, 'leaky_relu_alpha': 0.007970415991692527}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:23:37,904] Trial 53 pruned.
[I 2026-09-25 12:24:54,498] Trial 54 pruned.
[I 2026-09-25 12:26:09,052] Trial 55 pruned.
[I 2026-09-25 12:31:26,961] Trial 56 finished with value: 0.3639958627557058 and parameters: {'hidden_layer': 118, 'learning_rate': 0.004859893257961968, 'momentum': 0.03744664373828034, 'weight_decay': 1.3349613026230329e-05, 'leaky_relu_alpha': 0.025778694069503026}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:32:34,376] Trial 57 pruned.
[I 2026-09-25 12:33:36,168] Trial 58 pruned.
[I 2026-09-25 12:33:44,192] Trial 59 finished with value: inf and parameters: {'hidden_layer': 114, 'learning_rate': 0.008480938456219174, 'momentum': 0.04128042937413949, 'weight_decay': 0.00015230086817114, 'leaky_relu_alpha': 0.01299972439400726}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:35:07,182] Trial 60 pruned.
[I 2026-09-25 12:41:51,230] Trial 61 finished with value: 0.35914707392023504 and parameters: {'hidden_layer': 108, 'learning_rate': 0.004158242903116138, 'momentum': 0.09804308241031977, 'weight_decay': 4.1853010550892897e-05, 'leaky_relu_alpha': 0.014067271821728549}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:47:42,102] Trial 62 finished with value: 0.3600285433408562 and parameters: {'hidden_layer': 90, 'learning_rate': 0.004261661244013881, 'momentum': 0.20660153121458322, 'weight_decay': 8.932375628324713e-05, 'leaky_relu_alpha': 0.019818888730471867}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:48:27,140] Trial 63 pruned.
[I 2026-09-25 12:49:46,942] Trial 64 pruned.
[I 2026-09-25 12:51:16,642] Trial 65 pruned.
[I 2026-09-25 12:52:16,785] Trial 66 pruned.
[I 2026-09-25 12:57:12,240] Trial 67 finished with value: 0.3560260847217189 and parameters: {'hidden_layer': 120, 'learning_rate': 0.005048100634340998, 'momentum': 0.1385060531231384, 'weight_decay': 2.5054691687389152e-05, 'leaky_relu_alpha': 0.019978702116714847}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:58:19,685] Trial 68 pruned.
[I 2026-09-25 12:58:53,446] Trial 69 pruned.
[I 2026-09-25 13:05:02,838] Trial 70 finished with value: 0.35165084131526525 and parameters: {'hidden_layer': 118, 'learning_rate': 0.00555669549526032, 'momentum': 0.03357246500483846, 'weight_decay': 5.7525084300726465e-06, 'leaky_relu_alpha': 0.0043701136142289005}. Best is trial 70 with value: 0.35165084131526525.
[I 2026-09-25 13:09:21,229] Trial 71 finished with value: inf and parameters: {'hidden_layer': 118, 'learning_rate': 0.005907208393499563, 'momentum': 0.03374486820277567, 'weight_decay': 2.0089244407501634e-06, 'leaky_relu_alpha': 0.02123638904965488}. Best is trial 70 with value: 0.35165084131526525.
[I 2026-09-25 13:15:22,060] Trial 72 finished with value: 0.35665213495633025 and parameters: {'hidden_layer': 112, 'learning_rate': 0.005355730175489363, 'momentum': 0.005256875313842273, 'weight_decay': 6.2255306323930556e-06, 'leaky_relu_alpha': 0.0016915642457500273}. Best is trial 70 with value: 0.35165084131526525.
[I 2026-09-25 13:18:19,276] Trial 73 finished with value: inf and parameters: {'hidden_layer': 112, 'learning_rate': 0.008012494769850984, 'momentum': 0.005220184599177617, 'weight_decay': 5.006497910651872e-06, 'leaky_relu_alpha': 0.0016461168827407455}. Best is trial 70 with value: 0.35165084131526525.
[I 2026-09-25 13:18:38,699] Trial 74 pruned.
[I 2026-09-25 13:24:42,881] Trial 75 finished with value: 0.35092531902181173 and parameters: {'hidden_layer': 120, 'learning_rate': 0.005317746800160751, 'momentum': 0.20894003959285906, 'weight_decay': 2.9130934686171106e-06, 'leaky_relu_alpha': 0.0029763805914404997}. Best is trial 75 with value: 0.35092531902181173.
[I 2026-09-25 13:29:51,215] Trial 76 finished with value: inf and parameters: {'hidden_layer': 116, 'learning_rate': 0.005431080291943264, 'momentum': 0.20377019029930843, 'weight_decay': 3.169131530434142e-06, 'leaky_relu_alpha': 0.0016283490486115114}. Best is trial 75 with value: 0.35092531902181173.
[I 2026-09-25 13:31:22,014] Trial 77 pruned.
[I 2026-09-25 13:32:22,322] Trial 78 pruned.
[I 2026-09-25 13:33:49,271] Trial 79 pruned.
[I 2026-09-25 13:33:49,278] A new study created in memory with name: no-name-fd22ff0d-8fed-45b8-9c5e-7d4578014ad0

{'hidden_layer': 120, 'learning_rate': 0.005317746800160751, 'momentum': 0.20894003959285906, 'weight_decay': 2.9130934686171106e-06, 'leaky_relu_alpha': 0.0029763805914404997}
0.35092531902181173

[I 2026-09-25 13:39:50,793] Trial 0 finished with value: 0.4693701107610641 and parameters: {'hidden_layer': 47, 'learning_rate': 0.001734262365906389, 'momentum': 0.5047107896315642, 'weight_decay': 0.002032046171562881, 'elu_alpha': 1.3388134873784838}. Best is trial 0 with value: 0.4693701107610641.
[I 2026-09-25 13:47:39,141] Trial 1 finished with value: 0.453194784500096 and parameters: {'hidden_layer': 28, 'learning_rate': 0.0006927222559905066, 'momentum': 0.31742486722592045, 'weight_decay': 2.7946446306176854e-06, 'elu_alpha': 0.4791689934200174}. Best is trial 1 with value: 0.453194784500096.
[I 2026-09-25 13:53:07,686] Trial 2 finished with value: 0.47008506173751313 and parameters: {'hidden_layer': 96, 'learning_rate': 0.0027896345072476493, 'momentum': 0.09468942227907774, 'weight_decay': 3.285190188649579e-05, 'elu_alpha': 1.4476399735511372}. Best is trial 1 with value: 0.453194784500096.
[I 2026-09-25 13:53:16,936] Trial 3 finished with value: inf and parameters: {'hidden_layer': 88, 'learning_rate': 0.00939518774923352, 'momentum': 0.6990251347394527, 'weight_decay': 2.1122242730771064e-06, 'elu_alpha': 1.5700439488319833}. Best is trial 1 with value: 0.453194784500096.
[I 2026-09-25 14:00:29,708] Trial 4 finished with value: 0.4368676634722723 and parameters: {'hidden_layer': 35, 'learning_rate': 0.0006361486136385058, 'momentum': 0.7176168273901109, 'weight_decay': 0.002926064518252346, 'elu_alpha': 0.6811719313392224}. Best is trial 4 with value: 0.4368676634722723.
[I 2026-09-25 14:05:32,785] Trial 5 finished with value: 0.47213580341778083 and parameters: {'hidden_layer': 98, 'learning_rate': 0.0034585489883926872, 'momentum': 0.06780163954070004, 'weight_decay': 1.1416987131149908e-05, 'elu_alpha': 1.7108203387464134}. Best is trial 4 with value: 0.4368676634722723.
[I 2026-09-25 14:06:35,792] Trial 6 pruned.
[I 2026-09-25 14:08:13,920] Trial 7 pruned.
[I 2026-09-25 14:09:43,475] Trial 8 finished with value: inf and parameters: {'hidden_layer': 81, 'learning_rate': 0.0034881941857543763, 'momentum': 0.7675003386769005, 'weight_decay': 0.0012089096600519933, 'elu_alpha': 1.5850253611143994}. Best is trial 4 with value: 0.4368676634722723.
[I 2026-09-25 14:10:22,586] Trial 9 pruned.
[I 2026-09-25 14:12:02,286] Trial 10 pruned.
[I 2026-09-25 14:13:51,413] Trial 11 pruned.
[I 2026-09-25 14:15:27,778] Trial 12 pruned.
[I 2026-09-25 14:22:43,936] Trial 13 finished with value: 0.4379438182435515 and parameters: {'hidden_layer': 22, 'learning_rate': 0.00021373764491565455, 'momentum': 0.8853152789951362, 'weight_decay': 5.281475770002545e-05, 'elu_alpha': 0.5072830658433617}. Best is trial 4 with value: 0.4368676634722723.
[I 2026-09-25 14:23:45,254] Trial 14 pruned.
[I 2026-09-25 14:31:07,815] Trial 15 finished with value: 0.4339406241555291 and parameters: {'hidden_layer': 63, 'learning_rate': 0.0002590776817081807, 'momentum': 0.7810381721664956, 'weight_decay': 0.0003859201962371264, 'elu_alpha': 0.31608158453909535}. Best is trial 15 with value: 0.4339406241555291.
[I 2026-09-25 14:38:41,516] Trial 16 finished with value: 0.42764372641071374 and parameters: {'hidden_layer': 63, 'learning_rate': 0.00026975974471759716, 'momentum': 0.7823387859680478, 'weight_decay': 0.005963963699429705, 'elu_alpha': 0.13052916807225}. Best is trial 16 with value: 0.42764372641071374.
[I 2026-09-25 14:46:52,939] Trial 17 finished with value: 0.4213625852092974 and parameters: {'hidden_layer': 64, 'learning_rate': 0.00028266165003893893, 'momentum': 0.8088832349572583, 'weight_decay': 0.009820651329033286, 'elu_alpha': 0.15896357335823028}. Best is trial 17 with value: 0.4213625852092974.
[I 2026-09-25 14:48:37,129] Trial 18 pruned.
[I 2026-09-25 14:48:54,335] Trial 19 pruned.
[I 2026-09-25 14:55:41,411] Trial 20 finished with value: 0.4159957136435685 and parameters: {'hidden_layer': 58, 'learning_rate': 0.000932199127308832, 'momentum': 0.651508918151015, 'weight_decay': 0.0004819590641845639, 'elu_alpha': 0.3369300159055555}. Best is trial 20 with value: 0.4159957136435685.
[I 2026-09-25 15:02:33,429] Trial 21 finished with value: 0.401390234951454 and parameters: {'hidden_layer': 57, 'learning_rate': 0.0013338797678617651, 'momentum': 0.6526683443911279, 'weight_decay': 0.0009450448309866069, 'elu_alpha': 0.33809445473602906}. Best is trial 21 with value: 0.401390234951454.
[I 2026-09-25 15:09:39,979] Trial 22 finished with value: 0.40349498772888276 and parameters: {'hidden_layer': 55, 'learning_rate': 0.0011952612145271658, 'momentum': 0.6586081408971957, 'weight_decay': 0.0005915427477383939, 'elu_alpha': 0.3389010754557421}. Best is trial 21 with value: 0.401390234951454.
[I 2026-09-25 15:15:26,328] Trial 23 finished with value: 0.40870843753391795 and parameters: {'hidden_layer': 54, 'learning_rate': 0.0014656146824667047, 'momentum': 0.6388919256666638, 'weight_decay': 0.0006038010165479209, 'elu_alpha': 0.40670489215856903}. Best is trial 21 with value: 0.401390234951454.
[I 2026-09-25 15:16:59,278] Trial 24 pruned.
[I 2026-09-25 15:17:12,927] Trial 25 finished with value: inf and parameters: {'hidden_layer': 75, 'learning_rate': 0.005303303815115017, 'momentum': 0.6051083688020749, 'weight_decay': 0.0002200055699951966, 'elu_alpha': 0.45099597540032754}. Best is trial 21 with value: 0.401390234951454.
[I 2026-09-25 15:25:05,426] Trial 26 finished with value: 0.3936836348219737 and parameters: {'hidden_layer': 56, 'learning_rate': 0.0012371768344276366, 'momentum': 0.6815514284226698, 'weight_decay': 0.0014962868535244227, 'elu_alpha': 0.3214009401112775}. Best is trial 26 with value: 0.3936836348219737.
[I 2026-09-25 15:26:46,059] Trial 27 pruned.
[I 2026-09-25 15:34:16,914] Trial 28 finished with value: 0.40999105419128556 and parameters: {'hidden_layer': 35, 'learning_rate': 0.0008787148812235141, 'momentum': 0.711246898212765, 'weight_decay': 0.003551073193492227, 'elu_alpha': 0.2743193775637446}. Best is trial 26 with value: 0.3936836348219737.
[I 2026-09-25 15:40:25,501] Trial 29 finished with value: 0.42144820918698833 and parameters: {'hidden_layer': 46, 'learning_rate': 0.001925188282855361, 'momentum': 0.5606659530315385, 'weight_decay': 0.002135372742773731, 'elu_alpha': 0.5609144934177376}. Best is trial 26 with value: 0.3936836348219737.
[I 2026-09-25 15:42:04,403] Trial 30 pruned.
[I 2026-09-25 15:48:17,234] Trial 31 finished with value: 0.3995217397460193 and parameters: {'hidden_layer': 54, 'learning_rate': 0.0016188663961061304, 'momentum': 0.657583008404362, 'weight_decay': 0.0003338331614549638, 'elu_alpha': 0.3797135982079457}. Best is trial 26 with value: 0.3936836348219737.
[I 2026-09-25 15:54:17,879] Trial 32 finished with value: 0.3854946511091066 and parameters: {'hidden_layer': 49, 'learning_rate': 0.0016761441208528918, 'momentum': 0.6856528993810356, 'weight_decay': 0.0003435745090402842, 'elu_alpha': 0.24576054131570765}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:00:43,670] Trial 33 finished with value: 0.3987378335295845 and parameters: {'hidden_layer': 36, 'learning_rate': 0.0017490199907639246, 'momentum': 0.554760871276019, 'weight_decay': 0.00027613063645845454, 'elu_alpha': 0.2669723429687111}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:07:47,521] Trial 34 finished with value: 0.39582950600406713 and parameters: {'hidden_layer': 37, 'learning_rate': 0.001751799973127657, 'momentum': 0.5349099502190827, 'weight_decay': 0.00010708969719544198, 'elu_alpha': 0.23293447381454382}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:07:56,955] Trial 35 finished with value: inf and parameters: {'hidden_layer': 35, 'learning_rate': 0.004906769500822944, 'momentum': 0.5452657022470937, 'weight_decay': 0.00013400920977247373, 'elu_alpha': 0.20900934357176465}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:11:49,200] Trial 36 pruned.
[I 2026-09-25 16:13:30,457] Trial 37 pruned.
[I 2026-09-25 16:19:02,523] Trial 38 finished with value: 0.4125034865476862 and parameters: {'hidden_layer': 19, 'learning_rate': 0.0027622935716290404, 'momentum': 0.5506468115784903, 'weight_decay': 3.408150696021571e-05, 'elu_alpha': 0.466543831480756}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:19:11,554] Trial 39 finished with value: inf and parameters: {'hidden_layer': 42, 'learning_rate': 0.004355135876179493, 'momentum': 0.7181814664479762, 'weight_decay': 0.00026362279471888573, 'elu_alpha': 1.050043055906005}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:19:20,929] Trial 40 finished with value: inf and parameters: {'hidden_layer': 31, 'learning_rate': 0.007071267039440298, 'momentum': 0.5148852899064547, 'weight_decay': 0.0023329260102892824, 'elu_alpha': 0.727550876295474}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:25:17,224] Trial 41 finished with value: 0.39514708177648783 and parameters: {'hidden_layer': 44, 'learning_rate': 0.0017545635540034256, 'momentum': 0.7116074687448835, 'weight_decay': 0.00012311482347690655, 'elu_alpha': 0.39777725888811716}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:25:25,816] Trial 42 finished with value: inf and parameters: {'hidden_layer': 49, 'learning_rate': 0.0019841623392552296, 'momentum': 0.7324291911916243, 'weight_decay': 0.00015825996161992502, 'elu_alpha': 0.2394064682978435}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:25:34,147] Trial 43 finished with value: inf and parameters: {'hidden_layer': 42, 'learning_rate': 0.002520125881653893, 'momentum': 0.841245509632123, 'weight_decay': 0.00011607893713563915, 'elu_alpha': 0.20367755451583747}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:29:25,045] Trial 44 finished with value: 0.41163448447810846 and parameters: {'hidden_layer': 49, 'learning_rate': 0.0034010130423619573, 'momentum': 0.6189051140279385, 'weight_decay': 6.040698566496074e-05, 'elu_alpha': 0.556857563388363}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:36:01,680] Trial 45 finished with value: 0.39964320391143804 and parameters: {'hidden_layer': 29, 'learning_rate': 0.001731072692955858, 'momentum': 0.4758001051316556, 'weight_decay': 1.925755320770822e-05, 'elu_alpha': 0.1008686153415291}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:37:12,691] Trial 46 pruned.
[I 2026-09-25 16:38:37,412] Trial 47 pruned.
[I 2026-09-25 16:40:04,276] Trial 48 finished with value: inf and parameters: {'hidden_layer': 21, 'learning_rate': 0.0034402772596652384, 'momentum': 0.7464850331202129, 'weight_decay': 3.6946212612188416e-05, 'elu_alpha': 0.25331331370449484}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:41:31,640] Trial 49 pruned.
[I 2026-09-25 16:42:33,831] Trial 50 pruned.
[I 2026-09-25 16:48:03,047] Trial 51 finished with value: 0.40381758343713425 and parameters: {'hidden_layer': 46, 'learning_rate': 0.0014762122105986132, 'momentum': 0.6912675781542633, 'weight_decay': 0.00030505179974784974, 'elu_alpha': 0.39432816981007823}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:54:18,239] Trial 52 finished with value: 0.3972815130173818 and parameters: {'hidden_layer': 72, 'learning_rate': 0.0016704366584802358, 'momentum': 0.6721879557475655, 'weight_decay': 0.00016792904038617014, 'elu_alpha': 0.37104916148612466}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:56:50,790] Trial 53 finished with value: inf and parameters: {'hidden_layer': 86, 'learning_rate': 0.000998693527540096, 'momentum': 0.9077053044569359, 'weight_decay': 0.00017086015314547943, 'elu_alpha': 0.3016034512068119}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 17:01:36,008] Trial 54 finished with value: 0.370525098726602 and parameters: {'hidden_layer': 71, 'learning_rate': 0.001974864445191968, 'momentum': 0.7672712192036012, 'weight_decay': 4.669875060622569e-05, 'elu_alpha': 0.18579145454927054}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:08:59,721] Trial 55 finished with value: 0.38173164545853705 and parameters: {'hidden_layer': 74, 'learning_rate': 0.0008199605194559297, 'momentum': 0.8166055628137214, 'weight_decay': 5.435439801984566e-06, 'elu_alpha': 0.20624615049164385}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:14:25,561] Trial 56 finished with value: 0.3755543589536561 and parameters: {'hidden_layer': 78, 'learning_rate': 0.0008600509944537932, 'momentum': 0.8265625121164876, 'weight_decay': 3.8090861706098477e-06, 'elu_alpha': 0.15290844172235185}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:20:27,017] Trial 57 finished with value: 0.3724673271679764 and parameters: {'hidden_layer': 79, 'learning_rate': 0.0008439461533670473, 'momentum': 0.8265911182605921, 'weight_decay': 4.700027425661989e-06, 'elu_alpha': 0.1674933341982772}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:20:35,283] Trial 58 finished with value: inf and parameters: {'hidden_layer': 78, 'learning_rate': 0.0005908575664119825, 'momentum': 0.9890822695974986, 'weight_decay': 4.324390700472682e-06, 'elu_alpha': 0.16238986283140266}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:26:46,385] Trial 59 finished with value: 0.3752964667704392 and parameters: {'hidden_layer': 94, 'learning_rate': 0.0007965569099510398, 'momentum': 0.8278193217125913, 'weight_decay': 2.964915984562226e-06, 'elu_alpha': 0.172784258661832}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:31:11,967] Trial 60 finished with value: 0.39254544863330093 and parameters: {'hidden_layer': 93, 'learning_rate': 0.0003869789086984569, 'momentum': 0.8313291490606456, 'weight_decay': 3.036779186850766e-06, 'elu_alpha': 0.11693186657933557}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:35:01,131] Trial 61 finished with value: 0.39326958001868156 and parameters: {'hidden_layer': 101, 'learning_rate': 0.0004216002656363103, 'momentum': 0.8264422900726214, 'weight_decay': 2.8918500383112546e-06, 'elu_alpha': 0.157919718182427}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:37:43,801] Trial 62 finished with value: inf and parameters: {'hidden_layer': 92, 'learning_rate': 0.0008170505776616315, 'momentum': 0.8868185032032551, 'weight_decay': 1.0329797886529013e-06, 'elu_alpha': 0.10016668426317536}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:38:32,749] Trial 63 pruned.
[I 2026-09-25 17:41:42,312] Trial 64 finished with value: 0.3715904390032265 and parameters: {'hidden_layer': 84, 'learning_rate': 0.0007285866469085902, 'momentum': 0.8625756472454167, 'weight_decay': 1.91953210768792e-06, 'elu_alpha': 0.10118927147495571}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:44:31,953] Trial 65 finished with value: 0.3841510265733732 and parameters: {'hidden_layer': 87, 'learning_rate': 0.0006203760776280315, 'momentum': 0.8633896282696893, 'weight_decay': 2.0394793979706047e-06, 'elu_alpha': 0.187829772738897}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:48:09,959] Trial 66 finished with value: 0.376595571235992 and parameters: {'hidden_layer': 83, 'learning_rate': 0.0005667796303288743, 'momentum': 0.872435097089802, 'weight_decay': 1.5451080927394114e-06, 'elu_alpha': 0.17687727365991537}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:50:11,467] Trial 67 finished with value: inf and parameters: {'hidden_layer': 82, 'learning_rate': 0.0005020363781232371, 'momentum': 0.9469614943265083, 'weight_decay': 1.6097916638729466e-06, 'elu_alpha': 0.3018880281044053}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:51:00,331] Trial 68 pruned.
[I 2026-09-25 17:55:16,398] Trial 69 finished with value: 0.37827573225856714 and parameters: {'hidden_layer': 107, 'learning_rate': 0.0009513737292647709, 'momentum': 0.7586013997956617, 'weight_decay': 4.070455112626148e-06, 'elu_alpha': 0.19935250714071961}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:55:32,496] Trial 70 pruned.
[I 2026-09-25 17:57:05,162] Trial 71 finished with value: inf and parameters: {'hidden_layer': 78, 'learning_rate': 0.0009230265450411737, 'momentum': 0.8652493545257142, 'weight_decay': 4.322985800942208e-06, 'elu_alpha': 0.19184196033144035}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 18:01:41,667] Trial 72 finished with value: 0.3815997524508932 and parameters: {'hidden_layer': 108, 'learning_rate': 0.0005390158066697343, 'momentum': 0.8119537808251848, 'weight_decay': 6.026175048593204e-06, 'elu_alpha': 0.1012382611037164}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 18:02:35,461] Trial 73 pruned.
[I 2026-09-25 18:02:39,941] Trial 74 finished with value: inf and parameters: {'hidden_layer': 112, 'learning_rate': 0.0005520014156540877, 'momentum': 0.9842870082814137, 'weight_decay': 2.1454919564583156e-06, 'elu_alpha': 0.32732677323973536}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 18:05:58,907] Trial 75 finished with value: 0.3616198126481279 and parameters: {'hidden_layer': 82, 'learning_rate': 0.0004910762739354061, 'momentum': 0.9257687564245632, 'weight_decay': 1.3139548430197805e-05, 'elu_alpha': 0.1409809797548997}. Best is trial 75 with value: 0.3616198126481279.
[I 2026-09-25 18:08:31,958] Trial 76 finished with value: 0.721808146802399 and parameters: {'hidden_layer': 81, 'learning_rate': 0.0006831094604647776, 'momentum': 0.918342339924914, 'weight_decay': 1.2989624173959458e-05, 'elu_alpha': 0.2847740125253956}. Best is trial 75 with value: 0.3616198126481279.
[I 2026-09-25 18:12:55,573] Trial 77 finished with value: 0.3787893166561428 and parameters: {'hidden_layer': 85, 'learning_rate': 0.0004747107799113821, 'momentum': 0.8679030090418601, 'weight_decay': 2.216081863751875e-06, 'elu_alpha': 0.15805871916674297}. Best is trial 75 with value: 0.3616198126481279.
[I 2026-09-25 18:13:03,264] Trial 78 finished with value: inf and parameters: {'hidden_layer': 120, 'learning_rate': 0.0012517216950233892, 'momentum': 0.9614392654411404, 'weight_decay': 1.468942799461806e-06, 'elu_alpha': 0.3460343980749623}. Best is trial 75 with value: 0.3616198126481279.
[I 2026-09-25 18:13:24,690] Trial 79 pruned.
[I 2026-09-25 18:13:24,696] A new study created in memory with name: no-name-38604a37-7bce-40ce-8474-2d5293663a95

{'hidden_layer': 82, 'learning_rate': 0.0004910762739354061, 'momentum': 0.9257687564245632, 'weight_decay': 1.3139548430197805e-05, 'elu_alpha': 0.1409809797548997}
0.3616198126481279

[I 2026-09-25 18:16:21,865] Trial 0 finished with value: 0.4070397459731634 and parameters: {'hidden_layer': 26, 'learning_rate': 0.00802892031446619, 'momentum': 0.06309611296163853, 'weight_decay': 8.20258637894404e-06}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:20:58,206] Trial 1 finished with value: 0.4286748736933291 and parameters: {'hidden_layer': 74, 'learning_rate': 0.00019930292938529843, 'momentum': 0.9132897097333287, 'weight_decay': 5.658695845569574e-06}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:26:07,019] Trial 2 finished with value: 0.5222480224578778 and parameters: {'hidden_layer': 22, 'learning_rate': 0.00027185651981566074, 'momentum': 0.11379155274446981, 'weight_decay': 7.047009018720604e-06}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:31:22,458] Trial 3 finished with value: 0.47533748973298284 and parameters: {'hidden_layer': 15, 'learning_rate': 0.0008349020243737295, 'momentum': 0.01303335671719846, 'weight_decay': 0.00017879878696943263}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:36:31,634] Trial 4 finished with value: 0.43273185380976464 and parameters: {'hidden_layer': 119, 'learning_rate': 0.0020169174801107285, 'momentum': 0.18546121274469785, 'weight_decay': 9.1075607291343e-06}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:40:06,564] Trial 5 finished with value: 0.43181074780017087 and parameters: {'hidden_layer': 10, 'learning_rate': 0.004878652970756871, 'momentum': 0.02757065201015146, 'weight_decay': 0.001177383251643048}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:41:00,023] Trial 6 pruned.
[I 2026-09-25 18:42:32,622] Trial 7 pruned.
[I 2026-09-25 18:43:52,927] Trial 8 pruned.
[I 2026-09-25 18:48:45,816] Trial 9 finished with value: 0.4228021285442418 and parameters: {'hidden_layer': 101, 'learning_rate': 0.0005836089464730598, 'momentum': 0.8240972389470445, 'weight_decay': 0.0052352391039929055}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:48:51,734] Trial 10 finished with value: inf and parameters: {'hidden_layer': 59, 'learning_rate': 0.005630777229905078, 'momentum': 0.5327312896917765, 'weight_decay': 1.352506251185573e-06}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:48:57,276] Trial 11 finished with value: inf and parameters: {'hidden_layer': 109, 'learning_rate': 0.002210237472518753, 'momentum': 0.8197718620014434, 'weight_decay': 0.00010091770125717876}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:49:05,150] Trial 12 finished with value: inf and parameters: {'hidden_layer': 85, 'learning_rate': 0.00903336119835059, 'momentum': 0.6397728612972233, 'weight_decay': 0.008223872407766994}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:50:02,667] Trial 13 pruned.
[I 2026-09-25 18:51:03,328] Trial 14 pruned.
[I 2026-09-25 18:52:01,054] Trial 15 pruned.
[I 2026-09-25 18:52:06,096] Trial 16 finished with value: inf and parameters: {'hidden_layer': 41, 'learning_rate': 0.0033649191865288003, 'momentum': 0.7740202980818077, 'weight_decay': 1.3238581107075063e-06}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:52:12,094] Trial 17 finished with value: inf and parameters: {'hidden_layer': 74, 'learning_rate': 0.0012382475089319916, 'momentum': 0.9757068717260202, 'weight_decay': 3.704907582317059e-05}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:53:15,488] Trial 18 finished with value: inf and parameters: {'hidden_layer': 27, 'learning_rate': 0.009121584947965328, 'momentum': 0.5234529918604083, 'weight_decay': 0.0023334823209178296}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:54:16,459] Trial 19 pruned.
[I 2026-09-25 18:55:27,919] Trial 20 pruned.
[W 2026-09-25 18:58:39,970] Trial 21 failed with parameters: {'hidden_layer': 79, 'learning_rate': 0.00017940240324022057, 'momentum': 0.9510464743684093, 'weight_decay': 2.9606793326358785e-06} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\optuna\study\_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "C:\Users\dawid\OneDrive - Stellenbosch University\Documents\Universiteit\4th year\ML\assignment3\ML441_Assigment3\active_regression.py", line 317, in obj
    history = model.fit(
              ^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\backend\tensorflow\trainer.py", line 377, in fit
    logs = self.train_function(iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\backend\tensorflow\trainer.py", line 220, in function
    opt_outputs = multi_step_on_iterator(iterator)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\util\traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\polymorphic_function.py", line 833, in __call__
    result = self._call(*args, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\polymorphic_function.py", line 878, in _call
    results = tracing_compilation.call_function(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\tracing_compilation.py", line 139, in call_function
    return function._call_flat(  # pylint: disable=protected-access
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\concrete_function.py", line 1322, in _call_flat
    return self._inference_function.call_preflattened(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\atomic_function.py", line 216, in call_preflattened
    flat_outputs = self.call_flat(*args)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\atomic_function.py", line 251, in call_flat
    outputs = self._bound_context.call_function(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\context.py", line 1688, in call_function
    outputs = execute.execute(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
[W 2026-09-25 18:58:40,265] Trial 21 failed with value None.

KeyboardInterrupt:

In [10]:
acts = ['relu', 'leaky_relu', 'elu']
results = []
for activation in acts:
    setup = {'activation': activation}
    alpha = 0
    params = retrieve_params(f'params/california/{activation}.json')
    if activation == 'leaky_relu':
        alpha = params["leaky_relu_alpha"]
    elif activation == 'elu':
        alpha = params["elu_alpha"]
    result = cv_regression(X_pool, y_pool, out_units=1, out_act='linear', 
                    loss='mse', k=5, random_state=42, 
                    hidden_units=params['hidden_layer'], activation=activation, alpha=alpha, 
                    learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'])
    for key, val in result.items():
        setup[key] = val

    results.append(setup)

results_df = pd.DataFrame(results)
results_df.round(4).to_csv(f"results/california/cv_validation.csv", index=False)

In [5]:
results_df = pd.read_csv("results/california/cv_validation.csv")
results_df

   activation    rmse    mape  R_squared
0        relu  0.6678  0.2625     0.6476
1  leaky_relu  0.5929  0.2447     0.7345
2         elu  0.6083  0.2558     0.7204

In [30]:
activation = 'leaky_relu'
params = retrieve_params(f'params/california/{activation}.json')
scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)
model = create_regmodel(X_train.shape[1], hidden_units=params['hidden_layer'], activation=activation, alpha=params['leaky_relu_alpha'], 
                 learning_rate=params['learning_rate'], momentum=0.02, weight_decay=params['weight_decay'], loss='mse')
# params['learning_rate']
history = []
runs = 100
# runs = 200
epochs = 200 // runs

fit_kwargs = {
    "epochs": epochs,
    "batch_size": 32,
    # "validation_split": 0.15,
    # "callbacks": [early_stopping],
    "verbose": 0
}
tic = time()
for i in range(runs):
    iteration = {'cumulative epochs': epochs * (i + 1)}
    iter_hist = model.fit(
        X_train,
        y_pool,
        **fit_kwargs
    )

    train_loss = iter_hist.history['loss']
    weights = model.get_weights()

    print(f"Iteration {i+1}: ")
    for l in range(len(train_loss)):
        print(f"\t{train_loss[l]}")

    if not all(np.all(np.isfinite(w)) for w in weights):
        print(f"Model became unstable at iteration {i + 1}")
        break

    y_pred = model(X_val, training=False).numpy().ravel()

    if not np.all(np.isfinite(y_pred)):
        print(f"NaN/Inf predictions at iteration {i + 1}")
        break

    rmse = root_mean_squared_error(y_test, y_pred)
    mape = mean_absolute_percentage_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    toc = time()

    iteration['Training loss'] = train_loss[-1]
    iteration['RMSE'] = rmse
    iteration['MAPE'] = mape
    iteration['R2-score'] = r2
    iteration['time'] = toc - tic
    history.append(iteration)
    
    print(f"Iteration {i+1}: ")
    for l in range(len(train_loss)):
        print(f"\t{train_loss[l]}")

run_df = pd.DataFrame(history)
run_df.round(4).to_csv(f"results/california/passive_learning.csv", index=False)

Iteration 1:
	0.9823712110519409
	0.5953853130340576
Iteration 1:
	0.9823712110519409
	0.5953853130340576
Iteration 2:
	0.5597645044326782
	0.5119470357894897
Iteration 2:
	0.5597645044326782
	0.5119470357894897
Iteration 3:
	0.4798978269100189
	0.4788159132003784
Iteration 3:
	0.4798978269100189
	0.4788159132003784
Iteration 4:
	0.4629015028476715
	0.45966559648513794
Iteration 4:
	0.4629015028476715
	0.45966559648513794
Iteration 5:
	0.4492672085762024
	0.4436721205711365
Iteration 5:
	0.4492672085762024
	0.4436721205711365
Iteration 6:
	0.4414399266242981
	0.4415772557258606
Iteration 6:
	0.4414399266242981
	0.4415772557258606
Iteration 7:
	0.4346224367618561
	0.44651395082473755
Iteration 7:
	0.4346224367618561
	0.44651395082473755
Iteration 8:
	0.42259863018989563
	0.42580193281173706
Iteration 8:
	0.42259863018989563
	0.42580193281173706
Iteration 9:
	0.4185628592967987
	0.4180830419063568
Iteration 9:
	0.4185628592967987
	0.4180830419063568
Iteration 10:
	0.4195455312728882
	0.4069516360759735
Iteration 10:
	0.4195455312728882
	0.4069516360759735
Iteration 11:
	0.40813660621643066
	0.41020530462265015
Iteration 11:
	0.40813660621643066
	0.41020530462265015
Iteration 12:
	0.41185420751571655
	0.4088967740535736
Iteration 12:
	0.41185420751571655
	0.4088967740535736
Iteration 13:
	0.4054934084415436
	0.39680492877960205
Iteration 13:
	0.4054934084415436
	0.39680492877960205
Iteration 14:
	0.39576950669288635
	0.3982909619808197
Iteration 14:
	0.39576950669288635
	0.3982909619808197
Iteration 15:
	0.3942939341068268
	0.3932355046272278
Iteration 15:
	0.3942939341068268
	0.3932355046272278
Iteration 16:
	0.4051107168197632
	0.392563134431839
Iteration 16:
	0.4051107168197632
	0.392563134431839
Iteration 17:
	0.3880513906478882
	0.38708895444869995
Iteration 17:
	0.3880513906478882
	0.38708895444869995
Iteration 18:
	0.3857831358909607
	0.3857682943344116
Iteration 18:
	0.3857831358909607
	0.3857682943344116
Iteration 19:
	0.38465386629104614
	0.3838860094547272
Iteration 19:
	0.38465386629104614
	0.3838860094547272
Iteration 20:
	0.3747536242008209
	0.37716761231422424
Iteration 20:
	0.3747536242008209
	0.37716761231422424
Iteration 21:
	0.3775502145290375
	0.3920519948005676
Iteration 21:
	0.3775502145290375
	0.3920519948005676
Iteration 22:
	0.3754095435142517
	0.3728254735469818
Iteration 22:
	0.3754095435142517
	0.3728254735469818
Iteration 23:
	0.3736121952533722
	0.37223267555236816
Iteration 23:
	0.3736121952533722
	0.37223267555236816
Iteration 24:
	0.3753550946712494
	0.3703154921531677
Iteration 24:
	0.3753550946712494
	0.3703154921531677
Iteration 25:
	0.36793315410614014
	0.36805373430252075
Iteration 25:
	0.36793315410614014
	0.36805373430252075
Iteration 26:
	0.365533709526062
	0.3660218417644501
Iteration 26:
	0.365533709526062
	0.3660218417644501
Iteration 27:
	0.36433500051498413
	0.3638324737548828
Iteration 27:
	0.36433500051498413
	0.3638324737548828
Iteration 28:
	0.3648829758167267
	0.36332666873931885
Iteration 28:
	0.3648829758167267
	0.36332666873931885
Iteration 29:
	0.3596954047679901
	0.3641781210899353
Iteration 29:
	0.3596954047679901
	0.3641781210899353
Iteration 30:
	0.36354371905326843
	0.36945217847824097
Iteration 30:
	0.36354371905326843
	0.36945217847824097
Iteration 31:
	0.3633301854133606
	0.35783302783966064
Iteration 31:
	0.3633301854133606
	0.35783302783966064
Iteration 32:
	0.3577479124069214
	0.3647291362285614
Iteration 32:
	0.3577479124069214
	0.3647291362285614
Iteration 33:
	0.3563350439071655
	0.3616183400154114
Iteration 33:
	0.3563350439071655
	0.3616183400154114
Iteration 34:
	0.3724909722805023
	0.38121798634529114
Iteration 34:
	0.3724909722805023
	0.38121798634529114
Iteration 35:
	0.3718147873878479
	0.36899375915527344
Iteration 35:
	0.3718147873878479
	0.36899375915527344
Iteration 36:
	0.36461058259010315
	0.3565094769001007
Iteration 36:
	0.36461058259010315
	0.3565094769001007
Iteration 37:
	0.3555808961391449
	0.35994911193847656
Iteration 37:
	0.3555808961391449
	0.35994911193847656
Iteration 38:
	0.35361865162849426
	0.3563098907470703
Iteration 38:
	0.35361865162849426
	0.3563098907470703
Iteration 39:
	0.35594701766967773
	0.35179105401039124
Iteration 39:
	0.35594701766967773
	0.35179105401039124
Iteration 40:
	0.35150694847106934
	0.35312920808792114
Iteration 40:
	0.35150694847106934
	0.35312920808792114
Iteration 41:
	0.35473912954330444
	0.35617759823799133
Iteration 41:
	0.35473912954330444
	0.35617759823799133
Iteration 42:
	0.35160043835639954
	0.35413745045661926
Iteration 42:
	0.35160043835639954
	0.35413745045661926
Iteration 43:
	0.35168513655662537
	0.3539161682128906
Iteration 43:
	0.35168513655662537
	0.3539161682128906
Iteration 44:
	0.34780097007751465
	0.3523881137371063
Iteration 44:
	0.34780097007751465
	0.3523881137371063
Iteration 45:
	0.35787445306777954
	0.3558577001094818
Iteration 45:
	0.35787445306777954
	0.3558577001094818
Iteration 46:
	0.3515307903289795
	0.349907785654068
Iteration 46:
	0.3515307903289795
	0.349907785654068
Iteration 47:
	0.3504251539707184
	0.349945604801178
Iteration 47:
	0.3504251539707184
	0.349945604801178
Iteration 48:
	0.34908047318458557
	0.3491424024105072
Iteration 48:
	0.34908047318458557
	0.3491424024105072
Iteration 49:
	0.3548237979412079
	0.3608412444591522
Iteration 49:
	0.3548237979412079
	0.3608412444591522
Iteration 50:
	0.3534444272518158
	0.3498093783855438
Iteration 50:
	0.3534444272518158
	0.3498093783855438
Iteration 51:
	0.3544802963733673
	0.35213249921798706
Iteration 51:
	0.3544802963733673
	0.35213249921798706
Iteration 52:
	0.3522244095802307
	0.3559727966785431
Iteration 52:
	0.3522244095802307
	0.3559727966785431
Iteration 53:
	0.3510986566543579
	0.3484571576118469
Iteration 53:
	0.3510986566543579
	0.3484571576118469
Iteration 54:
	0.34702667593955994
	0.3442983329296112
Iteration 54:
	0.34702667593955994
	0.3442983329296112
Iteration 55:
	0.34493163228034973
	0.35300782322883606
Iteration 55:
	0.34493163228034973
	0.35300782322883606
Iteration 56:
	0.3452407717704773
	0.34781917929649353
Iteration 56:
	0.3452407717704773
	0.34781917929649353
Iteration 57:
	0.34970539808273315
	0.3465310037136078
Iteration 57:
	0.34970539808273315
	0.3465310037136078
Iteration 58:
	0.3536156713962555
	0.3458198010921478
Iteration 58:
	0.3536156713962555
	0.3458198010921478
Iteration 59:
	0.3467234969139099
	0.34172821044921875
Iteration 59:
	0.3467234969139099
	0.34172821044921875
Iteration 60:
	0.3467199504375458
	0.34533974528312683
Iteration 60:
	0.3467199504375458
	0.34533974528312683
Iteration 61:
	0.3736245036125183
	0.3488508462905884
Iteration 61:
	0.3736245036125183
	0.3488508462905884
Iteration 62:
	0.34624382853507996
	0.34182190895080566
Iteration 62:
	0.34624382853507996
	0.34182190895080566
Iteration 63:
	0.34670397639274597
	0.34304356575012207
Iteration 63:
	0.34670397639274597
	0.34304356575012207
Iteration 64:
	0.3425353765487671
	0.3473933935165405
Iteration 64:
	0.3425353765487671
	0.3473933935165405
Iteration 65:
	0.341974675655365
	0.34575939178466797
Iteration 65:
	0.341974675655365
	0.34575939178466797
Iteration 66:
	0.3404741585254669
	0.3482421338558197
Iteration 66:
	0.3404741585254669
	0.3482421338558197
Iteration 67:
	0.347375750541687
	0.34497350454330444
Iteration 67:
	0.347375750541687
	0.34497350454330444
Iteration 68:
	0.36026230454444885
	0.3562232255935669
Iteration 68:
	0.36026230454444885
	0.3562232255935669
Iteration 69:
	0.34991455078125
	0.3515629470348358
Iteration 69:
	0.34991455078125
	0.3515629470348358
Iteration 70:
	0.34607142210006714
	0.3472461700439453
Iteration 70:
	0.34607142210006714
	0.3472461700439453
Iteration 71:
	0.3514121472835541
	0.35189351439476013
Iteration 71:
	0.3514121472835541
	0.35189351439476013
Iteration 72:
	0.3426652252674103
	0.3532020151615143
Iteration 72:
	0.3426652252674103
	0.3532020151615143
Iteration 73:
	0.342491090297699
	0.3440747857093811
Iteration 73:
	0.342491090297699
	0.3440747857093811
Iteration 74:
	0.34213966131210327
	0.34154409170150757
Iteration 74:
	0.34213966131210327
	0.34154409170150757
Iteration 75:
	0.34096741676330566
	0.34113672375679016
Iteration 75:
	0.34096741676330566
	0.34113672375679016
Iteration 76:
	0.3438229560852051
	0.34241053462028503
Iteration 76:
	0.3438229560852051
	0.34241053462028503
Iteration 77:
	0.3409550189971924
	0.34114184975624084
Iteration 77:
	0.3409550189971924
	0.34114184975624084
Iteration 78:
	0.34008535742759705
	0.3408466577529907
Iteration 78:
	0.34008535742759705
	0.3408466577529907
Iteration 79:
	0.33972689509391785
	0.34067416191101074
Iteration 79:
	0.33972689509391785
	0.34067416191101074
Iteration 80:
	0.36779123544692993
	0.3568362891674042
Iteration 80:
	0.36779123544692993
	0.3568362891674042
Iteration 81:
	0.34572914242744446
	0.3461487591266632
Iteration 81:
	0.34572914242744446
	0.3461487591266632
Iteration 82:
	0.3443991541862488
	0.35150146484375
Iteration 82:
	0.3443991541862488
	0.35150146484375
Iteration 83:
	0.34184011816978455
	0.34897366166114807
Iteration 83:
	0.34184011816978455
	0.34897366166114807
Iteration 84:
	0.3405790328979492
	0.34504586458206177
Iteration 84:
	0.3405790328979492
	0.34504586458206177
Iteration 85:
	0.33873963356018066
	0.3400821089744568
Iteration 85:
	0.33873963356018066
	0.3400821089744568
Iteration 86:
	0.3422737121582031
	0.3403680920600891
Iteration 86:
	0.3422737121582031
	0.3403680920600891
Iteration 87:
	0.34256109595298767
	0.3439115285873413
Iteration 87:
	0.34256109595298767
	0.3439115285873413
Iteration 88:
	0.3417235016822815
	0.34538736939430237
Iteration 88:
	0.3417235016822815
	0.34538736939430237
Iteration 89:
	0.34188714623451233
	0.3382801413536072
Iteration 89:
	0.34188714623451233
	0.3382801413536072
Iteration 90:
	0.3371173143386841
	0.3359334170818329
Iteration 90:
	0.3371173143386841
	0.3359334170818329
Iteration 91:
	0.3395024538040161
	0.33822309970855713
Iteration 91:
	0.3395024538040161
	0.33822309970855713
Iteration 92:
	0.3348691761493683
	0.33548107743263245
Iteration 92:
	0.3348691761493683
	0.33548107743263245
Iteration 93:
	0.3367519974708557
	0.3451640009880066
Iteration 93:
	0.3367519974708557
	0.3451640009880066
Iteration 94:
	0.3416806757450104
	0.3394436538219452
Iteration 94:
	0.3416806757450104
	0.3394436538219452
Iteration 95:
	0.3391549289226532
	0.341949462890625
Iteration 95:
	0.3391549289226532
	0.341949462890625
Iteration 96:
	0.3372057378292084
	0.3403552174568176
Iteration 96:
	0.3372057378292084
	0.3403552174568176
Iteration 97:
	0.33969587087631226
	0.342467337846756
Iteration 97:
	0.33969587087631226
	0.342467337846756
Iteration 98:
	0.33916354179382324
	0.3364989757537842
Iteration 98:
	0.33916354179382324
	0.3364989757537842
Iteration 99:
	0.33903858065605164
	0.33539676666259766
Iteration 99:
	0.33903858065605164
	0.33539676666259766
Iteration 100:
	0.33645009994506836
	0.33751580119132996
Iteration 100:
	0.33645009994506836
	0.33751580119132996

In [13]:
activation = 'leaky_relu'
# params['leaky_relu_alpha']
# activation = 'relu'
params = retrieve_params(f'params/california/{activation}.json')

scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)

history = active_learning_reg(X_train, y_pool, X_val, y_test, random_sampling, num_iter=100, unlab_size=0.9, random_state=100, verbose=True,
                               hidden_units=params['hidden_layer'], activation=activation, alpha=params['leaky_relu_alpha'],
                               learning_rate=params['learning_rate'], momentum=0.02, weight_decay=params['weight_decay'] 
)

run_df = pd.DataFrame(history)
run_df.round(4).to_csv(f"results/california/uncertainty_sampling_reg.csv", index=False)

Iteration 1: 1651 labelled instances
	2.4452600479125977
	0.9759215116500854
	Test MAPE = 0.3952252245513445

Iteration 2: 1801 labelled instances
	0.8323790431022644
	0.8148404359817505
	Test MAPE = 0.3559932459001808

Iteration 3: 1951 labelled instances
	0.7612895965576172
	0.7220782041549683
	Test MAPE = 0.34849916298452244

Iteration 4: 2101 labelled instances
	0.7112033367156982
	0.7008821964263916
	Test MAPE = 0.3340011655520416

Iteration 5: 2251 labelled instances
	0.6672309637069702
	0.6523434519767761
	Test MAPE = 0.3197361478196392

Iteration 6: 2401 labelled instances
	0.6415755748748779
	0.6204569339752197
	Test MAPE = 0.3215394021096369

Iteration 7: 2551 labelled instances
	0.6189755797386169
	0.6044051647186279
	Test MAPE = 0.3117848759931833

Iteration 8: 2701 labelled instances
	0.6124839782714844
	0.6054306626319885
	Test MAPE = 0.3004766860416338

Iteration 9: 2851 labelled instances
	0.5938308238983154
	0.5804276466369629
	Test MAPE = 0.31098664439530777

Iteration 10: 3001 labelled instances
	0.5866270661354065
	0.5578179359436035
	Test MAPE = 0.29798081500409557

Iteration 11: 3151 labelled instances
	0.5695881247520447
	0.5627351403236389
	Test MAPE = 0.27980797756295267

Iteration 12: 3301 labelled instances
	0.5744717121124268
	0.6152941584587097
	Test MAPE = 0.27520735394027684

Iteration 13: 3451 labelled instances
	0.5521823763847351
	0.5531774759292603
	Test MAPE = 0.2971363431825476

Iteration 14: 3601 labelled instances
	0.5714253783226013
	0.6021958589553833
	Test MAPE = 0.28467422179807783

Iteration 15: 3751 labelled instances
	0.6951285600662231
	0.6532193422317505
	Test MAPE = 0.2828949474197914

Iteration 16: 3901 labelled instances
	0.54827880859375
	0.5207442045211792
	Test MAPE = 0.27023700487432223

Iteration 17: 4051 labelled instances
	0.5169689655303955
	0.5178879499435425
	Test MAPE = 0.27466288613217366

Iteration 18: 4201 labelled instances
	0.5227870941162109
	0.521998405456543
	Test MAPE = 0.2644108123918425

Iteration 19: 4351 labelled instances
	0.4989285469055176
	0.5125007629394531
	Test MAPE = 0.2722578626815913

Iteration 20: 4501 labelled instances
	0.4981605112552643
	0.5001168847084045
	Test MAPE = 0.2735114929102059

Iteration 21: 4651 labelled instances
	0.49622729420661926
	0.494180828332901
	Test MAPE = 0.2740389192858417

Iteration 22: 4801 labelled instances
	0.4886641800403595
	0.4817940592765808
	Test MAPE = 0.262491659754393

Iteration 23: 4951 labelled instances
	0.48414358496665955
	0.482305645942688
	Test MAPE = 0.26236141229272636

Iteration 24: 5101 labelled instances
	0.46779659390449524
	0.47260499000549316
	Test MAPE = 0.26771214371964236

Iteration 25: 5251 labelled instances
	0.47094279527664185
	0.4733521640300751
	Test MAPE = 0.2598403909252697

Iteration 26: 5401 labelled instances
	0.4596804082393646
	0.4660121202468872
	Test MAPE = 0.26546432017491683

Iteration 27: 5551 labelled instances
	0.4585336148738861
	0.4608575403690338
	Test MAPE = 0.2588764327120677

Iteration 28: 5701 labelled instances
	0.454465389251709
	0.4578161835670471
	Test MAPE = 0.25663930780363653

Iteration 29: 5851 labelled instances
	0.4512456953525543
	0.46198809146881104
	Test MAPE = 0.26393996345143145

Iteration 30: 6001 labelled instances
	0.45235633850097656
	0.4491730332374573
	Test MAPE = 0.2604644498233729

Iteration 31: 6151 labelled instances
	0.45014557242393494
	0.447190523147583
	Test MAPE = 0.25000919498165863

Iteration 32: 6301 labelled instances
	0.4497896134853363
	0.43884673714637756
	Test MAPE = 0.25102279882949263

Iteration 33: 6451 labelled instances
	0.4376945495605469
	0.43070024251937866
	Test MAPE = 0.24771313265062048

Iteration 34: 6601 labelled instances
	0.43082597851753235
	0.42430976033210754
	Test MAPE = 0.2604400888398258

Iteration 35: 6751 labelled instances
	0.4294508695602417
	0.4255230724811554
	Test MAPE = 0.25247560671894026

Iteration 36: 6901 labelled instances
	0.42537301778793335
	0.4208464026451111
	Test MAPE = 0.25455653440214954

Iteration 37: 7051 labelled instances
	0.4294065833091736
	0.4195680320262909
	Test MAPE = 0.2503307509292438

Iteration 38: 7201 labelled instances
	0.4200951159000397
	0.41835010051727295
	Test MAPE = 0.2541454590857014

Iteration 39: 7351 labelled instances
	0.4173544943332672
	0.415200412273407
	Test MAPE = 0.25355727008369094

Iteration 40: 7501 labelled instances
	0.411820650100708
	0.4292479455471039
	Test MAPE = 0.24510061524463755

Iteration 41: 7651 labelled instances
	0.42684224247932434
	0.4032776951789856
	Test MAPE = 0.25464093007373434

Iteration 42: 7801 labelled instances
	0.41237902641296387
	0.410346120595932
	Test MAPE = 0.2541120837057057

Iteration 43: 7951 labelled instances
	0.40165582299232483
	0.402468740940094
	Test MAPE = 0.2425104318513736

Iteration 44: 8101 labelled instances
	0.4054315388202667
	0.4065938889980316
	Test MAPE = 0.2426676421421731

Iteration 45: 8251 labelled instances
	0.4080105125904083
	0.40126991271972656
	Test MAPE = 0.2555969192079119

Iteration 46: 8401 labelled instances
	0.40322619676589966
	0.4011665880680084
	Test MAPE = 0.2521982619673945

Iteration 47: 8551 labelled instances
	0.43114858865737915
	0.462797075510025
	Test MAPE = 0.26365522340494185

Iteration 48: 8701 labelled instances
	0.407633513212204
	0.3981352150440216
	Test MAPE = 0.2418771062266757

Iteration 49: 8851 labelled instances
	0.40040260553359985
	0.39667436480522156
	Test MAPE = 0.2602824452559597

Iteration 50: 9001 labelled instances
	0.39220041036605835
	0.38714733719825745
	Test MAPE = 0.24084290398513353

Iteration 51: 9151 labelled instances
	0.3917355239391327
	0.39661332964897156
	Test MAPE = 0.24966477815565508

Iteration 52: 9301 labelled instances
	0.3912699818611145
	0.39429888129234314
	Test MAPE = 0.2404475704306459

Iteration 53: 9451 labelled instances
	0.38914117217063904
	0.3853585124015808
	Test MAPE = 0.24037420187887631

Iteration 54: 9601 labelled instances
	0.3888424336910248
	0.3888620436191559
	Test MAPE = 0.24207400712636945

Iteration 55: 9751 labelled instances
	0.3856905698776245
	0.38267719745635986
	Test MAPE = 0.24421763519514603

Iteration 56: 9901 labelled instances
	0.3817685842514038
	0.3850764036178589
	Test MAPE = 0.24313897324281028

Iteration 57: 10051 labelled instances
	0.3782620429992676
	0.38323962688446045
	Test MAPE = 0.2357858781271936

Iteration 58: 10201 labelled instances
	0.379935622215271
	0.37523970007896423
	Test MAPE = 0.2403385176931968

Iteration 59: 10351 labelled instances
	0.39100515842437744
	0.381610631942749
	Test MAPE = 0.23867903119209405

Iteration 60: 10501 labelled instances
	0.3812713623046875
	0.3768068552017212
	Test MAPE = 0.2430637260331004

Iteration 61: 10651 labelled instances
	0.3700540065765381
	0.36729276180267334
	Test MAPE = 0.23416000687731076

Iteration 62: 10801 labelled instances
	0.36694854497909546
	0.36898067593574524
	Test MAPE = 0.23837783088017195

Iteration 63: 10951 labelled instances
	0.37101200222969055
	0.371317595243454
	Test MAPE = 0.24850173304542417

Iteration 64: 11101 labelled instances
	0.3702213764190674
	0.37047919631004333
	Test MAPE = 0.24997438191014237

Iteration 65: 11251 labelled instances
	0.4154139459133148
	0.38137075304985046
	Test MAPE = 0.23877931388427762

Iteration 66: 11401 labelled instances
	0.37580516934394836
	0.3738040626049042
	Test MAPE = 0.23135550848812877

Iteration 67: 11551 labelled instances
	0.36974388360977173
	0.3699471354484558
	Test MAPE = 0.23123898589468794

Iteration 68: 11701 labelled instances
	0.3736571669578552
	0.37142083048820496
	Test MAPE = 0.22811757045619951

Iteration 69: 11851 labelled instances
	0.3663193881511688
	0.3729454278945923
	Test MAPE = 0.23480165608749953

Iteration 70: 12001 labelled instances
	0.36288321018218994
	0.3613888621330261
	Test MAPE = 0.22777936145059427

Iteration 71: 12151 labelled instances
	0.37365907430648804
	0.36617782711982727
	Test MAPE = 0.2306742894455858

Iteration 72: 12301 labelled instances
	0.3616073727607727
	0.3592042624950409
	Test MAPE = 0.2338912497199147

Iteration 73: 12451 labelled instances
	0.36628463864326477
	0.3646535873413086
	Test MAPE = 0.23989155899720987

Iteration 74: 12601 labelled instances
	0.36152973771095276
	0.3597021698951721
	Test MAPE = 0.24327030112951276

Iteration 75: 12751 labelled instances
	0.36019226908683777
	0.3619701862335205
	Test MAPE = 0.2339073416619897

Iteration 76: 12901 labelled instances
	0.3567979335784912
	0.3746943473815918
	Test MAPE = 0.23944445006488216

Iteration 77: 13051 labelled instances
	0.36435624957084656
	0.35949981212615967
	Test MAPE = 0.23730284204786964

Iteration 78: 13201 labelled instances
	0.3614616394042969
	0.3594341576099396
	Test MAPE = 0.24056881745652675

Iteration 79: 13351 labelled instances
	0.3568229377269745
	0.35463663935661316
	Test MAPE = 0.22894656763672583

Iteration 80: 13501 labelled instances
	0.35335561633110046
	0.36281105875968933
	Test MAPE = 0.23210903162860405

Iteration 81: 13651 labelled instances
	0.3608953356742859
	0.3587527871131897
	Test MAPE = 0.23766798953476195

Iteration 82: 13801 labelled instances
	0.36060866713523865
	0.3547358512878418
	Test MAPE = 0.2406893311297397

Iteration 83: 13951 labelled instances
	0.35788947343826294
	0.3613917827606201
	Test MAPE = 0.23666355434801917

Iteration 84: 14101 labelled instances
	0.35183587670326233
	0.3493221700191498
	Test MAPE = 0.22908280534927067

Iteration 85: 14251 labelled instances
	0.36479637026786804
	0.3558112382888794
	Test MAPE = 0.23636916346698705

Iteration 86: 14401 labelled instances
	0.35613498091697693
	0.34722739458084106
	Test MAPE = 0.23323429458329772

Iteration 87: 14551 labelled instances
	0.3510897755622864
	0.350308358669281
	Test MAPE = 0.232458148762137

Iteration 88: 14701 labelled instances
	0.3479306697845459
	0.34729450941085815
	Test MAPE = 0.23310128738513533

Iteration 89: 14851 labelled instances
	0.34690165519714355
	0.35697147250175476
	Test MAPE = 0.2599757380796394

Iteration 90: 15001 labelled instances
	0.34708371758461
	0.3503800630569458
	Test MAPE = 0.22837808130648635

Iteration 91: 15151 labelled instances
	0.3481478691101074
	0.3467460870742798
	Test MAPE = 0.23987506934449648

Iteration 92: 15301 labelled instances
	0.3454473912715912
	0.3455054759979248
	Test MAPE = 0.23358148385626729

Iteration 93: 15451 labelled instances
	0.34360766410827637
	0.3462868630886078
	Test MAPE = 0.2419644756470702

Iteration 94: 15601 labelled instances
	0.3672983646392822
	0.35336241126060486
	Test MAPE = 0.23396727790062846

Iteration 95: 15751 labelled instances
	0.3532828688621521
	0.3618977665901184
	Test MAPE = 0.23735542040951407

Iteration 96: 15901 labelled instances
	0.35333555936813354
	0.3552458882331848
	Test MAPE = 0.23714414874550677

Iteration 97: 16051 labelled instances
	0.3472851514816284
	0.3528897762298584
	Test MAPE = 0.22780876968992606

Iteration 98: 16201 labelled instances
	0.3458206355571747
	0.3547592759132385
	Test MAPE = 0.23283205580031013

Iteration 99: 16351 labelled instances
	0.349610835313797
	0.351362407207489
	Test MAPE = 0.22767127467944012

Iteration 100: 16512 labelled instances
	0.3490985929965973
	0.349525511264801
	Test MAPE = 0.22903604393582117

In [14]:
activation = 'leaky_relu'
params = retrieve_params(f'params/california/{activation}.json')

scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)
for beta in [0.9]:
    history = sasla_reg(X_train, y_pool, X_val, y_test, num_iter=100, unlab_size=0.9, random_state=100, verbose=True,
                                   hidden_units=params['hidden_layer'], activation=activation, alpha=params['leaky_relu_alpha'],
                                   learning_rate=params['learning_rate'], momentum=0.02, weight_decay=params['weight_decay'], beta=beta)
    
    run_df = pd.DataFrame(history)
    run_df.round(4).to_csv(f"results/california/sasla_{beta}.csv", index=False)

Iteration 1: 16512 labelled instances
	1.019371747970581
	0.6298829317092896
	Test MAPE = 0.3016471549998825

Iteration 2: 16512 labelled instances
	0.5375019907951355
	0.5239494442939758
	Test MAPE = 0.2875212619980342

Iteration 3: 16512 labelled instances
	0.49058249592781067
	0.47891464829444885
	Test MAPE = 0.26510649454987273

Iteration 4: 16512 labelled instances
	0.4749574065208435
	0.47081661224365234
	Test MAPE = 0.263144526859005

Iteration 5: 16512 labelled instances
	0.4779776334762573
	0.463943213224411
	Test MAPE = 0.25952576806376615

Iteration 6: 16512 labelled instances
	0.47072339057922363
	0.44773900508880615
	Test MAPE = 0.25796031010732773

Iteration 7: 16512 labelled instances
	0.44342663884162903
	0.4461696147918701
	Test MAPE = 0.27143228563856653

Iteration 8: 16512 labelled instances
	0.4318358898162842
	0.42480355501174927
	Test MAPE = 0.2552850435956843

Iteration 9: 16512 labelled instances
	0.4274255037307739
	0.4187794029712677
	Test MAPE = 0.253508100118575

Iteration 10: 16511 labelled instances
	0.4186490476131439
	0.41615161299705505
	Test MAPE = 0.26142438090382125

Iteration 11: 16507 labelled instances
	0.41435763239860535
	0.4176778495311737
	Test MAPE = 0.2522711288343388

Iteration 12: 16508 labelled instances
	0.41306471824645996
	0.409267395734787
	Test MAPE = 0.25465226082011094

Iteration 13: 16504 labelled instances
	0.4066965878009796
	0.40178999304771423
	Test MAPE = 0.2511979441782634

Iteration 14: 16501 labelled instances
	0.40840083360671997
	0.3980860412120819
	Test MAPE = 0.23529343809295783

Iteration 15: 16503 labelled instances
	0.3950524926185608
	0.41191366314888
	Test MAPE = 0.25060066517830965

Iteration 16: 16494 labelled instances
	0.4008840024471283
	0.39644262194633484
	Test MAPE = 0.2508962090558379

Iteration 17: 16485 labelled instances
	0.3907608687877655
	0.3954707086086273
	Test MAPE = 0.24684768034579815

Iteration 18: 16483 labelled instances
	0.3905300199985504
	0.39270174503326416
	Test MAPE = 0.27438162098189145

Iteration 19: 16412 labelled instances
	0.38781920075416565
	0.3875008523464203
	Test MAPE = 0.2529240461249016

Iteration 20: 16427 labelled instances
	0.37900087237358093
	0.3814321458339691
	Test MAPE = 0.24297939005236377

Iteration 21: 16457 labelled instances
	0.3820183277130127
	0.38131746649742126
	Test MAPE = 0.25104109412325926

Iteration 22: 16364 labelled instances
	0.3758851885795593
	0.3830263018608093
	Test MAPE = 0.25121147826496626

Iteration 23: 16393 labelled instances
	0.37970471382141113
	0.37501341104507446
	Test MAPE = 0.23139712948775001

Iteration 24: 16406 labelled instances
	0.37394076585769653
	0.37128642201423645
	Test MAPE = 0.2416236968298705

Iteration 25: 16351 labelled instances
	0.3717113733291626
	0.3741825520992279
	Test MAPE = 0.2400764929984096

Iteration 26: 16352 labelled instances
	0.37602174282073975
	0.37182286381721497
	Test MAPE = 0.23325321557055248

Iteration 27: 16324 labelled instances
	0.370138019323349
	0.3713766634464264
	Test MAPE = 0.24218541823771633

Iteration 28: 16282 labelled instances
	0.370143324136734
	0.3690790832042694
	Test MAPE = 0.23418746898254714

Iteration 29: 16249 labelled instances
	0.3673253655433655
	0.3638249635696411
	Test MAPE = 0.23281080107040467

Iteration 30: 16156 labelled instances
	0.3708987236022949
	0.3749513328075409
	Test MAPE = 0.23618364551356963

Iteration 31: 16141 labelled instances
	0.3714544177055359
	0.3640022575855255
	Test MAPE = 0.24527444535567947

Iteration 32: 16080 labelled instances
	0.36752694845199585
	0.365928053855896
	Test MAPE = 0.23039246257004095

Iteration 33: 16206 labelled instances
	0.3635047674179077
	0.3651282787322998
	Test MAPE = 0.2416524054042495

Iteration 34: 16026 labelled instances
	0.3660641610622406
	0.36286598443984985
	Test MAPE = 0.24108441671858405

Iteration 35: 16094 labelled instances
	0.36309814453125
	0.37001779675483704
	Test MAPE = 0.23140614904150145

Iteration 36: 16042 labelled instances
	0.3681880831718445
	0.36291491985321045
	Test MAPE = 0.23981457377299775

Iteration 37: 16006 labelled instances
	0.36727163195610046
	0.362493634223938
	Test MAPE = 0.25407310166893426

Iteration 38: 15834 labelled instances
	0.36444902420043945
	0.363292396068573
	Test MAPE = 0.24163829308121715

Iteration 39: 15955 labelled instances
	0.3607889711856842
	0.3637728989124298
	Test MAPE = 0.23556602274858873

Iteration 40: 16102 labelled instances
	0.363384872674942
	0.3582533299922943
	Test MAPE = 0.2337528639840761

Iteration 41: 15999 labelled instances
	0.3622303307056427
	0.3617410659790039
	Test MAPE = 0.24554841915299883

Iteration 42: 15706 labelled instances
	0.3645235300064087
	0.36300885677337646
	Test MAPE = 0.22968766641143773

Iteration 43: 16093 labelled instances
	0.3565294146537781
	0.3608975410461426
	Test MAPE = 0.23222577445245923

Iteration 44: 16047 labelled instances
	0.35784104466438293
	0.35767897963523865
	Test MAPE = 0.2385122305325207

Iteration 45: 15889 labelled instances
	0.36681509017944336
	0.36684030294418335
	Test MAPE = 0.23148189063996127

Iteration 46: 15867 labelled instances
	0.3613850772380829
	0.3639889359474182
	Test MAPE = 0.23468592037950303

Iteration 47: 15807 labelled instances
	0.3597327172756195
	0.3623444437980652
	Test MAPE = 0.2364905086616307

Iteration 48: 15758 labelled instances
	0.3608841598033905
	0.36367183923721313
	Test MAPE = 0.24207253587290242

Iteration 49: 15874 labelled instances
	0.364247590303421
	0.36027222871780396
	Test MAPE = 0.22992931856563117

Iteration 50: 15563 labelled instances
	0.36414822936058044
	0.3616928458213806
	Test MAPE = 0.24064071746455223

Iteration 51: 15372 labelled instances
	0.371733695268631
	0.3661966323852539
	Test MAPE = 0.2473566818471984

Iteration 52: 15471 labelled instances
	0.3627196252346039
	0.3755148947238922
	Test MAPE = 0.23942850728407933

Iteration 53: 15474 labelled instances
	0.36603379249572754
	0.3660274147987366
	Test MAPE = 0.244609189508152

Iteration 54: 15227 labelled instances
	0.3722374439239502
	0.3700413703918457
	Test MAPE = 0.23168345608659302

Iteration 55: 15955 labelled instances
	0.36057373881340027
	0.35944074392318726
	Test MAPE = 0.23596188340416055

Iteration 56: 15678 labelled instances
	0.3635093867778778
	0.35809603333473206
	Test MAPE = 0.2248053718531008

Iteration 57: 15613 labelled instances
	0.356880784034729
	0.36141088604927063
	Test MAPE = 0.23270483355068522

Iteration 58: 15680 labelled instances
	0.358852356672287
	0.35559403896331787
	Test MAPE = 0.2365393477271339

Iteration 59: 15374 labelled instances
	0.3635743260383606
	0.361327201128006
	Test MAPE = 0.22649389521022215

Iteration 60: 15619 labelled instances
	0.3577209711074829
	0.35734590888023376
	Test MAPE = 0.22887821860225305

Iteration 61: 15328 labelled instances
	0.3603709936141968
	0.36066216230392456
	Test MAPE = 0.22797849991550895

Iteration 62: 15295 labelled instances
	0.3584015369415283
	0.36335664987564087
	Test MAPE = 0.22587427841017427

Iteration 63: 15518 labelled instances
	0.35521072149276733
	0.3624127507209778
	Test MAPE = 0.23762914086433104

Iteration 64: 14929 labelled instances
	0.3723330795764923
	0.3698734939098358
	Test MAPE = 0.24016139386510146

Iteration 65: 15024 labelled instances
	0.36892446875572205
	0.36560022830963135
	Test MAPE = 0.22460868164125117

Iteration 66: 15392 labelled instances
	0.35907965898513794
	0.3549884855747223
	Test MAPE = 0.252298718052285

Iteration 67: 14742 labelled instances
	0.37735432386398315
	0.37444666028022766
	Test MAPE = 0.23724281469419156

Iteration 68: 15123 labelled instances
	0.37081044912338257
	0.363572359085083
	Test MAPE = 0.23755460027053005

Iteration 69: 14814 labelled instances
	0.3669610917568207
	0.3662025034427643
	Test MAPE = 0.2420963339776705

Iteration 70: 14818 labelled instances
	0.3763415813446045
	0.3675347566604614
	Test MAPE = 0.232645035301684

Iteration 71: 14745 labelled instances
	0.3702124059200287
	0.36663275957107544
	Test MAPE = 0.23161338880846896

Iteration 72: 14474 labelled instances
	0.3689068555831909
	0.36869901418685913
	Test MAPE = 0.24212686134035832

Iteration 73: 14532 labelled instances
	0.3702034056186676
	0.3677818775177002
	Test MAPE = 0.2386178070360866

Iteration 74: 14600 labelled instances
	0.3683120608329773
	0.37208545207977295
	Test MAPE = 0.23559673029826023

Iteration 75: 14544 labelled instances
	0.37187713384628296
	0.37089335918426514
	Test MAPE = 0.2392375246697146

Iteration 76: 14390 labelled instances
	0.3710862100124359
	0.3699013888835907
	Test MAPE = 0.23157777066435314

Iteration 77: 14639 labelled instances
	0.3662942349910736
	0.369265079498291
	Test MAPE = 0.23865169967031827

Iteration 78: 14436 labelled instances
	0.38008353114128113
	0.37967607378959656
	Test MAPE = 0.24105833397422916

Iteration 79: 14808 labelled instances
	0.36764851212501526
	0.3636445701122284
	Test MAPE = 0.23592695802521568

Iteration 80: 14723 labelled instances
	0.3665927052497864
	0.3659251034259796
	Test MAPE = 0.23350608749440327

Iteration 81: 15016 labelled instances
	0.36280861496925354
	0.3666577935218811
	Test MAPE = 0.23930778150429363

Iteration 82: 14812 labelled instances
	0.36250293254852295
	0.36072295904159546
	Test MAPE = 0.23453954670138474

Iteration 83: 14449 labelled instances
	0.3705776333808899
	0.3651988208293915
	Test MAPE = 0.24395644020915008

Iteration 84: 14492 labelled instances
	0.36975565552711487
	0.37120378017425537
	Test MAPE = 0.23532271544115443

Iteration 85: 14467 labelled instances
	0.3668144941329956
	0.3681868016719818
	Test MAPE = 0.2428624508731947

Iteration 86: 14377 labelled instances
	0.3676256537437439
	0.37067946791648865
	Test MAPE = 0.24137757354632694

Iteration 87: 14219 labelled instances
	0.3788146674633026
	0.38472306728363037
	Test MAPE = 0.2344240240023038

Iteration 88: 14771 labelled instances
	0.36905547976493835
	0.3684225082397461
	Test MAPE = 0.23223034097037715

Iteration 89: 14803 labelled instances
	0.36939737200737
	0.36583495140075684
	Test MAPE = 0.23560522538942147

Iteration 90: 14857 labelled instances
	0.3627951741218567
	0.3656945526599884
	Test MAPE = 0.2277906557921029

Iteration 91: 14912 labelled instances
	0.36234384775161743
	0.3656899034976959
	Test MAPE = 0.23244034002883562

Iteration 92: 14733 labelled instances
	0.3666623830795288
	0.3612695038318634
	Test MAPE = 0.24057159785305396

Iteration 93: 14462 labelled instances
	0.3742784857749939
	0.3671945631504059
	Test MAPE = 0.23110918970909952

Iteration 94: 14442 labelled instances
	0.36959025263786316
	0.36658814549446106
	Test MAPE = 0.23947676644500632

Iteration 95: 14443 labelled instances
	0.36815401911735535
	0.3670697808265686
	Test MAPE = 0.2239728829452788

Iteration 96: 14890 labelled instances
	0.3563588261604309
	0.36307406425476074
	Test MAPE = 0.23078635965662395

Iteration 97: 14767 labelled instances
	0.36337190866470337
	0.35968631505966187
	Test MAPE = 0.2264980737308113

Iteration 98: 15129 labelled instances
	0.3580073416233063
	0.3595259189605713
	Test MAPE = 0.2270629311813277

Iteration 99: 14828 labelled instances
	0.3578020930290222
	0.362995445728302
	Test MAPE = 0.2322487608114291

Iteration 100: 14871 labelled instances
	0.3557475805282593
	0.3647593855857849
	Test MAPE = 0.24360461120376073

## Concrete

In [2]:
concrete_compressive_strength = fetch_ucirepo(id=165) 
ccs_df = pd.concat(
    [concrete_compressive_strength.data.features, concrete_compressive_strength.data.targets],
    axis=1
)
ccs_df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Concrete compressive strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [3]:
X = concrete_compressive_strength.data.features.to_numpy()
y = concrete_compressive_strength.data.targets.to_numpy()

X_pool, X_test, y_pool, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=51
)

In [ ]:
acts = ['relu', 'leaky_relu', 'elu']
for activation in acts:
    base_params = tune_params(X_pool, y_pool,
                              loss='mse',
                              out_units=1, out_act='linear',
                              k=5, activation=activation,
                              random_state=42,
                              n_trials=80,
                              export=True, file = f'params/concrete/{activation}.json'
    )

In [13]:
acts = ['relu', 'leaky_relu', 'elu']
results = []
for activation in acts:
    setup = {'activation': activation}
    alpha = 0
    params = retrieve_params(f'params/concrete/{activation}.json')
    if activation == 'leaky_relu':
        alpha = params["leaky_relu_alpha"]
    elif activation == 'elu':
        alpha = params["elu_alpha"]
    result = cv_regression(X_pool, y_pool, out_units=1, out_act='linear', 
                    loss='mse', k=5, random_state=42, 
                    hidden_units=params['hidden_layer'], activation=activation, alpha=alpha, 
                    learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'])
    for key, val in result.items():
        setup[key] = val

    results.append(setup)

results_df = pd.DataFrame(results)
results_df.round(4).to_csv(f"results/concrete/cv_validation.csv", index=False)

In [4]:
results_df = pd.read_csv("results/concrete/cv_validation.csv")
results_df

   activation     rmse    mape  R_squared
0        relu   9.2752  0.2655     0.6822
1  leaky_relu  10.5160  0.3173     0.6035
2         elu   7.0351  0.1849     0.8225

In [8]:
activation = 'elu'
params = retrieve_params(f'params/concrete/{activation}.json')
scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)
model = create_regmodel(X_train.shape[1], hidden_units=params['hidden_layer'], activation=activation, alpha=params['elu_alpha'], 
                 learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], loss='mse')
# params['learning_rate']
history = []
runs = 100
# runs = 200
epochs = 200 // runs

fit_kwargs = {
    "epochs": epochs,
    "batch_size": 32,
    # "validation_split": 0.15,
    # "callbacks": [early_stopping],
    "verbose": 0
}
tic = time()
for i in range(runs):
    iteration = {'cumulative epochs': epochs * (i + 1)}
    iter_hist = model.fit(
        X_train,
        y_pool,
        **fit_kwargs
    )

    train_loss = iter_hist.history['loss']
    weights = model.get_weights()

    print(f"Iteration {i+1}: ")
    for l in range(len(train_loss)):
        print(f"\t{train_loss[l]}")

    if not all(np.all(np.isfinite(w)) for w in weights):
        print(f"Model became unstable at iteration {i + 1}")
        break

    y_pred = model(X_val, training=False).numpy().ravel()

    if not np.all(np.isfinite(y_pred)):
        print(f"NaN/Inf predictions at iteration {i + 1}")
        break

    rmse = root_mean_squared_error(y_test, y_pred)
    mape = mean_absolute_percentage_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    toc = time()

    iteration['Training loss'] = train_loss[-1]
    iteration['RMSE'] = rmse
    iteration['MAPE'] = mape
    iteration['R2-score'] = r2
    iteration['time'] = toc - tic
    history.append(iteration)
    
    print(f"Iteration {i+1}: ")
    for l in range(len(train_loss)):
        print(f"\t{train_loss[l]}")

run_df = pd.DataFrame(history)
run_df.round(4).to_csv(f"results/concrete/passive_learning.csv", index=False)

Iteration 1:
	715.452392578125
	118.73147583007812
Iteration 1:
	715.452392578125
	118.73147583007812
Iteration 2:
	108.20952606201172
	88.74417114257812
Iteration 2:
	108.20952606201172
	88.74417114257812
Iteration 3:
	81.27278900146484
	78.40422821044922
Iteration 3:
	81.27278900146484
	78.40422821044922
Iteration 4:
	71.33354187011719
	69.12801361083984
Iteration 4:
	71.33354187011719
	69.12801361083984
Iteration 5:
	74.04510498046875
	65.99049377441406
Iteration 5:
	74.04510498046875
	65.99049377441406
Iteration 6:
	66.22148895263672
	66.43378448486328
Iteration 6:
	66.22148895263672
	66.43378448486328
Iteration 7:
	68.75662231445312
	61.77617645263672
Iteration 7:
	68.75662231445312
	61.77617645263672
Iteration 8:
	67.7855224609375
	65.49376678466797
Iteration 8:
	67.7855224609375
	65.49376678466797
Iteration 9:
	62.75283432006836
	63.087310791015625
Iteration 9:
	62.75283432006836
	63.087310791015625
Iteration 10:
	65.11071014404297
	59.605159759521484
Iteration 10:
	65.11071014404297
	59.605159759521484
Iteration 11:
	61.46502685546875
	60.04175567626953
Iteration 11:
	61.46502685546875
	60.04175567626953
Iteration 12:
	60.92412185668945
	60.66380310058594
Iteration 12:
	60.92412185668945
	60.66380310058594
Iteration 13:
	59.92557144165039
	55.46100997924805
Iteration 13:
	59.92557144165039
	55.46100997924805
Iteration 14:
	57.64613342285156
	58.79072570800781
Iteration 14:
	57.64613342285156
	58.79072570800781
Iteration 15:
	57.31050109863281
	53.17457580566406
Iteration 15:
	57.31050109863281
	53.17457580566406
Iteration 16:
	58.519100189208984
	56.625492095947266
Iteration 16:
	58.519100189208984
	56.625492095947266
Iteration 17:
	59.00766372680664
	58.13343811035156
Iteration 17:
	59.00766372680664
	58.13343811035156
Iteration 18:
	57.31211471557617
	59.8269157409668
Iteration 18:
	57.31211471557617
	59.8269157409668
Iteration 19:
	58.70488357543945
	56.548126220703125
Iteration 19:
	58.70488357543945
	56.548126220703125
Iteration 20:
	58.45656967163086
	55.55595016479492
Iteration 20:
	58.45656967163086
	55.55595016479492
Iteration 21:
	54.884037017822266
	54.64087677001953
Iteration 21:
	54.884037017822266
	54.64087677001953
Iteration 22:
	53.20732879638672
	55.62211608886719
Iteration 22:
	53.20732879638672
	55.62211608886719
Iteration 23:
	52.39500045776367
	55.66847610473633
Iteration 23:
	52.39500045776367
	55.66847610473633
Iteration 24:
	54.34816360473633
	53.563926696777344
Iteration 24:
	54.34816360473633
	53.563926696777344
Iteration 25:
	52.29621505737305
	55.91159439086914
Iteration 25:
	52.29621505737305
	55.91159439086914
Iteration 26:
	55.16597366333008
	52.28240203857422
Iteration 26:
	55.16597366333008
	52.28240203857422
Iteration 27:
	50.36475372314453
	55.45967483520508
Iteration 27:
	50.36475372314453
	55.45967483520508
Iteration 28:
	51.81529998779297
	52.77046203613281
Iteration 28:
	51.81529998779297
	52.77046203613281
Iteration 29:
	52.51753616333008
	56.88408279418945
Iteration 29:
	52.51753616333008
	56.88408279418945
Iteration 30:
	52.936126708984375
	52.10429000854492
Iteration 30:
	52.936126708984375
	52.10429000854492
Iteration 31:
	50.16535186767578
	50.0892333984375
Iteration 31:
	50.16535186767578
	50.0892333984375
Iteration 32:
	52.84946823120117
	52.93453598022461
Iteration 32:
	52.84946823120117
	52.93453598022461
Iteration 33:
	52.64383316040039
	55.122310638427734
Iteration 33:
	52.64383316040039
	55.122310638427734
Iteration 34:
	52.28221893310547
	54.79557418823242
Iteration 34:
	52.28221893310547
	54.79557418823242
Iteration 35:
	55.54490661621094
	48.82256317138672
Iteration 35:
	55.54490661621094
	48.82256317138672
Iteration 36:
	56.32572555541992
	51.54653549194336
Iteration 36:
	56.32572555541992
	51.54653549194336
Iteration 37:
	49.492679595947266
	48.90766143798828
Iteration 37:
	49.492679595947266
	48.90766143798828
Iteration 38:
	47.73904800415039
	51.88126754760742
Iteration 38:
	47.73904800415039
	51.88126754760742
Iteration 39:
	51.7307014465332
	50.76484298706055
Iteration 39:
	51.7307014465332
	50.76484298706055
Iteration 40:
	52.069313049316406
	54.26310348510742
Iteration 40:
	52.069313049316406
	54.26310348510742
Iteration 41:
	50.29008483886719
	49.146812438964844
Iteration 41:
	50.29008483886719
	49.146812438964844
Iteration 42:
	52.74427032470703
	51.526771545410156
Iteration 42:
	52.74427032470703
	51.526771545410156
Iteration 43:
	49.864479064941406
	53.9322395324707
Iteration 43:
	49.864479064941406
	53.9322395324707
Iteration 44:
	51.187652587890625
	50.88873291015625
Iteration 44:
	51.187652587890625
	50.88873291015625
Iteration 45:
	50.564056396484375
	50.443782806396484
Iteration 45:
	50.564056396484375
	50.443782806396484
Iteration 46:
	51.90157699584961
	46.4779167175293
Iteration 46:
	51.90157699584961
	46.4779167175293
Iteration 47:
	49.22280502319336
	52.03236389160156
Iteration 47:
	49.22280502319336
	52.03236389160156
Iteration 48:
	51.26484680175781
	49.82027816772461
Iteration 48:
	51.26484680175781
	49.82027816772461
Iteration 49:
	53.15027618408203
	51.401268005371094
Iteration 49:
	53.15027618408203
	51.401268005371094
Iteration 50:
	48.24817657470703
	49.12348175048828
Iteration 50:
	48.24817657470703
	49.12348175048828
Iteration 51:
	50.05727767944336
	51.025787353515625
Iteration 51:
	50.05727767944336
	51.025787353515625
Iteration 52:
	52.555294036865234
	47.595489501953125
Iteration 52:
	52.555294036865234
	47.595489501953125
Iteration 53:
	48.143028259277344
	50.80294418334961
Iteration 53:
	48.143028259277344
	50.80294418334961
Iteration 54:
	50.5289421081543
	48.72431945800781
Iteration 54:
	50.5289421081543
	48.72431945800781
Iteration 55:
	46.34427261352539
	52.38315963745117
Iteration 55:
	46.34427261352539
	52.38315963745117
Iteration 56:
	50.60298538208008
	49.06624221801758
Iteration 56:
	50.60298538208008
	49.06624221801758
Iteration 57:
	51.8692512512207
	52.16642379760742
Iteration 57:
	51.8692512512207
	52.16642379760742
Iteration 58:
	50.37177276611328
	48.85697937011719
Iteration 58:
	50.37177276611328
	48.85697937011719
Iteration 59:
	49.049766540527344
	52.149375915527344
Iteration 59:
	49.049766540527344
	52.149375915527344
Iteration 60:
	50.406822204589844
	49.9766845703125
Iteration 60:
	50.406822204589844
	49.9766845703125
Iteration 61:
	46.8015022277832
	46.32419204711914
Iteration 61:
	46.8015022277832
	46.32419204711914
Iteration 62:
	53.052425384521484
	50.49053955078125
Iteration 62:
	53.052425384521484
	50.49053955078125
Iteration 63:
	48.19042205810547
	50.017642974853516
Iteration 63:
	48.19042205810547
	50.017642974853516
Iteration 64:
	48.76123809814453
	49.0988655090332
Iteration 64:
	48.76123809814453
	49.0988655090332
Iteration 65:
	51.47846221923828
	50.308013916015625
Iteration 65:
	51.47846221923828
	50.308013916015625
Iteration 66:
	48.51860046386719
	49.418453216552734
Iteration 66:
	48.51860046386719
	49.418453216552734
Iteration 67:
	49.064937591552734
	48.07959747314453
Iteration 67:
	49.064937591552734
	48.07959747314453
Iteration 68:
	46.65796661376953
	48.33669662475586
Iteration 68:
	46.65796661376953
	48.33669662475586
Iteration 69:
	48.282012939453125
	50.54829788208008
Iteration 69:
	48.282012939453125
	50.54829788208008
Iteration 70:
	50.3463020324707
	48.83448028564453
Iteration 70:
	50.3463020324707
	48.83448028564453
Iteration 71:
	45.57733154296875
	51.783451080322266
Iteration 71:
	45.57733154296875
	51.783451080322266
Iteration 72:
	49.35124588012695
	50.48129653930664
Iteration 72:
	49.35124588012695
	50.48129653930664
Iteration 73:
	46.92363357543945
	49.94847869873047
Iteration 73:
	46.92363357543945
	49.94847869873047
Iteration 74:
	51.369850158691406
	47.32908630371094
Iteration 74:
	51.369850158691406
	47.32908630371094
Iteration 75:
	51.10569763183594
	49.34492874145508
Iteration 75:
	51.10569763183594
	49.34492874145508
Iteration 76:
	49.51939392089844
	49.39410400390625
Iteration 76:
	49.51939392089844
	49.39410400390625
Iteration 77:
	48.91191101074219
	48.981380462646484
Iteration 77:
	48.91191101074219
	48.981380462646484
Iteration 78:
	50.15753936767578
	52.07218933105469
Iteration 78:
	50.15753936767578
	52.07218933105469
Iteration 79:
	48.16012954711914
	48.48982238769531
Iteration 79:
	48.16012954711914
	48.48982238769531
Iteration 80:
	49.399742126464844
	48.117733001708984
Iteration 80:
	49.399742126464844
	48.117733001708984
Iteration 81:
	51.80718994140625
	46.215938568115234
Iteration 81:
	51.80718994140625
	46.215938568115234
Iteration 82:
	46.89238739013672
	48.24240493774414
Iteration 82:
	46.89238739013672
	48.24240493774414
Iteration 83:
	46.16808319091797
	47.0354118347168
Iteration 83:
	46.16808319091797
	47.0354118347168
Iteration 84:
	48.4708137512207
	49.5329475402832
Iteration 84:
	48.4708137512207
	49.5329475402832
Iteration 85:
	48.88833236694336
	48.72620391845703
Iteration 85:
	48.88833236694336
	48.72620391845703
Iteration 86:
	48.48203659057617
	49.73434829711914
Iteration 86:
	48.48203659057617
	49.73434829711914
Iteration 87:
	49.71970748901367
	45.82473373413086
Iteration 87:
	49.71970748901367
	45.82473373413086
Iteration 88:
	51.280033111572266
	47.766151428222656
Iteration 88:
	51.280033111572266
	47.766151428222656
Iteration 89:
	47.72294616699219
	43.86732864379883
Iteration 89:
	47.72294616699219
	43.86732864379883
Iteration 90:
	47.27649688720703
	45.18653106689453
Iteration 90:
	47.27649688720703
	45.18653106689453
Iteration 91:
	48.166561126708984
	44.12635040283203
Iteration 91:
	48.166561126708984
	44.12635040283203
Iteration 92:
	47.9240837097168
	45.43895721435547
Iteration 92:
	47.9240837097168
	45.43895721435547
Iteration 93:
	47.35199737548828
	48.73776626586914
Iteration 93:
	47.35199737548828
	48.73776626586914
Iteration 94:
	48.038814544677734
	45.36354064941406
Iteration 94:
	48.038814544677734
	45.36354064941406
Iteration 95:
	47.31468200683594
	46.0892333984375
Iteration 95:
	47.31468200683594
	46.0892333984375
Iteration 96:
	45.30396270751953
	54.15983200073242
Iteration 96:
	45.30396270751953
	54.15983200073242
Iteration 97:
	47.750640869140625
	46.17310333251953
Iteration 97:
	47.750640869140625
	46.17310333251953
Iteration 98:
	47.84060287475586
	43.1682014465332
Iteration 98:
	47.84060287475586
	43.1682014465332
Iteration 99:
	43.71958541870117
	46.76301956176758
Iteration 99:
	43.71958541870117
	46.76301956176758
Iteration 100:
	46.97052001953125
	44.967769622802734
Iteration 100:
	46.97052001953125
	44.967769622802734

In [4]:
activation = 'elu'
params = retrieve_params(f'params/concrete/{activation}.json')

scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)

history = active_learning_reg(X_train, y_pool, X_val, y_test, random_sampling, num_iter=100, unlab_size=0.9, random_state=100, verbose=True,
                               hidden_units=params['hidden_layer'], activation=activation, alpha=params['elu_alpha'],
                               learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'] 
)

run_df = pd.DataFrame(history)
run_df.round(4).to_csv(f"results/concrete/uncertainty_sampling_reg.csv", index=False)

Iteration 1: 82 labelled instances
	1652.8074951171875
	1482.6337890625
	Test MAPE = 0.8513905685010371

Iteration 2: 89 labelled instances
	1154.8743896484375
	645.2828979492188
	Test MAPE = 0.41995340695202454

Iteration 3: 96 labelled instances
	257.98114013671875
	125.75469970703125
	Test MAPE = 0.4716047526195972

Iteration 4: 103 labelled instances
	143.87001037597656
	125.26988220214844
	Test MAPE = 0.3587848248374468

Iteration 5: 110 labelled instances
	126.94591522216797
	115.97632598876953
	Test MAPE = 0.3144570700694373

Iteration 6: 117 labelled instances
	96.29742431640625
	98.36064147949219
	Test MAPE = 0.32837733360740434

Iteration 7: 124 labelled instances
	102.82125091552734
	100.84709167480469
	Test MAPE = 0.28394330711411775

Iteration 8: 131 labelled instances
	90.04818725585938
	94.23802185058594
	Test MAPE = 0.28644058714125425

Iteration 9: 138 labelled instances
	104.96196746826172
	102.18533325195312
	Test MAPE = 0.2780566706239307

Iteration 10: 145 labelled instances
	92.47025299072266
	86.44818878173828
	Test MAPE = 0.2719362975635506

Iteration 11: 152 labelled instances
	94.28321838378906
	85.28471374511719
	Test MAPE = 0.23707825995065138

Iteration 12: 159 labelled instances
	77.27328491210938
	90.14460754394531
	Test MAPE = 0.23637161555086958

Iteration 13: 166 labelled instances
	70.13482666015625
	74.22747039794922
	Test MAPE = 0.2231359688390659

Iteration 14: 173 labelled instances
	78.46511840820312
	81.47506713867188
	Test MAPE = 0.22510318964313328

Iteration 15: 180 labelled instances
	68.28779602050781
	77.53666687011719
	Test MAPE = 0.20806729203079538

Iteration 16: 187 labelled instances
	76.69955444335938
	74.130126953125
	Test MAPE = 0.21079198115297468

Iteration 17: 194 labelled instances
	64.76679992675781
	100.03502655029297
	Test MAPE = 0.27162150696686144

Iteration 18: 201 labelled instances
	91.05305480957031
	78.76368713378906
	Test MAPE = 0.20273503582781732

Iteration 19: 208 labelled instances
	72.51370239257812
	75.08208465576172
	Test MAPE = 0.21195582121441456

Iteration 20: 215 labelled instances
	74.43255615234375
	76.44327545166016
	Test MAPE = 0.20385047011965765

Iteration 21: 222 labelled instances
	76.46845245361328
	75.56266021728516
	Test MAPE = 0.19825024715117526

Iteration 22: 229 labelled instances
	75.4458236694336
	66.0689926147461
	Test MAPE = 0.20627291698347164

Iteration 23: 236 labelled instances
	68.49240112304688
	63.746639251708984
	Test MAPE = 0.20236917526841186

Iteration 24: 243 labelled instances
	59.34758758544922
	69.55374908447266
	Test MAPE = 0.1936163677169107

Iteration 25: 250 labelled instances
	67.5400161743164
	72.85955810546875
	Test MAPE = 0.19252223379696928

Iteration 26: 257 labelled instances
	72.27730560302734
	62.23695755004883
	Test MAPE = 0.21640606354908745

Iteration 27: 264 labelled instances
	98.87751770019531
	70.2457504272461
	Test MAPE = 0.18778837503803314

Iteration 28: 271 labelled instances
	61.35538101196289
	65.9007797241211
	Test MAPE = 0.1853469083970314

Iteration 29: 278 labelled instances
	61.96505355834961
	67.6338882446289
	Test MAPE = 0.17911475707444535

Iteration 30: 285 labelled instances
	60.573463439941406
	59.75538635253906
	Test MAPE = 0.18692045756053804

Iteration 31: 292 labelled instances
	60.77627182006836
	63.75188446044922
	Test MAPE = 0.21354833060125364

Iteration 32: 299 labelled instances
	59.217620849609375
	66.03799438476562
	Test MAPE = 0.182497758193454

Iteration 33: 306 labelled instances
	60.374176025390625
	59.3016357421875
	Test MAPE = 0.18409922280045993

Iteration 34: 313 labelled instances
	63.409324645996094
	64.24292755126953
	Test MAPE = 0.18733710795140968

Iteration 35: 320 labelled instances
	56.75780487060547
	54.303802490234375
	Test MAPE = 0.1901630022189046

Iteration 36: 327 labelled instances
	59.45017623901367
	64.84800720214844
	Test MAPE = 0.2059543599546359

Iteration 37: 334 labelled instances
	67.13690185546875
	59.24446105957031
	Test MAPE = 0.18384799181884873

Iteration 38: 341 labelled instances
	62.19365310668945
	65.11214447021484
	Test MAPE = 0.19678968514130152

Iteration 39: 348 labelled instances
	57.2049560546875
	63.955589294433594
	Test MAPE = 0.1982932321982403

Iteration 40: 355 labelled instances
	62.35524368286133
	58.842777252197266
	Test MAPE = 0.18477047079395606

Iteration 41: 362 labelled instances
	59.45701599121094
	60.20890426635742
	Test MAPE = 0.1712689100796231

Iteration 42: 369 labelled instances
	66.44165802001953
	64.40446472167969
	Test MAPE = 0.16902731885795144

Iteration 43: 376 labelled instances
	69.75788116455078
	66.23085021972656
	Test MAPE = 0.16912980160321073

Iteration 44: 383 labelled instances
	63.74887466430664
	59.16585922241211
	Test MAPE = 0.18400023459427473

Iteration 45: 390 labelled instances
	65.01716613769531
	57.58685302734375
	Test MAPE = 0.18668850420747826

Iteration 46: 397 labelled instances
	59.07372283935547
	55.35295486450195
	Test MAPE = 0.17724362727497206

Iteration 47: 404 labelled instances
	60.1895866394043
	56.315208435058594
	Test MAPE = 0.17351864617692261

Iteration 48: 411 labelled instances
	60.82085418701172
	64.83716583251953
	Test MAPE = 0.17109157099461594

Iteration 49: 418 labelled instances
	60.44778060913086
	55.64089584350586
	Test MAPE = 0.17681686375545413

Iteration 50: 425 labelled instances
	66.96573638916016
	56.51766586303711
	Test MAPE = 0.17811171455852848

Iteration 51: 432 labelled instances
	60.415225982666016
	59.63216018676758
	Test MAPE = 0.16964177337857497

Iteration 52: 439 labelled instances
	60.686954498291016
	60.098331451416016
	Test MAPE = 0.17148247627103738

Iteration 53: 446 labelled instances
	54.91322708129883
	61.347496032714844
	Test MAPE = 0.1668128974047116

Iteration 54: 453 labelled instances
	60.83537292480469
	56.24169921875
	Test MAPE = 0.17101110428347793

Iteration 55: 460 labelled instances
	58.62168502807617
	56.429298400878906
	Test MAPE = 0.16328096710151302

Iteration 56: 467 labelled instances
	60.83034896850586
	59.76426315307617
	Test MAPE = 0.16587026740846644

Iteration 57: 474 labelled instances
	63.844242095947266
	52.478084564208984
	Test MAPE = 0.1674868872502945

Iteration 58: 481 labelled instances
	56.45425796508789
	53.286468505859375
	Test MAPE = 0.1764856069046888

Iteration 59: 488 labelled instances
	58.04936981201172
	59.92412567138672
	Test MAPE = 0.1859041018160587

Iteration 60: 495 labelled instances
	62.15205001831055
	56.28138732910156
	Test MAPE = 0.1638968426998862

Iteration 61: 502 labelled instances
	53.01823043823242
	54.35808563232422
	Test MAPE = 0.16548686414317884

Iteration 62: 509 labelled instances
	54.14154052734375
	50.53807067871094
	Test MAPE = 0.16023525134414243

Iteration 63: 516 labelled instances
	51.49164581298828
	58.46694564819336
	Test MAPE = 0.16813368165524012

Iteration 64: 523 labelled instances
	56.913753509521484
	56.97469711303711
	Test MAPE = 0.18001665813761444

Iteration 65: 530 labelled instances
	58.40737533569336
	56.451786041259766
	Test MAPE = 0.17326243521913784

Iteration 66: 537 labelled instances
	54.31179428100586
	54.864036560058594
	Test MAPE = 0.1577222986291295

Iteration 67: 544 labelled instances
	54.84148406982422
	53.951927185058594
	Test MAPE = 0.172114395866258

Iteration 68: 551 labelled instances
	58.77536392211914
	60.431175231933594
	Test MAPE = 0.1877809651406541

Iteration 69: 558 labelled instances
	57.75608825683594
	52.14027786254883
	Test MAPE = 0.18154950686598673

Iteration 70: 565 labelled instances
	53.966796875
	52.770877838134766
	Test MAPE = 0.16165788283122157

Iteration 71: 572 labelled instances
	50.08266830444336
	54.704193115234375
	Test MAPE = 0.17383095690741887

Iteration 72: 579 labelled instances
	55.79286193847656
	54.98817825317383
	Test MAPE = 0.1698448149865663

Iteration 73: 586 labelled instances
	54.60639190673828
	54.985191345214844
	Test MAPE = 0.16144771182869333

Iteration 74: 593 labelled instances
	56.11650848388672
	56.497047424316406
	Test MAPE = 0.16169147711734894

Iteration 75: 600 labelled instances
	51.22438049316406
	52.88349914550781
	Test MAPE = 0.16323920461460592

Iteration 76: 607 labelled instances
	50.84940719604492
	52.05702209472656
	Test MAPE = 0.17205046163304644

Iteration 77: 614 labelled instances
	54.769290924072266
	49.4588508605957
	Test MAPE = 0.16661178275881858

Iteration 78: 621 labelled instances
	60.43471908569336
	52.44525146484375
	Test MAPE = 0.17461867411463683

Iteration 79: 628 labelled instances
	50.348270416259766
	53.49563217163086
	Test MAPE = 0.16112420795479698

Iteration 80: 635 labelled instances
	53.375553131103516
	51.96406173706055
	Test MAPE = 0.1795466503890418

Iteration 81: 642 labelled instances
	54.537357330322266
	63.25669479370117
	Test MAPE = 0.1600074758017392

Iteration 82: 649 labelled instances
	52.834781646728516
	53.79086685180664
	Test MAPE = 0.16213666477717725

Iteration 83: 656 labelled instances
	57.65552520751953
	56.17672348022461
	Test MAPE = 0.16388444766903648

Iteration 84: 663 labelled instances
	52.20271301269531
	53.27327346801758
	Test MAPE = 0.16226701726049342

Iteration 85: 670 labelled instances
	50.45820999145508
	52.26171875
	Test MAPE = 0.16616264821340412

Iteration 86: 677 labelled instances
	51.31287384033203
	49.31251907348633
	Test MAPE = 0.16766273087252773

Iteration 87: 684 labelled instances
	49.55674362182617
	47.30502700805664
	Test MAPE = 0.16089252479272143

Iteration 88: 691 labelled instances
	48.8924560546875
	52.35725402832031
	Test MAPE = 0.1638916642553504

Iteration 89: 698 labelled instances
	52.228458404541016
	52.22361373901367
	Test MAPE = 0.16505080660629445

Iteration 90: 705 labelled instances
	54.37729263305664
	52.55659484863281
	Test MAPE = 0.16818689476410312

Iteration 91: 712 labelled instances
	49.1332893371582
	48.87229537963867
	Test MAPE = 0.16953960119915318

Iteration 92: 719 labelled instances
	50.90138244628906
	50.44361114501953
	Test MAPE = 0.15842618306979062

Iteration 93: 726 labelled instances
	56.20887756347656
	48.721622467041016
	Test MAPE = 0.16186387030624533

Iteration 94: 733 labelled instances
	50.325130462646484
	56.218990325927734
	Test MAPE = 0.15785052856288795

Iteration 95: 740 labelled instances
	52.211483001708984
	50.515419006347656
	Test MAPE = 0.15954890825829135

Iteration 96: 747 labelled instances
	49.88559341430664
	51.37303924560547
	Test MAPE = 0.15752830726387204

Iteration 97: 754 labelled instances
	51.719966888427734
	50.53302001953125
	Test MAPE = 0.15511246895080458

Iteration 98: 761 labelled instances
	48.72513961791992
	51.15143966674805
	Test MAPE = 0.16494577927505927

Iteration 99: 768 labelled instances
	50.17953872680664
	53.751773834228516
	Test MAPE = 0.1557984673001204

Iteration 100: 824 labelled instances
	53.630897521972656
	50.29735565185547
	Test MAPE = 0.16639749166801845

In [5]:
activation = 'elu'
params = retrieve_params(f'params/concrete/{activation}.json')

scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)
for beta in [0.9]:
    history = sasla_reg(X_train, y_pool, X_val, y_test, num_iter=100, unlab_size=0.9, random_state=100, verbose=True,
                                   hidden_units=params['hidden_layer'], activation=activation, alpha=params['elu_alpha'],
                                   learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], beta=beta)
    
    run_df = pd.DataFrame(history)
    run_df.round(4).to_csv(f"results/concrete/sasla_{beta}.csv", index=False)

Iteration 1: 824 labelled instances
	688.2462158203125
	123.20750427246094
	Test MAPE = 0.2741092705225349

Iteration 2: 824 labelled instances
	104.38902282714844
	88.89701843261719
	Test MAPE = 0.21002605618405695

Iteration 3: 824 labelled instances
	81.99990844726562
	76.89398956298828
	Test MAPE = 0.19235272940064357

Iteration 4: 824 labelled instances
	76.14723205566406
	70.67788696289062
	Test MAPE = 0.1847347545371697

Iteration 5: 824 labelled instances
	69.58319091796875
	70.58709716796875
	Test MAPE = 0.19958019366230306

WARNING:tensorflow:5 out of the last 5 calls to <function pfor.<locals>.f at 0x0000020292E78EA0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Iteration 6: 824 labelled instances
	64.50582885742188
	59.121524810791016
	Test MAPE = 0.19796174347036155

WARNING:tensorflow:6 out of the last 6 calls to <function pfor.<locals>.f at 0x0000020292E794E0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Iteration 7: 824 labelled instances
	65.65623474121094
	64.92139434814453
	Test MAPE = 0.18277869745450245

Iteration 8: 824 labelled instances
	70.00354766845703
	59.065704345703125
	Test MAPE = 0.1776642086578215

Iteration 9: 824 labelled instances
	65.09345245361328
	62.507816314697266
	Test MAPE = 0.16659587813195187

Iteration 10: 824 labelled instances
	64.6469497680664
	59.29486846923828
	Test MAPE = 0.19942128287745392

Iteration 11: 824 labelled instances
	64.4771957397461
	63.93233871459961
	Test MAPE = 0.1855934326955352

Iteration 12: 824 labelled instances
	61.42472457885742
	56.82373046875
	Test MAPE = 0.18102551582832122

Iteration 13: 824 labelled instances
	57.63992691040039
	60.74028015136719
	Test MAPE = 0.17126197616537064

Iteration 14: 824 labelled instances
	53.755531311035156
	58.84919357299805
	Test MAPE = 0.19140077599475344

Iteration 15: 824 labelled instances
	56.347476959228516
	58.378971099853516
	Test MAPE = 0.1752603996866668

Iteration 16: 824 labelled instances
	64.37838745117188
	56.38800048828125
	Test MAPE = 0.1853545309427415

Iteration 17: 824 labelled instances
	59.50568389892578
	57.334102630615234
	Test MAPE = 0.1690974719628886

Iteration 18: 824 labelled instances
	60.57054901123047
	57.647300720214844
	Test MAPE = 0.17172638775413485

Iteration 19: 824 labelled instances
	59.229820251464844
	57.025936126708984
	Test MAPE = 0.18000577629613584

Iteration 20: 824 labelled instances
	54.762454986572266
	59.2747688293457
	Test MAPE = 0.17371420454647155

Iteration 21: 824 labelled instances
	57.77162551879883
	52.477622985839844
	Test MAPE = 0.17161189257029813

Iteration 22: 824 labelled instances
	53.095096588134766
	55.36186218261719
	Test MAPE = 0.16499528247133355

Iteration 23: 824 labelled instances
	58.86915588378906
	56.305824279785156
	Test MAPE = 0.17608546701897168

Iteration 24: 824 labelled instances
	60.3521728515625
	56.991756439208984
	Test MAPE = 0.16887861010496608

Iteration 25: 824 labelled instances
	58.12618637084961
	52.97121810913086
	Test MAPE = 0.16603227546986815

Iteration 26: 824 labelled instances
	54.547115325927734
	56.249732971191406
	Test MAPE = 0.17239958329462368

Iteration 27: 824 labelled instances
	53.63429260253906
	56.53951644897461
	Test MAPE = 0.17032341081810484

Iteration 28: 824 labelled instances
	51.83695602416992
	55.80934143066406
	Test MAPE = 0.16816105104103685

Iteration 29: 824 labelled instances
	56.534568786621094
	53.81763458251953
	Test MAPE = 0.1759965984652308

Iteration 30: 824 labelled instances
	56.6550407409668
	56.821380615234375
	Test MAPE = 0.16978307278650898

Iteration 31: 824 labelled instances
	56.61522674560547
	56.705345153808594
	Test MAPE = 0.18973674411370964

Iteration 32: 824 labelled instances
	56.37771987915039
	52.637420654296875
	Test MAPE = 0.17511798098039505

Iteration 33: 824 labelled instances
	55.365142822265625
	56.21345520019531
	Test MAPE = 0.17649595895949363

Iteration 34: 824 labelled instances
	48.973541259765625
	52.54035568237305
	Test MAPE = 0.168168005257414

Iteration 35: 824 labelled instances
	52.12712860107422
	53.38169479370117
	Test MAPE = 0.17059169455141968

Iteration 36: 824 labelled instances
	50.62316131591797
	53.21175765991211
	Test MAPE = 0.16440921661745111

Iteration 37: 824 labelled instances
	54.66828536987305
	53.474830627441406
	Test MAPE = 0.17192218567752396

Iteration 38: 824 labelled instances
	52.64720153808594
	53.42320251464844
	Test MAPE = 0.16955797680678822

Iteration 39: 824 labelled instances
	55.84164810180664
	53.599220275878906
	Test MAPE = 0.1743749412555346

Iteration 40: 824 labelled instances
	51.09442901611328
	53.62392807006836
	Test MAPE = 0.18021745719021334

Iteration 41: 824 labelled instances
	54.35167694091797
	50.51776123046875
	Test MAPE = 0.17396402921381143

Iteration 42: 824 labelled instances
	52.495880126953125
	49.94308090209961
	Test MAPE = 0.16646981544236478

Iteration 43: 824 labelled instances
	53.66364669799805
	51.486209869384766
	Test MAPE = 0.16782094789991506

Iteration 44: 824 labelled instances
	58.15080642700195
	49.64052200317383
	Test MAPE = 0.16709211508198044

Iteration 45: 824 labelled instances
	53.5826301574707
	56.62696075439453
	Test MAPE = 0.15977406430572064

Iteration 46: 824 labelled instances
	52.95018768310547
	54.21162796020508
	Test MAPE = 0.173381776934355

Iteration 47: 824 labelled instances
	51.876502990722656
	57.75666046142578
	Test MAPE = 0.15985877039060467

Iteration 48: 824 labelled instances
	52.38679885864258
	54.62154006958008
	Test MAPE = 0.1602283671676453

Iteration 49: 824 labelled instances
	52.023555755615234
	51.77516174316406
	Test MAPE = 0.16045387195246524

Iteration 50: 824 labelled instances
	51.65854263305664
	53.17801284790039
	Test MAPE = 0.1685119048434753

Iteration 51: 824 labelled instances
	49.88912582397461
	51.92250061035156
	Test MAPE = 0.17873693935277937

Iteration 52: 824 labelled instances
	52.08937454223633
	49.102420806884766
	Test MAPE = 0.16670947560547658

Iteration 53: 824 labelled instances
	50.8905029296875
	51.27123260498047
	Test MAPE = 0.16896557956568134

Iteration 54: 824 labelled instances
	51.311683654785156
	53.14368438720703
	Test MAPE = 0.177168259748353

Iteration 55: 824 labelled instances
	51.05524826049805
	48.89588165283203
	Test MAPE = 0.1754594118757527

Iteration 56: 824 labelled instances
	51.4683952331543
	56.28530502319336
	Test MAPE = 0.17259458356068832

Iteration 57: 824 labelled instances
	50.00926208496094
	50.532718658447266
	Test MAPE = 0.16998644149007905

Iteration 58: 824 labelled instances
	53.61872863769531
	52.36237716674805
	Test MAPE = 0.17279802610931758

Iteration 59: 824 labelled instances
	50.03368377685547
	51.28736877441406
	Test MAPE = 0.161673484030532

Iteration 60: 824 labelled instances
	51.46403884887695
	52.712554931640625
	Test MAPE = 0.15803758031469511

Iteration 61: 824 labelled instances
	52.9676628112793
	49.22100067138672
	Test MAPE = 0.15959423504109088

Iteration 62: 824 labelled instances
	51.74417495727539
	50.69028854370117
	Test MAPE = 0.17600985866277524

Iteration 63: 824 labelled instances
	53.9197883605957
	52.05818557739258
	Test MAPE = 0.1637208161357138

Iteration 64: 824 labelled instances
	49.216304779052734
	52.643890380859375
	Test MAPE = 0.16124024422333175

Iteration 65: 824 labelled instances
	49.71269989013672
	48.83259963989258
	Test MAPE = 0.1676775033643126

Iteration 66: 824 labelled instances
	51.22571563720703
	52.41902542114258
	Test MAPE = 0.165601542008486

Iteration 67: 824 labelled instances
	47.94895935058594
	52.233707427978516
	Test MAPE = 0.17194049775280187

Iteration 68: 824 labelled instances
	51.79390335083008
	52.739994049072266
	Test MAPE = 0.16185415169495015

Iteration 69: 824 labelled instances
	50.12273406982422
	51.5908203125
	Test MAPE = 0.1611850136745548

Iteration 70: 824 labelled instances
	51.956634521484375
	48.1584587097168
	Test MAPE = 0.16530074860054172

Iteration 71: 824 labelled instances
	50.584049224853516
	52.663265228271484
	Test MAPE = 0.1737383818374686

Iteration 72: 824 labelled instances
	53.83974838256836
	52.23124694824219
	Test MAPE = 0.15960916370990447

Iteration 73: 824 labelled instances
	51.692359924316406
	51.23269271850586
	Test MAPE = 0.17532298790520182

Iteration 74: 824 labelled instances
	50.19757843017578
	52.00836181640625
	Test MAPE = 0.16874852532310422

Iteration 75: 824 labelled instances
	51.67184829711914
	49.227760314941406
	Test MAPE = 0.1664629659459338

Iteration 76: 824 labelled instances
	50.70949172973633
	50.419124603271484
	Test MAPE = 0.15696731925841564

Iteration 77: 824 labelled instances
	54.074440002441406
	51.98533248901367
	Test MAPE = 0.16890026898495758

Iteration 78: 824 labelled instances
	49.0267219543457
	52.460350036621094
	Test MAPE = 0.15704538150723965

Iteration 79: 824 labelled instances
	48.91210174560547
	54.146484375
	Test MAPE = 0.15754489392957804

Iteration 80: 824 labelled instances
	50.205326080322266
	48.579166412353516
	Test MAPE = 0.17167948727665608

Iteration 81: 824 labelled instances
	49.89349365234375
	52.02168273925781
	Test MAPE = 0.17565895164490347

Iteration 82: 824 labelled instances
	54.33513259887695
	52.025543212890625
	Test MAPE = 0.1669677680195369

Iteration 83: 824 labelled instances
	50.9871940612793
	48.938411712646484
	Test MAPE = 0.15272410569627684

Iteration 84: 824 labelled instances
	49.324214935302734
	48.176509857177734
	Test MAPE = 0.16849719972293484

Iteration 85: 824 labelled instances
	48.808685302734375
	50.99685287475586
	Test MAPE = 0.16203600043895722

Iteration 86: 824 labelled instances
	50.51445388793945
	49.519100189208984
	Test MAPE = 0.16432032494027055

Iteration 87: 824 labelled instances
	52.269981384277344
	48.95781326293945
	Test MAPE = 0.16800318606087203

Iteration 88: 824 labelled instances
	50.33094024658203
	49.3499755859375
	Test MAPE = 0.1679549642244348

Iteration 89: 824 labelled instances
	48.71540451049805
	48.11044692993164
	Test MAPE = 0.17025319343494777

Iteration 90: 824 labelled instances
	51.99100112915039
	49.41778564453125
	Test MAPE = 0.1745160631536611

Iteration 91: 824 labelled instances
	51.81697082519531
	50.98621368408203
	Test MAPE = 0.16677272240392255

Iteration 92: 824 labelled instances
	48.010467529296875
	49.5748291015625
	Test MAPE = 0.17347951198175965

Iteration 93: 824 labelled instances
	48.29972839355469
	53.06296920776367
	Test MAPE = 0.1706261734378674

Iteration 94: 824 labelled instances
	51.452083587646484
	50.00347900390625
	Test MAPE = 0.15650582272478972

Iteration 95: 824 labelled instances
	50.95695114135742
	51.33972930908203
	Test MAPE = 0.16803555193363495

Iteration 96: 824 labelled instances
	49.47261047363281
	50.33857727050781
	Test MAPE = 0.16381899571154424

Iteration 97: 824 labelled instances
	47.793338775634766
	49.95963668823242
	Test MAPE = 0.1673309492634412

Iteration 98: 824 labelled instances
	52.32079315185547
	48.880435943603516
	Test MAPE = 0.16828297020136201

Iteration 99: 824 labelled instances
	47.88672637939453
	50.691165924072266
	Test MAPE = 0.16018459827365053

Iteration 100: 824 labelled instances
	50.978458404541016
	48.694583892822266
	Test MAPE = 0.1678805693912139

## Seoul Bike sharing

In [6]:
seoul_bike_sharing_demand = fetch_ucirepo(id=560)
sbsd_df = pd.concat(
    [seoul_bike_sharing_demand.data.features, seoul_bike_sharing_demand.data.targets],
    axis=1
)

drop = ['Date', 'Hour', "Month", "DayOfWeek", 'Seasons']
sbsd_df['Date'] = pd.to_datetime(
    sbsd_df["Date"],
    format="%d/%m/%Y"
)
sbsd_df["Hour_sin"] = np.sin(2 * np.pi * sbsd_df["Hour"] / 24)
sbsd_df["Hour_cos"] = np.cos(2 * np.pi * sbsd_df["Hour"] / 24)

sbsd_df["Month"] = sbsd_df["Date"].dt.month
sbsd_df["DayOfWeek"] = sbsd_df["Date"].dt.dayofweek

sbsd_df["Month_sin"] = np.sin(2 * np.pi * sbsd_df["Month"] / 12)
sbsd_df["Month_cos"] = np.cos(2 * np.pi * sbsd_df["Month"] / 12)

sbsd_df["DayOfWeek_sin"] = np.sin(2 * np.pi * sbsd_df["DayOfWeek"] / 7)
sbsd_df["DayOfWeek_cos"] = np.cos(2 * np.pi * sbsd_df["DayOfWeek"] / 7)

sbsd_df["Holiday"] = (sbsd_df["Holiday"] == "Holiday").astype(int)
sbsd_df["Functioning Day"] = (sbsd_df["Functioning Day"] == "Yes").astype(int)

sbsd_df.drop(columns=drop, inplace=True)

sbsd_df.head()

,Rented Bike Count,Temperature,Humidity,Wind speed,Visibility,Dew point temperature,Solar Radiation,Rainfall,Snowfall,Holiday,Functioning Day,Hour_sin,Hour_cos,Month_sin,Month_cos,DayOfWeek_sin,DayOfWeek_cos
0,254,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,0,1,0.000000,1.000000,-2.449294e-16,1.0,-0.433884,-0.900969
1,204,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,0,1,0.258819,0.965926,-2.449294e-16,1.0,-0.433884,-0.900969
2,173,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,0,1,0.500000,0.866025,-2.449294e-16,1.0,-0.433884,-0.900969
3,107,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,0,1,0.707107,0.707107,-2.449294e-16,1.0,-0.433884,-0.900969
4,78,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,0,1,0.866025,0.500000,-2.449294e-16,1.0,-0.433884,-0.900969

In [7]:
X = sbsd_df.drop(columns=['Rented Bike Count']).to_numpy()
y = sbsd_df['Rented Bike Count'].to_numpy()

X_pool, X_test, y_pool, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=51
)

In [ ]:
acts = ['relu', 'leaky_relu', 'elu']
for activation in acts:
    base_params = tune_params(X_pool, y_pool,
                              loss='mse',
                              out_units=1, out_act='linear',
                              k=5, activation=activation,
                              random_state=42,
                              n_trials=80,
                              export=True, file = f'params/seoul_bikes/{activation}.json'
    )

In [19]:
acts = ['relu', 'leaky_relu', 'elu']
results = []
for activation in acts:
    setup = {'activation': activation}
    alpha = 0
    params = retrieve_params(f'params/seoul_bikes/{activation}.json')
    if activation == 'leaky_relu':
        alpha = params["leaky_relu_alpha"]
    elif activation == 'elu':
        alpha = params["elu_alpha"]
    result = cv_regression(X_pool, y_pool, out_units=1, out_act='linear', 
                    loss='mse', k=5, random_state=42, 
                    hidden_units=params['hidden_layer'], activation=activation, alpha=alpha, 
                    learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'])
    for key, val in result.items():
        setup[key] = val

    results.append(setup)

results_df = pd.DataFrame(results)
results_df.round(4).to_csv(f"results/seoul_bikes/cv_validation.csv", index=False)

In [7]:
results_df = pd.read_csv("results/seoul_bikes/cv_validation.csv")
results_df

   activation      rmse          mape  R_squared
0        relu  241.1777  3.171544e+15     0.8603
1  leaky_relu  243.0892  3.448171e+15     0.8579
2         elu  231.1582  9.392297e+15     0.8717

In [7]:
activation = 'elu'
params = retrieve_params(f'params/seoul_bikes/{activation}.json')
scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)
model = create_regmodel(X_train.shape[1], hidden_units=params['hidden_layer'], activation=activation, alpha=params['elu_alpha'], 
                 learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], loss='mse')
# params['learning_rate']
history = []
runs = 100
# runs = 200
epochs = 200 // runs

fit_kwargs = {
    "epochs": epochs,
    "batch_size": 32,
    # "validation_split": 0.15,
    # "callbacks": [early_stopping],
    "verbose": 0
}
tic = time()
for i in range(runs):
    iteration = {'cumulative epochs': epochs * (i + 1)}
    iter_hist = model.fit(
        X_train,
        y_pool,
        **fit_kwargs
    )

    train_loss = iter_hist.history['loss']
    weights = model.get_weights()

    print(f"Iteration {i+1}: ")
    for l in range(len(train_loss)):
        print(f"\t{train_loss[l]}")

    if not all(np.all(np.isfinite(w)) for w in weights):
        print(f"Model became unstable at iteration {i + 1}")
        break

    y_pred = model(X_val, training=False).numpy().ravel()

    if not np.all(np.isfinite(y_pred)):
        print(f"NaN/Inf predictions at iteration {i + 1}")
        break

    rmse = root_mean_squared_error(y_test, y_pred)
    mape = mean_absolute_percentage_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    toc = time()

    iteration['Training loss'] = train_loss[-1]
    iteration['RMSE'] = rmse
    iteration['MAPE'] = mape
    iteration['MAE'] = mae
    iteration['R2-score'] = r2
    iteration['time'] = toc - tic
    history.append(iteration)
    
    print(f"Iteration {i+1}: ")
    for l in range(len(train_loss)):
        print(f"\t{train_loss[l]}")

run_df = pd.DataFrame(history)
run_df.round(4).to_csv(f"results/seoul_bikes/passive_learning.csv", index=False)

Iteration 1:
	271371.375
	135844.4375
Iteration 1:
	271371.375
	135844.4375
Iteration 2:
	114327.609375
	101420.3125
Iteration 2:
	114327.609375
	101420.3125
Iteration 3:
	93129.875
	86644.03125
Iteration 3:
	93129.875
	86644.03125
Iteration 4:
	83417.1953125
	80139.9453125
Iteration 4:
	83417.1953125
	80139.9453125
Iteration 5:
	78015.0703125
	73294.859375
Iteration 5:
	78015.0703125
	73294.859375
Iteration 6:
	72965.8125
	71452.5078125
Iteration 6:
	72965.8125
	71452.5078125
Iteration 7:
	70121.34375
	67074.65625
Iteration 7:
	70121.34375
	67074.65625
Iteration 8:
	68969.8828125
	66530.390625
Iteration 8:
	68969.8828125
	66530.390625
Iteration 9:
	65855.3671875
	65657.6875
Iteration 9:
	65855.3671875
	65657.6875
Iteration 10:
	64201.01953125
	64392.484375
Iteration 10:
	64201.01953125
	64392.484375
Iteration 11:
	63395.2109375
	64908.65625
Iteration 11:
	63395.2109375
	64908.65625
Iteration 12:
	62141.27734375
	62868.30859375
Iteration 12:
	62141.27734375
	62868.30859375
Iteration 13:
	63226.05078125
	62012.40234375
Iteration 13:
	63226.05078125
	62012.40234375
Iteration 14:
	60807.2109375
	62336.109375
Iteration 14:
	60807.2109375
	62336.109375
Iteration 15:
	62342.27734375
	61609.94921875
Iteration 15:
	62342.27734375
	61609.94921875
Iteration 16:
	61194.09765625
	60598.9921875
Iteration 16:
	61194.09765625
	60598.9921875
Iteration 17:
	60542.44140625
	60291.19140625
Iteration 17:
	60542.44140625
	60291.19140625
Iteration 18:
	60973.046875
	59730.77734375
Iteration 18:
	60973.046875
	59730.77734375
Iteration 19:
	59068.86328125
	58934.62109375
Iteration 19:
	59068.86328125
	58934.62109375
Iteration 20:
	58717.79296875
	59480.984375
Iteration 20:
	58717.79296875
	59480.984375
Iteration 21:
	57429.58984375
	59783.8046875
Iteration 21:
	57429.58984375
	59783.8046875
Iteration 22:
	58495.76171875
	56910.4375
Iteration 22:
	58495.76171875
	56910.4375
Iteration 23:
	58357.78515625
	58644.10546875
Iteration 23:
	58357.78515625
	58644.10546875
Iteration 24:
	60076.6015625
	56553.73046875
Iteration 24:
	60076.6015625
	56553.73046875
Iteration 25:
	59381.7265625
	58365.8828125
Iteration 25:
	59381.7265625
	58365.8828125
Iteration 26:
	57135.921875
	59281.2890625
Iteration 26:
	57135.921875
	59281.2890625
Iteration 27:
	58047.921875
	56998.1640625
Iteration 27:
	58047.921875
	56998.1640625
Iteration 28:
	56917.88671875
	56829.25
Iteration 28:
	56917.88671875
	56829.25
Iteration 29:
	56961.1953125
	57135.4765625
Iteration 29:
	56961.1953125
	57135.4765625
Iteration 30:
	56775.26171875
	57211.51953125
Iteration 30:
	56775.26171875
	57211.51953125
Iteration 31:
	56694.1953125
	57387.046875
Iteration 31:
	56694.1953125
	57387.046875
Iteration 32:
	56343.05078125
	55774.77734375
Iteration 32:
	56343.05078125
	55774.77734375
Iteration 33:
	55791.65625
	57289.5625
Iteration 33:
	55791.65625
	57289.5625
Iteration 34:
	55966.96484375
	57057.39453125
Iteration 34:
	55966.96484375
	57057.39453125
Iteration 35:
	56278.20703125
	55081.34765625
Iteration 35:
	56278.20703125
	55081.34765625
Iteration 36:
	54968.25
	54519.5625
Iteration 36:
	54968.25
	54519.5625
Iteration 37:
	55999.97265625
	56823.5390625
Iteration 37:
	55999.97265625
	56823.5390625
Iteration 38:
	54758.85546875
	55219.5859375
Iteration 38:
	54758.85546875
	55219.5859375
Iteration 39:
	55838.48828125
	55049.140625
Iteration 39:
	55838.48828125
	55049.140625
Iteration 40:
	54925.24609375
	54953.26953125
Iteration 40:
	54925.24609375
	54953.26953125
Iteration 41:
	56221.48828125
	55375.66796875
Iteration 41:
	56221.48828125
	55375.66796875
Iteration 42:
	54618.90234375
	55923.51953125
Iteration 42:
	54618.90234375
	55923.51953125
Iteration 43:
	55817.14453125
	55610.76171875
Iteration 43:
	55817.14453125
	55610.76171875
Iteration 44:
	54069.29296875
	55000.73828125
Iteration 44:
	54069.29296875
	55000.73828125
Iteration 45:
	55008.7734375
	53394.046875
Iteration 45:
	55008.7734375
	53394.046875
Iteration 46:
	53894.4140625
	55676.6796875
Iteration 46:
	53894.4140625
	55676.6796875
Iteration 47:
	52816.08203125
	55528.484375
Iteration 47:
	52816.08203125
	55528.484375
Iteration 48:
	53778.19921875
	54025.6953125
Iteration 48:
	53778.19921875
	54025.6953125
Iteration 49:
	55916.8046875
	55568.02734375
Iteration 49:
	55916.8046875
	55568.02734375
Iteration 50:
	54528.16015625
	55074.7734375
Iteration 50:
	54528.16015625
	55074.7734375
Iteration 51:
	52762.35546875
	54916.0703125
Iteration 51:
	52762.35546875
	54916.0703125
Iteration 52:
	54838.80859375
	54135.3984375
Iteration 52:
	54838.80859375
	54135.3984375
Iteration 53:
	53506.94140625
	55128.94921875
Iteration 53:
	53506.94140625
	55128.94921875
Iteration 54:
	53574.78125
	54451.19140625
Iteration 54:
	53574.78125
	54451.19140625
Iteration 55:
	54779.84765625
	53841.34375
Iteration 55:
	54779.84765625
	53841.34375
Iteration 56:
	52556.9453125
	53894.94140625
Iteration 56:
	52556.9453125
	53894.94140625
Iteration 57:
	54253.19140625
	53399.70703125
Iteration 57:
	54253.19140625
	53399.70703125
Iteration 58:
	53693.0078125
	53766.9296875
Iteration 58:
	53693.0078125
	53766.9296875
Iteration 59:
	53382.68359375
	53763.2109375
Iteration 59:
	53382.68359375
	53763.2109375
Iteration 60:
	53885.96875
	53914.6796875
Iteration 60:
	53885.96875
	53914.6796875
Iteration 61:
	53946.02734375
	53703.0546875
Iteration 61:
	53946.02734375
	53703.0546875
Iteration 62:
	52742.125
	54345.73828125
Iteration 62:
	52742.125
	54345.73828125
Iteration 63:
	54102.40625
	52304.28125
Iteration 63:
	54102.40625
	52304.28125
Iteration 64:
	53136.328125
	52704.4765625
Iteration 64:
	53136.328125
	52704.4765625
Iteration 65:
	53087.5390625
	53311.78515625
Iteration 65:
	53087.5390625
	53311.78515625
Iteration 66:
	54249.15625
	55087.765625
Iteration 66:
	54249.15625
	55087.765625
Iteration 67:
	52525.66015625
	52717.078125
Iteration 67:
	52525.66015625
	52717.078125
Iteration 68:
	54373.484375
	54611.83203125
Iteration 68:
	54373.484375
	54611.83203125
Iteration 69:
	54275.6015625
	53092.51953125
Iteration 69:
	54275.6015625
	53092.51953125
Iteration 70:
	53574.859375
	52936.53515625
Iteration 70:
	53574.859375
	52936.53515625
Iteration 71:
	52340.9921875
	53783.49609375
Iteration 71:
	52340.9921875
	53783.49609375
Iteration 72:
	53419.625
	52526.140625
Iteration 72:
	53419.625
	52526.140625
Iteration 73:
	52842.9375
	51852.0234375
Iteration 73:
	52842.9375
	51852.0234375
Iteration 74:
	53338.98046875
	53539.66015625
Iteration 74:
	53338.98046875
	53539.66015625
Iteration 75:
	53148.40234375
	53307.0703125
Iteration 75:
	53148.40234375
	53307.0703125
Iteration 76:
	51827.640625
	53026.421875
Iteration 76:
	51827.640625
	53026.421875
Iteration 77:
	52912.94921875
	53760.4140625
Iteration 77:
	52912.94921875
	53760.4140625
Iteration 78:
	52967.12890625
	52032.64453125
Iteration 78:
	52967.12890625
	52032.64453125
Iteration 79:
	52134.8671875
	53179.54296875
Iteration 79:
	52134.8671875
	53179.54296875
Iteration 80:
	53425.55078125
	51901.1640625
Iteration 80:
	53425.55078125
	51901.1640625
Iteration 81:
	54246.6796875
	52876.34375
Iteration 81:
	54246.6796875
	52876.34375
Iteration 82:
	52581.83203125
	52955.88671875
Iteration 82:
	52581.83203125
	52955.88671875
Iteration 83:
	52080.01953125
	51817.9375
Iteration 83:
	52080.01953125
	51817.9375
Iteration 84:
	51072.98046875
	52954.1875
Iteration 84:
	51072.98046875
	52954.1875
Iteration 85:
	53706.55078125
	51630.484375
Iteration 85:
	53706.55078125
	51630.484375
Iteration 86:
	51051.5390625
	52853.68359375
Iteration 86:
	51051.5390625
	52853.68359375
Iteration 87:
	53008.3515625
	52675.2734375
Iteration 87:
	53008.3515625
	52675.2734375
Iteration 88:
	53090.0
	52566.015625
Iteration 88:
	53090.0
	52566.015625
Iteration 89:
	53702.22265625
	52721.91796875
Iteration 89:
	53702.22265625
	52721.91796875
Iteration 90:
	52554.6484375
	52519.171875
Iteration 90:
	52554.6484375
	52519.171875
Iteration 91:
	53171.921875
	52603.8671875
Iteration 91:
	53171.921875
	52603.8671875
Iteration 92:
	53830.25390625
	52260.6953125
Iteration 92:
	53830.25390625
	52260.6953125
Iteration 93:
	52910.13671875
	53601.20703125
Iteration 93:
	52910.13671875
	53601.20703125
Iteration 94:
	53394.41015625
	53086.44140625
Iteration 94:
	53394.41015625
	53086.44140625
Iteration 95:
	51327.60546875
	52731.75
Iteration 95:
	51327.60546875
	52731.75
Iteration 96:
	52327.16015625
	52748.859375
Iteration 96:
	52327.16015625
	52748.859375
Iteration 97:
	50489.19140625
	51790.3984375
Iteration 97:
	50489.19140625
	51790.3984375
Iteration 98:
	51578.92578125
	52025.25390625
Iteration 98:
	51578.92578125
	52025.25390625
Iteration 99:
	51387.43359375
	51446.67578125
Iteration 99:
	51387.43359375
	51446.67578125
Iteration 100:
	52672.91796875
	52013.95703125
Iteration 100:
	52672.91796875
	52013.95703125

In [8]:
activation = 'elu'
params = retrieve_params(f'params/seoul_bikes/{activation}.json')

scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)

history = active_learning_reg(X_train, y_pool, X_val, y_test, random_sampling, num_iter=100, unlab_size=0.9, random_state=100, verbose=True,
                               hidden_units=params['hidden_layer'], activation=activation, alpha=params['elu_alpha'],
                               learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'] 
)

run_df = pd.DataFrame(history)
run_df.round(4).to_csv(f"results/seoul_bikes/uncertainty_sampling_reg.csv", index=False)

Iteration 1: 700 labelled instances
	904755.0
	420137.28125
	Test MAPE = 3.979191421973299e+16

Iteration 2: 763 labelled instances
	202994.15625
	191988.25
	Test MAPE = 2.3550095957950464e+16

Iteration 3: 826 labelled instances
	177775.578125
	161995.625
	Test MAPE = 1.845965991654195e+16

Iteration 4: 889 labelled instances
	152419.765625
	143047.84375
	Test MAPE = 1.7364779337252864e+16

Iteration 5: 952 labelled instances
	146792.375
	142161.59375
	Test MAPE = 1.224598792175616e+16

Iteration 6: 1015 labelled instances
	140261.328125
	139911.90625
	Test MAPE = 1.279882000596992e+16

Iteration 7: 1078 labelled instances
	133114.171875
	127994.0625
	Test MAPE = 1.5143992408670208e+16

Iteration 8: 1141 labelled instances
	124280.734375
	123023.2734375
	Test MAPE = 1.7842671758344192e+16

Iteration 9: 1204 labelled instances
	115519.7734375
	116201.796875
	Test MAPE = 1.892964959780864e+16

Iteration 10: 1267 labelled instances
	114766.0390625
	106766.078125
	Test MAPE = 1.7020618239115264e+16

Iteration 11: 1330 labelled instances
	98972.8828125
	104086.4609375
	Test MAPE = 1.7150001981423616e+16

Iteration 12: 1393 labelled instances
	99772.046875
	89438.796875
	Test MAPE = 1.5817611858149376e+16

Iteration 13: 1456 labelled instances
	92907.671875
	90922.4453125
	Test MAPE = 1.4606921780690944e+16

Iteration 14: 1519 labelled instances
	90356.625
	86577.3125
	Test MAPE = 1.650968785584128e+16

Iteration 15: 1582 labelled instances
	85258.0546875
	78162.4765625
	Test MAPE = 1.6349669185552384e+16

Iteration 16: 1645 labelled instances
	78738.109375
	82848.203125
	Test MAPE = 1.2848055363567616e+16

Iteration 17: 1708 labelled instances
	77633.515625
	78478.8203125
	Test MAPE = 1.6379176684617728e+16

Iteration 18: 1771 labelled instances
	76945.828125
	77951.2734375
	Test MAPE = 1.1867942752878592e+16

Iteration 19: 1834 labelled instances
	73835.4296875
	72813.53125
	Test MAPE = 1.3692966698745856e+16

Iteration 20: 1897 labelled instances
	70636.796875
	72909.1875
	Test MAPE = 1.2833400935153664e+16

Iteration 21: 1960 labelled instances
	69781.9140625
	67819.1875
	Test MAPE = 1.2925078085828608e+16

Iteration 22: 2023 labelled instances
	67405.65625
	68625.234375
	Test MAPE = 1.0941621386346496e+16

Iteration 23: 2086 labelled instances
	68711.953125
	65039.87109375
	Test MAPE = 1.194179149430784e+16

Iteration 24: 2149 labelled instances
	67356.453125
	66543.765625
	Test MAPE = 1.0322421319991296e+16

Iteration 25: 2212 labelled instances
	67607.1484375
	68432.1796875
	Test MAPE = 1.1273169239277568e+16

Iteration 26: 2275 labelled instances
	65240.453125
	64556.94921875
	Test MAPE = 1.0723240552955904e+16

Iteration 27: 2338 labelled instances
	65788.171875
	66588.125
	Test MAPE = 1.2439233532788736e+16

Iteration 28: 2401 labelled instances
	69155.3046875
	70090.0625
	Test MAPE = 9770787531653120.0

Iteration 29: 2464 labelled instances
	66706.15625
	66276.375
	Test MAPE = 8856642934276096.0

Iteration 30: 2527 labelled instances
	66363.203125
	66456.515625
	Test MAPE = 7665625417646080.0

Iteration 31: 2590 labelled instances
	65267.03515625
	62923.34765625
	Test MAPE = 8158280715075584.0

Iteration 32: 2653 labelled instances
	68325.7578125
	65696.4296875
	Test MAPE = 8593629874487296.0

Iteration 33: 2716 labelled instances
	64660.44921875
	64802.890625
	Test MAPE = 9987345151426560.0

Iteration 34: 2779 labelled instances
	63569.10546875
	64931.109375
	Test MAPE = 1.0469198606106624e+16

Iteration 35: 2842 labelled instances
	66641.609375
	66060.6796875
	Test MAPE = 8261674536534016.0

Iteration 36: 2905 labelled instances
	63385.953125
	64978.13671875
	Test MAPE = 1.0137399497588736e+16

Iteration 37: 2968 labelled instances
	63691.515625
	62562.55078125
	Test MAPE = 1.122926178861056e+16

Iteration 38: 3031 labelled instances
	65392.71875
	66088.3046875
	Test MAPE = 1.0386924212584448e+16

Iteration 39: 3094 labelled instances
	63097.00390625
	61861.76953125
	Test MAPE = 7956421547130880.0

Iteration 40: 3157 labelled instances
	63927.99609375
	63563.703125
	Test MAPE = 1.229599207849984e+16

Iteration 41: 3220 labelled instances
	64011.70703125
	60774.83203125
	Test MAPE = 1.0185019947483136e+16

Iteration 42: 3283 labelled instances
	62131.66796875
	63038.76171875
	Test MAPE = 9314417191682048.0

Iteration 43: 3346 labelled instances
	60558.27734375
	62609.3515625
	Test MAPE = 9898705616371712.0

Iteration 44: 3409 labelled instances
	62259.796875
	60957.17578125
	Test MAPE = 9908722553847808.0

Iteration 45: 3472 labelled instances
	59907.203125
	59538.8984375
	Test MAPE = 1.0552676664213504e+16

Iteration 46: 3535 labelled instances
	62993.99609375
	61980.34765625
	Test MAPE = 9596677073666048.0

Iteration 47: 3598 labelled instances
	62444.15234375
	62201.0078125
	Test MAPE = 9455679739789312.0

Iteration 48: 3661 labelled instances
	61918.421875
	63277.68359375
	Test MAPE = 1.0834848499367936e+16

Iteration 49: 3724 labelled instances
	63229.24609375
	59640.671875
	Test MAPE = 9405238570123264.0

Iteration 50: 3787 labelled instances
	61443.26171875
	60663.41796875
	Test MAPE = 9715225687228416.0

Iteration 51: 3850 labelled instances
	59412.6796875
	60909.84375
	Test MAPE = 1.0178194170707968e+16

Iteration 52: 3913 labelled instances
	60972.01953125
	60805.98046875
	Test MAPE = 8565525755985920.0

Iteration 53: 3976 labelled instances
	61340.8359375
	57710.03125
	Test MAPE = 1.0337850990002176e+16

Iteration 54: 4039 labelled instances
	60691.28125
	58135.65625
	Test MAPE = 8220428354977792.0

Iteration 55: 4102 labelled instances
	59542.84765625
	60784.76953125
	Test MAPE = 1.0366443661033472e+16

Iteration 56: 4165 labelled instances
	57711.17578125
	59064.890625
	Test MAPE = 8520662675095552.0

Iteration 57: 4228 labelled instances
	56598.86328125
	58735.6796875
	Test MAPE = 9824356511252480.0

Iteration 58: 4291 labelled instances
	58263.9921875
	58137.8984375
	Test MAPE = 8987751105953792.0

Iteration 59: 4354 labelled instances
	57924.3125
	59652.3203125
	Test MAPE = 9760575173165056.0

Iteration 60: 4417 labelled instances
	57816.546875
	57403.65625
	Test MAPE = 9146054473678848.0

Iteration 61: 4480 labelled instances
	56264.22265625
	58483.078125
	Test MAPE = 8347828896137216.0

Iteration 62: 4543 labelled instances
	56843.09375
	57438.91015625
	Test MAPE = 8507820722880512.0

Iteration 63: 4606 labelled instances
	57056.71484375
	57717.25
	Test MAPE = 9580720196419584.0

Iteration 64: 4669 labelled instances
	58401.08203125
	59124.52734375
	Test MAPE = 7592985172639744.0

Iteration 65: 4732 labelled instances
	56156.84375
	59670.56640625
	Test MAPE = 8341311820136448.0

Iteration 66: 4795 labelled instances
	57545.50390625
	56637.17578125
	Test MAPE = 6849510764445696.0

Iteration 67: 4858 labelled instances
	55466.40625
	58067.47265625
	Test MAPE = 9896528067952640.0

Iteration 68: 4921 labelled instances
	56701.25
	57253.0859375
	Test MAPE = 7206963712622592.0

Iteration 69: 4984 labelled instances
	55128.859375
	55081.546875
	Test MAPE = 8410774326214656.0

Iteration 70: 5047 labelled instances
	56863.75390625
	55242.1953125
	Test MAPE = 8670720242483200.0

Iteration 71: 5110 labelled instances
	56957.46484375
	54695.265625
	Test MAPE = 8009712964468736.0

Iteration 72: 5173 labelled instances
	55787.41796875
	55580.0703125
	Test MAPE = 1.0695839735349248e+16

Iteration 73: 5236 labelled instances
	56366.66796875
	57321.2265625
	Test MAPE = 9482119558463488.0

Iteration 74: 5299 labelled instances
	55724.35546875
	56426.99609375
	Test MAPE = 7695325116497920.0

Iteration 75: 5362 labelled instances
	56741.50390625
	55127.15625
	Test MAPE = 1.1071504418603008e+16

Iteration 76: 5425 labelled instances
	56381.25
	55710.6796875
	Test MAPE = 9102107294564352.0

Iteration 77: 5488 labelled instances
	56544.40625
	55027.9296875
	Test MAPE = 9647946098278400.0

Iteration 78: 5551 labelled instances
	55268.47265625
	54393.359375
	Test MAPE = 8123818971234304.0

Iteration 79: 5614 labelled instances
	56160.83984375
	54892.73828125
	Test MAPE = 7776757696430080.0

Iteration 80: 5677 labelled instances
	56099.890625
	55355.0234375
	Test MAPE = 8191877559877632.0

Iteration 81: 5740 labelled instances
	55690.125
	54798.421875
	Test MAPE = 7255357256630272.0

Iteration 82: 5803 labelled instances
	54663.96875
	53935.140625
	Test MAPE = 9687576835260416.0

Iteration 83: 5866 labelled instances
	55587.10546875
	55746.3203125
	Test MAPE = 6356395905515520.0

Iteration 84: 5929 labelled instances
	55806.5859375
	54139.01953125
	Test MAPE = 6558381238124544.0

Iteration 85: 5992 labelled instances
	54237.7578125
	55749.3125
	Test MAPE = 7715953307549696.0

Iteration 86: 6055 labelled instances
	53507.1015625
	54783.24609375
	Test MAPE = 8492724449705984.0

Iteration 87: 6118 labelled instances
	54998.9921875
	55018.296875
	Test MAPE = 7024033002422272.0

Iteration 88: 6181 labelled instances
	55578.87890625
	54004.5546875
	Test MAPE = 1.055519888375808e+16

Iteration 89: 6244 labelled instances
	54008.17578125
	53714.0859375
	Test MAPE = 7472575227625472.0

Iteration 90: 6307 labelled instances
	53259.40625
	54805.37109375
	Test MAPE = 6648175045640192.0

Iteration 91: 6370 labelled instances
	53766.5859375
	54123.92578125
	Test MAPE = 7728158530863104.0

Iteration 92: 6433 labelled instances
	53481.21875
	52350.48828125
	Test MAPE = 7690417579491328.0

Iteration 93: 6496 labelled instances
	54712.08203125
	53649.05859375
	Test MAPE = 6480501669888000.0

Iteration 94: 6559 labelled instances
	53616.34375
	53021.7421875
	Test MAPE = 6656814372356096.0

Iteration 95: 6622 labelled instances
	53503.75
	54815.53125
	Test MAPE = 7294294356393984.0

Iteration 96: 6685 labelled instances
	54492.34375
	53857.55078125
	Test MAPE = 8221204670316544.0

Iteration 97: 6748 labelled instances
	52806.98828125
	53244.76953125
	Test MAPE = 7687676853485568.0

Iteration 98: 6811 labelled instances
	54245.07421875
	53831.04296875
	Test MAPE = 5892000419151872.0

Iteration 99: 6874 labelled instances
	55277.71875
	52873.39453125
	Test MAPE = 6361567583010816.0

Iteration 100: 7008 labelled instances
	52711.69140625
	54046.421875
	Test MAPE = 6861783633494016.0

In [9]:
activation = 'elu'
params = retrieve_params(f'params/seoul_bikes/{activation}.json')

scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)
for beta in [0.9]:
    history = sasla_reg(X_train, y_pool, X_val, y_test, num_iter=100, unlab_size=0.9, random_state=100, verbose=True,
                                   hidden_units=params['hidden_layer'], activation=activation, alpha=params['elu_alpha'],
                                   learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], beta=beta)
    
    run_df = pd.DataFrame(history)
    run_df.round(4).to_csv(f"results/seoul_bikes/sasla_{beta}.csv", index=False)

Iteration 1: 7008 labelled instances
	268123.625
	138471.9375
	Test MAPE = 1.1375652527669248e+16

Iteration 2: 7000 labelled instances
	115493.578125
	103872.2734375
	Test MAPE = 1.1639756509151232e+16

Iteration 3: 7007 labelled instances
	92817.96875
	88712.84375
	Test MAPE = 1.2042258295554048e+16

Iteration 4: 7008 labelled instances
	82297.984375
	80337.3125
	Test MAPE = 1.208479779913728e+16

Iteration 5: 7008 labelled instances
	75974.8984375
	75667.75
	Test MAPE = 9411008858685440.0

Iteration 6: 7008 labelled instances
	75214.9140625
	73566.453125
	Test MAPE = 8325271191027712.0

Iteration 7: 7008 labelled instances
	71082.03125
	69653.578125
	Test MAPE = 1.0362654426136576e+16

Iteration 8: 7008 labelled instances
	68501.2109375
	68190.5
	Test MAPE = 1.1014961174151168e+16

Iteration 9: 7008 labelled instances
	67330.0625
	66090.4921875
	Test MAPE = 8714527835160576.0

Iteration 10: 7008 labelled instances
	66076.0703125
	65602.9765625
	Test MAPE = 7483689529245696.0

Iteration 11: 7008 labelled instances
	65624.8046875
	65208.546875
	Test MAPE = 8477484831997952.0

Iteration 12: 7008 labelled instances
	64421.00390625
	64261.54296875
	Test MAPE = 7225691917516800.0

Iteration 13: 7008 labelled instances
	63044.6796875
	63222.0234375
	Test MAPE = 8115128104910848.0

Iteration 14: 7008 labelled instances
	62441.18359375
	63392.04296875
	Test MAPE = 6848420379623424.0

Iteration 15: 7008 labelled instances
	62395.671875
	61747.26953125
	Test MAPE = 6214024182104064.0

Iteration 16: 7008 labelled instances
	61927.9375
	62420.546875
	Test MAPE = 8450694436618240.0

Iteration 17: 7008 labelled instances
	61541.7734375
	62023.625
	Test MAPE = 6559880718581760.0

Iteration 18: 7008 labelled instances
	60460.78515625
	59690.015625
	Test MAPE = 8487868452306944.0

Iteration 19: 7007 labelled instances
	59134.1015625
	60530.58984375
	Test MAPE = 9459593528737792.0

Iteration 20: 7008 labelled instances
	60001.359375
	59353.0859375
	Test MAPE = 7763789579550720.0

Iteration 21: 7007 labelled instances
	60794.63671875
	59787.875
	Test MAPE = 7439603300564992.0

Iteration 22: 7006 labelled instances
	61156.05078125
	58806.91015625
	Test MAPE = 8495540337639424.0

Iteration 23: 7004 labelled instances
	57454.734375
	58787.58203125
	Test MAPE = 8049993852125184.0

Iteration 24: 7005 labelled instances
	58696.43359375
	59653.51953125
	Test MAPE = 7770390407413760.0

Iteration 25: 7006 labelled instances
	58145.2421875
	58646.7109375
	Test MAPE = 6904709684133888.0

Iteration 26: 7007 labelled instances
	57419.08203125
	58825.5546875
	Test MAPE = 7052677749932032.0

Iteration 27: 7006 labelled instances
	57444.96875
	57857.1953125
	Test MAPE = 7478526441684992.0

Iteration 28: 7006 labelled instances
	58245.1640625
	57151.5625
	Test MAPE = 6713419893833728.0

Iteration 29: 7005 labelled instances
	58768.29296875
	59074.21484375
	Test MAPE = 8034265681887232.0

Iteration 30: 7001 labelled instances
	57670.45703125
	56989.9765625
	Test MAPE = 7279438601388032.0

Iteration 31: 7000 labelled instances
	58015.94140625
	58491.64453125
	Test MAPE = 6609576174551040.0

Iteration 32: 7002 labelled instances
	56732.6953125
	56989.90234375
	Test MAPE = 6970635821514752.0

Iteration 33: 7000 labelled instances
	56517.06640625
	56516.984375
	Test MAPE = 5967614929010688.0

Iteration 34: 7002 labelled instances
	56378.328125
	55982.3046875
	Test MAPE = 7009627682111488.0

Iteration 35: 7002 labelled instances
	56393.375
	56862.13671875
	Test MAPE = 6172743640809472.0

Iteration 36: 7001 labelled instances
	57163.8515625
	56087.2734375
	Test MAPE = 6690505706438656.0

Iteration 37: 7004 labelled instances
	56945.796875
	56631.48828125
	Test MAPE = 7367470398570496.0

Iteration 38: 7006 labelled instances
	55149.21875
	56254.46484375
	Test MAPE = 7463711488868352.0

Iteration 39: 7004 labelled instances
	56716.83984375
	56338.4453125
	Test MAPE = 6667014919684096.0

Iteration 40: 7005 labelled instances
	55034.73828125
	56251.91015625
	Test MAPE = 8513882532347904.0

Iteration 41: 7003 labelled instances
	55438.5234375
	55638.859375
	Test MAPE = 7613334727688192.0

Iteration 42: 7002 labelled instances
	55569.64453125
	57028.73828125
	Test MAPE = 7661446414467072.0

Iteration 43: 7003 labelled instances
	55082.90625
	56032.53125
	Test MAPE = 7004068383817728.0

Iteration 44: 7002 labelled instances
	57589.65625
	54234.59765625
	Test MAPE = 6616742327484416.0

Iteration 45: 7002 labelled instances
	56982.41015625
	55239.83203125
	Test MAPE = 6376781967785984.0

Iteration 46: 7002 labelled instances
	54125.171875
	56033.234375
	Test MAPE = 8217847079632896.0

Iteration 47: 7004 labelled instances
	55013.28515625
	55237.9609375
	Test MAPE = 8486396352266240.0

Iteration 48: 7005 labelled instances
	55729.67578125
	54111.6328125
	Test MAPE = 6725238033219584.0

Iteration 49: 7002 labelled instances
	56067.71875
	54391.7890625
	Test MAPE = 5944755502448640.0

Iteration 50: 7001 labelled instances
	55232.89453125
	55863.1796875
	Test MAPE = 6561239001989120.0

Iteration 51: 7002 labelled instances
	56203.71484375
	54280.3828125
	Test MAPE = 6633920586055680.0

Iteration 52: 7003 labelled instances
	54662.32421875
	55116.4296875
	Test MAPE = 6849738934583296.0

Iteration 53: 7004 labelled instances
	55277.8515625
	55034.03125
	Test MAPE = 6148748195397632.0

Iteration 54: 7006 labelled instances
	53869.1953125
	53700.1796875
	Test MAPE = 7013281625538560.0

Iteration 55: 7004 labelled instances
	55509.046875
	54222.80859375
	Test MAPE = 6822500788862976.0

Iteration 56: 7008 labelled instances
	55121.30859375
	54008.1015625
	Test MAPE = 6583724766396416.0

Iteration 57: 7005 labelled instances
	54029.94140625
	54666.765625
	Test MAPE = 6213340208562176.0

Iteration 58: 7006 labelled instances
	54301.0234375
	54241.51171875
	Test MAPE = 6560770850553856.0

Iteration 59: 7005 labelled instances
	55640.43359375
	54565.01171875
	Test MAPE = 5964708846764032.0

Iteration 60: 7004 labelled instances
	55196.42578125
	54279.79296875
	Test MAPE = 6962463035621376.0

Iteration 61: 7006 labelled instances
	52980.984375
	54717.96875
	Test MAPE = 6263265445281792.0

Iteration 62: 7006 labelled instances
	53185.1875
	54887.55859375
	Test MAPE = 6033119622725632.0

Iteration 63: 7007 labelled instances
	55053.91796875
	53722.0703125
	Test MAPE = 6302836052721664.0

Iteration 64: 7006 labelled instances
	54716.5625
	54024.38671875
	Test MAPE = 6404292307058688.0

Iteration 65: 7003 labelled instances
	54222.2734375
	55141.41015625
	Test MAPE = 6220868749361152.0

Iteration 66: 7003 labelled instances
	53508.24609375
	54310.15625
	Test MAPE = 7661743840952320.0

Iteration 67: 7003 labelled instances
	52864.08203125
	54776.84375
	Test MAPE = 6978024239005696.0

Iteration 68: 7000 labelled instances
	53709.828125
	54829.76171875
	Test MAPE = 6597589457698816.0

Iteration 69: 7004 labelled instances
	53620.625
	53202.3515625
	Test MAPE = 7137247266603008.0

Iteration 70: 7002 labelled instances
	54734.88671875
	53937.234375
	Test MAPE = 6379456121798656.0

Iteration 71: 7000 labelled instances
	52424.46484375
	55189.19921875
	Test MAPE = 5395435090870272.0

Iteration 72: 7003 labelled instances
	53729.44921875
	52579.7734375
	Test MAPE = 8903640077041664.0

Iteration 73: 7002 labelled instances
	53678.125
	53085.11328125
	Test MAPE = 6898989861437440.0

Iteration 74: 6998 labelled instances
	53438.04296875
	52594.63671875
	Test MAPE = 6536645482381312.0

Iteration 75: 7000 labelled instances
	52626.953125
	52824.265625
	Test MAPE = 5871359880069120.0

Iteration 76: 6999 labelled instances
	53721.90625
	53651.28125
	Test MAPE = 8218407572865024.0

Iteration 77: 7001 labelled instances
	53781.99609375
	53287.75390625
	Test MAPE = 5881922815262720.0

Iteration 78: 7002 labelled instances
	54024.37890625
	53289.94140625
	Test MAPE = 6369847206215680.0

Iteration 79: 7002 labelled instances
	53554.5859375
	53539.8984375
	Test MAPE = 6519374882013184.0

Iteration 80: 6998 labelled instances
	51972.4140625
	54632.546875
	Test MAPE = 6159869476339712.0

Iteration 81: 7003 labelled instances
	53300.69921875
	53079.36328125
	Test MAPE = 5759769650397184.0

Iteration 82: 7000 labelled instances
	52292.43359375
	54463.60546875
	Test MAPE = 5329004831703040.0

Iteration 83: 7004 labelled instances
	52307.921875
	53370.1796875
	Test MAPE = 5295453620928512.0

Iteration 84: 6999 labelled instances
	54537.0390625
	52804.94140625
	Test MAPE = 5686517372551168.0

Iteration 85: 7000 labelled instances
	53867.4609375
	52442.28125
	Test MAPE = 5226679383359488.0

Iteration 86: 7001 labelled instances
	52966.98046875
	52306.125
	Test MAPE = 1.0295921371774976e+16

Iteration 87: 7000 labelled instances
	53184.4921875
	53800.96875
	Test MAPE = 5314225849237504.0

Iteration 88: 6996 labelled instances
	53497.70703125
	51569.29296875
	Test MAPE = 5206779726135296.0

Iteration 89: 6995 labelled instances
	52381.65625
	51934.88671875
	Test MAPE = 7289250991046656.0

Iteration 90: 6997 labelled instances
	52820.5859375
	52888.37109375
	Test MAPE = 5843993422200832.0

Iteration 91: 6998 labelled instances
	53155.00390625
	53525.4453125
	Test MAPE = 5308728291098624.0

Iteration 92: 6997 labelled instances
	53916.09765625
	52590.03125
	Test MAPE = 5611980362612736.0

Iteration 93: 6997 labelled instances
	53055.8046875
	52662.484375
	Test MAPE = 6516245461467136.0

Iteration 94: 6997 labelled instances
	52269.2265625
	54211.91796875
	Test MAPE = 6340834702131200.0

Iteration 95: 6998 labelled instances
	51838.68359375
	53141.55859375
	Test MAPE = 5723287124443136.0

Iteration 96: 6998 labelled instances
	53441.06640625
	53786.671875
	Test MAPE = 7281087868829696.0

Iteration 97: 6996 labelled instances
	52309.33203125
	52366.109375
	Test MAPE = 6185075565658112.0

Iteration 98: 6997 labelled instances
	50891.0234375
	53109.6953125
	Test MAPE = 5673540128866304.0

Iteration 99: 6996 labelled instances
	53468.20703125
	53817.5546875
	Test MAPE = 5490240588349440.0

Iteration 100: 7000 labelled instances
	52181.39453125
	52242.453125
	Test MAPE = 5934615084662784.0