# Libraries

In [1]:
import numpy as np
import pandas as pd

from ucimlrepo import fetch_ucirepo
from sklearn.datasets import fetch_california_housing

from tensorflow.keras import layers, models
import tensorflow as tf

from sklearn.metrics import root_mean_squared_error, mean_absolute_error, mean_absolute_percentage_error, r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# own functions
from active_regression import passive_sampling, uncertainty_sampling_reg, label_data, active_learning_reg, sasla_reg
from active_regression import tune_params, retrieve_params, cv_regression, create_regmodel

from time import time

# Models

## California Housing

In [2]:
california = fetch_california_housing(as_frame=True)
california_df = california.frame
california_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [3]:
X = california_df.drop(columns=['MedHouseVal']).to_numpy()
y = california_df.loc[:, 'MedHouseVal'].to_numpy()

X_pool, X_test, y_pool, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=51
)

In [5]:
acts = ['relu', 'leaky_relu', 'elu']
for activation in acts:
    base_params = tune_params(X_pool, y_pool,
                              loss='mse',
                              out_units=1, out_act='linear',
                              k=5, activation=activation,
                              random_state=42,
                              n_trials=80,
                              export=True, file = f'params/california/{activation}.json'
    )

[I 2026-09-25 07:37:05,168] A new study created in memory with name: no-name-595df385-cb03-48b6-b8c7-d5e3118a9b9b

WARNING:tensorflow:From C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

[I 2026-09-25 07:41:21,891] Trial 0 finished with value: 0.3916826523948034 and parameters: {'hidden_layer': 21, 'learning_rate': 0.003625073723242179, 'momentum': 0.367834230369271, 'weight_decay': 2.5430405201770885e-05}. Best is trial 0 with value: 0.3916826523948034.
[I 2026-09-25 07:41:28,609] Trial 1 finished with value: inf and parameters: {'hidden_layer': 55, 'learning_rate': 0.0044267163631692774, 'momentum': 0.7719791575309446, 'weight_decay': 4.871099891275516e-05}. Best is trial 0 with value: 0.3916826523948034.
[I 2026-09-25 07:47:38,742] Trial 2 finished with value: 0.5027052022348896 and parameters: {'hidden_layer': 30, 'learning_rate': 0.00030453461462901546, 'momentum': 0.003086914225791774, 'weight_decay': 2.7796470503845208e-05}. Best is trial 0 with value: 0.3916826523948034.
[I 2026-09-25 07:51:41,132] Trial 3 finished with value: 0.35935990197524603 and parameters: {'hidden_layer': 80, 'learning_rate': 0.006751255703576771, 'momentum': 0.16903264886659605, 'weight_decay': 0.0003044917422042604}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 07:58:33,840] Trial 4 finished with value: 0.47797452782118893 and parameters: {'hidden_layer': 36, 'learning_rate': 0.0001231110363448914, 'momentum': 0.7215392449250452, 'weight_decay': 1.5735252617682372e-05}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 07:59:55,419] Trial 5 pruned.
[I 2026-09-25 08:01:10,017] Trial 6 pruned.
[I 2026-09-25 08:04:37,891] Trial 7 finished with value: 0.3615210895310855 and parameters: {'hidden_layer': 72, 'learning_rate': 0.004133888435140076, 'momentum': 0.5141885184994636, 'weight_decay': 9.990706223896004e-05}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:05:50,538] Trial 8 pruned.
[I 2026-09-25 08:09:29,427] Trial 9 finished with value: 0.37098183687488506 and parameters: {'hidden_layer': 39, 'learning_rate': 0.000897925489144942, 'momentum': 0.8702193717746981, 'weight_decay': 1.1784209912208708e-05}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:11:10,097] Trial 10 finished with value: inf and parameters: {'hidden_layer': 86, 'learning_rate': 0.008421044735419327, 'momentum': 0.2293431470089783, 'weight_decay': 0.0035635396046568586}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:11:55,343] Trial 11 pruned.
[I 2026-09-25 08:12:01,878] Trial 12 finished with value: inf and parameters: {'hidden_layer': 76, 'learning_rate': 0.00788757216072886, 'momentum': 0.33560539948576973, 'weight_decay': 1.378240451888127e-06}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:12:06,850] Trial 13 finished with value: inf and parameters: {'hidden_layer': 98, 'learning_rate': 0.0014967976809352346, 'momentum': 0.989892017034552, 'weight_decay': 0.000574289347691211}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:17:53,207] Trial 14 finished with value: 0.3720132288913812 and parameters: {'hidden_layer': 60, 'learning_rate': 0.004444256889746512, 'momentum': 0.0020945332569987096, 'weight_decay': 0.0007183839372701406}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:19:00,360] Trial 15 pruned.
[I 2026-09-25 08:20:13,429] Trial 16 pruned.
[I 2026-09-25 08:21:08,194] Trial 17 finished with value: inf and parameters: {'hidden_layer': 99, 'learning_rate': 0.009249039177796847, 'momentum': 0.1654916655980712, 'weight_decay': 0.0002431953131887193}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:21:26,885] Trial 18 pruned.
[I 2026-09-25 08:27:02,776] Trial 19 finished with value: 0.37022260382048483 and parameters: {'hidden_layer': 51, 'learning_rate': 0.0028073336186535246, 'momentum': 0.4528908894882496, 'weight_decay': 0.0017623577083386763}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:27:27,770] Trial 20 pruned.
[I 2026-09-25 08:28:41,357] Trial 21 pruned.
[I 2026-09-25 08:29:33,777] Trial 22 pruned.
[I 2026-09-25 08:30:49,651] Trial 23 pruned.
[I 2026-09-25 08:32:03,593] Trial 24 pruned.
[I 2026-09-25 08:33:18,215] Trial 25 pruned.
[I 2026-09-25 08:33:52,572] Trial 26 pruned.
[I 2026-09-25 08:33:59,440] Trial 27 finished with value: inf and parameters: {'hidden_layer': 92, 'learning_rate': 0.0037217652460164417, 'momentum': 0.8114886005634561, 'weight_decay': 0.00016266779351491281}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:35:14,365] Trial 28 pruned.
[I 2026-09-25 08:36:27,851] Trial 29 pruned.
[I 2026-09-25 08:39:14,051] Trial 30 finished with value: inf and parameters: {'hidden_layer': 64, 'learning_rate': 0.006040182403191989, 'momentum': 0.405551593303278, 'weight_decay': 0.0005126679654698297}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:39:21,434] Trial 31 finished with value: inf and parameters: {'hidden_layer': 43, 'learning_rate': 0.0008240422821081872, 'momentum': 0.9752529935145924, 'weight_decay': 7.772399028749634e-06}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:43:25,787] Trial 32 finished with value: 0.3774068834831906 and parameters: {'hidden_layer': 33, 'learning_rate': 0.0006922138929961935, 'momentum': 0.8930491740087961, 'weight_decay': 1.2296467333672927e-05}. Best is trial 3 with value: 0.35935990197524603.
[I 2026-09-25 08:44:45,746] Trial 33 pruned.
[I 2026-09-25 08:45:15,269] Trial 34 pruned.
[I 2026-09-25 08:45:56,424] Trial 35 pruned.
[I 2026-09-25 08:48:51,636] Trial 36 finished with value: 0.3590877110713562 and parameters: {'hidden_layer': 74, 'learning_rate': 0.0018151866586540834, 'momentum': 0.7973662107501709, 'weight_decay': 1.7969467048451465e-05}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 08:50:07,039] Trial 37 pruned.
[I 2026-09-25 08:53:27,455] Trial 38 finished with value: inf and parameters: {'hidden_layer': 109, 'learning_rate': 0.0034471624984945292, 'momentum': 0.48491014291623796, 'weight_decay': 0.00013229225557744728}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 08:53:34,101] Trial 39 finished with value: inf and parameters: {'hidden_layer': 91, 'learning_rate': 0.004785291707316061, 'momentum': 0.7448247314116762, 'weight_decay': 8.571076166101852e-05}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 08:53:40,712] Trial 40 finished with value: inf and parameters: {'hidden_layer': 64, 'learning_rate': 0.007151782158721232, 'momentum': 0.8330715535265405, 'weight_decay': 5.2722120475392176e-05}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 08:54:20,413] Trial 41 pruned.
[I 2026-09-25 08:55:33,105] Trial 42 pruned.
[I 2026-09-25 08:56:02,638] Trial 43 pruned.
[I 2026-09-25 08:56:09,190] Trial 44 finished with value: inf and parameters: {'hidden_layer': 58, 'learning_rate': 0.0018123760735909017, 'momentum': 0.9162600001162704, 'weight_decay': 2.3696065575836914e-05}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 08:56:15,765] Trial 45 finished with value: inf and parameters: {'hidden_layer': 40, 'learning_rate': 0.00976003674787147, 'momentum': 0.6029941209700773, 'weight_decay': 8.052763066316213e-06}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 08:57:26,097] Trial 46 pruned.
[I 2026-09-25 08:58:04,890] Trial 47 pruned.
[I 2026-09-25 08:58:28,806] Trial 48 pruned.
[I 2026-09-25 08:59:27,526] Trial 49 pruned.
[I 2026-09-25 09:00:05,623] Trial 50 pruned.
[I 2026-09-25 09:01:18,884] Trial 51 pruned.
[I 2026-09-25 09:02:31,932] Trial 52 pruned.
[I 2026-09-25 09:03:38,940] Trial 53 pruned.
[I 2026-09-25 09:04:52,389] Trial 54 pruned.
[I 2026-09-25 09:09:21,566] Trial 55 finished with value: 0.36950022871848837 and parameters: {'hidden_layer': 67, 'learning_rate': 0.005186448882729236, 'momentum': 0.06767825714814266, 'weight_decay': 0.00023356990188993325}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 09:11:42,916] Trial 56 finished with value: inf and parameters: {'hidden_layer': 65, 'learning_rate': 0.008026719266815288, 'momentum': 0.28071052662188856, 'weight_decay': 0.0002493139056812603}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 09:12:51,876] Trial 57 pruned.
[I 2026-09-25 09:12:58,670] Trial 58 finished with value: inf and parameters: {'hidden_layer': 96, 'learning_rate': 0.006131762048176275, 'momentum': 0.5589685935583462, 'weight_decay': 9.515295681817726e-05}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 09:14:01,448] Trial 59 pruned.
[I 2026-09-25 09:15:14,498] Trial 60 pruned.
[I 2026-09-25 09:16:28,265] Trial 61 pruned.
[I 2026-09-25 09:17:43,875] Trial 62 pruned.
[I 2026-09-25 09:18:10,841] Trial 63 pruned.
[I 2026-09-25 09:21:59,763] Trial 64 finished with value: 0.36323093248267446 and parameters: {'hidden_layer': 67, 'learning_rate': 0.006934874668806461, 'momentum': 0.030607902666808018, 'weight_decay': 0.00036262667751965833}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 09:22:54,274] Trial 65 pruned.
[I 2026-09-25 09:24:08,122] Trial 66 pruned.
[I 2026-09-25 09:24:14,961] Trial 67 finished with value: inf and parameters: {'hidden_layer': 67, 'learning_rate': 0.008663404224134886, 'momentum': 0.20616963586066686, 'weight_decay': 3.337422027803434e-05}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 09:27:00,273] Trial 68 finished with value: 0.36230527133664625 and parameters: {'hidden_layer': 48, 'learning_rate': 0.0004862544006524706, 'momentum': 0.9677372011838943, 'weight_decay': 0.008045151313705694}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 09:28:13,306] Trial 69 pruned.
[I 2026-09-25 09:28:21,846] Trial 70 finished with value: inf and parameters: {'hidden_layer': 62, 'learning_rate': 0.0037464344626873575, 'momentum': 0.9598605439953047, 'weight_decay': 0.004835021904821295}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 09:29:30,200] Trial 71 pruned.
[I 2026-09-25 09:30:27,046] Trial 72 pruned.
[I 2026-09-25 09:31:41,430] Trial 73 pruned.
[I 2026-09-25 09:32:30,904] Trial 74 pruned.
[I 2026-09-25 09:33:14,658] Trial 75 pruned.
[I 2026-09-25 09:34:28,783] Trial 76 pruned.
[I 2026-09-25 09:34:35,907] Trial 77 finished with value: inf and parameters: {'hidden_layer': 39, 'learning_rate': 0.0019222484165270868, 'momentum': 0.9823355990001733, 'weight_decay': 5.7182562045791815e-06}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 09:37:05,433] Trial 78 finished with value: inf and parameters: {'hidden_layer': 77, 'learning_rate': 0.006816852627542694, 'momentum': 0.5103375728963397, 'weight_decay': 0.000465591938405848}. Best is trial 36 with value: 0.3590877110713562.
[I 2026-09-25 09:38:21,898] Trial 79 pruned.
[I 2026-09-25 09:38:21,903] A new study created in memory with name: no-name-b46efda9-933e-4e3c-ad70-7434da3a0381

{'hidden_layer': 74, 'learning_rate': 0.0018151866586540834, 'momentum': 0.7973662107501709, 'weight_decay': 1.7969467048451465e-05}
0.3590877110713562

[I 2026-09-25 09:44:25,376] Trial 0 finished with value: 0.4570477371068279 and parameters: {'hidden_layer': 42, 'learning_rate': 0.00028896699348474427, 'momentum': 0.5612715360675683, 'weight_decay': 0.0014350985614902906, 'leaky_relu_alpha': 0.009315682944208856}. Best is trial 0 with value: 0.4570477371068279.
[I 2026-09-25 09:48:17,114] Trial 1 finished with value: inf and parameters: {'hidden_layer': 127, 'learning_rate': 0.001363307018331313, 'momentum': 0.7636265700459369, 'weight_decay': 0.0027334731715486305, 'leaky_relu_alpha': 0.11080990486570994}. Best is trial 0 with value: 0.4570477371068279.
[I 2026-09-25 09:54:29,270] Trial 2 finished with value: 0.3639014486574298 and parameters: {'hidden_layer': 123, 'learning_rate': 0.0031019592521037984, 'momentum': 0.13211481220152355, 'weight_decay': 1.2633197640445262e-05, 'leaky_relu_alpha': 0.0040559735830498255}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 10:00:08,080] Trial 3 finished with value: 0.4500262387867406 and parameters: {'hidden_layer': 70, 'learning_rate': 0.0011129620720062986, 'momentum': 0.14876038961331017, 'weight_decay': 3.2544197312777775e-06, 'leaky_relu_alpha': 0.16274056343523874}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 10:04:44,842] Trial 4 finished with value: 0.6560605745740655 and parameters: {'hidden_layer': 29, 'learning_rate': 0.006066933989484268, 'momentum': 0.1640488479537832, 'weight_decay': 1.4284756826481268e-06, 'leaky_relu_alpha': 0.030922125907271492}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 10:07:41,629] Trial 5 pruned.
[I 2026-09-25 10:09:14,269] Trial 6 pruned.
[I 2026-09-25 10:09:22,776] Trial 7 finished with value: inf and parameters: {'hidden_layer': 59, 'learning_rate': 0.004722937988824842, 'momentum': 0.727806824114345, 'weight_decay': 7.164921036231217e-05, 'leaky_relu_alpha': 0.06758521103500197}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 10:10:55,274] Trial 8 pruned.
[I 2026-09-25 10:12:28,194] Trial 9 pruned.
[I 2026-09-25 10:19:36,303] Trial 10 finished with value: 0.3743084901022438 and parameters: {'hidden_layer': 126, 'learning_rate': 0.003085998449735609, 'momentum': 0.022570525223516547, 'weight_decay': 1.2925127946813972e-05, 'leaky_relu_alpha': 0.006286072161644384}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 10:26:17,273] Trial 11 finished with value: 0.37801537767005017 and parameters: {'hidden_layer': 125, 'learning_rate': 0.0030603039124089708, 'momentum': 0.013762780956428826, 'weight_decay': 1.6950764276881127e-05, 'leaky_relu_alpha': 0.005074886518117673}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 10:26:26,014] Trial 12 finished with value: inf and parameters: {'hidden_layer': 104, 'learning_rate': 0.009552291926402234, 'momentum': 0.9760330522914432, 'weight_decay': 1.4164862913956705e-05, 'leaky_relu_alpha': 0.0044256570665292564}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 10:34:01,747] Trial 13 finished with value: 0.3737985634859795 and parameters: {'hidden_layer': 113, 'learning_rate': 0.003024024863355713, 'momentum': 0.028617967748393675, 'weight_decay': 0.0002992875093159527, 'leaky_relu_alpha': 0.007561773118364016}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 10:41:11,436] Trial 14 finished with value: 0.3726778163451504 and parameters: {'hidden_layer': 85, 'learning_rate': 0.0024183170560072896, 'momentum': 0.30588378425287344, 'weight_decay': 0.0005126489487494641, 'leaky_relu_alpha': 0.002994900173532033}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 10:42:35,437] Trial 15 pruned.
[I 2026-09-25 10:44:01,280] Trial 16 pruned.
[I 2026-09-25 10:45:33,790] Trial 17 pruned.
[I 2026-09-25 10:47:03,743] Trial 18 pruned.
[I 2026-09-25 10:54:11,727] Trial 19 finished with value: 0.376818358315537 and parameters: {'hidden_layer': 114, 'learning_rate': 0.0018530791929472466, 'momentum': 0.4098265990274519, 'weight_decay': 4.300766686494685e-06, 'leaky_relu_alpha': 0.0022191534735745344}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 10:57:37,739] Trial 20 finished with value: inf and parameters: {'hidden_layer': 72, 'learning_rate': 0.005939607572922575, 'momentum': 0.2226004096081326, 'weight_decay': 1.100513793741947e-06, 'leaky_relu_alpha': 0.003328459976389941}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 11:03:38,235] Trial 21 finished with value: 0.3722761224252094 and parameters: {'hidden_layer': 113, 'learning_rate': 0.0031997254958048924, 'momentum': 0.08504387500279587, 'weight_decay': 0.0002036946692226469, 'leaky_relu_alpha': 0.00869359025197983}. Best is trial 2 with value: 0.3639014486574298.
[I 2026-09-25 11:09:54,825] Trial 22 finished with value: 0.3573790454282096 and parameters: {'hidden_layer': 112, 'learning_rate': 0.004186255774632859, 'momentum': 0.07428273924667625, 'weight_decay': 0.0007528503127045853, 'leaky_relu_alpha': 0.014692463332986903}. Best is trial 22 with value: 0.3573790454282096.
[I 2026-09-25 11:10:16,957] Trial 23 pruned.
[I 2026-09-25 11:16:02,763] Trial 24 finished with value: 0.3618034142081308 and parameters: {'hidden_layer': 117, 'learning_rate': 0.0041680438980751, 'momentum': 0.10243046283694787, 'weight_decay': 2.8893239884764883e-05, 'leaky_relu_alpha': 0.012102686028024678}. Best is trial 22 with value: 0.3573790454282096.
[I 2026-09-25 11:21:10,752] Trial 25 finished with value: 0.3592460827407532 and parameters: {'hidden_layer': 93, 'learning_rate': 0.004750099148554186, 'momentum': 0.11508874528699288, 'weight_decay': 3.134535823023502e-05, 'leaky_relu_alpha': 0.015194884245874323}. Best is trial 22 with value: 0.3573790454282096.
[I 2026-09-25 11:24:25,072] Trial 26 finished with value: inf and parameters: {'hidden_layer': 95, 'learning_rate': 0.0047518608975562525, 'momentum': 0.22843383246838367, 'weight_decay': 2.8285696552659587e-05, 'leaky_relu_alpha': 0.013373185689856185}. Best is trial 22 with value: 0.3573790454282096.
[I 2026-09-25 11:27:42,109] Trial 27 finished with value: inf and parameters: {'hidden_layer': 105, 'learning_rate': 0.006386121868960171, 'momentum': 0.07908973609760496, 'weight_decay': 0.0008774752514145896, 'leaky_relu_alpha': 0.03550710425833637}. Best is trial 22 with value: 0.3573790454282096.
[I 2026-09-25 11:28:55,887] Trial 28 pruned.
[I 2026-09-25 11:30:10,779] Trial 29 pruned.
[I 2026-09-25 11:31:25,610] Trial 30 pruned.
[I 2026-09-25 11:37:19,138] Trial 31 finished with value: 0.3577676287294253 and parameters: {'hidden_layer': 122, 'learning_rate': 0.004450876149795951, 'momentum': 0.10425539481277767, 'weight_decay': 3.0104232686380684e-05, 'leaky_relu_alpha': 0.010353525469877303}. Best is trial 22 with value: 0.3573790454282096.
[I 2026-09-25 11:43:15,082] Trial 32 finished with value: 0.354270402080534 and parameters: {'hidden_layer': 120, 'learning_rate': 0.004400260691686097, 'momentum': 0.10294424836361865, 'weight_decay': 8.504623283074862e-05, 'leaky_relu_alpha': 0.01109933865886212}. Best is trial 32 with value: 0.354270402080534.
[I 2026-09-25 11:43:23,197] Trial 33 finished with value: inf and parameters: {'hidden_layer': 128, 'learning_rate': 0.007499435499643236, 'momentum': 0.18935037803533783, 'weight_decay': 8.485629658018623e-05, 'leaky_relu_alpha': 0.009451499569162303}. Best is trial 32 with value: 0.354270402080534.
[I 2026-09-25 11:44:38,195] Trial 34 pruned.
[I 2026-09-25 11:46:10,123] Trial 35 finished with value: inf and parameters: {'hidden_layer': 110, 'learning_rate': 0.007374492509943337, 'momentum': 0.14093924605778088, 'weight_decay': 3.0793505141484836e-05, 'leaky_relu_alpha': 0.006203040515955463}. Best is trial 32 with value: 0.354270402080534.
[I 2026-09-25 11:47:33,762] Trial 36 finished with value: inf and parameters: {'hidden_layer': 91, 'learning_rate': 0.0023527007242166815, 'momentum': 0.7059462534275397, 'weight_decay': 7.470240561322057e-05, 'leaky_relu_alpha': 0.015308193045368797}. Best is trial 32 with value: 0.354270402080534.
[I 2026-09-25 11:48:50,681] Trial 37 pruned.
[I 2026-09-25 11:50:03,353] Trial 38 finished with value: inf and parameters: {'hidden_layer': 102, 'learning_rate': 0.005444810019088378, 'momentum': 0.17188085777821366, 'weight_decay': 8.501538328567935e-06, 'leaky_relu_alpha': 0.030970872375432692}. Best is trial 32 with value: 0.354270402080534.
[I 2026-09-25 11:50:10,402] Trial 39 finished with value: inf and parameters: {'hidden_layer': 75, 'learning_rate': 0.00376746445880701, 'momentum': 0.9857357753856419, 'weight_decay': 2.255554227581373e-06, 'leaky_relu_alpha': 0.07356742712863355}. Best is trial 32 with value: 0.354270402080534.
[I 2026-09-25 11:51:25,507] Trial 40 pruned.
[I 2026-09-25 11:57:17,907] Trial 41 finished with value: 0.35374399768039405 and parameters: {'hidden_layer': 118, 'learning_rate': 0.0050284500691448065, 'momentum': 0.1195419232485179, 'weight_decay': 4.850866476682255e-05, 'leaky_relu_alpha': 0.019506072456604167}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:00:13,206] Trial 42 finished with value: 0.3626971110885347 and parameters: {'hidden_layer': 120, 'learning_rate': 0.007555523844093053, 'momentum': 0.1144694613412357, 'weight_decay': 4.562445027924939e-05, 'leaky_relu_alpha': 0.01787539747894487}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:06:05,213] Trial 43 finished with value: 0.35506512130421525 and parameters: {'hidden_layer': 128, 'learning_rate': 0.004953671410600529, 'momentum': 0.1817860365291694, 'weight_decay': 5.9621282704095475e-05, 'leaky_relu_alpha': 0.021368415051506877}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:07:18,398] Trial 44 pruned.
[I 2026-09-25 12:13:09,361] Trial 45 finished with value: 0.3602908289237614 and parameters: {'hidden_layer': 107, 'learning_rate': 0.003768573849278384, 'momentum': 0.1893585467682783, 'weight_decay': 5.9457915345280275e-05, 'leaky_relu_alpha': 0.007067461729383667}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:13:59,029] Trial 46 pruned.
[I 2026-09-25 12:14:48,960] Trial 47 finished with value: inf and parameters: {'hidden_layer': 118, 'learning_rate': 0.008989113044302149, 'momentum': 0.16300258212430832, 'weight_decay': 8.771326104232422e-06, 'leaky_relu_alpha': 0.01039618594588215}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:14:55,998] Trial 48 finished with value: inf and parameters: {'hidden_layer': 100, 'learning_rate': 0.0062687445685001624, 'momentum': 0.6378726016553153, 'weight_decay': 0.0006268667578457255, 'leaky_relu_alpha': 0.0052517187526441005}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:16:10,210] Trial 49 pruned.
[I 2026-09-25 12:17:10,374] Trial 50 pruned.
[I 2026-09-25 12:23:00,768] Trial 51 finished with value: 0.3601886625034824 and parameters: {'hidden_layer': 108, 'learning_rate': 0.004449380600914902, 'momentum': 0.11921282616177196, 'weight_decay': 4.562671969741101e-05, 'leaky_relu_alpha': 0.014526210232399538}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:23:07,995] Trial 52 finished with value: inf and parameters: {'hidden_layer': 115, 'learning_rate': 0.005337507135746012, 'momentum': 0.911121211854161, 'weight_decay': 6.787244234134047e-05, 'leaky_relu_alpha': 0.007970415991692527}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:23:37,904] Trial 53 pruned.
[I 2026-09-25 12:24:54,498] Trial 54 pruned.
[I 2026-09-25 12:26:09,052] Trial 55 pruned.
[I 2026-09-25 12:31:26,961] Trial 56 finished with value: 0.3639958627557058 and parameters: {'hidden_layer': 118, 'learning_rate': 0.004859893257961968, 'momentum': 0.03744664373828034, 'weight_decay': 1.3349613026230329e-05, 'leaky_relu_alpha': 0.025778694069503026}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:32:34,376] Trial 57 pruned.
[I 2026-09-25 12:33:36,168] Trial 58 pruned.
[I 2026-09-25 12:33:44,192] Trial 59 finished with value: inf and parameters: {'hidden_layer': 114, 'learning_rate': 0.008480938456219174, 'momentum': 0.04128042937413949, 'weight_decay': 0.00015230086817114, 'leaky_relu_alpha': 0.01299972439400726}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:35:07,182] Trial 60 pruned.
[I 2026-09-25 12:41:51,230] Trial 61 finished with value: 0.35914707392023504 and parameters: {'hidden_layer': 108, 'learning_rate': 0.004158242903116138, 'momentum': 0.09804308241031977, 'weight_decay': 4.1853010550892897e-05, 'leaky_relu_alpha': 0.014067271821728549}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:47:42,102] Trial 62 finished with value: 0.3600285433408562 and parameters: {'hidden_layer': 90, 'learning_rate': 0.004261661244013881, 'momentum': 0.20660153121458322, 'weight_decay': 8.932375628324713e-05, 'leaky_relu_alpha': 0.019818888730471867}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:48:27,140] Trial 63 pruned.
[I 2026-09-25 12:49:46,942] Trial 64 pruned.
[I 2026-09-25 12:51:16,642] Trial 65 pruned.
[I 2026-09-25 12:52:16,785] Trial 66 pruned.
[I 2026-09-25 12:57:12,240] Trial 67 finished with value: 0.3560260847217189 and parameters: {'hidden_layer': 120, 'learning_rate': 0.005048100634340998, 'momentum': 0.1385060531231384, 'weight_decay': 2.5054691687389152e-05, 'leaky_relu_alpha': 0.019978702116714847}. Best is trial 41 with value: 0.35374399768039405.
[I 2026-09-25 12:58:19,685] Trial 68 pruned.
[I 2026-09-25 12:58:53,446] Trial 69 pruned.
[I 2026-09-25 13:05:02,838] Trial 70 finished with value: 0.35165084131526525 and parameters: {'hidden_layer': 118, 'learning_rate': 0.00555669549526032, 'momentum': 0.03357246500483846, 'weight_decay': 5.7525084300726465e-06, 'leaky_relu_alpha': 0.0043701136142289005}. Best is trial 70 with value: 0.35165084131526525.
[I 2026-09-25 13:09:21,229] Trial 71 finished with value: inf and parameters: {'hidden_layer': 118, 'learning_rate': 0.005907208393499563, 'momentum': 0.03374486820277567, 'weight_decay': 2.0089244407501634e-06, 'leaky_relu_alpha': 0.02123638904965488}. Best is trial 70 with value: 0.35165084131526525.
[I 2026-09-25 13:15:22,060] Trial 72 finished with value: 0.35665213495633025 and parameters: {'hidden_layer': 112, 'learning_rate': 0.005355730175489363, 'momentum': 0.005256875313842273, 'weight_decay': 6.2255306323930556e-06, 'leaky_relu_alpha': 0.0016915642457500273}. Best is trial 70 with value: 0.35165084131526525.
[I 2026-09-25 13:18:19,276] Trial 73 finished with value: inf and parameters: {'hidden_layer': 112, 'learning_rate': 0.008012494769850984, 'momentum': 0.005220184599177617, 'weight_decay': 5.006497910651872e-06, 'leaky_relu_alpha': 0.0016461168827407455}. Best is trial 70 with value: 0.35165084131526525.
[I 2026-09-25 13:18:38,699] Trial 74 pruned.
[I 2026-09-25 13:24:42,881] Trial 75 finished with value: 0.35092531902181173 and parameters: {'hidden_layer': 120, 'learning_rate': 0.005317746800160751, 'momentum': 0.20894003959285906, 'weight_decay': 2.9130934686171106e-06, 'leaky_relu_alpha': 0.0029763805914404997}. Best is trial 75 with value: 0.35092531902181173.
[I 2026-09-25 13:29:51,215] Trial 76 finished with value: inf and parameters: {'hidden_layer': 116, 'learning_rate': 0.005431080291943264, 'momentum': 0.20377019029930843, 'weight_decay': 3.169131530434142e-06, 'leaky_relu_alpha': 0.0016283490486115114}. Best is trial 75 with value: 0.35092531902181173.
[I 2026-09-25 13:31:22,014] Trial 77 pruned.
[I 2026-09-25 13:32:22,322] Trial 78 pruned.
[I 2026-09-25 13:33:49,271] Trial 79 pruned.
[I 2026-09-25 13:33:49,278] A new study created in memory with name: no-name-fd22ff0d-8fed-45b8-9c5e-7d4578014ad0

{'hidden_layer': 120, 'learning_rate': 0.005317746800160751, 'momentum': 0.20894003959285906, 'weight_decay': 2.9130934686171106e-06, 'leaky_relu_alpha': 0.0029763805914404997}
0.35092531902181173

[I 2026-09-25 13:39:50,793] Trial 0 finished with value: 0.4693701107610641 and parameters: {'hidden_layer': 47, 'learning_rate': 0.001734262365906389, 'momentum': 0.5047107896315642, 'weight_decay': 0.002032046171562881, 'elu_alpha': 1.3388134873784838}. Best is trial 0 with value: 0.4693701107610641.
[I 2026-09-25 13:47:39,141] Trial 1 finished with value: 0.453194784500096 and parameters: {'hidden_layer': 28, 'learning_rate': 0.0006927222559905066, 'momentum': 0.31742486722592045, 'weight_decay': 2.7946446306176854e-06, 'elu_alpha': 0.4791689934200174}. Best is trial 1 with value: 0.453194784500096.
[I 2026-09-25 13:53:07,686] Trial 2 finished with value: 0.47008506173751313 and parameters: {'hidden_layer': 96, 'learning_rate': 0.0027896345072476493, 'momentum': 0.09468942227907774, 'weight_decay': 3.285190188649579e-05, 'elu_alpha': 1.4476399735511372}. Best is trial 1 with value: 0.453194784500096.
[I 2026-09-25 13:53:16,936] Trial 3 finished with value: inf and parameters: {'hidden_layer': 88, 'learning_rate': 0.00939518774923352, 'momentum': 0.6990251347394527, 'weight_decay': 2.1122242730771064e-06, 'elu_alpha': 1.5700439488319833}. Best is trial 1 with value: 0.453194784500096.
[I 2026-09-25 14:00:29,708] Trial 4 finished with value: 0.4368676634722723 and parameters: {'hidden_layer': 35, 'learning_rate': 0.0006361486136385058, 'momentum': 0.7176168273901109, 'weight_decay': 0.002926064518252346, 'elu_alpha': 0.6811719313392224}. Best is trial 4 with value: 0.4368676634722723.
[I 2026-09-25 14:05:32,785] Trial 5 finished with value: 0.47213580341778083 and parameters: {'hidden_layer': 98, 'learning_rate': 0.0034585489883926872, 'momentum': 0.06780163954070004, 'weight_decay': 1.1416987131149908e-05, 'elu_alpha': 1.7108203387464134}. Best is trial 4 with value: 0.4368676634722723.
[I 2026-09-25 14:06:35,792] Trial 6 pruned.
[I 2026-09-25 14:08:13,920] Trial 7 pruned.
[I 2026-09-25 14:09:43,475] Trial 8 finished with value: inf and parameters: {'hidden_layer': 81, 'learning_rate': 0.0034881941857543763, 'momentum': 0.7675003386769005, 'weight_decay': 0.0012089096600519933, 'elu_alpha': 1.5850253611143994}. Best is trial 4 with value: 0.4368676634722723.
[I 2026-09-25 14:10:22,586] Trial 9 pruned.
[I 2026-09-25 14:12:02,286] Trial 10 pruned.
[I 2026-09-25 14:13:51,413] Trial 11 pruned.
[I 2026-09-25 14:15:27,778] Trial 12 pruned.
[I 2026-09-25 14:22:43,936] Trial 13 finished with value: 0.4379438182435515 and parameters: {'hidden_layer': 22, 'learning_rate': 0.00021373764491565455, 'momentum': 0.8853152789951362, 'weight_decay': 5.281475770002545e-05, 'elu_alpha': 0.5072830658433617}. Best is trial 4 with value: 0.4368676634722723.
[I 2026-09-25 14:23:45,254] Trial 14 pruned.
[I 2026-09-25 14:31:07,815] Trial 15 finished with value: 0.4339406241555291 and parameters: {'hidden_layer': 63, 'learning_rate': 0.0002590776817081807, 'momentum': 0.7810381721664956, 'weight_decay': 0.0003859201962371264, 'elu_alpha': 0.31608158453909535}. Best is trial 15 with value: 0.4339406241555291.
[I 2026-09-25 14:38:41,516] Trial 16 finished with value: 0.42764372641071374 and parameters: {'hidden_layer': 63, 'learning_rate': 0.00026975974471759716, 'momentum': 0.7823387859680478, 'weight_decay': 0.005963963699429705, 'elu_alpha': 0.13052916807225}. Best is trial 16 with value: 0.42764372641071374.
[I 2026-09-25 14:46:52,939] Trial 17 finished with value: 0.4213625852092974 and parameters: {'hidden_layer': 64, 'learning_rate': 0.00028266165003893893, 'momentum': 0.8088832349572583, 'weight_decay': 0.009820651329033286, 'elu_alpha': 0.15896357335823028}. Best is trial 17 with value: 0.4213625852092974.
[I 2026-09-25 14:48:37,129] Trial 18 pruned.
[I 2026-09-25 14:48:54,335] Trial 19 pruned.
[I 2026-09-25 14:55:41,411] Trial 20 finished with value: 0.4159957136435685 and parameters: {'hidden_layer': 58, 'learning_rate': 0.000932199127308832, 'momentum': 0.651508918151015, 'weight_decay': 0.0004819590641845639, 'elu_alpha': 0.3369300159055555}. Best is trial 20 with value: 0.4159957136435685.
[I 2026-09-25 15:02:33,429] Trial 21 finished with value: 0.401390234951454 and parameters: {'hidden_layer': 57, 'learning_rate': 0.0013338797678617651, 'momentum': 0.6526683443911279, 'weight_decay': 0.0009450448309866069, 'elu_alpha': 0.33809445473602906}. Best is trial 21 with value: 0.401390234951454.
[I 2026-09-25 15:09:39,979] Trial 22 finished with value: 0.40349498772888276 and parameters: {'hidden_layer': 55, 'learning_rate': 0.0011952612145271658, 'momentum': 0.6586081408971957, 'weight_decay': 0.0005915427477383939, 'elu_alpha': 0.3389010754557421}. Best is trial 21 with value: 0.401390234951454.
[I 2026-09-25 15:15:26,328] Trial 23 finished with value: 0.40870843753391795 and parameters: {'hidden_layer': 54, 'learning_rate': 0.0014656146824667047, 'momentum': 0.6388919256666638, 'weight_decay': 0.0006038010165479209, 'elu_alpha': 0.40670489215856903}. Best is trial 21 with value: 0.401390234951454.
[I 2026-09-25 15:16:59,278] Trial 24 pruned.
[I 2026-09-25 15:17:12,927] Trial 25 finished with value: inf and parameters: {'hidden_layer': 75, 'learning_rate': 0.005303303815115017, 'momentum': 0.6051083688020749, 'weight_decay': 0.0002200055699951966, 'elu_alpha': 0.45099597540032754}. Best is trial 21 with value: 0.401390234951454.
[I 2026-09-25 15:25:05,426] Trial 26 finished with value: 0.3936836348219737 and parameters: {'hidden_layer': 56, 'learning_rate': 0.0012371768344276366, 'momentum': 0.6815514284226698, 'weight_decay': 0.0014962868535244227, 'elu_alpha': 0.3214009401112775}. Best is trial 26 with value: 0.3936836348219737.
[I 2026-09-25 15:26:46,059] Trial 27 pruned.
[I 2026-09-25 15:34:16,914] Trial 28 finished with value: 0.40999105419128556 and parameters: {'hidden_layer': 35, 'learning_rate': 0.0008787148812235141, 'momentum': 0.711246898212765, 'weight_decay': 0.003551073193492227, 'elu_alpha': 0.2743193775637446}. Best is trial 26 with value: 0.3936836348219737.
[I 2026-09-25 15:40:25,501] Trial 29 finished with value: 0.42144820918698833 and parameters: {'hidden_layer': 46, 'learning_rate': 0.001925188282855361, 'momentum': 0.5606659530315385, 'weight_decay': 0.002135372742773731, 'elu_alpha': 0.5609144934177376}. Best is trial 26 with value: 0.3936836348219737.
[I 2026-09-25 15:42:04,403] Trial 30 pruned.
[I 2026-09-25 15:48:17,234] Trial 31 finished with value: 0.3995217397460193 and parameters: {'hidden_layer': 54, 'learning_rate': 0.0016188663961061304, 'momentum': 0.657583008404362, 'weight_decay': 0.0003338331614549638, 'elu_alpha': 0.3797135982079457}. Best is trial 26 with value: 0.3936836348219737.
[I 2026-09-25 15:54:17,879] Trial 32 finished with value: 0.3854946511091066 and parameters: {'hidden_layer': 49, 'learning_rate': 0.0016761441208528918, 'momentum': 0.6856528993810356, 'weight_decay': 0.0003435745090402842, 'elu_alpha': 0.24576054131570765}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:00:43,670] Trial 33 finished with value: 0.3987378335295845 and parameters: {'hidden_layer': 36, 'learning_rate': 0.0017490199907639246, 'momentum': 0.554760871276019, 'weight_decay': 0.00027613063645845454, 'elu_alpha': 0.2669723429687111}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:07:47,521] Trial 34 finished with value: 0.39582950600406713 and parameters: {'hidden_layer': 37, 'learning_rate': 0.001751799973127657, 'momentum': 0.5349099502190827, 'weight_decay': 0.00010708969719544198, 'elu_alpha': 0.23293447381454382}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:07:56,955] Trial 35 finished with value: inf and parameters: {'hidden_layer': 35, 'learning_rate': 0.004906769500822944, 'momentum': 0.5452657022470937, 'weight_decay': 0.00013400920977247373, 'elu_alpha': 0.20900934357176465}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:11:49,200] Trial 36 pruned.
[I 2026-09-25 16:13:30,457] Trial 37 pruned.
[I 2026-09-25 16:19:02,523] Trial 38 finished with value: 0.4125034865476862 and parameters: {'hidden_layer': 19, 'learning_rate': 0.0027622935716290404, 'momentum': 0.5506468115784903, 'weight_decay': 3.408150696021571e-05, 'elu_alpha': 0.466543831480756}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:19:11,554] Trial 39 finished with value: inf and parameters: {'hidden_layer': 42, 'learning_rate': 0.004355135876179493, 'momentum': 0.7181814664479762, 'weight_decay': 0.00026362279471888573, 'elu_alpha': 1.050043055906005}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:19:20,929] Trial 40 finished with value: inf and parameters: {'hidden_layer': 31, 'learning_rate': 0.007071267039440298, 'momentum': 0.5148852899064547, 'weight_decay': 0.0023329260102892824, 'elu_alpha': 0.727550876295474}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:25:17,224] Trial 41 finished with value: 0.39514708177648783 and parameters: {'hidden_layer': 44, 'learning_rate': 0.0017545635540034256, 'momentum': 0.7116074687448835, 'weight_decay': 0.00012311482347690655, 'elu_alpha': 0.39777725888811716}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:25:25,816] Trial 42 finished with value: inf and parameters: {'hidden_layer': 49, 'learning_rate': 0.0019841623392552296, 'momentum': 0.7324291911916243, 'weight_decay': 0.00015825996161992502, 'elu_alpha': 0.2394064682978435}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:25:34,147] Trial 43 finished with value: inf and parameters: {'hidden_layer': 42, 'learning_rate': 0.002520125881653893, 'momentum': 0.841245509632123, 'weight_decay': 0.00011607893713563915, 'elu_alpha': 0.20367755451583747}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:29:25,045] Trial 44 finished with value: 0.41163448447810846 and parameters: {'hidden_layer': 49, 'learning_rate': 0.0034010130423619573, 'momentum': 0.6189051140279385, 'weight_decay': 6.040698566496074e-05, 'elu_alpha': 0.556857563388363}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:36:01,680] Trial 45 finished with value: 0.39964320391143804 and parameters: {'hidden_layer': 29, 'learning_rate': 0.001731072692955858, 'momentum': 0.4758001051316556, 'weight_decay': 1.925755320770822e-05, 'elu_alpha': 0.1008686153415291}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:37:12,691] Trial 46 pruned.
[I 2026-09-25 16:38:37,412] Trial 47 pruned.
[I 2026-09-25 16:40:04,276] Trial 48 finished with value: inf and parameters: {'hidden_layer': 21, 'learning_rate': 0.0034402772596652384, 'momentum': 0.7464850331202129, 'weight_decay': 3.6946212612188416e-05, 'elu_alpha': 0.25331331370449484}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:41:31,640] Trial 49 pruned.
[I 2026-09-25 16:42:33,831] Trial 50 pruned.
[I 2026-09-25 16:48:03,047] Trial 51 finished with value: 0.40381758343713425 and parameters: {'hidden_layer': 46, 'learning_rate': 0.0014762122105986132, 'momentum': 0.6912675781542633, 'weight_decay': 0.00030505179974784974, 'elu_alpha': 0.39432816981007823}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:54:18,239] Trial 52 finished with value: 0.3972815130173818 and parameters: {'hidden_layer': 72, 'learning_rate': 0.0016704366584802358, 'momentum': 0.6721879557475655, 'weight_decay': 0.00016792904038617014, 'elu_alpha': 0.37104916148612466}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 16:56:50,790] Trial 53 finished with value: inf and parameters: {'hidden_layer': 86, 'learning_rate': 0.000998693527540096, 'momentum': 0.9077053044569359, 'weight_decay': 0.00017086015314547943, 'elu_alpha': 0.3016034512068119}. Best is trial 32 with value: 0.3854946511091066.
[I 2026-09-25 17:01:36,008] Trial 54 finished with value: 0.370525098726602 and parameters: {'hidden_layer': 71, 'learning_rate': 0.001974864445191968, 'momentum': 0.7672712192036012, 'weight_decay': 4.669875060622569e-05, 'elu_alpha': 0.18579145454927054}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:08:59,721] Trial 55 finished with value: 0.38173164545853705 and parameters: {'hidden_layer': 74, 'learning_rate': 0.0008199605194559297, 'momentum': 0.8166055628137214, 'weight_decay': 5.435439801984566e-06, 'elu_alpha': 0.20624615049164385}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:14:25,561] Trial 56 finished with value: 0.3755543589536561 and parameters: {'hidden_layer': 78, 'learning_rate': 0.0008600509944537932, 'momentum': 0.8265625121164876, 'weight_decay': 3.8090861706098477e-06, 'elu_alpha': 0.15290844172235185}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:20:27,017] Trial 57 finished with value: 0.3724673271679764 and parameters: {'hidden_layer': 79, 'learning_rate': 0.0008439461533670473, 'momentum': 0.8265911182605921, 'weight_decay': 4.700027425661989e-06, 'elu_alpha': 0.1674933341982772}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:20:35,283] Trial 58 finished with value: inf and parameters: {'hidden_layer': 78, 'learning_rate': 0.0005908575664119825, 'momentum': 0.9890822695974986, 'weight_decay': 4.324390700472682e-06, 'elu_alpha': 0.16238986283140266}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:26:46,385] Trial 59 finished with value: 0.3752964667704392 and parameters: {'hidden_layer': 94, 'learning_rate': 0.0007965569099510398, 'momentum': 0.8278193217125913, 'weight_decay': 2.964915984562226e-06, 'elu_alpha': 0.172784258661832}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:31:11,967] Trial 60 finished with value: 0.39254544863330093 and parameters: {'hidden_layer': 93, 'learning_rate': 0.0003869789086984569, 'momentum': 0.8313291490606456, 'weight_decay': 3.036779186850766e-06, 'elu_alpha': 0.11693186657933557}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:35:01,131] Trial 61 finished with value: 0.39326958001868156 and parameters: {'hidden_layer': 101, 'learning_rate': 0.0004216002656363103, 'momentum': 0.8264422900726214, 'weight_decay': 2.8918500383112546e-06, 'elu_alpha': 0.157919718182427}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:37:43,801] Trial 62 finished with value: inf and parameters: {'hidden_layer': 92, 'learning_rate': 0.0008170505776616315, 'momentum': 0.8868185032032551, 'weight_decay': 1.0329797886529013e-06, 'elu_alpha': 0.10016668426317536}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:38:32,749] Trial 63 pruned.
[I 2026-09-25 17:41:42,312] Trial 64 finished with value: 0.3715904390032265 and parameters: {'hidden_layer': 84, 'learning_rate': 0.0007285866469085902, 'momentum': 0.8625756472454167, 'weight_decay': 1.91953210768792e-06, 'elu_alpha': 0.10118927147495571}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:44:31,953] Trial 65 finished with value: 0.3841510265733732 and parameters: {'hidden_layer': 87, 'learning_rate': 0.0006203760776280315, 'momentum': 0.8633896282696893, 'weight_decay': 2.0394793979706047e-06, 'elu_alpha': 0.187829772738897}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:48:09,959] Trial 66 finished with value: 0.376595571235992 and parameters: {'hidden_layer': 83, 'learning_rate': 0.0005667796303288743, 'momentum': 0.872435097089802, 'weight_decay': 1.5451080927394114e-06, 'elu_alpha': 0.17687727365991537}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:50:11,467] Trial 67 finished with value: inf and parameters: {'hidden_layer': 82, 'learning_rate': 0.0005020363781232371, 'momentum': 0.9469614943265083, 'weight_decay': 1.6097916638729466e-06, 'elu_alpha': 0.3018880281044053}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:51:00,331] Trial 68 pruned.
[I 2026-09-25 17:55:16,398] Trial 69 finished with value: 0.37827573225856714 and parameters: {'hidden_layer': 107, 'learning_rate': 0.0009513737292647709, 'momentum': 0.7586013997956617, 'weight_decay': 4.070455112626148e-06, 'elu_alpha': 0.19935250714071961}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 17:55:32,496] Trial 70 pruned.
[I 2026-09-25 17:57:05,162] Trial 71 finished with value: inf and parameters: {'hidden_layer': 78, 'learning_rate': 0.0009230265450411737, 'momentum': 0.8652493545257142, 'weight_decay': 4.322985800942208e-06, 'elu_alpha': 0.19184196033144035}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 18:01:41,667] Trial 72 finished with value: 0.3815997524508932 and parameters: {'hidden_layer': 108, 'learning_rate': 0.0005390158066697343, 'momentum': 0.8119537808251848, 'weight_decay': 6.026175048593204e-06, 'elu_alpha': 0.1012382611037164}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 18:02:35,461] Trial 73 pruned.
[I 2026-09-25 18:02:39,941] Trial 74 finished with value: inf and parameters: {'hidden_layer': 112, 'learning_rate': 0.0005520014156540877, 'momentum': 0.9842870082814137, 'weight_decay': 2.1454919564583156e-06, 'elu_alpha': 0.32732677323973536}. Best is trial 54 with value: 0.370525098726602.
[I 2026-09-25 18:05:58,907] Trial 75 finished with value: 0.3616198126481279 and parameters: {'hidden_layer': 82, 'learning_rate': 0.0004910762739354061, 'momentum': 0.9257687564245632, 'weight_decay': 1.3139548430197805e-05, 'elu_alpha': 0.1409809797548997}. Best is trial 75 with value: 0.3616198126481279.
[I 2026-09-25 18:08:31,958] Trial 76 finished with value: 0.721808146802399 and parameters: {'hidden_layer': 81, 'learning_rate': 0.0006831094604647776, 'momentum': 0.918342339924914, 'weight_decay': 1.2989624173959458e-05, 'elu_alpha': 0.2847740125253956}. Best is trial 75 with value: 0.3616198126481279.
[I 2026-09-25 18:12:55,573] Trial 77 finished with value: 0.3787893166561428 and parameters: {'hidden_layer': 85, 'learning_rate': 0.0004747107799113821, 'momentum': 0.8679030090418601, 'weight_decay': 2.216081863751875e-06, 'elu_alpha': 0.15805871916674297}. Best is trial 75 with value: 0.3616198126481279.
[I 2026-09-25 18:13:03,264] Trial 78 finished with value: inf and parameters: {'hidden_layer': 120, 'learning_rate': 0.0012517216950233892, 'momentum': 0.9614392654411404, 'weight_decay': 1.468942799461806e-06, 'elu_alpha': 0.3460343980749623}. Best is trial 75 with value: 0.3616198126481279.
[I 2026-09-25 18:13:24,690] Trial 79 pruned.
[I 2026-09-25 18:13:24,696] A new study created in memory with name: no-name-38604a37-7bce-40ce-8474-2d5293663a95

{'hidden_layer': 82, 'learning_rate': 0.0004910762739354061, 'momentum': 0.9257687564245632, 'weight_decay': 1.3139548430197805e-05, 'elu_alpha': 0.1409809797548997}
0.3616198126481279

[I 2026-09-25 18:16:21,865] Trial 0 finished with value: 0.4070397459731634 and parameters: {'hidden_layer': 26, 'learning_rate': 0.00802892031446619, 'momentum': 0.06309611296163853, 'weight_decay': 8.20258637894404e-06}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:20:58,206] Trial 1 finished with value: 0.4286748736933291 and parameters: {'hidden_layer': 74, 'learning_rate': 0.00019930292938529843, 'momentum': 0.9132897097333287, 'weight_decay': 5.658695845569574e-06}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:26:07,019] Trial 2 finished with value: 0.5222480224578778 and parameters: {'hidden_layer': 22, 'learning_rate': 0.00027185651981566074, 'momentum': 0.11379155274446981, 'weight_decay': 7.047009018720604e-06}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:31:22,458] Trial 3 finished with value: 0.47533748973298284 and parameters: {'hidden_layer': 15, 'learning_rate': 0.0008349020243737295, 'momentum': 0.01303335671719846, 'weight_decay': 0.00017879878696943263}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:36:31,634] Trial 4 finished with value: 0.43273185380976464 and parameters: {'hidden_layer': 119, 'learning_rate': 0.0020169174801107285, 'momentum': 0.18546121274469785, 'weight_decay': 9.1075607291343e-06}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:40:06,564] Trial 5 finished with value: 0.43181074780017087 and parameters: {'hidden_layer': 10, 'learning_rate': 0.004878652970756871, 'momentum': 0.02757065201015146, 'weight_decay': 0.001177383251643048}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:41:00,023] Trial 6 pruned.
[I 2026-09-25 18:42:32,622] Trial 7 pruned.
[I 2026-09-25 18:43:52,927] Trial 8 pruned.
[I 2026-09-25 18:48:45,816] Trial 9 finished with value: 0.4228021285442418 and parameters: {'hidden_layer': 101, 'learning_rate': 0.0005836089464730598, 'momentum': 0.8240972389470445, 'weight_decay': 0.0052352391039929055}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:48:51,734] Trial 10 finished with value: inf and parameters: {'hidden_layer': 59, 'learning_rate': 0.005630777229905078, 'momentum': 0.5327312896917765, 'weight_decay': 1.352506251185573e-06}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:48:57,276] Trial 11 finished with value: inf and parameters: {'hidden_layer': 109, 'learning_rate': 0.002210237472518753, 'momentum': 0.8197718620014434, 'weight_decay': 0.00010091770125717876}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:49:05,150] Trial 12 finished with value: inf and parameters: {'hidden_layer': 85, 'learning_rate': 0.00903336119835059, 'momentum': 0.6397728612972233, 'weight_decay': 0.008223872407766994}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:50:02,667] Trial 13 pruned.
[I 2026-09-25 18:51:03,328] Trial 14 pruned.
[I 2026-09-25 18:52:01,054] Trial 15 pruned.
[I 2026-09-25 18:52:06,096] Trial 16 finished with value: inf and parameters: {'hidden_layer': 41, 'learning_rate': 0.0033649191865288003, 'momentum': 0.7740202980818077, 'weight_decay': 1.3238581107075063e-06}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:52:12,094] Trial 17 finished with value: inf and parameters: {'hidden_layer': 74, 'learning_rate': 0.0012382475089319916, 'momentum': 0.9757068717260202, 'weight_decay': 3.704907582317059e-05}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:53:15,488] Trial 18 finished with value: inf and parameters: {'hidden_layer': 27, 'learning_rate': 0.009121584947965328, 'momentum': 0.5234529918604083, 'weight_decay': 0.0023334823209178296}. Best is trial 0 with value: 0.4070397459731634.
[I 2026-09-25 18:54:16,459] Trial 19 pruned.
[I 2026-09-25 18:55:27,919] Trial 20 pruned.
[W 2026-09-25 18:58:39,970] Trial 21 failed with parameters: {'hidden_layer': 79, 'learning_rate': 0.00017940240324022057, 'momentum': 0.9510464743684093, 'weight_decay': 2.9606793326358785e-06} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\optuna\study\_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "C:\Users\dawid\OneDrive - Stellenbosch University\Documents\Universiteit\4th year\ML\assignment3\ML441_Assigment3\active_regression.py", line 317, in obj
    history = model.fit(
              ^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\backend\tensorflow\trainer.py", line 377, in fit
    logs = self.train_function(iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\keras\src\backend\tensorflow\trainer.py", line 220, in function
    opt_outputs = multi_step_on_iterator(iterator)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\util\traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\polymorphic_function.py", line 833, in __call__
    result = self._call(*args, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\polymorphic_function.py", line 878, in _call
    results = tracing_compilation.call_function(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\tracing_compilation.py", line 139, in call_function
    return function._call_flat(  # pylint: disable=protected-access
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\concrete_function.py", line 1322, in _call_flat
    return self._inference_function.call_preflattened(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\atomic_function.py", line 216, in call_preflattened
    flat_outputs = self.call_flat(*args)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\polymorphic_function\atomic_function.py", line 251, in call_flat
    outputs = self._bound_context.call_function(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\context.py", line 1688, in call_function
    outputs = execute.execute(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\dawid\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\eager\execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
[W 2026-09-25 18:58:40,265] Trial 21 failed with value None.

KeyboardInterrupt:

In [10]:
acts = ['relu', 'leaky_relu', 'elu']
results = []
for activation in acts:
    setup = {'activation': activation}
    alpha = 0
    params = retrieve_params(f'params/california/{activation}.json')
    if activation == 'leaky_relu':
        alpha = params["leaky_relu_alpha"]
    elif activation == 'elu':
        alpha = params["elu_alpha"]
    result = cv_regression(X_pool, y_pool, out_units=1, out_act='linear', 
                    loss='mse', k=5, random_state=42, 
                    hidden_units=params['hidden_layer'], activation=activation, alpha=alpha, 
                    learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'])
    for key, val in result.items():
        setup[key] = val

    results.append(setup)

results_df = pd.DataFrame(results)
results_df.round(4).to_csv(f"results/california/cv_validation.csv", index=False)

In [5]:
results_df = pd.read_csv("results/california/cv_validation.csv")
results_df

   activation    rmse    mape  R_squared
0        relu  0.6678  0.2625     0.6476
1  leaky_relu  0.5929  0.2447     0.7345
2         elu  0.6083  0.2558     0.7204

In [11]:
activation = 'leaky_relu'
params = retrieve_params(f'params/california/{activation}.json')
scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)
model = create_regmodel(X_train.shape[1], hidden_units=params['hidden_layer'], activation=activation, alpha=params['leaky_relu_alpha'], 
                 learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], loss='mse')
# params['learning_rate']
history = []
runs = 100
# runs = 200
epochs = 200 // runs

fit_kwargs = {
    "epochs": epochs,
    "batch_size": 32,
    # "validation_split": 0.15,
    # "callbacks": [early_stopping],
    "verbose": 0
}
tic = time()
for i in range(runs):
    iteration = {'cumulative epochs': epochs * (i + 1)}
    iter_hist = model.fit(
        X_train,
        y_pool,
        **fit_kwargs
    )

    train_loss = iter_hist.history['loss']
    weights = model.get_weights()

    print(f"Iteration {i+1}: ")
    for l in range(len(train_loss)):
        print(f"\t{train_loss[l]}")

    if not all(np.all(np.isfinite(w)) for w in weights):
        print(f"Model became unstable at iteration {i + 1}")
        break

    y_pred = model(X_val, training=False).numpy().ravel()

    if not np.all(np.isfinite(y_pred)):
        print(f"NaN/Inf predictions at iteration {i + 1}")
        break

    rmse = root_mean_squared_error(y_test, y_pred)
    mape = mean_absolute_percentage_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    toc = time()

    iteration['Training loss'] = train_loss[-1]
    iteration['RMSE'] = rmse
    iteration['MAPE'] = mape
    iteration['R2-score'] = r2
    iteration['time'] = toc - tic
    history.append(iteration)
    
    print(f"Iteration {i+1}: ")
    for l in range(len(train_loss)):
        print(f"\t{train_loss[l]}")

run_df = pd.DataFrame(history)
run_df.round(4).to_csv(f"results/california/passive_learning.csv", index=False)

Iteration 1:
	0.8864449858665466
	0.5983476042747498
	0.5244823098182678
	0.4976836144924164
Iteration 2:
	0.4819352626800537
	0.4785275161266327
	0.476483553647995
	0.4542883634567261
Iteration 3:
	0.44996973872184753
	0.4482862651348114
	0.4493209719657898
	0.4393377900123596
Iteration 4:
	0.4342212975025177
	0.42445966601371765
	0.4208027422428131
	0.4181661605834961
Iteration 5:
	0.4150742292404175
	0.4157498776912689
	0.40638625621795654
	0.40310871601104736
Iteration 6:
	0.4062226712703705
	0.45524150133132935
	0.4911082983016968
	0.4327504634857178
Iteration 7:
	0.42066067457199097
	0.4433033764362335
	0.41511794924736023
	0.4099682867527008
Iteration 8:
	0.40156289935112
	0.39395928382873535
	0.39474862813949585
	0.3922727108001709
Iteration 9:
	0.38521888852119446
	0.3894878327846527
	0.3858407139778137
	0.3829437792301178
Iteration 10:
	0.384768009185791
	0.3820318579673767
	0.3764415681362152
	0.37688153982162476
Iteration 11:
	0.3764477074146271
	0.38493111729621887
	0.3935977518558502
	0.3783400058746338
Iteration 12:
	0.3730614483356476
	0.36885616183280945
	0.3718528151512146
	0.36663076281547546
Iteration 13:
	0.3647497296333313
	0.37195348739624023
	0.3681401312351227
	0.368487685918808
Iteration 14:
	0.365658164024353
	0.36611801385879517
	0.3627709746360779
	0.361782968044281
Iteration 15:
	0.3618004024028778
	0.3653128445148468
	0.3637075424194336
	0.35914620757102966
Iteration 16:
	0.36335715651512146
	0.3640986382961273
	0.360411137342453
	0.3611889183521271
Iteration 17:
	0.36522403359413147
	0.3598931133747101
	0.36492443084716797
	0.3636009693145752
Iteration 18:
	0.366946816444397
	0.3575967848300934
	0.3615249693393707
	0.3524259924888611
Iteration 19:
	0.3561636507511139
	0.3533622622489929
	0.3529651165008545
	0.363090842962265
Iteration 20:
	0.35703521966934204
	0.35812273621559143
	0.3531389832496643
	0.3540828227996826
Iteration 21:
	0.3556843400001526
	0.35127073526382446
	0.3520515263080597
	0.3488044738769531
Iteration 22:
	0.35346612334251404
	0.34906888008117676
	0.3503879904747009
	0.35262060165405273
Iteration 23:
	0.3509390652179718
	0.3481622040271759
	0.35051971673965454
	0.3503926694393158
Iteration 24:
	0.3493528664112091
	0.35095664858818054
	0.3661420941352844
	0.35568952560424805
Iteration 25:
	0.35715699195861816
	0.36852818727493286
	0.3490414023399353
	0.34868526458740234
Iteration 26:
	0.36596086621284485
	0.34608206152915955
	0.34969407320022583
	0.3485642969608307
Iteration 27:
	0.3475770652294159
	0.34880736470222473
	0.3456263244152069
	0.3459358215332031
Iteration 28:
	0.34709978103637695
	0.34957101941108704
	0.3441202640533447
	0.34555935859680176
Iteration 29:
	0.34557783603668213
	0.3436708152294159
	0.3441879153251648
	0.34365394711494446
Iteration 30:
	0.3411034941673279
	0.3454563319683075
	0.34727659821510315
	0.34145212173461914
Iteration 31:
	0.3415442407131195
	0.34607458114624023
	0.3468265235424042
	0.33918386697769165
Iteration 32:
	0.3412550389766693
	0.3412606418132782
	0.3409958481788635
	0.3442380428314209
Iteration 33:
	0.34279635548591614
	0.34183770418167114
	0.3395995795726776
	0.33557167649269104
Iteration 34:
	0.33676838874816895
	0.34030285477638245
	0.34828439354896545
	0.34013134241104126
Iteration 35:
	0.34033527970314026
	0.3427533507347107
	0.34139731526374817
	0.3466934859752655
Iteration 36:
	0.3625412583351135
	0.34299567341804504
	0.34141018986701965
	0.33997777104377747
Iteration 37:
	0.34560635685920715
	0.34408143162727356
	0.343462735414505
	0.3430817723274231
Iteration 38:
	0.3390514552593231
	0.33742478489875793
	0.3352663516998291
	0.3387306034564972
Iteration 39:
	0.3415142893791199
	0.33418554067611694
	0.33607420325279236
	0.3332168161869049
Iteration 40:
	0.3379192352294922
	0.33833014965057373
	0.33573538064956665
	0.33736440539360046
Iteration 41:
	0.3345678150653839
	0.34072625637054443
	0.3331037163734436
	0.3403359353542328
Iteration 42:
	0.33525151014328003
	0.3354654014110565
	0.33625420928001404
	0.3340205252170563
Iteration 43:
	0.33430320024490356
	0.3351407051086426
	0.3346734941005707
	0.33469316363334656
Iteration 44:
	0.3339718282222748
	0.33431190252304077
	0.3353934586048126
	0.3320501148700714
Iteration 45:
	0.33720338344573975
	0.3359358608722687
	0.3357384204864502
	0.335419625043869
Iteration 46:
	0.3355655372142792
	0.33659887313842773
	0.33421802520751953
	0.35127782821655273
Iteration 47:
	0.3549477756023407
	0.3369081914424896
	0.34316807985305786
	0.33653488755226135
Iteration 48:
	0.33583390712738037
	0.338695764541626
	0.33597177267074585
	0.33396777510643005
Iteration 49:
	0.3394792377948761
	0.3402152359485626
	0.3391093611717224
	0.33518293499946594
Iteration 50:
	0.3355594575405121
	0.3342738151550293
	0.3366985619068146
	0.3354095220565796

In [ ]:
activation = 'leaky_relu'
params = retrieve_params(f'params/california/{activation}.json')

scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)

history = active_learning_reg(X_train, y_pool, X_val, y_test, uncertainty_sampling, num_iter=100, unlab_size=0.9, random_state=100, verbose=True,
                               hidden_units=params['hidden_layer'], activation=activation, alpha=params['leaky_relu_alpha'],
                               learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'] 
)

run_df = pd.DataFrame(history)
run_df.round(4).to_csv(f"results/california/uncertainty_sampling.csv", index=False)

In [ ]:
activation = 'leaky_relu'
params = retrieve_params(f'params/california/{activation}.json')

scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)
for beta in [0.9, 0.8, 0.7, 0.6]:
    history = sasla_reg(X_train, y_pool, X_val, y_test, num_iter=100, unlab_size=0.9, random_state=100, verbose=True,
                                   hidden_units=32, activation=activation, alpha=params['leaky_relu_alpha'],
                                   learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], beta=beta)
    
    run_df = pd.DataFrame(history)
    run_df.round(4).to_csv(f"results/california/sasla_{beta}.csv", index=False)

## Concrete

In [11]:
concrete_compressive_strength = fetch_ucirepo(id=165) 
ccs_df = pd.concat(
    [concrete_compressive_strength.data.features, concrete_compressive_strength.data.targets],
    axis=1
)
ccs_df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Concrete compressive strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [12]:
X = concrete_compressive_strength.data.features.to_numpy()
y = concrete_compressive_strength.data.targets.to_numpy()

X_pool, X_test, y_pool, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=51
)

In [ ]:
acts = ['relu', 'leaky_relu', 'elu']
for activation in acts:
    base_params = tune_params(X_pool, y_pool,
                              loss='mse',
                              out_units=1, out_act='linear',
                              k=5, activation=activation,
                              random_state=42,
                              n_trials=80,
                              export=True, file = f'params/concrete/{activation}.json'
    )

In [13]:
acts = ['relu', 'leaky_relu', 'elu']
results = []
for activation in acts:
    setup = {'activation': activation}
    alpha = 0
    params = retrieve_params(f'params/concrete/{activation}.json')
    if activation == 'leaky_relu':
        alpha = params["leaky_relu_alpha"]
    elif activation == 'elu':
        alpha = params["elu_alpha"]
    result = cv_regression(X_pool, y_pool, out_units=1, out_act='linear', 
                    loss='mse', k=5, random_state=42, 
                    hidden_units=params['hidden_layer'], activation=activation, alpha=alpha, 
                    learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'])
    for key, val in result.items():
        setup[key] = val

    results.append(setup)

results_df = pd.DataFrame(results)
results_df.round(4).to_csv(f"results/concrete/cv_validation.csv", index=False)

In [ ]:
results_df = pd.read_csv("results/concrete/cv_validation.csv")
results_df

In [ ]:
activation = 'leaky_relu'
params = retrieve_params(f'params/concrete/{activation}.json')
scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)
model = create_regmodel(X_train.shape[1], hidden_units=params['hidden_layer'], activation=activation, alpha=params['leaky_relu_alpha'], 
                 learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], loss='mse')
# params['learning_rate']
history = []
runs = 100
# runs = 200
epochs = 200 // runs

fit_kwargs = {
    "epochs": epochs,
    "batch_size": 32,
    # "validation_split": 0.15,
    # "callbacks": [early_stopping],
    "verbose": 0
}
tic = time()
for i in range(runs):
    iteration = {'cumulative epochs': epochs * (i + 1)}
    iter_hist = model.fit(
        X_train,
        y_pool,
        **fit_kwargs
    )

    train_loss = iter_hist.history['loss']
    weights = model.get_weights()

    print(f"Iteration {i+1}: ")
    for l in range(len(train_loss)):
        print(f"\t{train_loss[l]}")

    if not all(np.all(np.isfinite(w)) for w in weights):
        print(f"Model became unstable at iteration {i + 1}")
        break

    y_pred = model(X_val, training=False).numpy().ravel()

    if not np.all(np.isfinite(y_pred)):
        print(f"NaN/Inf predictions at iteration {i + 1}")
        break

    rmse = root_mean_squared_error(y_test, y_pred)
    mape = mean_absolute_percentage_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    toc = time()

    iteration['Training loss'] = train_loss[-1]
    iteration['RMSE'] = rmse
    iteration['MAPE'] = mape
    iteration['R2-score'] = r2
    iteration['time'] = toc - tic
    history.append(iteration)
    
    print(f"Iteration {i+1}: ")
    for l in range(len(train_loss)):
        print(f"\t{train_loss[l]}")

run_df = pd.DataFrame(history)
run_df.round(4).to_csv(f"results/concrete/passive_learning.csv", index=False)

In [ ]:
activation = 'leaky_relu'
params = retrieve_params(f'params/concrete/{activation}.json')

scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)

history = active_learning_reg(X_train, y_pool, X_val, y_test, uncertainty_sampling, num_iter=100, unlab_size=0.9, random_state=100, verbose=True,
                               hidden_units=params['hidden_layer'], activation=activation, alpha=params['leaky_relu_alpha'],
                               learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'] 
)

run_df = pd.DataFrame(history)
run_df.round(4).to_csv(f"results/concrete/uncertainty_sampling.csv", index=False)

In [ ]:
activation = 'leaky_relu'
params = retrieve_params(f'params/concrete/{activation}.json')

scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)
for beta in [0.9, 0.8, 0.7, 0.6]:
    history = sasla_reg(X_train, y_pool, X_val, y_test, num_iter=100, unlab_size=0.9, random_state=100, verbose=True,
                                   hidden_units=32, activation=activation, alpha=params['leaky_relu_alpha'],
                                   learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], beta=beta)
    
    run_df = pd.DataFrame(history)
    run_df.round(4).to_csv(f"results/concrete/sasla_{beta}.csv", index=False)

## Seoul Bike sharing

In [14]:
seoul_bike_sharing_demand = fetch_ucirepo(id=560)
sbsd_df = pd.concat(
    [seoul_bike_sharing_demand.data.features, seoul_bike_sharing_demand.data.targets],
    axis=1
)

drop = ['Date', 'Hour', "Month", "DayOfWeek", 'Seasons']
sbsd_df['Date'] = pd.to_datetime(
    sbsd_df["Date"],
    format="%d/%m/%Y"
)
sbsd_df["Hour_sin"] = np.sin(2 * np.pi * sbsd_df["Hour"] / 24)
sbsd_df["Hour_cos"] = np.cos(2 * np.pi * sbsd_df["Hour"] / 24)

sbsd_df["Month"] = sbsd_df["Date"].dt.month
sbsd_df["DayOfWeek"] = sbsd_df["Date"].dt.dayofweek

sbsd_df["Month_sin"] = np.sin(2 * np.pi * sbsd_df["Month"] / 12)
sbsd_df["Month_cos"] = np.cos(2 * np.pi * sbsd_df["Month"] / 12)

sbsd_df["DayOfWeek_sin"] = np.sin(2 * np.pi * sbsd_df["DayOfWeek"] / 7)
sbsd_df["DayOfWeek_cos"] = np.cos(2 * np.pi * sbsd_df["DayOfWeek"] / 7)

sbsd_df["Holiday"] = (sbsd_df["Holiday"] == "Holiday").astype(int)
sbsd_df["Functioning Day"] = (sbsd_df["Functioning Day"] == "Yes").astype(int)

sbsd_df.drop(columns=drop, inplace=True)

sbsd_df.head()

,Rented Bike Count,Temperature,Humidity,Wind speed,Visibility,Dew point temperature,Solar Radiation,Rainfall,Snowfall,Holiday,Functioning Day,Hour_sin,Hour_cos,Month_sin,Month_cos,DayOfWeek_sin,DayOfWeek_cos
0,254,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,0,1,0.000000,1.000000,-2.449294e-16,1.0,-0.433884,-0.900969
1,204,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,0,1,0.258819,0.965926,-2.449294e-16,1.0,-0.433884,-0.900969
2,173,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,0,1,0.500000,0.866025,-2.449294e-16,1.0,-0.433884,-0.900969
3,107,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,0,1,0.707107,0.707107,-2.449294e-16,1.0,-0.433884,-0.900969
4,78,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,0,1,0.866025,0.500000,-2.449294e-16,1.0,-0.433884,-0.900969

In [18]:
X = sbsd_df.drop(columns=['Rented Bike Count']).to_numpy()
y = sbsd_df['Rented Bike Count'].to_numpy()

X_pool, X_test, y_pool, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=51
)

In [ ]:
acts = ['relu', 'leaky_relu', 'elu']
for activation in acts:
    base_params = tune_params(X_pool, y_pool,
                              loss='mse',
                              out_units=1, out_act='linear',
                              k=5, activation=activation,
                              random_state=42,
                              n_trials=80,
                              export=True, file = f'params/seoul_bikes/{activation}.json'
    )

In [19]:
acts = ['relu', 'leaky_relu', 'elu']
results = []
for activation in acts:
    setup = {'activation': activation}
    alpha = 0
    params = retrieve_params(f'params/seoul_bikes/{activation}.json')
    if activation == 'leaky_relu':
        alpha = params["leaky_relu_alpha"]
    elif activation == 'elu':
        alpha = params["elu_alpha"]
    result = cv_regression(X_pool, y_pool, out_units=1, out_act='linear', 
                    loss='mse', k=5, random_state=42, 
                    hidden_units=params['hidden_layer'], activation=activation, alpha=alpha, 
                    learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'])
    for key, val in result.items():
        setup[key] = val

    results.append(setup)

results_df = pd.DataFrame(results)
results_df.round(4).to_csv(f"results/seoul_bikes/cv_validation.csv", index=False)

In [ ]:
results_df = pd.read_csv("results/seoul_bikes/cv_validation.csv")
results_df

In [ ]:
activation = 'leaky_relu'
params = retrieve_params(f'params/seoul_bikes/{activation}.json')
scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)
model = create_regmodel(X_train.shape[1], hidden_units=params['hidden_layer'], activation=activation, alpha=params['leaky_relu_alpha'], 
                 learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], loss='mse')
# params['learning_rate']
history = []
runs = 100
# runs = 200
epochs = 200 // runs

fit_kwargs = {
    "epochs": epochs,
    "batch_size": 32,
    # "validation_split": 0.15,
    # "callbacks": [early_stopping],
    "verbose": 0
}
tic = time()
for i in range(runs):
    iteration = {'cumulative epochs': epochs * (i + 1)}
    iter_hist = model.fit(
        X_train,
        y_pool,
        **fit_kwargs
    )

    train_loss = iter_hist.history['loss']
    weights = model.get_weights()

    print(f"Iteration {i+1}: ")
    for l in range(len(train_loss)):
        print(f"\t{train_loss[l]}")

    if not all(np.all(np.isfinite(w)) for w in weights):
        print(f"Model became unstable at iteration {i + 1}")
        break

    y_pred = model(X_val, training=False).numpy().ravel()

    if not np.all(np.isfinite(y_pred)):
        print(f"NaN/Inf predictions at iteration {i + 1}")
        break

    rmse = root_mean_squared_error(y_test, y_pred)
    mape = mean_absolute_percentage_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    toc = time()

    iteration['Training loss'] = train_loss[-1]
    iteration['RMSE'] = rmse
    iteration['MAPE'] = mape
    iteration['R2-score'] = r2
    iteration['time'] = toc - tic
    history.append(iteration)
    
    print(f"Iteration {i+1}: ")
    for l in range(len(train_loss)):
        print(f"\t{train_loss[l]}")

run_df = pd.DataFrame(history)
run_df.round(4).to_csv(f"results/seoul_bikes/passive_learning.csv", index=False)

In [ ]:
activation = 'leaky_relu'
params = retrieve_params(f'params/seoul_bikes/{activation}.json')

scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)

history = active_learning_reg(X_train, y_pool, X_val, y_test, uncertainty_sampling, num_iter=100, unlab_size=0.9, random_state=100, verbose=True,
                               hidden_units=params['hidden_layer'], activation=activation, alpha=params['leaky_relu_alpha'],
                               learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'] 
)

run_df = pd.DataFrame(history)
run_df.round(4).to_csv(f"results/seoul_bikes/uncertainty_sampling.csv", index=False)

In [ ]:
activation = 'leaky_relu'
params = retrieve_params(f'params/seoul_bikes/{activation}.json')

scaler = StandardScaler()
X_train = scaler.fit_transform(X_pool)
X_val = scaler.transform(X_test)
for beta in [0.9, 0.8, 0.7, 0.6]:
    history = sasla_reg(X_train, y_pool, X_val, y_test, num_iter=100, unlab_size=0.9, random_state=100, verbose=True,
                                   hidden_units=32, activation=activation, alpha=params['leaky_relu_alpha'],
                                   learning_rate=params['learning_rate'], momentum=params['momentum'], weight_decay=params['weight_decay'], beta=beta)
    
    run_df = pd.DataFrame(history)
    run_df.round(4).to_csv(f"results/seoul_bikes/sasla_{beta}.csv", index=False)